
SCHEMA ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA;

(* V 1.1 - 2003-10-20 *)

CONSTANT
  property_code_len : INTEGER := 14;
  revision_len : INTEGER := 3;
  value_format_len : INTEGER := 80;
  det_classification_len : INTEGER := 3;
  dictionary_code_len : INTEGER := 80;
  http_directory_name_length : INTEGER := 128;
  pref_name_len : INTEGER := 70;
  sep_cv : STRING := '-';
  sep_id : STRING := '.';
  version_len : INTEGER := 9;
  syn_name_len : INTEGER := pref_name_len;
  http_file_name_length : INTEGER := 128;
  element_code_len : INTEGER := 14;
  compiler_version_length : INTEGER := 9;
  value_code_len : INTEGER := 18;
  external_item_code_length : INTEGER := 128;
  dummy_gri : geometric_representation_item := representation_item('')||
  geometric_representation_item();
  supplier_code_len : INTEGER := 70;
  class_code_len : INTEGER := 14;
  source_doc_len : INTEGER := 80;
  short_name_len : INTEGER := 30;
  external_file_address_length : INTEGER := 18;
  data_type_code_len : INTEGER := 14;
END_CONSTANT;
 
TYPE absolute_url_type = identifier;
WHERE
  wr1 : SELF LIKE '*://*';
END_TYPE;
 
TYPE ahead_or_behind = ENUMERATION OF 
  (ahead, exact, behind);
END_TYPE;
 
TYPE amount_of_substance_measure = REAL;
END_TYPE;
 
TYPE area_measure = REAL;
END_TYPE;

TYPE axis2_placement = SELECT 
  (axis2_placement_2d, axis2_placement_3d);
END_TYPE;
 
TYPE boolean_value = BOOLEAN;
END_TYPE;
 
TYPE character_set_type = identifier;
END_TYPE;
 
TYPE class_code_type = code_type;
WHERE
  wr1 : LENGTH(SELF) <= class_code_len;
END_TYPE;
 
TYPE classification_value = INTEGER;
END_TYPE;
 
TYPE code_type = identifier;
WHERE
  wr1 : NOT (SELF LIKE '.*');
  wr2 : NOT (SELF LIKE '*-*');
  wr3 : NOT (SELF LIKE '* *');
  wr4 : NOT (SELF = '');
END_TYPE;
 
TYPE compiler_version_type = identifier;
WHERE
  wr1 : LENGTH(SELF) <= compiler_version_length;
  wr2 : control_compiler_version_format(SELF);
END_TYPE;
 
TYPE complex_value = SELECT 
  (entity_instance_value, level_spec_value, dic_class_instance);
END_TYPE;
 
TYPE content_encoding_type = identifier;
WHERE
  wr1 : (SELF = '7bit') OR (SELF = '8bit') OR (SELF = 'binary') OR (SELF = 
    'quoted-printable') OR (SELF = 'base64');
END_TYPE;
 
TYPE context_dependent_measure = REAL;
END_TYPE;
 
TYPE controlled_entity_instance_value = SELECT 
  (step_entity_instance_value, plib_entity_instance_value);
END_TYPE;
 
TYPE count_measure = NUMBER;
END_TYPE;
 
TYPE currency_code = identifier;
WHERE
  wr1 : LENGTH(SELF) = 3;
END_TYPE;
 
TYPE data_type_code_type = code_type;
WHERE
  wr1 : LENGTH(SELF) = data_type_code_len;
END_TYPE;

TYPE date_time_select = SELECT 
  (date, local_time, date_and_time);
END_TYPE;
 
TYPE date_type = STRING;
END_TYPE;
 
TYPE day_in_month_number = INTEGER;
WHERE
  wr1 : {1 <= SELF <= 31};
END_TYPE;
 
TYPE day_in_week_number = INTEGER;
WHERE
  wr1 : {1 <= SELF <= 7};
END_TYPE;
 
TYPE day_in_year_number = INTEGER;
WHERE
  wr1 : {1 <= SELF <= 366};
END_TYPE;
 
TYPE defined_entity_instance_value = SELECT 
  (placement, axis1_placement, axis2_placement_2d, axis2_placement_3d);
END_TYPE;
 
TYPE definition_type = translatable_text;
END_TYPE;
 
TYPE description_attribute_select = SELECT 
  (application_context, representation);
END_TYPE;

TYPE det_classification_type = identifier;
WHERE
  wr1 : LENGTH(SELF) = det_classification_len;
END_TYPE;
 
TYPE dictionary_code_type = code_type;
WHERE
  wr1 : LENGTH(SELF) <= dictionary_code_len;
END_TYPE;
 
TYPE dimension_count = INTEGER;
WHERE
  wr1 : SELF > 0;
END_TYPE;
 
TYPE document_code_type = code_type;
WHERE
  wr1 : LENGTH(SELF) <= element_code_len;
END_TYPE;
 
TYPE electric_current_measure = REAL;
END_TYPE;
 
TYPE entity_instance_value = SELECT 
  (defined_entity_instance_value, controlled_entity_instance_value, 
  uncontrolled_entity_instance_value);
END_TYPE;
 
TYPE external_file_address = identifier;
WHERE
  wr1 : LENGTH(SELF) <= external_file_address_length;
  wr2 : NOT (SELF LIKE '* *');
END_TYPE;
 
TYPE external_item_code_type = identifier;
WHERE
  wr1 : LENGTH(SELF) <= external_item_code_length;
  wr2 : NOT (SELF LIKE '* *');
END_TYPE;
 
TYPE founded_item_select = SELECT 
  (representation_item);
END_TYPE;
 
TYPE geometric_set_select = SELECT 
  (point);
END_TYPE;
 
TYPE hour_in_day = INTEGER;
WHERE
  wr1 : {0 <= SELF <= 24};
END_TYPE;
 
TYPE http_directory_name_type = identifier;
WHERE
  wr1 : LENGTH(SELF) <= http_directory_name_length;
  wr2 : NOT (SELF LIKE '* *');
END_TYPE;
 
TYPE http_file_name_type = identifier;
WHERE
  wr1 : LENGTH(SELF) <= http_file_name_length;
  wr2 : NOT (SELF LIKE '* *');
  wr3 : NOT (SELF LIKE '.*.*');
  wr4 : NOT (SELF LIKE '.*') AND (
    LENGTH(SELF) <= http_file_name_length - 4) OR (SELF LIKE 
    '.?') AND (LENGTH(SELF) <= 
    http_file_name_length - 2) OR (SELF LIKE 
    '.??') AND (LENGTH(SELF) <= 
    http_file_name_length - 1) OR (SELF LIKE 
    '.???');
END_TYPE;
 
TYPE iab_rfc = INTEGER;
WHERE
  wr1 : SELF > 0;
END_TYPE;
 
TYPE id_attribute_select = SELECT 
  (address, application_context, representation);
END_TYPE;
 
TYPE identifier = STRING;
END_TYPE;
 
TYPE illustration_type = ENUMERATION OF 
  (schematic_drawing, realistic_picture, not_static_picture);
END_TYPE;
 
TYPE integer_type = INTEGER;
END_TYPE;
 
TYPE integer_value = INTEGER;
END_TYPE;
 
TYPE label = STRING;
END_TYPE;
 
TYPE language_code = identifier;
END_TYPE;
 
TYPE length_measure = REAL;
END_TYPE;
 
TYPE level = ENUMERATION OF 
  (min, nom, typ, max);
END_TYPE;
 
TYPE luminous_intensity_measure = REAL;
END_TYPE;
 
TYPE mass_measure = REAL;
END_TYPE;
 
TYPE measure_value = SELECT 
  (length_measure, mass_measure, time_measure, electric_current_measure, 
  thermodynamic_temperature_measure, amount_of_substance_measure, 
  luminous_intensity_measure, plane_angle_measure, solid_angle_measure, 
  area_measure, volume_measure, ratio_measure, parameter_value, numeric_measure
  , context_dependent_measure, positive_length_measure,
  positive_plane_angle_measure, count_measure);
END_TYPE;
 
TYPE mime_subtype = identifier;
WHERE
  wr1 : NOT (SELF LIKE '* *');
END_TYPE;
 
TYPE mime_type = identifier;
WHERE
  wr1 : NOT (SELF LIKE '* *');
END_TYPE;
 
TYPE minute_in_hour = INTEGER;
WHERE
  wr1 : {0 <= SELF <= 59};
END_TYPE;
 
TYPE month_in_year_number = INTEGER;
WHERE
  wr1 : {1 <= SELF <= 12};
END_TYPE;
 
TYPE name_attribute_select = SELECT 
  (address, derived_unit);
END_TYPE;
 
TYPE note_type = translatable_text;
END_TYPE;
 
TYPE null_or_boolean_value = SELECT 
  (null_value, boolean_value);
END_TYPE;
 
TYPE null_or_complex_value = SELECT 
  (null_value, complex_value);
END_TYPE;
 
TYPE null_or_dic_class_instance = SELECT 
  (null_value, dic_class_instance);
END_TYPE;
 
TYPE null_or_entity_instance_value = SELECT 
  (null_value, entity_instance_value);
END_TYPE;
 
TYPE null_or_int_level_spec_value = SELECT 
  (null_value, int_level_spec_value);
END_TYPE;
 
TYPE null_or_integer_value = SELECT 
  (null_value, integer_value);
END_TYPE;
 
TYPE null_or_level_spec_value = SELECT 
  (null_value, level_spec_value);
END_TYPE;
 
TYPE null_or_number_value = SELECT 
  (null_value, number_value);
END_TYPE;
 
TYPE null_or_primitive_value = SELECT 
  (null_value, primitive_value);
END_TYPE;
 
TYPE null_or_real_level_spec_value = SELECT 
  (null_value, real_level_spec_value);
END_TYPE;
 
TYPE null_or_real_value = SELECT 
  (null_value, real_value);
END_TYPE;
 
TYPE null_or_simple_value = SELECT 
  (null_value, simple_value);
END_TYPE;
 
TYPE null_or_translatable_string_value = SELECT 
  (null_value, translatable_string_value);
END_TYPE;
 
TYPE number_value = SELECT 
  (integer_value, real_value);
END_TYPE;
 
TYPE numeric_measure = NUMBER;
END_TYPE;
 
TYPE parameter_value = REAL;
END_TYPE;

 
TYPE plane_angle_measure = REAL;
END_TYPE;
 
TYPE plib_entity_instance_value = SELECT 
  (program_reference, representation_reference, property_value_external_item);
END_TYPE;
 
TYPE positive_length_measure = length_measure;
WHERE
  wr1 : SELF > 0.0;
END_TYPE;
 
TYPE positive_plane_angle_measure = plane_angle_measure;
WHERE
  wr1 : SELF > 0.0;
END_TYPE;

TYPE pref_name_type = translatable_label;
WHERE
  wr1 : check_label_length(SELF, pref_name_len);
END_TYPE;
 
TYPE primitive_value = SELECT 
  (simple_value, complex_value);
END_TYPE;
 
TYPE program_library_code_type = code_type;
WHERE
  wr1 : LENGTH(SELF) <= element_code_len;
END_TYPE;
 
TYPE program_reference_name_type = identifier;
END_TYPE;
 
TYPE program_status = ENUMERATION OF 
  (source, compiled);
END_TYPE;
 
TYPE property_code_type = code_type;
WHERE
  wr1 : LENGTH(SELF) <= property_code_len;
END_TYPE;
 
TYPE property_or_data_type_bsu = SELECT 
  (property_bsu, data_type_bsu);
END_TYPE;
 
TYPE ratio_measure = REAL;
END_TYPE;
 
TYPE real_value = REAL;
END_TYPE;
 
TYPE remark_type = translatable_text;
END_TYPE;
 
TYPE revision_type = code_type;
WHERE
  wr1 : LENGTH(SELF) <= revision_len;
END_TYPE;
 
TYPE second_in_minute = REAL;
WHERE
  wr1 : {0 <= SELF <= 60.0};
END_TYPE;
 
TYPE short_name_type = translatable_label;
WHERE
  wr1 : check_label_length(SELF, short_name_len);
END_TYPE;
 
TYPE si_prefix = ENUMERATION OF 
  (exa, peta, tera, giga, mega, kilo, hecto, deca, deci, centi, milli, micro, 
  nano, pico, femto, atto);
END_TYPE;
 
TYPE si_unit_name = ENUMERATION OF 
  (metre, gram, second, ampere, kelvin, mole, candela, radian, steradian, hertz
  , newton, pascal, joule, watt, coulomb, volt, farad, ohm, siemens, weber, 
  tesla, henry, degree_celsius, lumen, lux, becquerel, gray, sievert);
END_TYPE;
 
TYPE simple_value = SELECT 
  (number_value, translatable_string_value, boolean_value);
END_TYPE;
 
TYPE solid_angle_measure = REAL;
END_TYPE;
 
TYPE source_doc_type = identifier;
WHERE
  wr1 : LENGTH(SELF) <= source_doc_len;
END_TYPE;
 
TYPE step_entity_instance_value = SELECT 
  ( representation, representation_context,
  geometric_representation_context, representation_item, date, date_and_time,
  local_time, calendar_date, ordinal_date, week_of_year_and_day_date, person, 
  organization, address 
);
END_TYPE;
 
TYPE string_value = STRING;
END_TYPE;
 
TYPE supplier_code_type = code_type;
WHERE
  wr1 : LENGTH(SELF) <= supplier_code_len;
END_TYPE;
 
TYPE syn_name_type = SELECT 
  (label_with_language, label);
WHERE
  wr1 : check_syn_length(SELF, syn_name_len);
END_TYPE;
 
TYPE table_code_type = code_type;
WHERE
  wr1 : LENGTH(SELF) <= element_code_len;
END_TYPE;
 
TYPE text = STRING;
END_TYPE;
 
TYPE thermodynamic_temperature_measure = REAL;
END_TYPE;
 
TYPE time_measure = REAL;
END_TYPE;
 
TYPE translatable_label = SELECT 
  (label, translated_label);
END_TYPE;
 
TYPE translatable_string_value = SELECT 
  (string_value, translated_string_value);
END_TYPE;
 
TYPE translatable_text = SELECT 
  (text, translated_text);
END_TYPE;
 
TYPE trimming_select = SELECT 
  (cartesian_point, parameter_value);
END_TYPE;
 
TYPE unit = SELECT 
  (named_unit, derived_unit);
END_TYPE;
 
TYPE value_code_type = identifier;
WHERE
  wr1 : LENGTH(SELF) <= value_code_len;
END_TYPE;
 
TYPE value_format_type = identifier;
WHERE
  wr1 : LENGTH(SELF) <= value_format_len;
END_TYPE;
 
TYPE value_type = SELECT 
  (value_code_type, integer_type);
END_TYPE;
 
TYPE vector_or_direction = SELECT 
  (vector, direction);
END_TYPE;
 
TYPE version_type = code_type;
WHERE
  wr1 : LENGTH(SELF) <= version_len;
  wr2 : EXISTS(VALUE(SELF)) AND ('INTEGER' IN TYPEOF(VALUE(SELF))) AND (VALUE(
    SELF) >= 0);
END_TYPE;
 
TYPE volume_measure = REAL;
END_TYPE;
 
TYPE week_in_year_number = INTEGER;
WHERE
  wr1 : {1 <= SELF <= 53};
END_TYPE;
 
TYPE year_number = INTEGER;
END_TYPE;
 
ENTITY a6_illustration
SUBTYPE OF (illustration);
END_ENTITY;
 
ENTITY a9_illustration
SUBTYPE OF (illustration);
END_ENTITY;
 
ENTITY a_posteriori_case_of
SUBTYPE OF (a_posteriori_semantic_relationship);
  source : class_bsu;
  is_case_of : class_bsu;
  corresponding_properties : SET OF  LIST [2:2] OF property_bsu;
WHERE
  wr1 : definition_available_implies(SELF.source, (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ITEM_CLASS' IN TYPEOF(SELF.source
    .definition[1])) OR (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ABSTRACT_FUNCTIONAL_MODEL_CLASS' 
    IN TYPEOF(SELF.source.definition[1])));
  wr2 : definition_available_implies(SELF.source, (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ITEM_CLASS' IN TYPEOF(SELF.source
    .definition[1])) AND definition_available_implies(SELF.is_case_of, 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ITEM_CLASS' IN TYPEOF(SELF.source
    .definition[1])) OR (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ABSTRACT_FUNCTIONAL_MODEL_CLASS' 
    IN TYPEOF(SELF.source.definition[1])) AND definition_available_implies(SELF
    .is_case_of, 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ABSTRACT_FUNCTIONAL_MODEL_CLASS' 
    IN TYPEOF(SELF.source.definition[1])));
  wr3 : QUERY(couple <* SELF.corresponding_properties | NOT compatible_types(
    couple[1], couple[2])) = [];
  wr4 : QUERY(couple <* SELF.corresponding_properties | NOT 
    applicable_properties(SELF.source, [couple[1]]) OR NOT 
    applicable_properties(SELF.is_case_of, [couple[2]])) = [];
END_ENTITY;
 
ENTITY a_posteriori_semantic_relationship
ABSTRACT SUPERTYPE OF (ONEOF (a_posteriori_case_of, a_posteriori_view_of));
END_ENTITY;
 
ENTITY a_posteriori_view_of
SUBTYPE OF (a_posteriori_semantic_relationship);
  functional_model : class_bsu;
  is_view_of : class_bsu;
  corresponding_properties : SET OF  LIST [2:2] OF property_bsu;
WHERE
  wr1 : definition_available_implies(SELF.functional_model, 
     
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.FUNCTIONAL_MODEL_CLASS' IN TYPEOF
    (SELF.functional_model.definition[1]));
  wr2 : definition_available_implies(SELF.is_view_of, 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ITEM_CLASS' IN TYPEOF(SELF.
    is_view_of.definition[1]));
  wr3 : QUERY(couple <* SELF.corresponding_properties | NOT compatible_types(
    couple[1], couple[2])) = [];
  wr4 : QUERY(couple <* SELF.corresponding_properties | NOT 
    applicable_properties(SELF.functional_model, [couple[1]]) OR NOT 
    applicable_properties(SELF.is_view_of, [couple[2]])) = [];
END_ENTITY;
 
ENTITY a_priori_semantic_relationship
ABSTRACT SUPERTYPE OF (ONEOF (item_class_case_of, fm_class_view_of, 
functional_model_class))
SUBTYPE OF (class);
  referenced_classes : SET [1:?] OF class_bsu;
  referenced_properties :  LIST OF property_bsu;
  referenced_data_types : SET OF data_type_bsu;
  referenced_tables : SET OF table_bsu;
  referenced_documents : SET OF document_bsu;
END_ENTITY;
 
ENTITY abstract_functional_model_class
ABSTRACT SUPERTYPE OF (ONEOF (functional_model_class, fm_class_view_of))
SUBTYPE OF (class);
  created_view : class_bsu;
  v_c_v_range : SET OF view_control_variable_range;
  imported_properties_from_view :  LIST OF property_bsu;
  imported_types_from_view : SET OF data_type_bsu;
  imported_tables_from_view : SET OF table_bsu;
  imported_documents_from_view : SET OF document_bsu;
  case_of : SET OF class_bsu;
  imported_properties_from_models :  LIST OF property_bsu;
  imported_types_from_models : SET OF data_type_bsu;
  imported_tables_from_models : SET OF table_bsu;
  imported_documents_from_models : SET OF document_bsu;
WHERE
  wr1 : created_view_is_functional_view(SELF.created_view);
  wr2 : QUERY(v_c_v <* SELF.v_c_v_range | NOT applicable_properties(SELF.
    created_view, [v_c_v.parameter_type])) = [];
  wr3 : QUERY(v_c_v <* SELF.v_c_v_range | NOT (v_c_v.parameter_type IN SELF.
    imported_properties_from_view)) = [];
  wr4 : NOT EXISTS(SELF\class.its_superclass) OR (
     
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ABSTRACT_FUNCTIONAL_MODEL_CLASS' 
    IN TYPEOF(SELF\class.its_superclass));
  wr5 : QUERY(v_c_v <* SELF.v_c_v_range | SIZEOF(QUERY(v_c_v_2 <* SELF.
    v_c_v_range | v_c_v.parameter_type = v_c_v_2.parameter_type)) <> 1) = [];
  wr6 : QUERY(prop <* SELF\class.described_by | definition_available_implies(
    prop, 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.REPRESENTATION_P_DET' IN TYPEOF(
    prop.definition[1]))) = SELF\class.described_by;
  wr7 : QUERY(cl <* SELF.case_of | definition_available_implies(cl, 
     
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ABSTRACT_FUNCTIONAL_MODEL_CLASS' 
    IN TYPEOF(cl.definition[1]))) = SELF.case_of;
END_ENTITY;
 
ENTITY address;
  internal_location : OPTIONAL label;
  street_number : OPTIONAL label;
  street : OPTIONAL label;
  postal_box : OPTIONAL label;
  town : OPTIONAL label;
  region : OPTIONAL label;
  postal_code : OPTIONAL label;
  country : OPTIONAL label;
  facsimile_number : OPTIONAL label;
  telephone_number : OPTIONAL label;
  electronic_mail_address : OPTIONAL label;
  telex_number : OPTIONAL label;
DERIVE
  name : label := get_name_value(SELF);
  url : identifier := get_id_value(SELF);
WHERE
  wr1 : EXISTS(internal_location) OR EXISTS(street_number) OR EXISTS(street) OR
     EXISTS(postal_box) OR EXISTS(town) OR EXISTS(region) OR EXISTS(postal_code
    ) OR EXISTS(country) OR EXISTS(facsimile_number) OR EXISTS(telephone_number
    ) OR EXISTS(electronic_mail_address) OR EXISTS(telex_number);
END_ENTITY;
 
ENTITY aggregate_entity_instance_value
SUBTYPE OF (uncontrolled_entity_instance_value);
  the_value : aggregate_value;
END_ENTITY;
 
ENTITY aggregate_type
ABSTRACT SUPERTYPE OF (ONEOF (list_type, set_type, bag_type, array_type, 
set_with_subset_constraint_type));
  bound_1 : OPTIONAL INTEGER;
  bound_2 : OPTIONAL INTEGER;
  value_type : data_type;
WHERE
  wr1 : bound_1 <= bound_2;
END_ENTITY;
 
ENTITY aggregate_value
ABSTRACT SUPERTYPE OF (ONEOF (list_value, set_value, bag_value, array_value, 
set_with_subset_constraint_value));
  values :  LIST OF null_or_primitive_value;
END_ENTITY;

ENTITY application_context;
  application : label;
DERIVE
  description : text := get_description_value(SELF);
  id : identifier := get_id_value(SELF);
INVERSE
  context_elements : SET [1:?] OF application_context_element FOR 
  frame_of_reference;
WHERE
  wr1 : SIZEOF(USEDIN(SELF, 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.DESCRIPTION_ATTRIBUTE.DESCRIBED_ITEM'
    )) <= 1;
  wr2 : SIZEOF(USEDIN(SELF, 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ID_ATTRIBUTE.IDENTIFIED_ITEM'))
     <= 1;
END_ENTITY;
 
ENTITY application_context_element;
  name : label;
  frame_of_reference : application_context;
END_ENTITY;
 
ENTITY application_protocol_definition;
  status : label;
  application_interpreted_model_SCHEMA_name : label;
  application_protocol_year : year_number;
  application : application_context;
END_ENTITY;

ENTITY array_type
SUBTYPE OF (aggregate_type);
  SELF\aggregate_type.bound_1 : INTEGER;
  SELF\aggregate_type.bound_2 : INTEGER;
  uniqueness : BOOLEAN;
  are_optional : BOOLEAN;
END_ENTITY;
 
ENTITY array_value
SUBTYPE OF (aggregate_value);
  bound_1 : INTEGER;
  bound_2 : INTEGER;
WHERE
  wr1 : SIZEOF(SELF\aggregate_value.values) = SELF.bound_2 - SELF.bound_1 + 1;
END_ENTITY;
 
ENTITY axis1_placement
SUBTYPE OF (placement);
  axis : OPTIONAL direction;
DERIVE
  z : direction := NVL(normalise(axis), dummy_gri||direction([0.0, 0.0, 1.0]));
WHERE
  wr1 : SELF\geometric_representation_item.dim = 3;
END_ENTITY;
 
ENTITY axis1_placement_type
SUBTYPE OF (placement_type);
WHERE
  wr1 : 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.AXIS1_PLACEMENT' IN SELF\
    entity_instance_type.type_name;
END_ENTITY;
 
ENTITY axis2_placement_2d
SUBTYPE OF (placement);
  ref_direction : OPTIONAL direction;
DERIVE
  p :  LIST [2:2] OF direction := build_2axes(ref_direction);
WHERE
  wr1 : SELF\geometric_representation_item.dim = 2;
END_ENTITY;
 
ENTITY axis2_placement_2d_type
SUBTYPE OF (placement_type);
WHERE
  wr1 : 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.AXIS2_PLACEMENT_2D' IN SELF\
    entity_instance_type.type_name;
END_ENTITY;
 
ENTITY axis2_placement_3d
SUBTYPE OF (placement);
  axis : OPTIONAL direction;
  ref_direction : OPTIONAL direction;
DERIVE
  p :  LIST [3:3] OF direction := build_axes(axis, ref_direction);
WHERE
  wr1 : SELF\placement.location.dim = 3;
  wr2 : NOT EXISTS(axis) OR (axis.dim = 3);
  wr3 : NOT EXISTS(ref_direction) OR (ref_direction.dim = 3);
  wr4 : NOT EXISTS(axis) OR NOT EXISTS(ref_direction) OR (cross_product(axis, 
    ref_direction).magnitude > 0.0);
END_ENTITY;
 
ENTITY axis2_placement_3d_type
SUBTYPE OF (placement_type);
WHERE
  wr1 : 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.AXIS2_PLACEMENT_3D' IN SELF\
    entity_instance_type.type_name;
END_ENTITY;
 
ENTITY bag_type
SUBTYPE OF (aggregate_type);
WHERE
  wr1 : EXISTS(bound_1) OR NOT EXISTS(bound_2);
  wr2 : NOT EXISTS(bound_1) OR (bound_1 >= 0);
END_ENTITY;
 
ENTITY bag_value
SUBTYPE OF (aggregate_value);
  SELF\aggregate_value.values :  LIST OF primitive_value;
END_ENTITY;
 
ENTITY basic_semantic_unit
ABSTRACT SUPERTYPE OF (ONEOF (supplier_bsu, class_bsu, property_bsu, 
data_type_bsu, supplier_related_bsu, class_related_bsu));
  code : code_type;
  version : version_type;
DERIVE
  dic_identifier : identifier := code + sep_cv + version;
INVERSE
  definition : SET [0:1] OF dictionary_element FOR identified_by;
  referenced_by : SET [0:1] OF content_item FOR dictionary_definition;
END_ENTITY;
 
ENTITY boolean_type
SUBTYPE OF (simple_type);
END_ENTITY;
 
ENTITY calendar_date
SUBTYPE OF (date);
  day_component : day_in_month_number;
  month_component : month_in_year_number;
WHERE
  wr1 : valid_calendar_date(SELF);
END_ENTITY;
 
ENTITY cartesian_point
SUBTYPE OF (point);
  coordinates :  LIST [1:3] OF length_measure;
END_ENTITY;
 
ENTITY class
ABSTRACT SUPERTYPE OF (item_class)
SUBTYPE OF (class_and_property_elements);
  SELF\dictionary_element.identified_by : class_bsu;
  its_superclass : OPTIONAL class_bsu;
  described_by :  LIST OF UNIQUE property_bsu;
  defined_types : SET OF data_type_bsu;
DERIVE
  subclasses : SET OF class := identified_by.subclasses;
  known_applicable_properties : SET OF property_bsu := 
  compute_known_applicable_properties(SELF\dictionary_element.identified_by);
  known_applicable_data_types : SET OF data_type_bsu := 
  compute_known_applicable_data_types(SELF\dictionary_element.identified_by);
INVERSE
  associated_items : SET OF class_bsu_relationship FOR relating_class;
WHERE
  wr1 : acyclic_superclass_relationship(SELF.identified_by, []);
  wr2 : NOT all_class_descriptions_reachable(SELF\dictionary_element.
    identified_by) OR (list_to_set(SELF.described_by) <= SELF\
    dictionary_element.identified_by\class_bsu.known_visible_properties);
  wr3 : NOT all_class_descriptions_reachable(SELF\dictionary_element.
    identified_by) OR (SELF.defined_types <= SELF\dictionary_element.
    identified_by\class_bsu.known_visible_data_types);
  wr4 : check_properties_applicability(SELF);
  wr5 : check_datatypes_applicability(SELF);
END_ENTITY;
 
ENTITY class_and_property_elements
ABSTRACT SUPERTYPE OF (ONEOF (property_det, class))
SUBTYPE OF (dictionary_element);
  names : item_names;
  definition : definition_type;
  source_doc_of_definition : OPTIONAL document;
  note : OPTIONAL note_type;
  remark : OPTIONAL remark_type;
END_ENTITY;
 
ENTITY class_bsu
SUBTYPE OF (basic_semantic_unit);
  SELF\basic_semantic_unit.code : class_code_type;
  defined_by : supplier_bsu;
DERIVE
  absolute_id : identifier := defined_by.absolute_id + sep_id + dic_identifier;
  known_visible_properties : SET OF property_bsu := 
  compute_known_visible_properties(SELF);
  known_visible_data_types : SET OF data_type_bsu := 
  compute_known_visible_data_types(SELF);
INVERSE
  subclasses : SET OF class FOR its_superclass;
  added_visible_properties : SET OF property_bsu FOR name_scope;
  added_visible_data_types : SET OF data_type_bsu FOR name_scope;
UNIQUE
  ur1 : absolute_id;
END_ENTITY;
 
ENTITY class_bsu_related_content
ABSTRACT SUPERTYPE OF (document_content)
SUBTYPE OF (dictionary_external_item);
  SELF\content_item.dictionary_definition : class_related_bsu;
END_ENTITY;
 
ENTITY class_bsu_relationship ABSTRACT SUPERTYPE;
  relating_class : class;
  related_tokens : SET [1:?] OF class_related_bsu;
END_ENTITY;
 
ENTITY class_document_relationship
SUBTYPE OF (class_bsu_relationship);
  SELF\class_bsu_relationship.related_tokens : SET [1:?] OF document_bsu;
WHERE
  wr1 : visible_documents(SELF\class_bsu_relationship.relating_class.
    identified_by, SELF.related_tokens);
END_ENTITY;
 
ENTITY class_extension
ABSTRACT SUPERTYPE OF (ONEOF (model_class_extension))
SUBTYPE OF (content_item);
  SELF\content_item.dictionary_definition : class_bsu;
END_ENTITY;
 
ENTITY class_extension_external_item
ABSTRACT SUPERTYPE OF (ONEOF (dialogue_resource, representation_reference, 
program_reference))
SUBTYPE OF (external_item);
  code : external_item_code_type;
INVERSE
  belongs_to : model_class_extension FOR referenced_external_items;
UNIQUE
  ur1 : code, belongs_to;
END_ENTITY;
 
ENTITY class_instance_type
SUBTYPE OF (complex_type);
  domain : class_bsu;
END_ENTITY;
 
ENTITY class_related_bsu ABSTRACT SUPERTYPE
SUBTYPE OF (basic_semantic_unit);
END_ENTITY;
 
ENTITY class_related_dictionary_element
ABSTRACT SUPERTYPE OF (ONEOF (document_element))
SUBTYPE OF (dictionary_element);
  SELF\dictionary_element.identified_by : class_related_bsu;
  names : item_names;
  definition : definition_type;
  note : OPTIONAL note_type;
  remark : OPTIONAL remark_type;
END_ENTITY;
 
ENTITY class_value_assignment;
  super_class_defined_property : property_bsu;
  assigned_value : value_code_type;
WHERE
  wr1 : definition_available_implies(super_class_defined_property, 
     
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NON_QUANTITATIVE_CODE_TYPE' IN 
    TYPEOF(super_class_defined_property.definition[1]\property_det.domain));
  wr2 : definition_available_implies(super_class_defined_property, SIZEOF(
    QUERY(v <* super_class_defined_property.definition[1]\property_det.domain\
    non_quantitative_code_type.domain.its_values | assigned_value = v.
    value_code)) = 1);
END_ENTITY;
 
ENTITY complex_type
ABSTRACT SUPERTYPE OF (ONEOF (level_type, class_instance_type, 
entity_instance_type))
SUBTYPE OF (data_type);
END_ENTITY;
 
ENTITY component_class
SUBTYPE OF (item_class);
END_ENTITY;
 
ENTITY component_class_case_of
SUBTYPE OF (item_class_case_of, component_class);
WHERE
  wr1 : check_is_case_of_referenced_classes_definition(SELF);
END_ENTITY;
 
ENTITY condition_det
SUBTYPE OF (property_det);
END_ENTITY;
 
ENTITY content_item ABSTRACT SUPERTYPE;
  dictionary_definition : basic_semantic_unit;
END_ENTITY;
 
ENTITY context_dependent_property_value
SUBTYPE OF (property_value);
  the_context :  LIST [1:?] OF property_value;
WHERE
  wr1 : QUERY(c <* SELF.the_context | NOT is_condition_det(c)) = [];
  wr2 : is_dependent_p_det(SELF\property_value.prop_def);
  wr3 : all_context_parameters_referenced(SELF);
END_ENTITY;
 
ENTITY context_dependent_unit
SUBTYPE OF (named_unit);
  name : label;
END_ENTITY;
 
ENTITY conversion_based_unit
SUBTYPE OF (named_unit);
  name : label;
  conversion_factor : measure_with_unit;
END_ENTITY;
 
ENTITY coordinated_universal_time_offset;
  hour_offset : INTEGER;
  minute_offset : OPTIONAL INTEGER;
  sense : ahead_or_behind;
DERIVE
  actual_minute_offset : INTEGER := NVL(minute_offset, 0);
WHERE
  wr1 : {0 <= hour_offset <= 24};
  wr2 : {0 <= actual_minute_offset <= 59};
  wr3 : NOT (((hour_offset <> 0) OR (actual_minute_offset <> 0)) AND (sense = 
    exact));
END_ENTITY;
 
ENTITY data_exchange_specification_identification
ABSTRACT SUPERTYPE OF (ONEOF (library_iim_identification, 
view_exchange_protocol_identification));
  source_document_identifier : OPTIONAL identifier;
  status : label;
  name : identifier;
  date : year_number;
  application : OPTIONAL identifier;
  level : OPTIONAL identifier;
  external_file_protocols : SET OF external_file_protocol;
END_ENTITY;
 
ENTITY data_protocol
ABSTRACT SUPERTYPE OF (ONEOF (standard_data_protocol, 
non_standard_data_protocol))
SUBTYPE OF (external_file_protocol);
END_ENTITY;
 
ENTITY data_type
ABSTRACT SUPERTYPE OF (ONEOF (simple_type, complex_type, named_type));
END_ENTITY;
 
ENTITY data_type_bsu
SUBTYPE OF (basic_semantic_unit);
  SELF\basic_semantic_unit.code : data_type_code_type;
  name_scope : class_bsu;
DERIVE
  absolute_id : identifier := name_scope.defined_by.absolute_id + sep_id + 
  name_scope.dic_identifier + sep_id + dic_identifier;
INVERSE
  defining_class : SET OF class FOR defined_types;
UNIQUE
  absolute_id;
WHERE
  wr1 : is_subclass(defining_class[1], name_scope.definition[1]);
END_ENTITY;
 
ENTITY data_type_element
SUBTYPE OF (dictionary_element);
  SELF\dictionary_element.identified_by : data_type_bsu;
  names : item_names;
  type_definition : data_type;
END_ENTITY;
 
ENTITY date
SUPERTYPE OF (ONEOF (calendar_date, ordinal_date, week_of_year_and_day_date));
  year_component : year_number;
END_ENTITY;
 
ENTITY date_and_time;
  date_component : date;
  time_component : local_time;
END_ENTITY;
 
ENTITY dates;
  date_of_original_definition : date_type;
  date_of_current_version : date_type;
  date_of_current_revision : OPTIONAL date_type;
END_ENTITY;
 
ENTITY dependent_p_det
SUBTYPE OF (property_det);
  depends_on : SET [1:?] OF property_bsu;
WHERE
  wr1 : QUERY(p <* depends_on | NOT definition_available_implies(p, 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CONDITION_DET' IN TYPEOF(p.
    definition[1]))) = [];
END_ENTITY;
 
ENTITY derived_unit;
  elements : SET [1:?] OF derived_unit_element;
DERIVE
  name : label := get_name_value(SELF);
WHERE
  wr1 : (SIZEOF(elements) > 1) OR (SIZEOF(elements) = 1) AND (elements[1].
    exponent <> 1.0);
  wr2 : SIZEOF(USEDIN(SELF, 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NAME_ATTRIBUTE.NAMED_ITEM')) <= 1
    ;
END_ENTITY;
 
ENTITY derived_unit_element;
  unit : named_unit;
  exponent : REAL;
END_ENTITY;
 
ENTITY description_attribute;
  attribute_value : text;
  described_item : description_attribute_select;
END_ENTITY;
 
ENTITY dialogue_resource
ABSTRACT SUPERTYPE OF (ONEOF (message, illustration))
SUBTYPE OF (class_extension_external_item);
  SELF\external_item.used_protocol : data_protocol;
END_ENTITY;
 
ENTITY dic_class_instance
ABSTRACT SUPERTYPE OF (ONEOF (dic_item_instance, dic_f_model_instance, dic_f_view_instance));
  class_def : class_bsu;
  properties :  LIST OF property_value;
  case_of : SET OF class_bsu;
WHERE
  wr1 : QUERY(prop <* SELF.properties | NOT applicable_properties(SELF.
    class_def, [prop.prop_def])) = [];
  wr2 : QUERY(prop <* SELF.properties | SIZEOF(QUERY(prop1 <* SELF.properties
     | prop1.prop_def = prop.prop_def)) = 1) = SELF.properties;
  wr3 : check_property_values_translations(QUERY(prop_val <* properties | 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.' + 'TRANSLATED_STRING_VALUE' IN 
    TYPEOF(prop_val.its_value)));
END_ENTITY;
 
ENTITY dic_component_instance
SUPERTYPE OF (lib_component_instance)
SUBTYPE OF (dic_item_instance);
WHERE
  wr1 : check_class_type_for_dic_item_instance(SELF);
END_ENTITY;
 
ENTITY dic_f_model_instance
SUPERTYPE OF (lib_f_model_instance)
SUBTYPE OF (dic_class_instance);
WHERE
  wr1 : check_class_type_for_dic_f_model_instance(SELF);
  wr2 : compatible_model_caseof_with_class_definition(SELF);
END_ENTITY;

ENTITY dic_f_view_instance
SUBTYPE OF(dic_class_instance, representation);
	generated_by: OPTIONAL dic_f_model_instance;
	view_of: OPTIONAL dic_item_instance;
DERIVE
	SELF\dic_class_instance.case_of: SET OF class_BSU := [];
WHERE
	WR1: check_class_type_for_dic_f_view_instance(SELF);
	WR2: NOT all_class_descriptions_reachable(
		SELF\dic_class_instance.class_def)
		OR (QUERY(prop <* functional_view_v_c_v(
		SELF\dic_class_instance.class_def)
		| SIZEOF(QUERY(prop2 <* SELF.properties
		| prop2.prop_def = prop))<>1) = []);
	WR3: correct_view_from_model(SELF);
END_ENTITY; -- dic_f_view_instance
 
ENTITY dic_feature_instance
SUPERTYPE OF (lib_feature_instance)
SUBTYPE OF (dic_item_instance);
WHERE
  wr1 : check_class_type_for_dic_item_instance(SELF);
END_ENTITY;
 
ENTITY dic_item_instance
SUPERTYPE OF (ONEOF (dic_component_instance, dic_material_instance, 
dic_feature_instance) ANDOR lib_item_instance)
SUBTYPE OF (dic_class_instance);
WHERE
  wr1 : check_class_type_for_dic_item_instance(SELF);
  wr2 : QUERY(prop <* SELF.properties | (SIZEOF(prop.prop_def.definition) = 1) 
    AND ( 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.DEPENDENT_P_DET' IN TYPEOF(prop.
    prop_def.definition[1])) AND (prop.prop_def.definition[1]\dependent_p_det.
    depends_on >= collects_property_context(prop.prop_def, SELF))) = [];
  wr3 : compatible_item_caseof_with_class_definition(SELF);
END_ENTITY;
 
ENTITY dic_material_instance
SUPERTYPE OF (lib_material_instance)
SUBTYPE OF (dic_item_instance);
WHERE
  wr1 : check_class_type_for_dic_item_instance(SELF);
END_ENTITY;
 
ENTITY dic_unit;
  structured_representation : unit;
  string_representation : OPTIONAL mathematical_string;
END_ENTITY;
 
ENTITY dic_value;
  value_code : value_type;
  meaning : item_names;
  source_doc_of_value : OPTIONAL document;
END_ENTITY;
 
ENTITY dictionary
SUPERTYPE OF (dictionary_in_standard_format);
  identified_by : OPTIONAL dictionary_identification;
  is_complete : OPTIONAL BOOLEAN;
  updates : OPTIONAL dictionary_identification;
  update_agreement : OPTIONAL identifier;
  referenced_dictionaries : SET OF dictionary_identification;
  responsible_supplier : supplier_bsu;
  library_structure : library_iim_identification;
  base_protocols : SET OF external_file_protocol;
  supported_vep : SET OF view_exchange_protocol_identification;
  referred_suppliers : SET [1:?] OF supplier_bsu;
  contained_classes :  LIST OF UNIQUE class_bsu;
  a_posteriori_semantic_relationships : SET OF 
  a_posteriori_semantic_relationship;
  names : item_names;
  note : OPTIONAL note_type;
  remark : OPTIONAL remark_type;
WHERE
  wr1 : prefix_ordered_class_list(SELF.contained_classes);
  wr2 : EXISTS(identified_by) AND EXISTS(is_complete) OR NOT EXISTS(
    identified_by) AND NOT EXISTS(is_complete);
  wr3 : NOT EXISTS(identified_by) OR (SELF.identified_by.defined_by = SELF.
    responsible_supplier);
  wr4 : NOT EXISTS(updates) OR EXISTS(identified_by) AND (is_complete = FALSE);
  wr5 : NOT EXISTS(update_agreement) OR EXISTS(updates);
  wr6 : NOT EXISTS(updates) OR (updates.code = identified_by.code) AND (updates
    .defined_by = identified_by.defined_by) AND (updates.version <= 
    identified_by.version) AND (NOT (updates.version = identified_by.version) 
    OR (updates.revision < identified_by.revision));
END_ENTITY;
 
ENTITY dictionary_element
ABSTRACT SUPERTYPE OF (ONEOF (supplier_element, class_and_property_elements, 
data_type_element));
  identified_by : basic_semantic_unit;
  time_stamps : OPTIONAL dates;
  revision : revision_type;
END_ENTITY;
 
ENTITY dictionary_external_item
ABSTRACT SUPERTYPE OF (ONEOF (supplier_bsu_related_content, 
class_bsu_related_content))
SUBTYPE OF (content_item, external_item);
  revision : revision_type;
END_ENTITY;
 
ENTITY dictionary_identification;
  code : dictionary_code_type;
  version : version_type;
  revision : revision_type;
  defined_by : supplier_bsu;
DERIVE
  absolute_id : identifier := defined_by.absolute_id + sep_id + code + sep_cv
   + version;
INVERSE
  definition : SET [0:1] OF dictionary FOR identified_by;
UNIQUE
  ur1 : absolute_id;
END_ENTITY;
 
ENTITY dictionary_in_standard_format
SUBTYPE OF (dictionary);
WHERE
  wr1 : QUERY(int <* SELF\dictionary.base_protocols | (SIZEOF(QUERY(vep <* SELF
    \dictionary.supported_vep | int IN vep\
    data_exchange_specification_identification.external_file_protocols)) = 0) 
    AND NOT (int IN SELF\dictionary.library_structure.external_file_protocols))
     = [];
END_ENTITY;
 
ENTITY dimensional_exponents;
  length_exponent : REAL;
  mass_exponent : REAL;
  time_exponent : REAL;
  electric_current_exponent : REAL;
  thermodynamic_temperature_exponent : REAL;
  amount_of_substance_exponent : REAL;
  luminous_intensity_exponent : REAL;
END_ENTITY;
 
ENTITY direction
SUBTYPE OF (geometric_representation_item);
  direction_ratios :  LIST [2:3] OF REAL;
WHERE
  wr1 : SIZEOF(QUERY(tmp <* direction_ratios | tmp <> 0.0)) > 0;
END_ENTITY;
 
ENTITY document ABSTRACT SUPERTYPE;
END_ENTITY;
 
ENTITY document_bsu
SUBTYPE OF (class_related_bsu);
  name_scope : class_bsu;
  SELF\basic_semantic_unit.code : document_code_type;
DERIVE
  absolute_id : identifier := name_scope.defined_by.dic_identifier + sep_id + 
  name_scope.dic_identifier + sep_id + dic_identifier;
INVERSE
  associate_to_class : class_bsu_relationship FOR related_tokens;
UNIQUE
  ur1 : absolute_id;
END_ENTITY;
 
ENTITY document_content
SUBTYPE OF (class_bsu_related_content);
  SELF\content_item.dictionary_definition : document_bsu;
  SELF\external_item.used_protocol : data_protocol;
END_ENTITY;
 
ENTITY document_element
SUPERTYPE OF (ONEOF (document_element_with_http_access, 
document_element_with_translated_http_access))
SUBTYPE OF (class_related_dictionary_element);
  SELF\dictionary_element.identified_by : document_bsu;
  authors : OPTIONAL  LIST [1:?] OF person;
  publishing_organisation : organization;
END_ENTITY;
 
ENTITY document_element_with_http_access
SUBTYPE OF (document_element);
  remote_location : absolute_url_type;
END_ENTITY;
 
ENTITY document_element_with_translated_http_access
SUBTYPE OF (document_element);
  remote_locations :  LIST [1:?] OF absolute_url_type;
  languages : present_translations;
WHERE
  wr1 : SIZEOF(remote_locations) = SIZEOF(languages.language_codes);
END_ENTITY;

ENTITY entity_instance_type
SUBTYPE OF (complex_type);
  type_name : SET OF STRING;
END_ENTITY;
 
ENTITY entity_instance_type_for_aggregate
SUBTYPE OF (entity_instance_type);
  type_structure : aggregate_type;
WHERE
  wr1 : SELF\entity_instance_type.type_name = [
     
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.AGGREGATE_TYPE'];
END_ENTITY;
 
ENTITY explicit_functional_model_class_extension
SUBTYPE OF (explicit_model_class_extension);
  measure_unit : OPTIONAL global_unit_assigned_context;
  required_item_values : SET OF property_bsu;
  referenced_representation : OPTIONAL property_bsu;
  available_views_icon : OPTIONAL a6_illustration;
  available_views_msg : OPTIONAL message;
  context_param_icon :  LIST OF a6_illustration;
  context_param_msg : OPTIONAL message;
WHERE
  wr1 : definition_available_implies(SELF\content_item.dictionary_definition, 
     
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ABSTRACT_FUNCTIONAL_MODEL_CLASS' 
    IN TYPEOF(SELF\content_item.dictionary_definition.definition[1]));
  wr2 : required_values_are_non_dependent_p_det(SELF);
  wr3 : required_values_are_imported_properties(SELF);
  wr4 : SELF.required_item_values <= list_to_set(SELF\
    explicit_model_class_extension.instance_identification);
  wr5 : NOT EXISTS(SELF.available_views_icon) OR (SELF.available_views_icon IN 
    SELF\model_class_extension.referenced_external_items);
  wr6 : NOT EXISTS(SELF.available_views_msg) OR (SELF.available_views_msg IN 
    SELF\model_class_extension.referenced_external_items);
  wr7 : list_to_set(SELF.context_param_icon) <= SELF\model_class_extension.
    referenced_external_items;
  wr8 : NOT EXISTS(SELF.context_param_msg) OR (SELF.context_param_msg IN SELF\
    model_class_extension.referenced_external_items);
  wr9 : exists_representation_for_instanciable_view(SELF);
  wr10 : all_view_control_variables_belong_to_each_view(SELF);
  wr11 : QUERY(a_view <* SELF\explicit_model_class_extension.POPULATION | NOT (
     
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.DIC_F_MODEL_INSTANCE' IN TYPEOF(
    a_view))) = [];
  wr12 : all_vcvs_belong_to_instance_identification(SELF);
  wr13 : NOT EXISTS(referenced_representation) OR (QUERY(inst <* SELF.
    POPULATION | NOT is_provided_once_property_value(inst, 
    referenced_representation)) = []);
  wr14 : NOT EXISTS(referenced_representation) OR (QUERY(inst <* SELF.
    POPULATION | NOT (number_of_instance_representations(inst) = 1)) = []);
  wr15 : EXISTS(referenced_representation) OR (QUERY(inst <* SELF.POPULATION | 
    NOT (number_of_instance_representations(inst) = 0)) = []);
  wr16 : NOT EXISTS(referenced_representation) OR (SIZEOF(
    referenced_representation.definition) = 0) OR NOT (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.' + 'PROGRAM_REFERENCE_TYPE' IN 
    data_type_typeof(referenced_representation)) OR (QUERY(inst <* SELF.
    POPULATION | NOT correct_parameters_for_explicit_program(inst, 
    referenced_representation)) = []);
END_ENTITY;
 
ENTITY explicit_item_class_extension
SUBTYPE OF (explicit_model_class_extension);
  access_icon : OPTIONAL a9_illustration;
  content_msg : OPTIONAL message;
  create_icon :  LIST OF a6_illustration;
  create_msg : OPTIONAL message;
  class_presentation_on_paper :  LIST OF illustration;
  class_presentation_on_screen :  LIST OF illustration;
WHERE
  wr1 : QUERY(inst <* SELF\explicit_model_class_extension.POPULATION | NOT (
     
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.DIC_ITEM_INSTANCE' IN TYPEOF(inst
    ))) = [];
  wr2 : definition_available_implies(SELF\content_item.dictionary_definition, 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ITEM_CLASS' IN TYPEOF(SELF\
    content_item.dictionary_definition.definition[1]));
  wr3 : NOT EXISTS(SELF.access_icon) OR (SELF.access_icon IN SELF\
    model_class_extension.referenced_external_items);
  wr4 : NOT EXISTS(SELF.content_msg) OR (SELF.content_msg IN SELF\
    model_class_extension.referenced_external_items);
  wr5 : list_to_set(SELF.create_icon) <= SELF\model_class_extension.
    referenced_external_items;
  wr6 : NOT EXISTS(SELF.create_msg) OR (SELF.create_msg IN SELF\
    model_class_extension.referenced_external_items);
  wr7 : list_to_set(SELF.class_presentation_on_paper) <= SELF\
    model_class_extension.referenced_external_items;
  wr8 : list_to_set(SELF.class_presentation_on_screen) <= SELF\
    model_class_extension.referenced_external_items;
  wr9 : QUERY(icon <* SELF.class_presentation_on_paper | NOT EXISTS(icon.width)
     OR (icon.kind_of_content = illustration_type.not_static_picture)) = [];
  wr10 : QUERY(icon <* SELF.class_presentation_on_screen | NOT EXISTS(icon.
    width)) = [];
END_ENTITY;
 
ENTITY explicit_model_class_extension
ABSTRACT SUPERTYPE OF (ONEOF (explicit_item_class_extension, 
explicit_functional_model_class_extension))
SUBTYPE OF (model_class_extension);
  instance_identification :  LIST [1:?] OF UNIQUE property_bsu;
  POPULATION :  LIST [1:?] OF UNIQUE dic_class_instance;
  table_like : BOOLEAN;
WHERE
  wr1 : NOT table_like OR (QUERY(inst <* SELF.POPULATION | NOT 
    same_order_for_properties(POPULATION[1].properties, inst.properties)) = [])
    ;
  wr2 : applicable_properties(SELF\content_item.dictionary_definition, 
    list_to_set(SELF.instance_identification));
  wr3 : all_properties_are_applicable(SELF);
  wr4 : same_string_values_translations_for_class_extension(SELF);
  wr5 : QUERY(inst <* SELF.POPULATION | inst.class_def :<>: SELF\content_item.
    dictionary_definition) = [];
  wr6 : QUERY(inst <* SELF.POPULATION | NOT (QUERY(prop <* inst.properties | 
    NOT EXISTS(prop.its_value) AND (prop.prop_def IN SELF.
    instance_identification)) = [])) = [];
END_ENTITY;
 
ENTITY external_content
ABSTRACT SUPERTYPE OF (ONEOF (translated_external_content, 
not_translated_external_content, not_translatable_external_content));
  consists_of :  LIST [1:?] OF language_specific_content;
INVERSE
  content_of : external_item FOR content;
END_ENTITY;
 
ENTITY external_file_protocol
ABSTRACT SUPERTYPE OF (ONEOF (standard_protocol, non_standard_protocol) ANDOR 
ONEOF (program_protocol, data_protocol));
  organisation : organization;
  country : OPTIONAL identifier;
  protocol_name : identifier;
  protocol_version : identifier;
  level : OPTIONAL identifier;
  designation : item_names;
  base_protocol : OPTIONAL program_protocol;
WHERE
  wr1 : NOT (SELF.protocol_name LIKE '* *') AND NOT (SELF.protocol_name LIKE 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.*') AND NOT (SELF.protocol_name 
    LIKE '*-*');
  wr2 : NOT (SELF.protocol_version LIKE '* *');
END_ENTITY;
 
ENTITY external_file_unit
SUPERTYPE OF (http_file);
  file : external_file_address;
  content_encoding : OPTIONAL content_encoding_type;
INVERSE
  unit_of : language_specific_content FOR content_files;
WHERE
  wr1 : ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.HTTP_PROTOCOL' IN TYPEOF(
    SELF.unit_of.content_of.content_of.used_protocol)) AND (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.HTTP_FILE' IN TYPEOF(SELF)) XOR 
    NOT (('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.HTTP_PROTOCOL' IN TYPEOF(
    SELF.unit_of.content_of.content_of.used_protocol)) OR (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.HTTP_FILE' IN TYPEOF(SELF)));
END_ENTITY;
 
ENTITY external_item
ABSTRACT SUPERTYPE OF (ONEOF (dictionary_external_item, 
class_extension_external_item, property_value_external_item));
  used_protocol : external_file_protocol;
  content : external_content;
END_ENTITY;
 
ENTITY feature_class
SUBTYPE OF (item_class);
WHERE
  wr1 : NOT ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.' + 'COMPONENT_CLASS' IN
     TYPEOF(SELF));
  wr2 : NOT ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.' + 'MATERIAL_CLASS' IN 
    TYPEOF(SELF));
END_ENTITY;
 
ENTITY feature_class_case_of
SUBTYPE OF (item_class_case_of, feature_class);
WHERE
  wr1 : check_is_case_of_referenced_classes_definition(SELF);
END_ENTITY;
 
ENTITY fm_class_view_of
SUBTYPE OF (a_priori_semantic_relationship, abstract_functional_model_class);
  view_of : class_bsu;
  imported_properties_from_item :  LIST OF property_bsu;
  imported_types_from_item : SET OF data_type_bsu;
  imported_tables_from_item : SET OF table_bsu;
  imported_documents_from_item : SET OF document_bsu;
DERIVE
  SELF\a_priori_semantic_relationship.referenced_classes : SET [2:2] OF 
  class_bsu := [SELF\abstract_functional_model_class.created_view, SELF.view_of
  ] + SELF\abstract_functional_model_class.case_of;
  SELF\a_priori_semantic_relationship.referenced_properties :  LIST OF 
  property_bsu := SELF\abstract_functional_model_class.
  imported_properties_from_view + SELF\abstract_functional_model_class.
  imported_properties_from_models + SELF.imported_properties_from_item;
  SELF\a_priori_semantic_relationship.referenced_data_types : SET OF 
  data_type_bsu := SELF\abstract_functional_model_class.
  imported_types_from_view + SELF\abstract_functional_model_class.
  imported_types_from_models + SELF.imported_types_from_item;
  SELF\a_priori_semantic_relationship.referenced_tables : SET OF table_bsu := 
  SELF\abstract_functional_model_class.imported_tables_from_view + SELF\
  abstract_functional_model_class.imported_tables_from_models + SELF.
  imported_tables_from_item;
  SELF\a_priori_semantic_relationship.referenced_documents : SET OF 
  document_bsu := SELF\abstract_functional_model_class.
  imported_documents_from_view + SELF\abstract_functional_model_class.
  imported_documents_from_models + SELF.imported_documents_from_item;
WHERE
  wr1 : check_view_of_instance_datatype(SELF);
END_ENTITY;
 
ENTITY functional_model_class
SUBTYPE OF (a_priori_semantic_relationship, abstract_functional_model_class);
DERIVE
  SELF\a_priori_semantic_relationship.referenced_classes : SET [1:?] OF 
  class_bsu := [SELF\abstract_functional_model_class.created_view] + SELF\
  abstract_functional_model_class.case_of;
  SELF\a_priori_semantic_relationship.referenced_properties :  LIST OF 
  property_bsu := SELF\abstract_functional_model_class.
  imported_properties_from_view + SELF\abstract_functional_model_class.
  imported_properties_from_models;
  SELF\a_priori_semantic_relationship.referenced_data_types : SET OF 
  data_type_bsu := SELF\abstract_functional_model_class.
  imported_types_from_view + SELF\abstract_functional_model_class.
  imported_types_from_models;
  SELF\a_priori_semantic_relationship.referenced_tables : SET OF table_bsu := 
  SELF\abstract_functional_model_class.imported_tables_from_view + SELF\
  abstract_functional_model_class.imported_tables_from_models;
  SELF\a_priori_semantic_relationship.referenced_documents : SET OF 
  document_bsu := SELF\abstract_functional_model_class.
  imported_documents_from_view + SELF\abstract_functional_model_class.
  imported_documents_from_models;
END_ENTITY;
 
ENTITY functional_view_class
SUPERTYPE OF (non_instantiable_functional_view_class)
SUBTYPE OF (class);
  representation_type : OPTIONAL STRING;
  view_control_variables :  LIST OF UNIQUE property_bsu;
  view_properties :  LIST OF UNIQUE property_bsu;
DERIVE
  SELF\class.described_by :  LIST OF UNIQUE property_bsu := SELF.
  view_control_variables + SELF.view_properties;
WHERE
  wr1 : QUERY(v_c_v <* SELF.view_control_variables | NOT ((data_type_typeof(
    v_c_v) = []) OR ( 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NON_QUANTITATIVE_INT_TYPE' IN 
    data_type_typeof(v_c_v)) AND ordered_index_value(
    data_type_non_quantitative_int_type(v_c_v)[1].domain))) = [];
  wr2 : NOT EXISTS(SELF.representation_type) OR (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.' LIKE SELF.representation_type);
  wr3 : NOT EXISTS(SELF\class.its_superclass) OR (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.' + 'FUNCTIONAL_VIEW_CLASS' IN 
    TYPEOF(SELF\class.its_superclass));
  wr4 : QUERY(prop <* SELF\class.described_by | definition_available_implies(
    prop,  
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.REPRESENTATION_P_DET' IN TYPEOF(
    prop.definition[1]))) = SELF\class.described_by;
END_ENTITY;
 
ENTITY geometric_representation_context
SUBTYPE OF (representation_context);
  coordinate_space_dimension : dimension_count;
END_ENTITY;
 
ENTITY geometric_representation_context_type
SUBTYPE OF (entity_instance_type);
WHERE
  wr1 : 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.GEOMETRIC_REPRESENTATION_CONTEXT'
     IN SELF\entity_instance_type.type_name;
END_ENTITY;
 
ENTITY geometric_representation_item
SUPERTYPE OF (ONEOF (point, direction, vector, placement))
SUBTYPE OF (representation_item);
DERIVE
  dim : dimension_count := dimension_of(SELF);
WHERE
  wr1 : SIZEOF(QUERY(using_rep <* using_representations(SELF) | NOT (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.GEOMETRIC_REPRESENTATION_CONTEXT'
     IN TYPEOF(using_rep.context_of_items)))) = 0;
END_ENTITY;
 
ENTITY global_language_assignment;
  language : language_code;
END_ENTITY;
 
ENTITY global_unit_assigned_context
SUBTYPE OF (representation_context);
  units : SET [1:?] OF unit;
END_ENTITY;
 
ENTITY graphics ABSTRACT SUPERTYPE;
END_ENTITY;
 
ENTITY http_class_directory;
  name : http_directory_name_type;
  class : class_bsu;
UNIQUE
  ur1 : class;
END_ENTITY;
 
ENTITY http_file
SUBTYPE OF (external_file_unit);
  mime : mime_type;
  exchange_format : mime_subtype;
  format_rfc : OPTIONAL iab_rfc;
  http_file_name : http_file_name_type;
  http_directory : OPTIONAL http_class_directory;
  remote_access : OPTIONAL absolute_url_type;
UNIQUE
  ur1 : http_file_name, http_directory;
WHERE
   wr1 : EXISTS(http_directory) OR NOT (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CLASS_EXTENSION_EXTERNAL_ITEM' IN
     TYPEOF(SELF.unit_of.content_of.content_of));
END_ENTITY;
 
ENTITY http_protocol
SUBTYPE OF (standard_data_protocol);
  http_rfc : iab_rfc;
END_ENTITY;
 
ENTITY id_attribute;
  attribute_value : identifier;
  identified_item : id_attribute_select;
END_ENTITY;
 
ENTITY identified_document
SUBTYPE OF (document);
  document_identifier : source_doc_type;
END_ENTITY;
 
ENTITY illustration
SUPERTYPE OF (ONEOF (a6_illustration, a9_illustration))
SUBTYPE OF (dialogue_resource, graphics);
  kind_of_content : illustration_type;
  width : OPTIONAL length_measure_with_unit;
  height : OPTIONAL length_measure_with_unit;
WHERE
  wr1 : NOT EXISTS(SELF.width) AND NOT EXISTS(SELF.height) OR EXISTS(SELF.width
    ) AND EXISTS(SELF.height);
END_ENTITY;
 
ENTITY int_currency_type
SUBTYPE OF (int_type);
  currency : OPTIONAL currency_code;
END_ENTITY;
 
ENTITY int_level_spec_value
SUBTYPE OF (level_spec_value);
  SELF\level_spec_value.values :  ARRAY [1 : 4] OF INTEGER;
END_ENTITY;
 
ENTITY int_measure_type
SUBTYPE OF (int_type);
  unit : dic_unit;
END_ENTITY;
 
ENTITY int_type
SUPERTYPE OF (ONEOF (int_measure_type, int_currency_type, 
non_quantitative_int_type))
SUBTYPE OF (number_type);
END_ENTITY;
 
ENTITY item_class
SUPERTYPE OF (ONEOF (component_class, material_class))
SUBTYPE OF (class);
  simplified_drawing : OPTIONAL graphics;
  sub_class_properties : SET OF property_bsu;
  class_constant_values : SET OF class_value_assignment;
  coded_name : OPTIONAL value_code_type;
WHERE
  wr1 : QUERY(p <* sub_class_properties | NOT (p IN SELF.described_by)) = [];
  wr2 : NOT all_class_descriptions_reachable(SELF.identified_by) OR (QUERY(va
     <* class_constant_values | SIZEOF(QUERY(c <* va.
    super_class_defined_property.describes_classes | is_subclass(SELF, c) AND (
    va.super_class_defined_property IN c\item_class.sub_class_properties))) <> 
    1) = []);
END_ENTITY;
 
ENTITY item_class_case_of
SUPERTYPE OF (ONEOF (component_class_case_of, material_class_case_of, 
feature_class_case_of))
SUBTYPE OF (item_class, a_priori_semantic_relationship);
  is_case_of : SET [1:?] OF class_bsu;
  imported_properties :  LIST OF property_bsu;
  imported_types : SET OF data_type_bsu;
  imported_tables : SET OF table_bsu;
  imported_documents : SET OF document_bsu;
DERIVE
  SELF\a_priori_semantic_relationship.referenced_classes : SET [1:?] OF 
  class_bsu := SELF.is_case_of;
  SELF\a_priori_semantic_relationship.referenced_properties :  LIST OF 
  property_bsu := SELF.imported_properties;
  SELF\a_priori_semantic_relationship.referenced_data_types : SET OF 
  data_type_bsu := SELF.imported_types;
  SELF\a_priori_semantic_relationship.referenced_tables : SET OF table_bsu := 
  SELF.imported_tables;
  SELF\a_priori_semantic_relationship.referenced_documents : SET OF 
  document_bsu := SELF.imported_documents;
WHERE
  wr1 : superclass_of_item_is_item(SELF);
  wr2 : check_is_case_of_referenced_classes_definition(SELF);
END_ENTITY;
 
ENTITY item_names;
  preferred_name : pref_name_type;
  synonymous_names : SET OF syn_name_type;
  short_name : OPTIONAL short_name_type;
  languages : OPTIONAL present_translations;
  icon : OPTIONAL graphics;
WHERE
  wr1 : NOT EXISTS(languages) OR ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.TRANSLATED_LABEL' IN TYPEOF(
    preferred_name)) AND (languages :=: preferred_name\translated_label.
    languages) AND (NOT EXISTS(short_name) OR (
     
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.TRANSLATED_LABEL' IN TYPEOF(
    short_name)) AND (languages :=: short_name\translated_label.languages)) AND
     (QUERY(s <* synonymous_names | NOT ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.LABEL_WITH_LANGUAGE' IN TYPEOF
    (s))) = []);
  wr2 : NOT EXISTS(languages) OR (QUERY(s <* synonymous_names | EXISTS(s.
    language) AND NOT (s.language IN QUERY(l <* languages.language_codes | TRUE
    ))) = []);
  wr3 : EXISTS(languages) OR ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.LABEL' 
    IN TYPEOF(preferred_name)) AND (NOT EXISTS(short_name) OR (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.LABEL' IN TYPEOF(short_name))) 
    AND (QUERY(s <* synonymous_names | 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.LABEL_WITH_LANGUAGE' IN TYPEOF(s)
    ) = []);
END_ENTITY;
 
ENTITY label_with_language;
  l : label;
  language : language_code;
END_ENTITY;
 
ENTITY language_specific_content;
  content_files : SET [1:?] OF external_file_unit;
  main_file : OPTIONAL external_file_unit;
  character_encoding : OPTIONAL character_set_type;
INVERSE
  content_of : external_content FOR consists_of;
WHERE
  wr1 : NOT EXISTS(main_file) OR (main_file IN content_files);
  wr2 : EXISTS(main_file) XOR (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.PROGRAM_LIBRARY_CONTENT' IN 
    TYPEOF(SELF.content_of.content_of));
  wr3 : EXISTS(character_encoding) OR NOT (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.HTTP_PROTOCOL' IN TYPEOF(SELF.
    content_of.content_of.used_protocol));
END_ENTITY;
 
ENTITY length_measure_with_unit
SUBTYPE OF (measure_with_unit);
WHERE
  wr1 : 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.LENGTH_UNIT' IN TYPEOF(SELF\
    measure_with_unit.unit_component);
END_ENTITY;
 
ENTITY length_unit
SUBTYPE OF (named_unit);
WHERE
  wr1 : (SELF\named_unit.dimensions.length_exponent = 1.0) AND (SELF\named_unit
    .dimensions.mass_exponent = 0.0) AND (SELF\named_unit.dimensions.
    time_exponent = 0.0) AND (SELF\named_unit.dimensions.
    electric_current_exponent = 0.0) AND (SELF\named_unit.dimensions.
    thermodynamic_temperature_exponent = 0.0) AND (SELF\named_unit.dimensions.
    amount_of_substance_exponent = 0.0) AND (SELF\named_unit.dimensions.
    luminous_intensity_exponent = 0.0);
END_ENTITY;
 
ENTITY level_spec_value
ABSTRACT SUPERTYPE OF (ONEOF (int_level_spec_value, real_level_spec_value));
  values :  ARRAY [1 : 4] OF NUMBER;
END_ENTITY;
 
ENTITY level_type
SUBTYPE OF (complex_type);
  levels :  LIST [1:4] OF UNIQUE level;
  value_type : simple_type;
WHERE
  wr1 : 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NUMBER_TYPE' IN TYPEOF(
    value_type);
END_ENTITY;
 
ENTITY lib_component_instance
SUBTYPE OF (dic_component_instance, lib_item_instance);
END_ENTITY;
 
ENTITY lib_f_model_instance
SUBTYPE OF (dic_f_model_instance);
END_ENTITY;
 
ENTITY lib_feature_instance
SUBTYPE OF (dic_feature_instance, lib_item_instance);
END_ENTITY;
 
ENTITY lib_item_instance
SUPERTYPE OF (ONEOF (lib_component_instance, lib_material_instance, 
lib_feature_instance))
SUBTYPE OF (dic_item_instance);
  supplier_identification : OPTIONAL STRING;
  supplier_designation : OPTIONAL translatable_label;
  user_identification : OPTIONAL STRING;
  user_designation : OPTIONAL translatable_label;
  is_global_id : BOOLEAN;
  source_class_content : OPTIONAL version_type;
END_ENTITY;
 
ENTITY lib_material_instance
SUBTYPE OF (dic_material_instance, lib_item_instance);
END_ENTITY;
 
ENTITY library
SUPERTYPE OF (library_in_standard_format)
SUBTYPE OF (dictionary);
  linked_interfaces : SET OF external_file_protocol;
WHERE
  wr1 : QUERY(class <* SELF\dictionary.contained_classes | 
    referenced_veps_exist_in_supported_veps(SELF, class)) = [];
  wr2 : QUERY(class <* SELF.contained_classes | 
    referenced_protocols_exist_in_supported_protocols(SELF, class)) = [];
  wr3 : QUERY(int <* SELF.linked_interfaces | NOT (
     
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.LINKED_INTERFACE_PROGRAM_PROTOCOL'
     IN TYPEOF(int))) = [];
END_ENTITY;
 
ENTITY library_iim_identification
SUBTYPE OF (data_exchange_specification_identification);
END_ENTITY;
 
ENTITY library_in_standard_format
SUBTYPE OF (library, dictionary_in_standard_format);
WHERE
  wr1 : QUERY(int <* SELF\library.linked_interfaces | SIZEOF(QUERY(vep <* SELF\
    dictionary.supported_vep | int\external_file_protocol.base_protocol IN vep\
    data_exchange_specification_identification.external_file_protocols)) = 0)
     = [];
END_ENTITY;
 
ENTITY linked_interface_program_protocol
SUBTYPE OF (program_protocol);
  link_libraries : SET [1:?] OF program_library_bsu;
WHERE
  wr1 : QUERY(pl <* SELF.link_libraries | (SIZEOF(pl\basic_semantic_unit.
    referenced_by) > 0) AND (pl\basic_semantic_unit.referenced_by[1]\
    external_item.used_protocol <> SELF.base_protocol)) = [];
  wr2 : NOT ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.STANDARD_PROTOCOL' IN 
    TYPEOF(SELF)) AND NOT (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NON_STANDARD_PROTOCOL' IN TYPEOF(
    SELF));
  wr3 : EXISTS(base_protocol) AND (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.PROGRAM_PROTOCOL' IN TYPEOF(
    base_protocol));
END_ENTITY;
 
ENTITY list_type
SUBTYPE OF (aggregate_type);
  uniqueness : BOOLEAN;
WHERE
  wr1 : EXISTS(bound_1) OR NOT EXISTS(bound_2);
  wr2 : NOT EXISTS(bound_1) OR (bound_1 >= 0);
END_ENTITY;
 
ENTITY list_value
SUBTYPE OF (aggregate_value);
  SELF\aggregate_value.values :  LIST OF primitive_value;
END_ENTITY;
 
ENTITY local_time;
  hour_component : hour_in_day;
  minute_component : OPTIONAL minute_in_hour;
  second_component : OPTIONAL second_in_minute;
  zone : coordinated_universal_time_offset;
WHERE
  wr1 : valid_time(SELF);
END_ENTITY;

ENTITY material_class
SUBTYPE OF (item_class);
END_ENTITY;
 
ENTITY material_class_case_of
SUBTYPE OF (item_class_case_of, material_class);
WHERE
  wr1 : check_is_case_of_referenced_classes_definition(SELF);
END_ENTITY;
 
ENTITY mathematical_string;
  text_representation : text;
  sgml_representation : OPTIONAL text;
END_ENTITY;
 
ENTITY measure_with_unit
SUPERTYPE OF (ONEOF (length_measure_with_unit));
  value_component : measure_value;
  unit_component : unit;
WHERE
  wr1 : valid_units(SELF);
END_ENTITY;
 
ENTITY message
SUBTYPE OF (dialogue_resource);
END_ENTITY;
 
ENTITY model_class_extension
ABSTRACT SUPERTYPE OF (ONEOF (explicit_model_class_extension))
SUBTYPE OF (class_extension);
  referenced_external_items : SET OF class_extension_external_item;
  used_protocols : SET OF external_file_protocol;
  referenced_view_exchange_protocol :  LIST OF 
  view_exchange_protocol_identification;
  content_version : OPTIONAL version_type;
  content_revision : OPTIONAL revision_type;
  recommended_presentation : SET OF property_value_recommended_presentation;
  classification : SET OF property_classification;
WHERE
  wr1 : QUERY(item <* SELF.referenced_external_items | NOT (item\external_item.
    used_protocol IN SELF.used_protocols)) = [];
  wr2 : QUERY(prop <* classification | NOT applicable_properties(SELF\
    content_item.dictionary_definition, [prop.prop_def])) = [];
  wr3 : EXISTS(SELF.content_version) AND EXISTS(SELF.content_revision) OR NOT 
    EXISTS(SELF.content_version) AND NOT EXISTS(SELF.content_revision);
END_ENTITY;
 
ENTITY name_attribute;
  attribute_value : label;
  named_item : name_attribute_select;
END_ENTITY;
 
ENTITY named_type
SUBTYPE OF (data_type);
  referred_type : data_type_bsu;
END_ENTITY;
 
ENTITY named_unit
SUPERTYPE OF (ONEOF (si_unit, conversion_based_unit, context_dependent_unit)
 ANDOR ONEOF (length_unit));
  dimensions : dimensional_exponents;
END_ENTITY;
 
ENTITY non_dependent_p_det
SUBTYPE OF (property_det);
END_ENTITY;
 
ENTITY non_instantiable_functional_view_class
SUBTYPE OF (functional_view_class);
DERIVE
  SELF\functional_view_class.view_properties :  LIST OF UNIQUE property_bsu := 
  [];
WHERE
  wr1 : NOT EXISTS(SELF\functional_view_class.representation_type);
END_ENTITY;
 
ENTITY non_quantitative_code_type
SUBTYPE OF (string_type);
  domain : value_domain;
WHERE
  wr1 : QUERY(v <* domain.its_values | NOT (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.VALUE_CODE_TYPE' IN TYPEOF(v.
    value_code))) = [];
END_ENTITY;
 
ENTITY non_quantitative_int_type
SUBTYPE OF (int_type);
  domain : value_domain;
WHERE
  wr1 : QUERY(v <* domain.its_values | 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.VALUE_CODE_TYPE' IN TYPEOF(v.
    value_code)) = [];
END_ENTITY;
 
ENTITY non_si_unit
SUBTYPE OF (named_unit);
  name : label;
END_ENTITY;
 
ENTITY non_standard_data_protocol
SUBTYPE OF (data_protocol, non_standard_protocol);
WHERE
  wr1 : NOT EXISTS(SELF\external_file_protocol.base_protocol);
END_ENTITY;
 
ENTITY non_standard_protocol
ABSTRACT SUPERTYPE OF (ONEOF (non_standard_simple_program_protocol, 
non_standard_data_protocol))
SUBTYPE OF (external_file_protocol);
END_ENTITY;
 
ENTITY non_standard_simple_program_protocol
SUBTYPE OF (non_standard_protocol, simple_program_protocol);
WHERE
  wr1 : NOT EXISTS(SELF\external_file_protocol.base_protocol);
END_ENTITY;
 
ENTITY not_translatable_external_content
SUBTYPE OF (external_content);
WHERE
  wr1 : SIZEOF(SELF\external_content.consists_of) = 1;
END_ENTITY;
 
ENTITY not_translated_external_content
SUBTYPE OF (external_content);
WHERE
  wr1 : SIZEOF(SELF\external_content.consists_of) = 1;
END_ENTITY;
 
ENTITY null_value;
END_ENTITY;
 
ENTITY number_type
SUPERTYPE OF (ONEOF (int_type, real_type))
SUBTYPE OF (simple_type);
END_ENTITY;
 
ENTITY ordinal_date
SUBTYPE OF (date);
  day_component : day_in_year_number;
WHERE
  wr1 : NOT leap_year(SELF.year_component) AND {1 <= day_component <= 365} OR 
    leap_year(SELF.year_component) AND {1 <= day_component <= 366};
END_ENTITY;
 
ENTITY organization;
  id : OPTIONAL identifier;
  name : label;
  description : OPTIONAL text;
END_ENTITY;

ENTITY person;
  id : identifier;
  last_name : OPTIONAL label;
  first_name : OPTIONAL label;
  middle_names : OPTIONAL  LIST [1:?] OF label;
  prefix_titles : OPTIONAL  LIST [1:?] OF label;
  suffix_titles : OPTIONAL  LIST [1:?] OF label;
WHERE
  wr1 : EXISTS(last_name) OR EXISTS(first_name);
END_ENTITY;

ENTITY placement
SUPERTYPE OF (ONEOF (axis1_placement, axis2_placement_2d, axis2_placement_3d))
SUBTYPE OF (geometric_representation_item);
  location : cartesian_point;
END_ENTITY;
 
ENTITY placement_type
SUPERTYPE OF (ONEOF (axis1_placement_type, axis2_placement_2d_type, 
axis2_placement_3d_type))
SUBTYPE OF (entity_instance_type);
WHERE
  wr1 : 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.PLACEMENT' IN SELF\
    entity_instance_type.type_name;
END_ENTITY;

ENTITY point
SUPERTYPE OF (ONEOF (cartesian_point))
SUBTYPE OF (geometric_representation_item);
END_ENTITY;
 
ENTITY present_translations;
  language_codes :  LIST [1:?] OF UNIQUE language_code;
UNIQUE
  ur1 : language_codes;
END_ENTITY;
 
ENTITY program_library_bsu
SUBTYPE OF (supplier_related_bsu);
  defined_by : supplier_bsu;
  SELF\basic_semantic_unit.code : program_library_code_type;
DERIVE
  absolute_id : identifier := defined_by.dic_identifier + sep_id + 
  dic_identifier;
INVERSE
  associated_to_supplier : supplier_bsu_relationship FOR related_tokens;
UNIQUE
  ur1 : absolute_id;
WHERE
  wr1 : defined_by :=: associated_to_supplier.relating_supplier\
    dictionary_element.identified_by;
END_ENTITY;
 
ENTITY program_library_content
SUBTYPE OF (supplier_bsu_related_content);
  SELF\content_item.dictionary_definition : program_library_bsu;
  SELF\external_item.used_protocol : program_protocol;
END_ENTITY;
 
ENTITY program_library_element
SUBTYPE OF (supplier_related_dictionary_element);
  SELF\dictionary_element.identified_by : program_library_bsu;
END_ENTITY;
 
ENTITY program_protocol
ABSTRACT SUPERTYPE OF (ONEOF (linked_interface_program_protocol, 
simple_program_protocol))
SUBTYPE OF (external_file_protocol);
END_ENTITY;
 
ENTITY program_reference
SUBTYPE OF (class_extension_external_item);
  SELF\external_item.used_protocol : program_protocol;
  syntactical_name : program_reference_name_type;
  in_parameters :  LIST OF property_or_data_type_bsu;
  out_parameters :  LIST OF property_or_data_type_bsu;
  inout_parameters :  LIST OF property_or_data_type_bsu;
END_ENTITY;
 
ENTITY program_reference_type
SUBTYPE OF (entity_instance_type);
WHERE
  wr1 : 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.PROGRAM_REFERENCE' IN SELF\
    entity_instance_type.type_name;
END_ENTITY;
 
ENTITY property_bsu
SUBTYPE OF (basic_semantic_unit);
  SELF\basic_semantic_unit.code : property_code_type;
  name_scope : class_bsu;
DERIVE
  absolute_id : identifier := name_scope.defined_by.absolute_id + sep_id + 
  name_scope.dic_identifier + sep_id + dic_identifier;
INVERSE
  describes_classes : SET OF class FOR described_by;
UNIQUE
  ur1 : absolute_id;
WHERE
  wr1 : QUERY(c <* describes_classes | NOT is_subclass(c, name_scope.definition
    [1])) = [];
END_ENTITY;
 
ENTITY property_classification;
  its_value : classification_value;
  prop_def : property_bsu;
END_ENTITY;
 
ENTITY property_det
ABSTRACT SUPERTYPE OF (ONEOF (condition_det, dependent_p_det, 
non_dependent_p_det))
SUBTYPE OF (class_and_property_elements);
  SELF\dictionary_element.identified_by : property_bsu;
  preferred_symbol : OPTIONAL mathematical_string;
  synonymous_symbols : SET OF mathematical_string;
  figure : OPTIONAL graphics;
  det_classification : OPTIONAL det_classification_type;
  domain : data_type;
  formula : OPTIONAL mathematical_string;
DERIVE
  describes_classes : SET OF class := identified_by.describes_classes;
END_ENTITY;
 
ENTITY property_value;
  its_value : OPTIONAL primitive_value;
  prop_def : property_bsu;
WHERE
  wr1 : EXISTS(SELF.its_value) AND compatible_type_and_value(SELF.prop_def,
    SELF.its_value) OR NOT EXISTS(SELF.its_value);
END_ENTITY;
 
ENTITY property_value_external_item
SUBTYPE OF (external_item);
END_ENTITY;
 
ENTITY property_value_recommended_presentation;
  prop_def : property_bsu;
  recommended_presentation_unit : unit;
  recommended_presentation_format : value_format_type;
WHERE
  wr1 : presentation_unit_is_correct(SELF.prop_def, SELF.
    recommended_presentation_unit);
END_ENTITY;

ENTITY real_currency_type
SUBTYPE OF (real_type);
  currency : OPTIONAL currency_code;
END_ENTITY;
 
ENTITY real_level_spec_value
SUBTYPE OF (level_spec_value);
  SELF\level_spec_value.values :  ARRAY [1 : 4] OF REAL;
END_ENTITY;
 
ENTITY real_measure_type
SUBTYPE OF (real_type);
  unit : dic_unit;
END_ENTITY;
 
ENTITY real_type
SUPERTYPE OF (ONEOF (real_measure_type, real_currency_type))
SUBTYPE OF (number_type);
END_ENTITY;
 
ENTITY referenced_document
SUBTYPE OF (document);
  document_reference : document_bsu;
WHERE
  wr1 : NOT ( 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.IDENTIFIED_DOCUMENT' IN TYPEOF(
    SELF));
END_ENTITY;
 
ENTITY referenced_graphics
SUBTYPE OF (graphics);
  graphics_reference : document_bsu;
END_ENTITY;
 
ENTITY representation;
  name : label;
  items : SET [1:?] OF representation_item;
  context_of_items : representation_context;
DERIVE
  id : identifier := get_id_value(SELF);
  description : text := get_description_value(SELF);
WHERE
  wr1 : SIZEOF(USEDIN(SELF, 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ID_ATTRIBUTE.IDENTIFIED_ITEM'))
     <= 1;
  wr2 : SIZEOF(USEDIN(SELF, 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.DESCRIPTION_ATTRIBUTE.DESCRIBED_ITEM'
    )) <= 1;
END_ENTITY;
 
ENTITY representation_context;
  context_identifier : identifier;
  context_type : text;
INVERSE
  representations_in_context : SET [1:?] OF representation FOR context_of_items
  ;
END_ENTITY;
 
ENTITY representation_item;
  name : label;
WHERE
  wr1 : SIZEOF(using_representations(SELF)) > 0;
END_ENTITY;
 
ENTITY representation_p_det
SUBTYPE OF (property_det);
WHERE
  wr1 : NOT ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CONDITION_DET' IN TYPEOF
    (SELF)) AND NOT ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.DEPENDENT_P_DET'
     IN TYPEOF(SELF)) AND NOT ( 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NON_DEPENDENT_P_DET' IN TYPEOF(
    SELF));
END_ENTITY;
 
ENTITY representation_reference
SUBTYPE OF (class_extension_external_item);
  SELF\external_item.used_protocol : data_protocol;
  representation_id : OPTIONAL label;
END_ENTITY;
 
ENTITY representation_reference_type
SUBTYPE OF (entity_instance_type);
WHERE
  wr1 : 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.REPRESENTATION_REFERENCE' IN 
    SELF\entity_instance_type.type_name;
END_ENTITY;
 
ENTITY representation_type
SUBTYPE OF (entity_instance_type);
WHERE
  wr1 : 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.REPRESENTATION' IN SELF\
    entity_instance_type.type_name;
END_ENTITY;
 
ENTITY set_type
SUBTYPE OF (aggregate_type);
WHERE
  wr1 : EXISTS(bound_1) OR NOT EXISTS(bound_2);
  wr2 : NOT EXISTS(bound_1) OR (bound_1 >= 0);
END_ENTITY;
 
ENTITY set_value
SUBTYPE OF (aggregate_value);
  SELF\aggregate_value.values :  LIST OF primitive_value;
WHERE
  wr1 : VALUE_UNIQUE(values);
END_ENTITY;
 
ENTITY set_with_subset_constraint_type
SUBTYPE OF (aggregate_type);
  cardinal_min : OPTIONAL INTEGER;
  cardinal_max : OPTIONAL INTEGER;
WHERE
  wr1 : cardinal_min <= cardinal_max;
  wr2 : NOT EXISTS(bound_2) OR NOT EXISTS(cardinal_max) OR (cardinal_max <= 
    bound_2);
  wr3 : NOT EXISTS(bound_1) OR NOT EXISTS(cardinal_min) OR (cardinal_min <= 
    bound_1);
END_ENTITY;
 
ENTITY set_with_subset_constraint_value
SUBTYPE OF (aggregate_value);
  SELF\aggregate_value.values :  LIST OF primitive_value;
  min : OPTIONAL INTEGER;
  max : OPTIONAL INTEGER;
WHERE
  wr1 : NOT EXISTS(min) OR NOT EXISTS(max) OR (min <= max);
  wr2 : VALUE_UNIQUE(values);
END_ENTITY;
 
ENTITY si_unit
SUBTYPE OF (named_unit);
  prefix : OPTIONAL si_prefix;
  name : si_unit_name;
DERIVE
  SELF\named_unit.dimensions : dimensional_exponents := dimensions_for_si_unit(
  name);
END_ENTITY;
 
ENTITY simple_program_protocol
ABSTRACT SUPERTYPE OF (ONEOF (standard_simple_program_protocol, 
non_standard_simple_program_protocol))
SUBTYPE OF (program_protocol);
  language : identifier;
  status : program_status;
  compiler_supplier : OPTIONAL organization;
  compiler_name : OPTIONAL identifier;
  compiler_version : OPTIONAL compiler_version_type;
WHERE
  wr1 : (SELF.status = source) AND NOT EXISTS(SELF.compiler_supplier) AND NOT 
    EXISTS(SELF.compiler_name) AND NOT EXISTS(SELF.compiler_version) OR (SELF.
    status = compiled) AND EXISTS(SELF.compiler_supplier) AND EXISTS(SELF.
    compiler_name) AND EXISTS(SELF.compiler_version);
END_ENTITY;
 
ENTITY simple_type
ABSTRACT SUPERTYPE OF (ONEOF (number_type, boolean_type, string_type))
SUBTYPE OF (data_type);
  value_format : value_format_type;
END_ENTITY;

ENTITY standard_data_protocol
SUBTYPE OF (data_protocol, standard_protocol);
WHERE
  wr1 : NOT EXISTS(SELF\external_file_protocol.base_protocol);
END_ENTITY;
 
ENTITY standard_protocol
ABSTRACT SUPERTYPE OF (ONEOF (standard_simple_program_protocol, 
standard_data_protocol))
SUBTYPE OF (external_file_protocol);
END_ENTITY;
 
ENTITY standard_simple_program_protocol
SUBTYPE OF (standard_protocol, simple_program_protocol);
WHERE
  wr1 : NOT EXISTS(SELF\external_file_protocol.base_protocol);
END_ENTITY;
 
ENTITY string_type
SUBTYPE OF (simple_type);
END_ENTITY;
 
ENTITY supplier_bsu
SUBTYPE OF (basic_semantic_unit);
  SELF\basic_semantic_unit.code : supplier_code_type;
DERIVE
  SELF\basic_semantic_unit.version : version_type := '1';
  absolute_id : identifier := SELF\basic_semantic_unit.code;
UNIQUE
  ur1 : absolute_id;
END_ENTITY;
 
ENTITY supplier_bsu_related_content
ABSTRACT SUPERTYPE OF (program_library_content)
SUBTYPE OF (dictionary_external_item);
  SELF\content_item.dictionary_definition : supplier_related_bsu;
END_ENTITY;
 
ENTITY supplier_bsu_relationship ABSTRACT SUPERTYPE;
  relating_supplier : supplier_element;
  related_tokens : SET [1:?] OF supplier_related_bsu;
END_ENTITY;
 
ENTITY supplier_element
SUBTYPE OF (dictionary_element);
  SELF\dictionary_element.identified_by : supplier_bsu;
  org : organization;
  addr : address;
INVERSE
  associated_items : SET OF supplier_bsu_relationship FOR relating_supplier;
END_ENTITY;
 
ENTITY supplier_program_library_relationship
SUBTYPE OF (supplier_bsu_relationship);
  SELF\supplier_bsu_relationship.related_tokens : SET [1:?] OF 
  program_library_bsu;
END_ENTITY;
 
ENTITY supplier_related_bsu ABSTRACT SUPERTYPE
SUBTYPE OF (basic_semantic_unit);
END_ENTITY;
 
ENTITY supplier_related_dictionary_element
ABSTRACT SUPERTYPE OF (program_library_element)
SUBTYPE OF (dictionary_element);
  SELF\dictionary_element.identified_by : supplier_related_bsu;
  names : item_names;
  definition : definition_type;
  note : OPTIONAL note_type;
  remark : OPTIONAL remark_type;
END_ENTITY;
 
ENTITY table_bsu
SUBTYPE OF (class_related_bsu, table_identification);
  name_scope : class_bsu;
  SELF\basic_semantic_unit.code : table_code_type;
DERIVE
  absolute_id : identifier := name_scope.defined_by.dic_identifier + sep_id + 
  name_scope.dic_identifier + sep_id + dic_identifier;
UNIQUE
  ur1 : absolute_id;
END_ENTITY;
 
ENTITY table_identification ABSTRACT SUPERTYPE;
WHERE
  wr1 : SIZEOF(USEDIN(SELF, 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.TABLE_SPECIFICATION.TABLE_IDENTIFIER'
    )) <= 1;
  wr2 : SIZEOF(USEDIN(SELF, 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.TABLE_EXTENSION.TABLE_IDENTIFIER'
    )) <= 1;
END_ENTITY;
 
ENTITY translated_external_content
SUBTYPE OF (external_content);
  languages : present_translations;
WHERE
  wr1 : SIZEOF(SELF\external_content.consists_of) = SIZEOF(SELF.languages.
    language_codes);
END_ENTITY;
 
ENTITY translated_label;
  labels :  LIST [1:?] OF label;
  languages : present_translations;
WHERE
  wr1 : SIZEOF(labels) = SIZEOF(languages.language_codes);
END_ENTITY;
 
ENTITY translated_string_value;
  string_values :  LIST [1:?] OF string_value;
  languages : present_translations;
WHERE
  wr1 : SIZEOF(string_values) = SIZEOF(languages.language_codes);
END_ENTITY;
 
ENTITY translated_text;
  texts :  LIST [1:?] OF text;
  languages : present_translations;
WHERE
  wr1 : SIZEOF(texts) = SIZEOF(languages.language_codes);
END_ENTITY;
 
ENTITY uncontrolled_entity_instance_value ABSTRACT SUPERTYPE;
END_ENTITY;
 
ENTITY value_domain;
  its_values :  LIST [1:?] OF dic_value;
  source_doc_of_value_domain : OPTIONAL document;
  languages : OPTIONAL present_translations;
  terms :  LIST OF item_names;
WHERE
  wr1 : NOT EXISTS(languages) OR (QUERY(v <* its_values | languages :<>: v.
    meaning.languages) = []);
  wr2 : codes_are_unique(its_values);
  wr3 : EXISTS(languages) OR (QUERY(v <* its_values | EXISTS(v.meaning.
    languages)) = []);
END_ENTITY;
 
ENTITY vector
SUBTYPE OF (geometric_representation_item);
  orientation : direction;
  magnitude : length_measure;
WHERE
  wr1 : magnitude >= 0.0;
END_ENTITY;
 
ENTITY view_control_variable_range;
  parameter_type : property_bsu;
  range_lobound : INTEGER;
  range_hibound : INTEGER;
WHERE
  wr1 : (data_type_typeof(SELF.parameter_type) = []) OR (
     
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NON_QUANTITATIVE_INT_TYPE' IN 
    data_type_typeof(SELF.parameter_type));
  wr2 : SELF.range_lobound <= SELF.range_hibound;
  wr3 : view_control_variables_attributes_belong_to_domain(SELF);
END_ENTITY;
 
ENTITY view_exchange_protocol_identification
SUBTYPE OF (data_exchange_specification_identification);
  referenced_iso10303_ap : OPTIONAL application_protocol_definition;
END_ENTITY;
 
ENTITY week_of_year_and_day_date
SUBTYPE OF (date);
  week_component : week_in_year_number;
  day_component : OPTIONAL day_in_week_number;
END_ENTITY;
 
RULE allowed_aggregate_values FOR (property_value,
  entity_instance_type_for_aggregate);
WHERE
  wr1 : QUERY(prop <* property_value | NOT compatible_complete_types_and_value(
    prop.prop_def, prop.its_value)) = [];
END_RULE;
 
RULE allowed_entity_instance_type_in_liim_25_rule FOR (entity_instance_type);
 
WHERE
    QUERY(x <* entity_instance_type | 
    
 NOT ((
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.REPRESENTATION' 
    IN x.type_name) OR (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.REPRESENTATION_CONTEXT' 
    IN x.type_name) OR (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.GEOMETRIC_REPRESENTATION_CONTEXT'
     IN x.type_name) OR (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.REPRESENTATION_ITEM' 
    IN x.type_name) OR (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.DATE' 
    IN x.type_name) OR (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.DATE_AND_TIME' 
    IN x.type_name) OR (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.LOCAL_TIME' 
    IN x.type_name) OR (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA. CALENDAR_TIME' 
    IN x.type_name) OR (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ORDINAL_TIME' 
    IN x.type_name) OR (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.WEEK_OF_YEAR_AND_DAY_TIME' 
    IN x.type_name) OR (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.PERSON' 
    IN x.type_name) OR (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ORGANIZATION' 
    IN x.type_name) OR (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ADDRESS'
     IN x.type_name) OR (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.PROGRAM_REFERENCE' 
    IN x.type_name) OR (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.REPRESENTATION_REFERENCE' 
    IN x.type_name) OR (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.PROPERTY_VALUE_EXTERNAL_ITEM' 
    IN x.type_name))) = [];
   
END_RULE;
 
RULE allowed_language_assignment_rule FOR (present_translations, 
  global_language_assignment);
WHERE
  wr1 : (QUERY(x <* global_language_assignment | TRUE) = []) XOR (QUERY(x <* 
    present_translations | TRUE) = []);
END_RULE;
 
RULE allowed_named_type_usage_rule FOR (class);
LOCAL
  named_type_usage_allowed : LOGICAL := TRUE;
  is_app : LOGICAL;
  prop : property_bsu;
  cl : class;
  dtnt : SET [0:1] OF data_type_bsu := [];
END_LOCAL;
  REPEAT i := 1 TO SIZEOF(class);
    cl := class[i];
    REPEAT j := 1 TO SIZEOF(class[i].described_by);
      prop := cl.described_by[j];
      dtnt := data_type_named_type(prop);
      IF SIZEOF(dtnt) = 1 THEN
        is_app := applicable_types(cl.identified_by, dtnt);
        IF NOT is_app THEN
          named_type_usage_allowed := FALSE;
        END_IF;
      END_IF;
    END_REPEAT;
  END_REPEAT;
WHERE
  wr1 : named_type_usage_allowed;
END_RULE;
 
 
RULE allowed_reference_to_liim_25_rule FOR (library_iim_identification);
WHERE
  wr1 : QUERY(liim_id <* library_iim_identification | ((liim_id\
    data_exchange_specification_identification.status = 'WD') OR (liim_id\
    data_exchange_specification_identification.status = 'CD') OR (liim_id\
    data_exchange_specification_identification.status = 'DIS') OR (liim_id\
    data_exchange_specification_identification.status = 'FDIS') OR (liim_id\
    data_exchange_specification_identification.status = 'IS') OR (liim_id\
    data_exchange_specification_identification.status = 'TS') OR (liim_id\
    data_exchange_specification_identification.status = 'PAS') OR (liim_id\
    data_exchange_specification_identification.status = 'ITA')) AND (liim_id\
    data_exchange_specification_identification.name = 'ISO_13584_25') AND 
    is_correct_liim_25_application_value(liim_id) AND (QUERY(efp <* liim_id\
    data_exchange_specification_identification.external_file_protocols | NOT 
    compliant_external_file_protocol_25([efp])) = [])) = QUERY(liim_id <* 
    library_iim_identification | liim_id\
    data_exchange_specification_identification.name = 'ISO_13584_25');
END_RULE;
 
RULE assert_oneof FOR (named_unit);
WHERE
  QUERY(u <* named_unit | (
  'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NON_SI_UNIT' IN TYPEOF(u)) AND (
  'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.SI_UNIT' IN TYPEOF(u)) OR (
  'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NON_SI_UNIT' IN TYPEOF(u)) AND (
  'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CONTEXT_DEPENDENT_UNIT' IN TYPEOF(u
  )) OR ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NON_SI_UNIT' IN TYPEOF(u)) 
  AND ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CONVERSION_BASED_UNIT' IN 
  TYPEOF(u))) = [];
END_RULE;
 
RULE assert_oneof_for_library_rule FOR (library);
WHERE
  wr1 : QUERY(temp <* library | NOT ( 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.LIBRARY_IN_STANDARD_FORMAT' IN 
    TYPEOF(temp)) AND ( 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.DICTIONARY_IN_STANDARD_FORMAT' IN
     TYPEOF(temp))) = [];
END_RULE;
 
RULE at_most_one_dictionary_rule FOR (dictionary);
WHERE
  wr1 : SIZEOF(dictionary) <= 1;
END_RULE;
 
RULE class_associated_items_rule FOR (class);
WHERE
  wr1 : QUERY(temp <* class | (SIZEOF(temp.associated_items) > 2) OR (SIZEOF(
    temp.associated_items) = 1) AND NOT (( 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CLASS_TABLE_RELATIONSHIP' IN 
    TYPEOF(temp.associated_items[1])) OR ( 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CLASS_DOCUMENT_RELATIONSHIP' IN 
    TYPEOF(temp.associated_items[1]))) OR (SIZEOF(temp.associated_items) = 2) 
    AND NOT (( 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CLASS_TABLE_RELATIONSHIP' IN 
    TYPEOF(temp.associated_items[1])) AND ( 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CLASS_DOCUMENT_RELATIONSHIP' IN 
    TYPEOF(temp.associated_items[2])) OR ( 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CLASS_TABLE_RELATIONSHIP' IN 
    TYPEOF(temp.associated_items[2])) AND ( 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CLASS_DOCUMENT_RELATIONSHIP' IN 
    TYPEOF(temp.associated_items[1])))) = [];
END_RULE;
(*
RULE class_associated_items_rule FOR (class);
WHERE
  wr1 : QUERY(temp <* class | (SIZEOF(temp.associated_items) > 2) OR (SIZEOF(
    temp.associated_items) = 1) AND NOT (( 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CLASS_TABLE_RELATIONSHIP' IN 
    TYPEOF(temp.associated_items[1])) OR ( 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CLASS_DOCUMENT_RELATIONSHIP' IN 
    TYPEOF(temp.associated_items[1]))) OR (SIZEOF(temp.associated_items) = 2) 
    AND NOT (( 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CLASS_TABLE_RELATIONSHIP' IN 
    TYPEOF(temp.associated_items[1])) AND ( 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CLASS_DOCUMENT_RELATIONSHIP' IN 
    TYPEOF(temp.associated_items[2])) OR ( 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CLASS_TABLE_RELATIONSHIP' IN 
    TYPEOF(temp.associated_items[2])) AND ( 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CLASS_DOCUMENT_RELATIONSHIP' IN 
    TYPEOF(temp.associated_items[1])))) = [];
END_RULE;

RULE class_associated_items_rule FOR (class);
WHERE
  wr1 : QUERY(temp <* class | (SIZEOF(temp.associated_items) > 2) OR (SIZEOF(
    temp.associated_items) = 1) AND NOT (( 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CLASS_TABLE_RELATIONSHIP' IN 
    TYPEOF(temp.associated_items[1])) OR ( 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CLASS_DOCUMENT_RELATIONSHIP' IN 
    TYPEOF(temp.associated_items[1]))) OR (SIZEOF(temp.associated_items) = 2) 
    AND NOT (( 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CLASS_TABLE_RELATIONSHIP' IN 
    TYPEOF(temp.associated_items[1])) AND ( 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CLASS_DOCUMENT_RELATIONSHIP' IN 
    TYPEOF(temp.associated_items[2])) OR ( 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CLASS_TABLE_RELATIONSHIP' IN 
    TYPEOF(temp.associated_items[2])) AND ( 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CLASS_DOCUMENT_RELATIONSHIP' IN 
    TYPEOF(temp.associated_items[1])))) = [];
END_RULE;
*)
 
RULE compatible_dimension FOR (cartesian_point, direction, 
  representation_context, geometric_representation_context);
WHERE
  wr1 : SIZEOF(QUERY(x <* cartesian_point | SIZEOF(QUERY(y <* 
    geometric_representation_context | item_in_context(x, y) AND (HIINDEX(x.
    coordinates) <> y.coordinate_space_dimension))) > 0)) = 0;
  wr2 : SIZEOF(QUERY(x <* direction | SIZEOF(QUERY(y <* 
    geometric_representation_context | item_in_context(x, y) AND (HIINDEX(x.
    direction_ratios) <> y.coordinate_space_dimension))) > 0)) = 0;
END_RULE;
(* 
RULE exactly_one_dictionary_rule FOR (dictionary);
WHERE
  wr1 : SIZEOF(dictionary) = 1;
END_RULE;
*) 
 
RULE exactly_one_dictionary_rule FOR (dictionary);
WHERE
  wr1 : SIZEOF(dictionary) = 1;
END_RULE;
 
RULE http_directory_refers_to_bsu_related_class_rule FOR (http_file, 
  class_bsu_related_content);
WHERE
  wr1 : QUERY(http_f <* http_file | ( 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CLASS_BSU_RELATED_CONTENT' IN 
    TYPEOF(http_f\external_file_unit.unit_of.content_of.content_of)) AND (
    http_f.http_directory.class <> http_f\external_file_unit.unit_of.content_of
    .content_of\content_item.dictionary_definition.name_scope)) = [];
END_RULE;
 
RULE http_directory_refers_to_class_extension_rule FOR (http_file, 
  class_extension_external_item);
WHERE
  wr1 : QUERY(http_f <* http_file | ( 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CLASS_EXTENSION_EXTERNAL_ITEM' IN
     TYPEOF(http_f\external_file_unit.unit_of.content_of.content_of)) AND (
    http_f.http_directory.class <> http_f\external_file_unit.unit_of.content_of
    .content_of\class_extension_external_item.belongs_to\content_item.
    dictionary_definition)) = [];
END_RULE;
 
RULE illustration_is_not_a_referenced_graphics_rule FOR (graphics);
WHERE
  wr1 : QUERY(icon <* graphics | (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.REFERENCED_GRAPHICS' IN TYPEOF(
    icon)) AND ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ILLUSTRATION' IN 
    TYPEOF(icon))) = [];
END_RULE;
 
RULE nesting_level_aggregate_limit_rule FOR (library_iim_identification, 
  aggregate_type);
WHERE
  wr1 : NOT (QUERY(liim_id <* library_iim_identification | (liim_id\
    data_exchange_specification_identification.name = 'ISO_13584_25') AND ((
    liim_id\data_exchange_specification_identification.application[1] = '4') OR
     (liim_id\data_exchange_specification_identification.application[1] = '7'))
    ) <> []) OR (QUERY(x <* aggregate_type | NOT no_more_than_two_nested_levels
    (x)) = []);
END_RULE;
 
RULE no_http_directory_for_supplier_related_file_rule FOR (http_file, 
  supplier_bsu_related_content);
WHERE
  wr1 : QUERY(http_f <* http_file | ( 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.SUPPLIER_BSU_RELATED_CONTENT' IN 
    TYPEOF(http_f\external_file_unit.unit_of.content_of.content_of)) AND EXISTS
    (http_f.http_directory)) = [];
END_RULE;
 
RULE representation_properties_for_model_and_view_rule FOR (property_det);
WHERE
  wr1 : QUERY(prop <* property_det | (SIZEOF(prop.identified_by.name_scope.
    definition) = 1) AND (( 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.FUNCTIONAL_MODEL_CLASS' IN TYPEOF
    (prop.identified_by.name_scope.definition)) OR (
     
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.FUNCTIONAL_VIEW_CLASS' IN TYPEOF(
    prop.identified_by.name_scope.definition))) AND NOT (
     
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.REPRESENTATION_P_DET' IN TYPEOF(
    prop))) = [];
END_RULE;
 
RULE single_language_assignment FOR (global_language_assignment);
WHERE
  SIZEOF(global_language_assignment) <= 1;
END_RULE;
 
RULE supplier_associated_items_rule FOR (supplier_element);
WHERE
  wr1 : QUERY(temp <* supplier_element | (SIZEOF(temp.associated_items) > 1) OR
     (SIZEOF(temp.associated_items) = 1) AND NOT ( 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.SUPPLIER_PROGRAM_LIBRARY_RELATIONSHIP'
     IN TYPEOF(temp.associated_items))) = [];
END_RULE;
 
RULE unique_http_directory_name_per_supplier_rule FOR (http_class_directory);
WHERE
  wr1 : QUERY(dir_1 <* http_class_directory | QUERY(dir_2 <* 
    http_class_directory | (dir_1.name = dir_2.name) AND (dir_1.class.
    defined_by = dir_2.class.defined_by)) <> [dir_1]) = [];
END_RULE;
 
RULE unique_http_file_name_per_supplier_element_rule FOR (supplier_bsu);
WHERE
  wr1 : QUERY(sup_bsu <* supplier_bsu | (SIZEOF(sup_bsu.definition) = 1) AND (
    QUERY(fil_1 <* supplier_associated_http_files(sup_bsu) | QUERY(fil_2 <* 
    supplier_associated_http_files(sup_bsu) | fil_1.http_file_name = fil_2.
    http_file_name) <> [fil_1]) <> [])) = [];
END_RULE;
 
RULE imported_documents_are_visible_or_applicable_rule FOR(
	a_priori_semantic_relationship, document_element);
WHERE
	WR1: QUERY(rel <* a_priori_semantic_relationship
		| QUERY(doc <* rel.referenced_documents
		| QUERY(cl <* rel.referenced_classes
		| NOT visible_documents(cl, [doc])
		AND NOT applicable_documents(cl, [doc]))
		= rel.referenced_classes) = [])
		= a_priori_semantic_relationship;
END_RULE; -- imported_documents_are_visible_or_applicable_rule

FUNCTION applicable_documents(cl: class_BSU;
	doc: AGGREGATE OF document_BSU): LOGICAL;

IF SIZEOF(doc) = 0
THEN
	RETURN(TRUE);
END_IF;

IF NOT EXISTS(cl)
THEN
	RETURN(UNKNOWN);
END_IF;

IF SIZEOF(cl.definition) = 0
THEN
	RETURN(UNKNOWN);
END_IF;

doc := doc - retrieve_documents(cl);

IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA' +
	'.A_PRIORI_SEMANTIC_RELATIONSHIP' IN TYPEOF(cl.definition[1])
THEN
	Doc := doc - cl.definition[1]\a_priori_semantic_relationship.
		referenced_documents;
END_IF;

IF SIZEOF(doc) = 0
THEN
	RETURN(TRUE);
ELSE
	IF EXISTS(cl.definition[1]\class.its_superclass)
	THEN
		RETURN(applicable_documents(cl.definition[1]
			\class.its_superclass, doc));
	ELSE
		RETURN(FALSE);
	END_IF;
END_IF;

END_FUNCTION; -- applicable_documents

FUNCTION retrieve_documents(cl: class_BSU): SET[0:?] OF document_BSU;
-- requires: { SIZEOF(cl.definition) <> O }

LOCAL
	s: SET[0:?] OF document_BSU := [];
END_LOCAL;

REPEAT i := 1 TO SIZEOF(cl.definition[1]\class.associated_items);
	IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA' +
		'.CLASS_DOCUMENT_RELATIONSHIP'
		IN TYPEOF(cl.definition[1]\class.associated_items[i])
	THEN
		s := s+ cl.definition[1]\class.associated_items[i]
			\class_document_relationship.related_tokens;
	END_IF;
END_REPEAT;

RETURN(s);

END_FUNCTION; -- retrieve_documents


FUNCTION acyclic_superclass_relationship(current : class_bsu; visited : SET OF
  class) : LOGICAL;
  IF SIZEOF(current.definition) = 1 THEN
    IF current.definition[1] IN visited THEN
      RETURN (FALSE);
    ELSE
      IF EXISTS(current.definition[1]\class.its_superclass) THEN
        RETURN (acyclic_superclass_relationship(current.definition[1]\class.
        its_superclass, visited + current.definition[1]));
      ELSE
        RETURN (TRUE);
      END_IF;
    END_IF;
  ELSE
    RETURN (UNKNOWN);
  END_IF;
END_FUNCTION;
 
FUNCTION all_class_descriptions_reachable(cl : class_bsu) : BOOLEAN;
  IF NOT EXISTS(cl) THEN
    RETURN (?);
  END_IF;
  IF SIZEOF(cl.definition) = 0 THEN
    RETURN (FALSE);
  END_IF;
  IF NOT EXISTS(cl.definition[1]\class.its_superclass) THEN
    RETURN (TRUE);
  ELSE
    RETURN (all_class_descriptions_reachable(cl.definition[1]\class.
    its_superclass));
  END_IF;
END_FUNCTION;
 
FUNCTION all_context_parameters_referenced(cdpv : 
  context_dependent_property_value) : LOGICAL;
  IF SIZEOF(cdpv\property_value.prop_def.definition) > 0 THEN
    RETURN (cdpv\property_value.prop_def.definition[1]\dependent_p_det.
    depends_on >= collects_assigned_instance_properties(list_to_set(cdpv.
    the_context)));
  ELSE
    RETURN (UNKNOWN);
  END_IF;
END_FUNCTION;
 
FUNCTION all_properties_are_applicable(expl : explicit_model_class_extension)
   : LOGICAL;
LOCAL
  inst : dic_class_instance;
  prop_val : property_value;
  res : LOGICAL := TRUE;
END_LOCAL;
  REPEAT i := 1 TO SIZEOF(expl.POPULATION);
    inst := expl.POPULATION[i];
    REPEAT j := 1 TO SIZEOF(inst.properties);
      prop_val := inst.properties[j];
      res := res AND applicable_properties(expl\content_item.
      dictionary_definition, [prop_val.prop_def]);
    END_REPEAT;
  END_REPEAT;
  RETURN (res);
END_FUNCTION;
 
FUNCTION all_vcvs_belong_to_instance_identification(class_ext : 
  explicit_model_class_extension) : LOGICAL;
LOCAL
  vcvs : SET OF property_bsu := [];
  created_view : class_bsu;
  cl : class_bsu;
END_LOCAL;
  cl := class_ext\content_item.dictionary_definition;
  IF SIZEOF(cl.definition) = 1 THEN
    created_view := cl.definition[1]\abstract_functional_model_class.
    created_view;
    vcvs := list_to_set(functional_view_v_c_v(created_view));
    IF SIZEOF(created_view.definition) = 1 THEN
      RETURN (vcvs <= list_to_set(class_ext\explicit_model_class_extension.
      instance_identification));
    ELSE
      RETURN (UNKNOWN);
    END_IF;
  ELSE
    RETURN (UNKNOWN);
  END_IF;
END_FUNCTION;
 
FUNCTION all_view_control_variables_belong_to_each_view(class_ext : 
  explicit_model_class_extension) : LOGICAL;
LOCAL
  created_view : class_bsu;
  cl : class_bsu;
  vcvs : SET OF property_bsu;
  i : INTEGER;
  max : INTEGER;
  result : LOGICAL := TRUE;
END_LOCAL;
  cl := class_ext\content_item.dictionary_definition;
  IF SIZEOF(cl.definition) = 1 THEN
    created_view := cl.definition[1]\abstract_functional_model_class.
    created_view;
    vcvs := list_to_set(functional_view_v_c_v(created_view));
    IF SIZEOF(created_view.definition) = 1 THEN
      IF SIZEOF(vcvs) > 0 THEN
        i := 1;
        max := SIZEOF(class_ext.POPULATION);
      ELSE
        result := TRUE;
      END_IF;
    ELSE
      result := UNKNOWN;
    END_IF;
    RETURN (result);
  ELSE
    RETURN (UNKNOWN);
  END_IF;
END_FUNCTION;
 
FUNCTION applicable_properties(cl : class_bsu; prop :  AGGREGATE OF 
  property_bsu) : LOGICAL;
  IF SIZEOF(prop) = 0 THEN
    RETURN (TRUE);
  END_IF;
  IF NOT EXISTS(cl) THEN
    RETURN (UNKNOWN);
  END_IF;
  IF SIZEOF(cl.definition) = 0 THEN
    RETURN (UNKNOWN);
  END_IF;
  prop := prop - list_to_set(cl.definition[1]\class.described_by);
  IF  
  'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.A_PRIORI_SEMANTIC_RELATIONSHIP' IN 
  TYPEOF(cl.definition[1]) THEN
    prop := prop - list_to_set(cl.definition[1]\a_priori_semantic_relationship.
    referenced_properties);
  END_IF;
  IF SIZEOF(prop) = 0 THEN
    RETURN (TRUE);
  ELSE
    IF EXISTS(cl.definition[1]\class.its_superclass) THEN
      RETURN (applicable_properties(cl.definition[1]\class.its_superclass, prop
      ));
    ELSE
      RETURN (FALSE);
    END_IF;
  END_IF;
END_FUNCTION;
 
FUNCTION applicable_types(cl : class_bsu; typ :  AGGREGATE OF data_type_bsu) : 
  LOGICAL;
  IF SIZEOF(typ) = 0 THEN
    RETURN (TRUE);
  END_IF;
  IF NOT EXISTS(cl) THEN
    RETURN (UNKNOWN);
  END_IF;
  IF SIZEOF(cl.definition) = 0 THEN
    RETURN (UNKNOWN);
  END_IF;
  typ := typ - cl.definition[1]\class.defined_types;
  IF  
  'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.A_PRIORI_SEMANTIC_RELATIONSHIP' IN 
  TYPEOF(cl.definition[1]) THEN
    typ := typ - cl.definition[1]\a_priori_semantic_relationship.
    referenced_data_types;
  END_IF;
  IF SIZEOF(typ) = 0 THEN
    RETURN (TRUE);
  ELSE
    IF EXISTS(cl.definition[1]\class.its_superclass) THEN
      RETURN (applicable_types(cl.definition[1]\class.its_superclass, typ));
    ELSE
      RETURN (FALSE);
    END_IF;
  END_IF;
END_FUNCTION;
 
FUNCTION bag_to_set(the_bag :  BAG OF GENERIC : intype) : SET OF GENERIC : 
  intype;
LOCAL
  the_set : SET OF GENERIC : intype := [];
END_LOCAL;
  IF SIZEOF(the_bag) > 0 THEN
    REPEAT i := 1 TO HIINDEX(the_bag);
      the_set := the_set + the_bag[i];
    END_REPEAT;
  END_IF;
  RETURN (the_set);
END_FUNCTION;
 
FUNCTION build_2axes(ref_direction : direction) :  LIST [2:2] OF direction;
LOCAL
  d : direction := NVL(normalise(ref_direction), dummy_gri||direction([1.0, 0.0
  ]));
END_LOCAL;
  RETURN ([d, orthogonal_complement(d)]);
END_FUNCTION;
 
FUNCTION build_axes(axis : direction; ref_direction : direction) :  LIST [3:3]
   OF direction;
LOCAL
  d1 : direction;
  d2 : direction;
END_LOCAL;
  d1 := NVL(normalise(axis), dummy_gri||direction([0.0, 0.0, 1.0]));
  d2 := first_proj_axis(d1, ref_direction);
  RETURN ([d2, normalise(cross_product(d1, d2)).orientation, d1]);
END_FUNCTION;
 
FUNCTION check_class_type_for_dic_f_model_instance(dic_cl : 
  dic_f_model_instance) : LOGICAL;
  IF SIZEOF(dic_cl.class_def.definition) = 1 THEN
    RETURN ( 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ABSTRACT_FUNCTIONAL_MODEL_CLASS' 
    IN TYPEOF(dic_cl.class_def.definition[1]));
  ELSE
    RETURN (UNKNOWN);
  END_IF;
END_FUNCTION;
 
FUNCTION check_class_type_for_dic_item_instance(dic_cl : dic_item_instance) : 
  LOGICAL;
  IF SIZEOF(dic_cl.class_def.definition) = 1 THEN
    IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.' + 'DIC_COMPONENT_INSTANCE' 
    IN TYPEOF(dic_cl) THEN
      RETURN ( 
      'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.COMPONENT_CLASS' IN TYPEOF(
      dic_cl.class_def.definition[1]));
    END_IF;
    IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.' + 'DIC_MATERIAL_INSTANCE' IN
     TYPEOF(dic_cl) THEN
      RETURN ( 
      'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.MATERIAL_CLASS' IN TYPEOF(
      dic_cl.class_def.definition[1]));
    END_IF;
    IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.' + 'DIC_FEATURE_INSTANCE' IN 
    TYPEOF(dic_cl) THEN
      RETURN ( 
      'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.FEATURE_CLASS' IN TYPEOF(dic_cl
      .class_def.definition[1]));
    END_IF;
    IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.' + 'DIC_ITEM_INSTANCE' IN 
    TYPEOF(dic_cl) THEN
      RETURN ( 
      'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ITEM_CLASS' IN TYPEOF(dic_cl.
      class_def.definition[1]));
    END_IF;
  ELSE
    RETURN (UNKNOWN);
  END_IF;
END_FUNCTION;
 
FUNCTION check_datatypes_applicability(cl : class) : LOGICAL;
LOCAL
  inter : SET OF data_type_bsu := [];
END_LOCAL;
  IF EXISTS(cl.its_superclass) THEN
    IF SIZEOF(cl.its_superclass.definition) = 1 THEN
      inter := cl.defined_types * cl.its_superclass.definition[1]\class.
      known_applicable_data_types;
      RETURN (inter = []);
    ELSE
      RETURN (UNKNOWN);
    END_IF;
  ELSE
    RETURN (TRUE);
  END_IF;
END_FUNCTION;
 
FUNCTION check_is_case_of_referenced_classes_definition(cl : item_class_case_of
  ) : BOOLEAN;
LOCAL
  class_def_ok : BOOLEAN := TRUE;
  done : BOOLEAN := FALSE;
END_LOCAL;
  REPEAT i := 1 TO SIZEOF(cl.is_case_of);
    IF SIZEOF(cl.is_case_of[i].definition) = 1 THEN
      IF  
      'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.COMPONENT_CLASS_CASE_OF' IN 
      TYPEOF(cl) THEN
        IF NOT ( 
        'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.COMPONENT_CLASS' IN TYPEOF(cl
        .is_case_of[i].definition[1])) THEN
          class_def_ok := FALSE;
        END_IF;
        done := TRUE;
      END_IF;
      IF  
      'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.FEATURE_CLASS_CASE_OF' IN 
      TYPEOF(cl) THEN
        IF NOT ( 
        'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.FEATURE_CLASS' IN TYPEOF(cl.
        is_case_of[i].definition[1])) THEN
          class_def_ok := FALSE;
        END_IF;
        done := TRUE;
      END_IF;
      IF  
      'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.MATERIAL_CLASS_CASE_OF' IN 
      TYPEOF(cl) THEN
        IF NOT ( 
        'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.MATERIAL_CLASS' IN TYPEOF(cl.
        is_case_of[i].definition[1])) THEN
          class_def_ok := FALSE;
        END_IF;
        done := TRUE;
      END_IF;
      IF ( 
      'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ITEM_CLASS_CASE_OF' IN TYPEOF(
      cl)) AND NOT done THEN
        IF NOT ( 
        'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ITEM_CLASS' IN TYPEOF(cl.
        is_case_of[i].definition[1])) THEN
          class_def_ok := FALSE;
        END_IF;
      END_IF;
      done := FALSE;
    END_IF;
  END_REPEAT;
  RETURN (class_def_ok);
END_FUNCTION;
 
FUNCTION check_label_length(l : translatable_label; l_length : INTEGER) : 
  BOOLEAN;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.TRANSLATED_LABEL' IN TYPEOF(l)
   THEN
    REPEAT i := 1 TO SIZEOF(l.labels);
      IF LENGTH(l.labels[i]) > l_length THEN
        RETURN (FALSE);
      END_IF;
    END_REPEAT;
    RETURN (TRUE);
  ELSE
    RETURN (LENGTH(l) <= l_length);
  END_IF;
END_FUNCTION;
 
FUNCTION check_properties_applicability(cl : class) : LOGICAL;
LOCAL
  inter : SET OF property_bsu := [];
END_LOCAL;
  IF EXISTS(cl.its_superclass) THEN
    IF SIZEOF(cl.its_superclass.definition) = 1 THEN
      inter := list_to_set(cl.described_by) * cl.its_superclass.definition[1]\
      class.known_applicable_properties;
      RETURN (inter = []);
    ELSE
      RETURN (UNKNOWN);
    END_IF;
  ELSE
    RETURN (TRUE);
  END_IF;
END_FUNCTION;
 
FUNCTION check_property_values_translations(props : LIST OF property_value) : 
  LOGICAL;
LOCAL
  translated_string_values : SET OF translated_string_value := [];
END_LOCAL;
  REPEAT i := 1 TO SIZEOF(props);
    translated_string_values := translated_string_values + props[i].its_value;
  END_REPEAT;
  RETURN (same_translations(translated_string_values));
END_FUNCTION;
 
FUNCTION check_syn_length(s : syn_name_type; s_length : INTEGER) : BOOLEAN;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.LABEL_WITH_LANGUAGE' IN TYPEOF(s
  ) THEN
    RETURN (LENGTH(s.l) <= s_length);
  ELSE
    RETURN (LENGTH(s) <= s_length);
  END_IF;
END_FUNCTION;
 
FUNCTION check_view_of_instance_datatype(fmc_view_of : fm_class_view_of) : 
  LOGICAL;
  IF SIZEOF(fmc_view_of.view_of.definition) = 1 THEN
    RETURN ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ITEM_CLASS' IN TYPEOF(
    fmc_view_of.view_of.definition[1]));
  ELSE
    RETURN (UNKNOWN);
  END_IF;
END_FUNCTION;
 
FUNCTION codes_are_unique(values : LIST OF dic_value) : BOOLEAN;
LOCAL
  ls : SET OF STRING := [];
  li : SET OF INTEGER := [];
END_LOCAL;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.VALUE_CODE_TYPE' IN TYPEOF(
  values[1].value_code) THEN
    REPEAT i := 1 TO SIZEOF(values);
      ls := ls + values[i].value_code;
    END_REPEAT;
    RETURN (SIZEOF(values) = SIZEOF(ls));
  ELSE
    IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.INTEGER_TYPE' IN TYPEOF(values
    [1].value_code) THEN
      REPEAT i := 1 TO SIZEOF(values);
        li := li + values[i].value_code;
      END_REPEAT;
      RETURN (SIZEOF(values) = SIZEOF(li));
    ELSE
      RETURN (?);
    END_IF;
  END_IF;
END_FUNCTION;
 
FUNCTION collects_assigned_instance_properties(props : SET OF property_value)
   : SET OF property_bsu;
LOCAL
  assign_prop : SET OF property_bsu;
END_LOCAL;
  assign_prop := [];
  REPEAT i := 1 TO SIZEOF(props);
    assign_prop := assign_prop + props[i].prop_def;
  END_REPEAT;
  RETURN (assign_prop);
END_FUNCTION;
 
FUNCTION collects_property_context(prop : property_bsu; inst : 
  dic_class_instance) : SET OF property_bsu;
LOCAL
  assigned_context_parameters : SET OF property_bsu;
  correct : BOOLEAN;
END_LOCAL;
  assigned_context_parameters := [];
  correct := FALSE;
  REPEAT i := 1 TO SIZEOF(inst.properties);
    IF inst.properties[i].prop_def :=: prop THEN
      correct := TRUE;
    END_IF;
    IF (SIZEOF(inst.properties[i].prop_def.definition) = 0) OR (SIZEOF(inst.
    properties[i].prop_def.definition) = 1) AND (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CONDITION_DET' IN TYPEOF(inst.
    properties[i].prop_def.definition[1])) THEN
      assigned_context_parameters := assigned_context_parameters + inst.
      properties[i].prop_def;
    END_IF;
    IF  
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CONTEXT_DEPENDENT_PROPERTY_VALUE'
     IN TYPEOF(inst.properties[i]) THEN
      assigned_context_parameters := assigned_context_parameters + 
      collects_assigned_instance_properties(list_to_set(inst.properties[i].
      the_context));
    END_IF;
  END_REPEAT;
  IF NOT correct THEN
    assigned_context_parameters := [];
  END_IF;
  RETURN (assigned_context_parameters);
END_FUNCTION;
 
FUNCTION compatible_class_and_class(cl1 : class_bsu; cl2 : class_bsu) : LOGICAL
  ;
  IF (cl1.defined_by\basic_semantic_unit.code = cl2.defined_by\
  basic_semantic_unit.code) AND (cl1\basic_semantic_unit.code = cl2\
  basic_semantic_unit.code) AND (cl1\basic_semantic_unit.version >= cl2\
  basic_semantic_unit.version) THEN
    RETURN (TRUE);
  END_IF;
  IF SIZEOF(cl2\basic_semantic_unit.definition) = 0 THEN
    RETURN (UNKNOWN);
  END_IF;
  IF (SIZEOF(cl2\basic_semantic_unit.definition) = 1) AND NOT EXISTS(cl2\
  basic_semantic_unit.definition[1]\class.its_superclass) THEN
    RETURN (FALSE);
  END_IF;
  RETURN (compatible_class_and_class(cl1, cl2\basic_semantic_unit.definition[1]
  \class.its_superclass));
END_FUNCTION;
 
FUNCTION compatible_complete_types_and_value(dom : property_or_data_type_bsu; 
  val : primitive_value) : LOGICAL;
  IF data_type_typeof(dom) = [] THEN
    RETURN (UNKNOWN);
  END_IF;
  IF ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.PRIMITIVE_VALUE' IN TYPEOF(val)
  ) AND NOT ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.' + 
  'AGGREGATE_ENTITY_INSTANCE_VALUE' IN TYPEOF(val)) THEN
    RETURN (compatible_type_and_value(dom, val));
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.' + 
  'AGGREGATE_ENTITY_INSTANCE_VALUE' IN TYPEOF(val) THEN
    RETURN (compatible_aggregate_domain_and_aggregate_value(dom, val));
  END_IF;
  RETURN (UNKNOWN);
END_FUNCTION;
 
FUNCTION compatible_item_caseof_with_class_definition(inst : dic_item_instance)
   : LOGICAL;
  IF SIZEOF(inst.case_of) > 0 THEN
    IF SIZEOF(inst.class_def.definition) = 1 THEN
      RETURN (inst.case_of <= item_caseof_closure([inst.class_def]));
    ELSE
      RETURN (UNKNOWN);
    END_IF;
  ELSE
    RETURN (TRUE);
  END_IF;
END_FUNCTION;
 
FUNCTION compatible_level_type_and_instance(levels :  LIST [1:4] OF level; 
  value_typeof : SET OF STRING; val : level_spec_value) : BOOLEAN;
LOCAL
  c_val : BOOLEAN;
END_LOCAL;
  c_val := FALSE;
  IF ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.INT_LEVEL_SPEC_VALUE' IN TYPEOF
  (val)) AND NOT ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.REAL_TYPE' IN 
  value_typeof) THEN
    c_val := TRUE;
  END_IF;
  IF ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.REAL_LEVEL_SPEC_VALUE' IN 
  TYPEOF(val)) AND NOT ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.INT_TYPE' IN 
  value_typeof) THEN
    c_val := TRUE;
  END_IF;
  RETURN (c_val AND right_values_for_level_spec(levels, val));
END_FUNCTION;
 
FUNCTION compatible_model_caseof_with_class_definition(inst : 
  dic_f_model_instance) : LOGICAL;
  IF SIZEOF(inst.case_of) > 0 THEN
    IF SIZEOF(inst.class_def.definition) = 1 THEN
      RETURN (inst.case_of <= model_caseof_closure([inst.class_def]));
    ELSE
      RETURN (UNKNOWN);
    END_IF;
  ELSE
    RETURN (TRUE);
  END_IF;
END_FUNCTION;
 
FUNCTION compatible_subclass(c1 : class_bsu; c2 : class_bsu) : LOGICAL;
  IF NOT EXISTS(c1) OR NOT EXISTS(c2) THEN
    RETURN (UNKNOWN);
  END_IF;
  IF c1 = c2 THEN
    RETURN (TRUE);
  END_IF;
  IF (c1.code = c2.code) AND (c1.version >= c2.version) AND (c1.defined_by.code
   = c2.defined_by.code) THEN
    RETURN (TRUE);
  END_IF;
  IF SIZEOF(c2.definition) = 0 THEN
    RETURN (UNKNOWN);
  ELSE
    IF EXISTS(c2.definition[1]\class.its_superclass) THEN
      RETURN (compatible_subclass(c1, c2.definition[1]\class.its_superclass));
    ELSE
      RETURN (FALSE);
    END_IF;
  END_IF;
END_FUNCTION;

FUNCTION compatible_type_and_value(dom : property_or_data_type_bsu; val :
  primitive_value) : LOGICAL;
LOCAL
  temp : SET [0:1] OF class_bsu;
  set_string : SET OF STRING := [];
  set_integer : SET OF INTEGER := [];
  code_type : non_quantitative_code_type;
  int_type : non_quantitative_int_type;
END_LOCAL;
  IF data_type_typeof(dom) = [] THEN
    RETURN (UNKNOWN);
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.INTEGER_VALUE' IN TYPEOF(val)
   THEN
    IF ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.' +
    'NON_QUANTITATIVE_INT_TYPE' IN data_type_typeof(dom)) AND (SIZEOF(
    data_type_non_quantitative_int_type(dom)) = 1) THEN
      set_integer := [];
      int_type := data_type_non_quantitative_int_type(dom)[1];
      REPEAT j := 1 TO SIZEOF(code_type.domain.its_values);
        set_integer := set_integer + code_type.domain.its_values[j].value_code;
      END_REPEAT;
      RETURN (val IN set_integer);
    ELSE
      RETURN (('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.INT_TYPE' IN 
      data_type_typeof(dom)) OR (
      'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NUMBER_TYPE' IN 
      data_type_typeof(dom)) AND NOT (
      'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.REAL_TYPE' IN data_type_typeof(
      dom)));
    END_IF;
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.REAL_VALUE' IN TYPEOF(val) THEN
    RETURN (('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.REAL_TYPE' IN 
    data_type_typeof(dom)) OR (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NUMBER_TYPE' IN data_type_typeof(
    dom)) AND NOT ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.INT_TYPE' IN 
    data_type_typeof(dom)));
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NUMBER_VALUE' IN TYPEOF(val)
   THEN
    RETURN ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NUMBER_TYPE' IN 
    data_type_typeof(dom));
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.BOOLEAN_VALUE' IN TYPEOF(val)
   THEN
    RETURN ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.BOOLEAN_TYPE' IN 
    data_type_typeof(dom));
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.TRANSLATABLE_STRING_VALUE' IN 
  TYPEOF(val) THEN
    IF  
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NON_QUANTITATIVE_CODE_TYPE' IN 
    data_type_typeof(dom) THEN
      IF SIZEOF(data_type_non_quantitative_code_type(dom)) = 1 THEN
        set_string := [];
        code_type := data_type_non_quantitative_code_type(dom)[1];
        REPEAT j := 1 TO SIZEOF(code_type.domain.its_values);
          set_string := set_string + code_type.domain.its_values[j].value_code;
        END_REPEAT;
        RETURN (('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.STRING_VALUE' IN 
        TYPEOF(val)) AND (val IN set_string));
      ELSE
        RETURN (UNKNOWN);
      END_IF;
    ELSE
      RETURN ( 
      'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.STRING_TYPE' IN 
      data_type_typeof(dom));
    END_IF;
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ENTITY_INSTANCE_VALUE' IN TYPEOF
  (val) THEN
    IF  
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.UNCONTROLLED_ENTITY_INSTANCE_VALUE'
     IN TYPEOF(val) THEN
      RETURN (UNKNOWN);
    END_IF;
    IF ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ENTITY_INSTANCE_TYPE' IN 
    data_type_typeof(dom)) AND (SIZEOF(data_type_type_name(dom)) <> 0) AND (
    data_type_type_name(dom) <= TYPEOF(val)) THEN
      RETURN (TRUE);
    ELSE
      RETURN (FALSE);
    END_IF;
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.DIC_CLASS_INSTANCE' IN TYPEOF(
  val) THEN
    IF ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CLASS_INSTANCE_TYPE' IN 
    data_type_typeof(dom)) AND (SIZEOF(data_type_class_of(dom)) <> 0) THEN
      temp := data_type_class_of(dom);
      RETURN (compatible_class_and_class(temp[1], val\dic_class_instance.
      class_def));
    ELSE
      RETURN (FALSE);
    END_IF;
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.LEVEL_SPEC_VALUE' IN TYPEOF(val)
   THEN
    IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.LEVEL_TYPE' IN 
    data_type_typeof(dom) THEN
      RETURN (compatible_level_type_and_instance(data_type_level_spec(dom), 
      data_type_level_value_typeof(dom), val));
    ELSE
      RETURN (FALSE);
    END_IF;
  END_IF;
  RETURN (FALSE);
END_FUNCTION;
 
FUNCTION compatible_types(p1 : property_or_data_type_bsu; p2 : 
  property_or_data_type_bsu) : LOGICAL;
LOCAL
  p1_domain : data_type;
  p2_domain : data_type;
END_LOCAL;
  IF NOT EXISTS(p1) OR NOT EXISTS(p2) THEN
    RETURN (UNKNOWN);
  END_IF;
  IF p1 = p2 THEN
    RETURN (TRUE);
  END_IF;
  IF (TYPEOF(p1) = TYPEOF(p2)) AND (p1\basic_semantic_unit.code = p2.code) AND 
  (p1.name_scope\basic_semantic_unit.code = p2.name_scope\basic_semantic_unit.
  code) AND (p1\basic_semantic_unit.version >= p2\basic_semantic_unit.version)
   THEN
    RETURN (TRUE);
  END_IF;
  IF (SIZEOF(p1\basic_semantic_unit.definition) = 0) OR (SIZEOF(p2\
  basic_semantic_unit.definition) = 0) THEN
    RETURN (UNKNOWN);
  ELSE
    IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.PROPERTY_BSU' IN TYPEOF(p1)
     THEN
      p1_domain := p1.definition[1]\property_det.domain;
    ELSE
      p1_domain := p1.definition[1]\data_type_element.type_definition;
    END_IF;
    IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.PROPERTY_BSU' IN TYPEOF(p2)
     THEN
      p2_domain := p2.definition[1]\property_det.domain;
    ELSE
      p2_domain := p2.definition[1]\data_type_element.type_definition;
    END_IF;
  END_IF;
  IF p1_domain = p2_domain THEN
    RETURN (TRUE);
  END_IF;
  IF NOT (SIZEOF(data_type_typeof(p1)) = 0) AND (data_type_typeof(p1) <= 
  data_type_typeof(p2)) AND NOT (
  'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.COMPLEX_TYPE' IN data_type_typeof(
  p2)) THEN
    RETURN (TRUE);
  END_IF;
  IF ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CLASS_INSTANCE_TYPE' IN 
  data_type_typeof(p1)) AND (
  'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CLASS_INSTANCE_TYPE' IN 
  data_type_typeof(p2)) THEN
    RETURN (compatible_subclass(data_type_class_of(p1)[1], data_type_class_of(
    p2)[1]));
  END_IF;
  IF ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ENTITY_INSTANCE_TYPE' IN 
  data_type_typeof(p1)) AND (
  'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ENTITY_INSTANCE_TYPE' IN 
  data_type_typeof(p2)) THEN
    IF (data_type_type_name(p1) <= data_type_type_name(p2)) AND (
    data_type_type_name(p1) <> []) THEN
      RETURN (TRUE);
    ELSE
      RETURN (FALSE);
    END_IF;
  END_IF;
  IF ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.LEVEL_TYPE' IN data_type_typeof
  (p1)) AND ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.LEVEL_TYPE' IN 
  data_type_typeof(p2)) THEN
    IF (data_type_level_spec(p1) = data_type_level_spec(p2)) AND (
    data_type_level_value_typeof(p1) <> []) AND (data_type_level_value_typeof(
    p1) <= data_type_level_value_typeof(p2)) THEN
      RETURN (TRUE);
    ELSE
      RETURN (FALSE);
    END_IF;
  END_IF;
  IF (data_type_typeof(p1) = []) OR (data_type_typeof(p2) = []) THEN
    RETURN (UNKNOWN);
  ELSE
    RETURN (FALSE);
  END_IF;
END_FUNCTION;
 
FUNCTION compliant_8859_1_protocol_25(ef : external_file_protocol) : BOOLEAN;
  IF ( 
  'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.STANDARD_DATA_PROTOCOL' IN TYPEOF(
  ef)) AND (ef.organisation.id = 'ISO') AND (ef.organisation.name = 
  'International Organisation for Standardization') AND (ef.protocol_name = 
  'ISO_8859_1') AND (ef.designation.preferred_name = 'Latin alphabet No 1') AND
   (ef.designation.short_name = 'ISO 8859-1') THEN
    RETURN (TRUE);
  ELSE
    RETURN (FALSE);
  END_IF;
END_FUNCTION;
 
FUNCTION compliant_external_file_protocol_25(s : SET OF external_file_protocol)
   : BOOLEAN;
  REPEAT i := 1 TO SIZEOF(s);
    IF NOT (compliant_8859_1_protocol_25(s[i]) OR compliant_http_protocol_25(s[
    i])) THEN
      RETURN (FALSE);
    END_IF;
  END_REPEAT;
  RETURN (TRUE);
END_FUNCTION;
 
FUNCTION compliant_http_protocol_25(ef : external_file_protocol) : BOOLEAN;
LOCAL
  ok : BOOLEAN := TRUE;
END_LOCAL;
  IF ( 
  'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.HTTP_PROTOCOL' IN TYPEOF(ef)) AND (
  ef.organisation.id = 'IAB') AND (ef.organisation.name = 
  'Internet Architecture Board') AND ((ef.protocol_name = 'HTTP') OR (ef.
  protocol_name = 'HTTPS')) AND (ef.designation.preferred_name = 
  'Hypertext Transfer Protocol') THEN
    IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.TRANSLATED_LABEL' IN TYPEOF(ef
    .designation.short_name) THEN
      REPEAT i := 1 TO SIZEOF(ef.designation.short_name\translated_label.labels
        );
        IF ef.designation.short_name\translated_label.labels[i] LIKE 'RFC####&'
         THEN
          ok := ok AND TRUE;
        ELSE
          ok := ok AND FALSE;
        END_IF;
      END_REPEAT;
      RETURN (ok);
    ELSE
      IF ef.designation.short_name LIKE 'RFC####&' THEN
        RETURN (TRUE);
      ELSE
        RETURN (FALSE);
      END_IF;
    END_IF;
  ELSE
    RETURN (FALSE);
  END_IF;
END_FUNCTION;
 
FUNCTION compute_known_applicable_data_types(cl : class_bsu) : SET OF 
  data_type_bsu;
LOCAL
  s : SET OF data_type_bsu := [];
END_LOCAL;
  IF SIZEOF(cl.definition) = 0 THEN
    RETURN (s);
  ELSE
    REPEAT i := 1 TO SIZEOF(cl.definition[1]\class.defined_types);
      s := s + cl.definition[1]\class.defined_types[i];
    END_REPEAT;
    IF EXISTS(cl.definition[1]\class.its_superclass) THEN
      s := s + compute_known_applicable_data_types(cl.definition[1]\class.
      its_superclass);
    END_IF;
    RETURN (s);
  END_IF;
END_FUNCTION;
 
FUNCTION compute_known_applicable_properties(cl : class_bsu) : SET OF 
  property_bsu;
LOCAL
  s : SET OF property_bsu := [];
END_LOCAL;
  IF SIZEOF(cl.definition) = 0 THEN
    RETURN (s);
  ELSE
    REPEAT i := 1 TO SIZEOF(cl.definition[1]\class.described_by);
      s := s + cl.definition[1]\class.described_by[i];
    END_REPEAT;
    IF EXISTS(cl.definition[1]\class.its_superclass) THEN
      s := s + compute_known_applicable_properties(cl.definition[1]\class.
      its_superclass);
    END_IF;
    RETURN (s);
  END_IF;
END_FUNCTION;
 
FUNCTION compute_known_visible_data_types(cl : class_bsu) : SET OF 
  data_type_bsu;
LOCAL
  s : SET OF data_type_bsu := [];
END_LOCAL;
  s := s + USEDIN(cl, 
  'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.DATA_TYPE_BSU.NAME_SCOPE');
  IF SIZEOF(cl.definition) = 0 THEN
    RETURN (s);
  ELSE
    IF EXISTS(cl.definition[1]\class.its_superclass) THEN
      s := s + compute_known_visible_data_types(cl.definition[1]\class.
      its_superclass);
    END_IF;
    RETURN (s);
  END_IF;
END_FUNCTION;
 
FUNCTION compute_known_visible_properties(cl : class_bsu) : SET OF property_bsu
  ;
LOCAL
  s : SET OF property_bsu := [];
END_LOCAL;
  s := s + USEDIN(cl, 
  'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.PROPERTY_BSU.NAME_SCOPE');
  IF SIZEOF(cl.definition) = 0 THEN
    RETURN (s);
  ELSE
    IF EXISTS(cl.definition[1]\class.its_superclass) THEN
      s := s + compute_known_visible_properties(cl.definition[1]\class.
      its_superclass);
    END_IF;
    RETURN (s);
  END_IF;
END_FUNCTION;
 
 
FUNCTION control_compiler_version_format(the_compiler_version : STRING) : 
  BOOLEAN;
LOCAL
  result : BOOLEAN := TRUE;
END_LOCAL;
  REPEAT i := 1 TO LENGTH(the_compiler_version);
    IF NOT ((the_compiler_version[i] LIKE '#') OR (the_compiler_version[i] LIKE
     '.') OR (the_compiler_version[i] 
    LIKE '_')) THEN
      result := FALSE;
    END_IF;
  END_REPEAT;
  RETURN (result);
END_FUNCTION;

FUNCTION correct_view_from_model(fv: dic_f_view_instance): LOGICAL;

IF NOT EXISTS(fv.generated_by)
THEN
	RETURN(UNKNOWN);
END_IF;

IF NOT(SIZEOF(fv.generated_by\dic_class_instance.class_def.
	definition) = 1)
THEN
	RETURN(UNKNOWN);
ELSE
	RETURN(fv.generated_by\dic_class_instance.class_def
		.definition[1].created_view = 
		fv\dic_class_instance.class_def);
END_IF;

END_FUNCTION; -- correct_view_from_model

FUNCTION check_class_type_for_dic_f_view_instance(
	dic_cl: dic_f_view_instance): LOGICAL;

IF (SIZEOF(dic_cl.class_def.definition) = 1)
THEN
	IF ('ISO13584_EXTENDED_DICTIONARY_SCHEMA' +
		'.DIC_F_VIEW_INSTANCE') IN TYPEOF(dic_cl)
	THEN
			RETURN('ISO13584_EXTENDED_DICTIONARY_SCHEMA'
			+ '.FUNCTIONAL_VIEW_CLASS'
			IN TYPEOF(dic_cl.class_def.definition[1]));
	END_IF;

ELSE
	RETURN(UNKNOWN);
END_IF;
END_FUNCTION; -- check_class_type_for_dic_f_view_instance
 
FUNCTION correct_parameters_for_explicit_program(a_model : dic_class_instance; 
  prop : property_bsu) : BOOLEAN;
  IF NOT ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.' + 
  'PROGRAM_REFERENCE_TYPE' IN data_type_typeof(prop)) THEN
    RETURN (FALSE);
  END_IF;
  REPEAT i := 1 TO SIZEOF(a_model.properties);
    IF prop = a_model.properties[i].prop_def THEN
      IF EXISTS(a_model.properties[i].its_value) AND (
      'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.' + 'PROGRAM_REFERENCE' IN 
      TYPEOF(a_model.properties[i].its_value)) AND (SIZEOF(a_model.properties[i
      ].its_value.out_parameters) = 0) AND (SIZEOF(a_model.properties[i].
      its_value.inout_parameters) = 0) AND (QUERY(in_p <* a_model.properties[i]
      .its_value.in_parameters | NOT (
      'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.' + 'PROPERTY_BSU' IN TYPEOF(
      in_p)) OR NOT is_provided_once_property_value(a_model, in_p)) = []) THEN
        RETURN (TRUE);
      ELSE
        RETURN (FALSE);
      END_IF;
    END_IF;
  END_REPEAT;
  RETURN (FALSE);
END_FUNCTION;
 
FUNCTION created_view_is_functional_view(cl : class_bsu) : LOGICAL;
  IF SIZEOF(cl\basic_semantic_unit.definition) = 1 THEN
    RETURN ( 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.FUNCTIONAL_VIEW_CLASS' IN TYPEOF(
    cl\basic_semantic_unit.definition[1]));
  ELSE
    RETURN (UNKNOWN);
  END_IF;
END_FUNCTION;
 
FUNCTION cross_product(arg1 : direction; arg2 : direction) : vector;
LOCAL
  mag : REAL;
  res : direction;
  v1 :  LIST [3:3] OF REAL;
  v2 :  LIST [3:3] OF REAL;
  result : vector;
END_LOCAL;
  IF NOT EXISTS(arg1) OR (arg1.dim = 2) OR NOT EXISTS(arg2) OR (arg2.dim = 2)
   THEN
    RETURN (?);
  ELSE
    v1 := normalise(arg1).direction_ratios;
    v2 := normalise(arg2).direction_ratios;
    res := dummy_gri||direction([v1[2] * v2[3] - v1[3] * v2[2], v1[3] * v2[1]
     - v1[1] * v2[3], v1[1] * v2[2] - v1[2] * v2[1]]);
    mag := 0.0;
    REPEAT i := 1 TO 3;
      mag := mag + res.direction_ratios[i] * res.direction_ratios[i];
    END_REPEAT;
    IF mag > 0.0 THEN
      result := dummy_gri||vector(res, (mag));
    ELSE
      result := dummy_gri||vector(arg1, 0.0);
    END_IF;
    RETURN (result);
  END_IF;
END_FUNCTION;
 
FUNCTION data_type_class_of(type_spec : property_or_data_type_bsu) : SET [0:1]
   OF class_bsu;
LOCAL
  res : BOOLEAN := FALSE;
  s : SET [0:1] OF class_bsu := [];
  x : data_type;
END_LOCAL;
  IF NOT EXISTS(type_spec) THEN
    RETURN ([]);
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.PROPERTY_BSU' IN TYPEOF(
  type_spec) THEN
    IF NOT (SIZEOF(type_spec.definition) = 0) THEN
      x := type_spec.definition[1]\property_det.domain;
      res := TRUE;
    END_IF;
  ELSE
    IF NOT (SIZEOF(type_spec.definition) = 0) THEN
      x := type_spec.definition[1]\data_type_element.type_definition;
      res := TRUE;
    END_IF;
  END_IF;
  IF res THEN
    IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CLASS_INSTANCE_TYPE' IN TYPEOF
    (x) THEN
      s := s + x\class_instance_type.domain;
      RETURN (s);
    END_IF;
    IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NAMED_TYPE' IN TYPEOF(x) THEN
      s := data_type_class_of(x\named_type.referred_type);
      RETURN (s);
    END_IF;
  END_IF;
  RETURN (s);
END_FUNCTION;
 
FUNCTION data_type_level_spec(t : property_or_data_type_bsu) :  LIST [0:4] OF 
  level;
LOCAL
  res : BOOLEAN := FALSE;
  s :  LIST [0:4] OF level := [];
  x : data_type;
END_LOCAL;
  IF NOT EXISTS(t) THEN
    RETURN ([]);
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.PROPERTY_BSU' IN TYPEOF(t) THEN
    IF NOT (SIZEOF(t.definition) = 0) THEN
      x := t.definition[1]\property_det.domain;
      res := TRUE;
    END_IF;
  ELSE
    IF NOT (SIZEOF(t.definition) = 0) THEN
      x := t.definition[1]\data_type_element.type_definition;
      res := TRUE;
    END_IF;
  END_IF;
  IF res THEN
    IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.LEVEL_TYPE' IN TYPEOF(x) THEN
      s := x\level_type.levels;
    END_IF;
    IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NAMED_TYPE' IN TYPEOF(x) THEN
      s := data_type_level_spec(x\named_type.referred_type);
    END_IF;
  END_IF;
  RETURN (s);
END_FUNCTION;
 
FUNCTION data_type_level_value_typeof(t : property_or_data_type_bsu) : SET OF 
  STRING;
LOCAL
  res : BOOLEAN := FALSE;
  s : SET OF STRING := [];
  x : data_type;
END_LOCAL;
  IF NOT EXISTS(t) THEN
    RETURN ([]);
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.PROPERTY_BSU' IN TYPEOF(t) THEN
    IF NOT (SIZEOF(t.definition) = 0) THEN
      x := t.definition[1]\property_det.domain;
      res := TRUE;
    END_IF;
  ELSE
    IF NOT (SIZEOF(t.definition) = 0) THEN
      x := t.definition[1]\data_type_element.type_definition;
      res := TRUE;
    END_IF;
  END_IF;
  IF res THEN
    IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.LEVEL_TYPE' IN TYPEOF(x) THEN
      s := TYPEOF(x\level_type.value_type);
    END_IF;
    IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NAMED_TYPE' IN TYPEOF(x) THEN
      s := data_type_level_value_typeof(x\named_type.referred_type);
    END_IF;
  END_IF;
  RETURN (s);
END_FUNCTION;
 
FUNCTION data_type_named_type(type_spec : property_or_data_type_bsu) : SET [0:1
  ] OF data_type_bsu;
LOCAL
  res : BOOLEAN := FALSE;
  s : SET [0:1] OF data_type_bsu := [];
  x : data_type;
END_LOCAL;
  IF NOT EXISTS(type_spec) THEN
    RETURN ([]);
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.PROPERTY_BSU' IN TYPEOF(
  type_spec) THEN
    IF NOT (SIZEOF(type_spec.definition) = 0) THEN
      x := type_spec.definition[1]\property_det.domain;
      res := TRUE;
    END_IF;
  ELSE
    IF NOT (SIZEOF(type_spec.definition) = 0) THEN
      x := type_spec.definition[1]\data_type_element.type_definition;
      res := TRUE;
    END_IF;
  END_IF;
  IF res THEN
    IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NAMED_TYPE' IN TYPEOF(x) THEN
      s := s + x\named_type.referred_type;
    END_IF;
  END_IF;
  RETURN (s);
END_FUNCTION;
 
FUNCTION data_type_non_quantitative_code_type(type_spec : 
  property_or_data_type_bsu) : SET [0:1] OF non_quantitative_code_type;
LOCAL
  res : BOOLEAN := FALSE;
  s : SET [0:1] OF non_quantitative_code_type := [];
  x : data_type;
END_LOCAL;
  IF NOT EXISTS(type_spec) THEN
    RETURN ([]);
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.PROPERTY_BSU' IN TYPEOF(
  type_spec) THEN
    IF NOT (SIZEOF(type_spec.definition) = 0) THEN
      x := type_spec.definition[1]\property_det.domain;
      res := TRUE;
    END_IF;
  ELSE
    IF NOT (SIZEOF(type_spec.definition) = 0) THEN
      x := type_spec.definition[1]\data_type_element.type_definition;
      res := TRUE;
    END_IF;
  END_IF;
  IF res THEN
    IF  
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NON_QUANTITATIVE_CODE_TYPE' IN 
    TYPEOF(x) THEN
      s := s + x;
      RETURN (s);
    END_IF;
    IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NAMED_TYPE' IN TYPEOF(x) THEN
      s := data_type_non_quantitative_code_type(x\named_type.referred_type);
      RETURN (s);
    END_IF;
  END_IF;
  RETURN ([]);
END_FUNCTION;
 
FUNCTION data_type_non_quantitative_int_type(type_spec : 
  property_or_data_type_bsu) : SET [0:1] OF non_quantitative_int_type;
LOCAL
  res : BOOLEAN := FALSE;
  s : SET [0:1] OF non_quantitative_int_type := [];
  x : data_type;
END_LOCAL;
  IF NOT EXISTS(type_spec) THEN
    RETURN ([]);
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.PROPERTY_BSU' IN TYPEOF(
  type_spec) THEN
    IF NOT (SIZEOF(type_spec.definition) = 0) THEN
      x := type_spec.definition[1]\property_det.domain;
      res := TRUE;
    END_IF;
  ELSE
    IF NOT (SIZEOF(type_spec.definition) = 0) THEN
      x := type_spec.definition[1]\data_type_element.type_definition;
      res := TRUE;
    END_IF;
  END_IF;
  IF res THEN
    IF  
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NON_QUANTITATIVE_INT_TYPE' IN 
    TYPEOF(x) THEN
      s := s + x;
      RETURN (s);
    END_IF;
    IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NAMED_TYPE' IN TYPEOF(x) THEN
      s := data_type_non_quantitative_int_type(x\named_type.referred_type);
      RETURN (s);
    END_IF;
  END_IF;
  RETURN ([]);
END_FUNCTION;
 
FUNCTION data_type_of_bsu(type_spec : property_or_data_type_bsu) : SET [0:1]
   OF data_type;
LOCAL
  res : BOOLEAN := FALSE;
  x : data_type;
END_LOCAL;
  IF NOT EXISTS(type_spec) THEN
    RETURN ([]);
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.PROPERTY_BSU' IN TYPEOF(
  type_spec) THEN
    IF NOT (SIZEOF(type_spec.definition) = 0) THEN
      x := type_spec.definition[1]\property_det.domain;
      res := TRUE;
    END_IF;
  ELSE
    IF NOT (SIZEOF(type_spec.definition) = 0) THEN
      x := type_spec.definition[1]\data_type_element.type_definition;
      res := TRUE;
    END_IF;
  END_IF;
  IF NOT res THEN
    RETURN ([]);
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NAMED_TYPE' IN TYPEOF(x) THEN
    IF NOT (SIZEOF(x\named_type.referred_type.definition) = 0) THEN
      RETURN (data_type_of_bsu(x\named_type.referred_type));
    ELSE
      RETURN ([]);
    END_IF;
  ELSE
    RETURN ([x]);
  END_IF;
END_FUNCTION;
 
FUNCTION data_type_type_name(t : property_or_data_type_bsu) : SET OF STRING;
LOCAL
  res : BOOLEAN := FALSE;
  s : SET [0:1] OF STRING := [];
  x : data_type;
END_LOCAL;
  IF NOT EXISTS(t) THEN
    RETURN ([]);
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.PROPERTY_BSU' IN TYPEOF(t) THEN
    IF NOT (SIZEOF(t.definition) = 0) THEN
      x := t.definition[1]\property_det.domain;
      res := TRUE;
    END_IF;
  ELSE
    IF NOT (SIZEOF(t.definition) = 0) THEN
      x := t.definition[1]\data_type_element.type_definition;
      res := TRUE;
    END_IF;
  END_IF;
  IF res THEN
    IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ENTITY_INSTANCE_TYPE' IN 
    TYPEOF(x) THEN
      s := x\entity_instance_type.type_name;
    END_IF;
    IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NAMED_TYPE' IN TYPEOF(x) THEN
      s := data_type_type_name(x\named_type.referred_type);
    END_IF;
  END_IF;
  RETURN (s);
END_FUNCTION;
 
FUNCTION data_type_typeof(type_spec : property_or_data_type_bsu) : SET OF 
  STRING;
LOCAL
  res : BOOLEAN := FALSE;
  x : data_type;
END_LOCAL;
  IF NOT EXISTS(type_spec) THEN
    RETURN ([]);
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.PROPERTY_BSU' IN TYPEOF(
  type_spec) THEN
    IF NOT (SIZEOF(type_spec.definition) = 0) THEN
      x := type_spec.definition[1]\property_det.domain;
      res := TRUE;
    END_IF;
  ELSE
    IF NOT (SIZEOF(type_spec.definition) = 0) THEN
      x := type_spec.definition[1]\data_type_element.type_definition;
      res := TRUE;
    END_IF;
  END_IF;
  IF NOT res THEN
    RETURN ([]);
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NAMED_TYPE' IN TYPEOF(x) THEN
    IF NOT (SIZEOF(x\named_type.referred_type.definition) = 0) THEN
      RETURN (data_type_typeof(x\named_type.referred_type));
    ELSE
      RETURN ([]);
    END_IF;
  ELSE
    RETURN (TYPEOF(x));
  END_IF;
END_FUNCTION;
 
FUNCTION definition_available_implies(bsu : basic_semantic_unit; expression : 
  LOGICAL) : LOGICAL;
  RETURN (NOT (SIZEOF(bsu.definition) = 1) OR expression);
END_FUNCTION;
 
FUNCTION derive_dimensional_exponents(x : unit) : dimensional_exponents;
LOCAL
  result : dimensional_exponents := dimensional_exponents(0.0, 0.0, 0.0, 0.0, 
  0.0, 0.0, 0.0);
END_LOCAL;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.DERIVED_UNIT' IN TYPEOF(x) THEN
    REPEAT i := LOINDEX(x.elements) TO HIINDEX(x.elements);
      result.length_exponent := result.length_exponent + x.elements[i].exponent
       * x.elements[i].unit.dimensions.length_exponent;
      result.mass_exponent := result.mass_exponent + x.elements[i].exponent * x
      .elements[i].unit.dimensions.mass_exponent;
      result.time_exponent := result.time_exponent + x.elements[i].exponent * x
      .elements[i].unit.dimensions.time_exponent;
      result.electric_current_exponent := result.electric_current_exponent + x.
      elements[i].exponent * x.elements[i].unit.dimensions.
      electric_current_exponent;
      result.thermodynamic_temperature_exponent := result.
      thermodynamic_temperature_exponent + x.elements[i].exponent * x.elements[
      i].unit.dimensions.thermodynamic_temperature_exponent;
      result.amount_of_substance_exponent := result.
      amount_of_substance_exponent + x.elements[i].exponent * x.elements[i].
      unit.dimensions.amount_of_substance_exponent;
      result.luminous_intensity_exponent := result.luminous_intensity_exponent
       + x.elements[i].exponent * x.elements[i].unit.dimensions.
      luminous_intensity_exponent;
    END_REPEAT;
  ELSE
    result := x.dimensions;
  END_IF;
  RETURN (result);
END_FUNCTION;
 
FUNCTION dimension_of(item : geometric_representation_item) : dimension_count;
LOCAL
  x : SET OF representation;
  y : representation_context;
  dim : dimension_count;
END_LOCAL;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CARTESIAN_POINT' IN TYPEOF(item)
   THEN
    dim := SIZEOF(item\cartesian_point.coordinates);
    RETURN (dim);
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.DIRECTION' IN TYPEOF(item) THEN
    dim := SIZEOF(item\direction.direction_ratios);
    RETURN (dim);
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.VECTOR' IN TYPEOF(item) THEN
    dim := SIZEOF(item\vector.orientation\direction.direction_ratios);
    RETURN (dim);
  END_IF;
  x := using_representations(item);
  y := x[1].context_of_items;
  dim := y\geometric_representation_context.coordinate_space_dimension;
  RETURN (dim);
END_FUNCTION;
 
FUNCTION dimensions_for_si_unit(n : si_unit_name) : dimensional_exponents;
  CASE n OF 
      metre : RETURN (dimensional_exponents(1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)
      );
      gram : RETURN (dimensional_exponents(0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0));
      second : RETURN (dimensional_exponents(0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0)
      );
      ampere : RETURN (dimensional_exponents(0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0)
      );
      kelvin : RETURN (dimensional_exponents(0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0)
      );
      mole : RETURN (dimensional_exponents(0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0));
      candela : RETURN (dimensional_exponents(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0
      ));
      radian : RETURN (dimensional_exponents(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)
      );
      steradian : RETURN (dimensional_exponents(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
      0.0));
      hertz : RETURN (dimensional_exponents(0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0)
      );
      newton : RETURN (dimensional_exponents(1.0, 1.0, -2.0, 0.0, 0.0, 0.0, 0.0
      ));
      pascal : RETURN (dimensional_exponents(-1.0, 1.0, -2.0, 0.0, 0.0, 0.0, 
      0.0));
      joule : RETURN (dimensional_exponents(2.0, 1.0, -2.0, 0.0, 0.0, 0.0, 0.0)
      );
      watt : RETURN (dimensional_exponents(2.0, 1.0, -3.0, 0.0, 0.0, 0.0, 0.0)
      );
      coulomb : RETURN (dimensional_exponents(0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0
      ));
      volt : RETURN (dimensional_exponents(2.0, 1.0, -3.0, -1.0, 0.0, 0.0, 0.0)
      );
      farad : RETURN (dimensional_exponents(-2.0, -1.0, 4.0, 1.0, 0.0, 0.0, 0.0
      ));
      ohm : RETURN (dimensional_exponents(2.0, 1.0, -3.0, -2.0, 0.0, 0.0, 0.0)
      );
      siemens : RETURN (dimensional_exponents(-2.0, -1.0, 3.0, 2.0, 0.0, 0.0, 
      0.0));
      weber : RETURN (dimensional_exponents(2.0, 1.0, -2.0, -1.0, 0.0, 0.0, 0.0
      ));
      tesla : RETURN (dimensional_exponents(0.0, 1.0, -2.0, -1.0, 0.0, 0.0, 0.0
      ));
      henry : RETURN (dimensional_exponents(2.0, 1.0, -2.0, -2.0, 0.0, 0.0, 0.0
      ));
      degree_celsius : RETURN (dimensional_exponents(0.0, 0.0, 0.0, 0.0, 1.0, 
      0.0, 0.0));
      lumen : RETURN (dimensional_exponents(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0)
      );
      lux : RETURN (dimensional_exponents(-2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0));
      becquerel : RETURN (dimensional_exponents(0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 
      0.0));
      gray : RETURN (dimensional_exponents(2.0, 0.0, -2.0, 0.0, 0.0, 0.0, 0.0)
      );
      sievert : RETURN (dimensional_exponents(2.0, 0.0, -2.0, 0.0, 0.0, 0.0, 
      0.0));
      OTHERWISE  : RETURN (?);
  END_CASE;
END_FUNCTION;
 
FUNCTION dot_product(arg1 : direction; arg2 : direction) : REAL;
LOCAL
  scalar : REAL;
  vec1 : direction;
  vec2 : direction;
  ndim : INTEGER;
END_LOCAL;
  IF NOT EXISTS(arg1) OR NOT EXISTS(arg2) THEN
    scalar := ?;
  ELSE
    IF arg1.dim <> arg2.dim THEN
      scalar := ?;
    ELSE
      vec1 := normalise(arg1);
      vec2 := normalise(arg2);
      ndim := arg1.dim;
      scalar := 0.0;
      REPEAT i := 1 TO ndim;
        scalar := scalar + vec1.direction_ratios[i] * vec2.direction_ratios[i];
      END_REPEAT;
    END_IF;
  END_IF;
  RETURN (scalar);
END_FUNCTION;
 
FUNCTION exists_representation_for_instanciable_view(ext : 
  explicit_functional_model_class_extension) : LOGICAL;
LOCAL
  cpt : INTEGER := 0;
  prop_val : property_value;
END_LOCAL;
  IF SIZEOF(ext.dictionary_definition.definition) = 1 THEN
    IF SIZEOF(ext.dictionary_definition.definition[1]\
    abstract_functional_model_class.created_view.definition) = 1 THEN
      IF NOT ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.' + 
      'NON_INSTANTIABLE_FUNCTIONAL_VIEW_CLASS' IN TYPEOF(ext.
      dictionary_definition.definition[1]\abstract_functional_model_class.
      created_view.definition[1])) THEN
        RETURN (EXISTS(ext.referenced_representation) AND ((
        'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.' + 'PROGRAM_REFERENCE' IN 
        data_type_type_name(ext.referenced_representation)) OR (
        'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.' + 
        'REPRESENTATION_REFERENCE' IN data_type_type_name(ext.
        referenced_representation)) OR (
        'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.' + 'REPRESENTATION' IN 
        data_type_type_name(ext.referenced_representation))));
      ELSE
        RETURN (NOT EXISTS(ext.referenced_representation));
      END_IF;
    ELSE
      RETURN (UNKNOWN);
    END_IF;
  ELSE
    RETURN (UNKNOWN);
  END_IF;
END_FUNCTION;
 
FUNCTION first_proj_axis(z_axis : direction; arg : direction) : direction;
LOCAL
  x_axis : direction;
  v : direction;
  z : direction;
  x_vec : vector;
END_LOCAL;
  IF NOT EXISTS(z_axis) THEN
    RETURN (?);
  ELSE
    z := normalise(z_axis);
    IF NOT EXISTS(arg) THEN
      IF (z.direction_ratios <> [1.0, 0.0, 0.0]) AND (z.direction_ratios <> [-
      1.0, 0.0, 0.0]) THEN
        v := dummy_gri||direction([1.0, 0.0, 0.0]);
      ELSE
        v := dummy_gri||direction([0.0, 1.0, 0.0]);
      END_IF;
    ELSE
      IF arg.dim <> 3 THEN
        RETURN (?);
      END_IF;
      IF cross_product(arg, z).magnitude = 0.0 THEN
        RETURN (?);
      ELSE
        v := normalise(arg);
      END_IF;
    END_IF;
    x_vec := scalar_times_vector(dot_product(v, z), z);
    x_axis := vector_difference(v, x_vec).orientation;
    x_axis := normalise(x_axis);
  END_IF;
  RETURN (x_axis);
END_FUNCTION;
 
FUNCTION functional_view_v_c_v(cl : class_bsu) : LIST OF property_bsu;
  IF NOT EXISTS(cl) THEN
    RETURN ([]);
  END_IF;
  IF NOT all_class_descriptions_reachable(cl) THEN
    RETURN ([]);
  END_IF;
  IF NOT ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.FUNCTIONAL_VIEW_CLASS' IN 
  TYPEOF(cl.definition[1])) THEN
    RETURN ([]);
  END_IF;
  RETURN (retrieve_functional_view_v_c_v(cl, []));
END_FUNCTION;
 
FUNCTION get_description_value(obj : description_attribute_select) : text;
LOCAL
  description_bag :  BAG OF description_attribute := USEDIN(obj, 
  'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.DESCRIPTION_ATTRIBUTE.DESCRIBED_ITEM'
  );
END_LOCAL;
  IF SIZEOF(description_bag) = 1 THEN
    RETURN (description_bag[1].attribute_value);
  ELSE
    RETURN (?);
  END_IF;
END_FUNCTION;
 
FUNCTION get_id_value(obj : id_attribute_select) : identifier;
LOCAL
  id_bag :  BAG OF id_attribute := USEDIN(obj, 
  'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ID_ATTRIBUTE.IDENTIFIED_ITEM');
END_LOCAL;
  IF SIZEOF(id_bag) = 1 THEN
    RETURN (id_bag[1].attribute_value);
  ELSE
    RETURN (?);
  END_IF;
END_FUNCTION;
 
FUNCTION get_name_value(obj : name_attribute_select) : label;
LOCAL
  name_bag :  BAG OF name_attribute := USEDIN(obj, 
  'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NAME_ATTRIBUTE.NAMED_ITEM');
END_LOCAL;
  IF SIZEOF(name_bag) = 1 THEN
    RETURN (name_bag[1].attribute_value);
  ELSE
    RETURN (?);
  END_IF;
END_FUNCTION;
 
FUNCTION is_condition_det(prop : property_value) : LOGICAL;
  IF SIZEOF(prop.prop_def.definition) > 0 THEN
    RETURN ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CONDITION_DET' IN TYPEOF(
    prop.prop_def.definition[1]));
  ELSE
    RETURN (UNKNOWN);
  END_IF;
END_FUNCTION;
 
FUNCTION is_correct_liim_24_1_application_value(liim_id : 
  library_iim_identification) : BOOLEAN;
  IF EXISTS(liim_id\data_exchange_specification_identification.application) AND
   ((liim_id\data_exchange_specification_identification.application[1] = '1') 
  OR (liim_id\data_exchange_specification_identification.application[1] = '2') 
  OR (liim_id\data_exchange_specification_identification.application[1] = '3') 
  OR (liim_id\data_exchange_specification_identification.application[1] = '4') 
  OR (liim_id\data_exchange_specification_identification.application[1] = '5') 
  OR (liim_id\data_exchange_specification_identification.application[1] = '6'))
   AND ((liim_id\data_exchange_specification_identification.application LIKE 
  '#') OR (liim_id\data_exchange_specification_identification.application LIKE 
  '#E')) THEN
    RETURN (TRUE);
  ELSE
    RETURN (FALSE);
  END_IF;
END_FUNCTION;
 
FUNCTION is_correct_liim_24_2_application_value(liim_id : 
  library_iim_identification) : BOOLEAN;
  IF EXISTS(liim_id\data_exchange_specification_identification.application) AND
   ((liim_id\data_exchange_specification_identification.application[1] = '1') 
  OR (liim_id\data_exchange_specification_identification.application[1] = '2') 
  OR (liim_id\data_exchange_specification_identification.application[1] = '3') 
  OR (liim_id\data_exchange_specification_identification.application[1] = '4') 
  OR (liim_id\data_exchange_specification_identification.application[1] = '5') 
  OR (liim_id\data_exchange_specification_identification.application[1] = '6'))
   AND ((liim_id\data_exchange_specification_identification.application LIKE 
  '#') OR (liim_id\data_exchange_specification_identification.application LIKE 
  '#E')) THEN
    RETURN (TRUE);
  ELSE
    RETURN (FALSE);
  END_IF;
END_FUNCTION;
 
FUNCTION is_correct_liim_24_3_application_value(liim_id : 
  library_iim_identification) : BOOLEAN;
  IF EXISTS(liim_id\data_exchange_specification_identification.application) AND
   ((liim_id\data_exchange_specification_identification.application[1] = '1') 
  OR (liim_id\data_exchange_specification_identification.application[1] = '2'))
   AND ((liim_id\data_exchange_specification_identification.application LIKE 
  '#') OR (liim_id\data_exchange_specification_identification.application LIKE 
  '#E')) THEN
    RETURN (TRUE);
  ELSE
    RETURN (FALSE);
  END_IF;
END_FUNCTION;
 
FUNCTION is_correct_liim_25_application_value(liim_id : 
  library_iim_identification) : BOOLEAN;
  IF EXISTS(liim_id\data_exchange_specification_identification.application) AND
   ((liim_id\data_exchange_specification_identification.application[1] = '2') 
  OR (liim_id\data_exchange_specification_identification.application[1] = '3') 
  OR (liim_id\data_exchange_specification_identification.application[1] = '4') 
  OR (liim_id\data_exchange_specification_identification.application[1] = '5') 
  OR (liim_id\data_exchange_specification_identification.application[1] = '6') 
  OR (liim_id\data_exchange_specification_identification.application[1] = '7'))
   AND (liim_id\data_exchange_specification_identification.application LIKE '#'
  ) OR (liim_id\data_exchange_specification_identification.application[1] = '1'
  ) AND ((liim_id\data_exchange_specification_identification.application[2] = 
  '0') OR (liim_id\data_exchange_specification_identification.application[2] = 
  '1')) THEN
    RETURN (TRUE);
  ELSE
    RETURN (FALSE);
  END_IF;
END_FUNCTION;
 
FUNCTION is_dependent_p_det(prop : property_bsu) : LOGICAL;
  IF SIZEOF(prop.definition) > 0 THEN
    RETURN ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.DEPENDENT_P_DET' IN 
    TYPEOF(prop.definition[1]));
  ELSE
    RETURN (UNKNOWN);
  END_IF;
END_FUNCTION;
 
FUNCTION is_extended_liim_24_1_application_value(liim_id : 
  library_iim_identification) : BOOLEAN;
  IF EXISTS(liim_id\data_exchange_specification_identification.application) AND
   (liim_id\data_exchange_specification_identification.application LIKE '#E')
   THEN
    RETURN (TRUE);
  ELSE
    RETURN (FALSE);
  END_IF;
END_FUNCTION;
 
FUNCTION is_extended_liim_24_2_application_value(liim_id : 
  library_iim_identification) : BOOLEAN;
  IF EXISTS(liim_id\data_exchange_specification_identification.application) AND
   (liim_id\data_exchange_specification_identification.application LIKE '#E')
   THEN
    RETURN (TRUE);
  ELSE
    RETURN (FALSE);
  END_IF;
END_FUNCTION;
 
FUNCTION is_extended_liim_24_3_application_value(liim_id : 
  library_iim_identification) : BOOLEAN;
  IF EXISTS(liim_id\data_exchange_specification_identification.application) AND
   (liim_id\data_exchange_specification_identification.application LIKE '#E')
   THEN
    RETURN (TRUE);
  ELSE
    RETURN (FALSE);
  END_IF;
END_FUNCTION;
 
FUNCTION is_provided_once_property_value(a_model : dic_class_instance; prop : 
  property_or_data_type_bsu) : BOOLEAN;
LOCAL
  cpt : INTEGER := 0;
END_LOCAL;
  IF NOT ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.' + 'PROPERTY_BSU' IN 
  TYPEOF(prop)) THEN
    RETURN (FALSE);
  END_IF;
  REPEAT i := 1 TO SIZEOF(a_model.properties);
    IF (prop = a_model.properties[i].prop_def) AND EXISTS(a_model.properties[i]
    .its_value) THEN
      cpt := cpt + 1;
    END_IF;
  END_REPEAT;
  RETURN (cpt = 1);
END_FUNCTION;
 
FUNCTION is_subclass(sub : class; super : class) : LOGICAL;
  IF NOT EXISTS(sub) OR NOT EXISTS(super) THEN
    RETURN (UNKNOWN);
  END_IF;
  IF sub = super THEN
    RETURN (TRUE);
  END_IF;
  IF NOT EXISTS(sub.its_superclass) THEN
    RETURN (FALSE);
  END_IF;
  IF SIZEOF(sub.its_superclass.definition) = 1 THEN
    IF sub.its_superclass.definition[1] = super THEN
      RETURN (TRUE);
    ELSE
      RETURN (is_subclass(sub.its_superclass.definition[1], super));
    END_IF;
  ELSE
    RETURN (UNKNOWN);
  END_IF;
END_FUNCTION;
 
FUNCTION item_caseof_closure(current : SET OF class_bsu) : SET OF class_bsu;
LOCAL
  caseof : SET OF class_bsu := next_item_caseof(superclass_closure(current));
END_LOCAL;
  compute_item_caseof_closure(caseof, caseof);
  RETURN (caseof);
END_FUNCTION;
 
FUNCTION item_in_context(item : representation_item; cntxt : 
  representation_context) : BOOLEAN;
LOCAL
  y :  BAG OF representation_item;
END_LOCAL;
  IF SIZEOF(USEDIN(item, 
  'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.REPRESENTATION.ITEMS') * cntxt.
  representations_in_context) > 0 THEN
    RETURN (TRUE);
  ELSE
    y := QUERY(z <* USEDIN(item, '') | 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.REPRESENTATION_ITEM' IN TYPEOF(z)
    );
    IF SIZEOF(y) > 0 THEN
      REPEAT i := 1 TO HIINDEX(y);
        IF item_in_context(y[i], cntxt) THEN
          RETURN (TRUE);
        END_IF;
      END_REPEAT;
    END_IF;
  END_IF;
  RETURN (FALSE);
END_FUNCTION;
 
FUNCTION leap_year(year : year_number) : BOOLEAN;
  IF (year MOD 4 = 0) AND (year MOD 100 <> 0) OR (year MOD 400 = 0) THEN
    RETURN (TRUE);
  ELSE
    RETURN (FALSE);
  END_IF;
END_FUNCTION;
 
FUNCTION list_to_set(l : LIST OF GENERIC : type_elem) : SET OF GENERIC : 
  type_elem;
LOCAL
  s : SET OF GENERIC : type_elem := [];
END_LOCAL;
  REPEAT i := 1 TO SIZEOF(l);
    s := s + l[i];
  END_REPEAT;
  RETURN (s);
END_FUNCTION;
 
FUNCTION makes_reference_outside(p :  AGGREGATE OF property_or_data_type_bsu; l
   :  LIST [1:?] OF class_bsu) : BOOLEAN;
LOCAL
  bool : BOOLEAN := FALSE;
  temp : SET [0:1] OF class_bsu := [];
END_LOCAL;
  REPEAT j := 1 TO SIZEOF(p);
    IF ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.PROPERTY_BSU' IN TYPEOF(p[j])
    ) AND NOT (p[j]\property_bsu.name_scope IN l) OR (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.DATA_TYPE_BSU' IN TYPEOF(p[j])) 
    AND NOT (p[j]\data_type_bsu.name_scope IN l) THEN
      bool := TRUE;
      RETURN (bool);
    END_IF;
    IF ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.PROPERTY_BSU' IN TYPEOF(p[j])
    ) AND NOT (SIZEOF(p[j]\basic_semantic_unit.definition) = 0) OR (
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.DATA_TYPE_BSU' IN TYPEOF(p[j])) 
    AND NOT (SIZEOF(p[j]\basic_semantic_unit.definition) = 0) THEN
      IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CLASS_INSTANCE_TYPE' IN 
      data_type_typeof(p[j]) THEN
        temp := data_type_class_of(p[j]);
        IF NOT (temp[1] IN l) THEN
          bool := bool OR TRUE;
        ELSE
          bool := bool OR FALSE;
        END_IF;
      END_IF;
      IF SIZEOF(data_type_named_type(p[j])) = 1 THEN
        bool := bool OR makes_reference_outside(data_type_named_type(p[j]), l);
      END_IF;
    END_IF;
  END_REPEAT;
  RETURN (bool);
END_FUNCTION;
 
FUNCTION makes_sub_list(cla :  LIST [1:?] OF class_bsu; i : INTEGER; j : 
  INTEGER) :  LIST [1:?] OF class_bsu;
LOCAL
  c : LIST OF class_bsu := [];
END_LOCAL;
  REPEAT k := i TO j;
    c := c + cla[k];
  END_REPEAT;
  RETURN (c);
END_FUNCTION;
 
FUNCTION model_caseof_closure(current : SET OF class_bsu) : SET OF class_bsu;
LOCAL
  caseof : SET OF class_bsu := next_model_caseof(superclass_closure(current));
END_LOCAL;
  compute_model_caseof_closure(caseof, caseof);
  RETURN (caseof);
END_FUNCTION;
 
FUNCTION next_item_caseof(current : SET OF class_bsu) : SET OF class_bsu;
LOCAL
  caseof : SET OF class_bsu := [];
END_LOCAL;
  IF EXISTS(current) THEN
    REPEAT i := 1 TO SIZEOF(current);
      IF SIZEOF(current[i].definition) = 0 THEN
        caseof := ?;
      ELSE
        IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.' + 'ITEM_CLASS_CASE_OF' 
        IN TYPEOF(current[i].definition[1]) THEN
          caseof := caseof + current[i].definition[1]\item_class_case_of.
          is_case_of;
        END_IF;
      END_IF;
    END_REPEAT;
    RETURN (caseof);
  ELSE
    RETURN (?);
  END_IF;
END_FUNCTION;
 
FUNCTION next_model_caseof(current : SET OF class_bsu) : SET OF class_bsu;
LOCAL
  caseof : SET OF class_bsu := [];
END_LOCAL;
  IF EXISTS(current) THEN
    REPEAT i := 1 TO SIZEOF(current);
      IF SIZEOF(current[i].definition) = 0 THEN
        caseof := ?;
      ELSE
        IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.' + 
        'ABSTRACT_FUNCTIONAL_MODEL_CLASS' IN TYPEOF(current[i].definition[1])
         THEN
          caseof := caseof + current[i].definition[1]\
          abstract_functional_model_class.case_of;
        END_IF;
      END_IF;
    END_REPEAT;
    RETURN (caseof);
  ELSE
    RETURN (?);
  END_IF;
END_FUNCTION;
 
FUNCTION no_more_than_two_nested_levels(typ : aggregate_type) : BOOLEAN;
  IF NOT ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.' + 
  'ENTITY_INSTANCE_TYPE_FOR_AGGREGATE' IN TYPEOF(typ.value_type)) THEN
    RETURN (TRUE);
  END_IF;
  IF NOT ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.' + 
  'ENTITY_INSTANCE_TYPE_FOR_AGGREGATE' IN TYPEOF(typ.value_type.type_structure.
  value_type)) THEN
    RETURN (TRUE);
  END_IF;
  RETURN (FALSE);
END_FUNCTION;
 
FUNCTION normalise(arg : vector_or_direction) : vector_or_direction;
LOCAL
  ndim : INTEGER;
  v : direction;
  result : vector_or_direction;
  vec : vector;
  mag : REAL;
END_LOCAL;
  IF NOT EXISTS(arg) THEN
    result := ?;
  ELSE
    ndim := arg.dim;
    IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.VECTOR' IN TYPEOF(arg) THEN
      v := dummy_gri||direction(arg.orientation.direction_ratios);
      IF arg.magnitude = 0.0 THEN
        RETURN (?);
      ELSE
        vec := dummy_gri||vector(v, 1.0);
      END_IF;
    ELSE
      v := dummy_gri||direction(arg.direction_ratios);
    END_IF;
    mag := 0.0;
    REPEAT i := 1 TO ndim;
      mag := mag + v.direction_ratios[i] * v.direction_ratios[i];
    END_REPEAT;
    IF mag > 0.0 THEN
      mag := (mag);
      REPEAT i := 1 TO ndim;
        v.direction_ratios[i] := v.direction_ratios[i]/mag;
      END_REPEAT;
      IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.VECTOR' IN TYPEOF(arg) THEN
        vec.orientation := v;
        result := vec;
      ELSE
        result := v;
      END_IF;
    ELSE
      RETURN (?);
    END_IF;
  END_IF;
  RETURN (result);
END_FUNCTION;
 
FUNCTION number_of_instance_representations(a_model : dic_class_instance) : 
  INTEGER;
LOCAL
  cpt : INTEGER := 0;
  prop_val : property_value;
END_LOCAL;
  REPEAT i := 1 TO SIZEOF(a_model.properties);
    prop_val := a_model.properties[i];
    IF data_type_typeof(prop_val.prop_def) = [] THEN
      RETURN (?);
    END_IF;
    IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.' + 'ENTITY_INSTANCE_TYPE' IN 
    data_type_typeof(prop_val.prop_def) THEN
      IF ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.' + 'PROGRAM_REFERENCE' IN 
      data_type_type_name(prop_val.prop_def)) OR (
      'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.' + 'REPRESENTATION_REFERENCE' 
      IN data_type_type_name(prop_val.prop_def)) OR (
      'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.' + 'REPRESENTATION' IN 
      data_type_type_name(prop_val.prop_def)) THEN
        cpt := cpt + 1;
      END_IF;
    END_IF;
  END_REPEAT;
  RETURN (cpt);
END_FUNCTION;
 
FUNCTION ordered_index_value(x : value_domain) : BOOLEAN;
  REPEAT i := LOBOUND(x.its_values) TO SIZEOF(x.its_values);
    IF x.its_values[i].value_code <> x.its_values[i - 1].value_code + 1 THEN
      RETURN (FALSE);
    END_IF;
  END_REPEAT;
  RETURN (TRUE);
END_FUNCTION;
 
FUNCTION orthogonal_complement(vec : direction) : direction;
LOCAL
  result : direction;
END_LOCAL;
  IF (vec.dim <> 2) OR NOT EXISTS(vec) THEN
    RETURN (?);
  ELSE
    result := dummy_gri||direction([-vec.direction_ratios[2], vec.
    direction_ratios[1]]);
    RETURN (result);
  END_IF;
END_FUNCTION;
 
FUNCTION prefix_ordered_class_list(classes :  LIST [2:?] OF class_bsu) : 
  BOOLEAN;
LOCAL
  related_token : class_related_bsu;
END_LOCAL;
  REPEAT i := 1 TO SIZEOF(classes);
    IF SIZEOF(classes[i].definition) = 1 THEN
      IF EXISTS(classes[i].definition[1]\class.its_superclass) AND NOT (classes
      [i].definition[1]\class.its_superclass IN makes_sub_list(classes, 1, i - 
      1)) THEN
        RETURN (FALSE);
      END_IF;
      IF  
      'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.A_PRIORI_SEMANTIC_RELATIONSHIP'
       IN TYPEOF(classes[i].definition[1]) THEN
        IF QUERY(x <* classes[i].definition[1]\a_priori_semantic_relationship.
        referenced_classes | NOT (x IN makes_sub_list(classes, 1, i - 1))) <> [
        ] THEN
          RETURN (FALSE);
        END_IF;
      END_IF;
      IF NOT (SIZEOF(classes[i].definition[1]\class.described_by) = 0) THEN
        IF makes_reference_outside(classes[i].definition[1]\class.described_by
        , makes_sub_list(classes, 1, i)) THEN
          RETURN (FALSE);
        END_IF;
      END_IF;
      IF  
      'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.A_PRIORI_SEMANTIC_RELATIONSHIP'
       IN TYPEOF(classes[i].definition[1]) THEN
        IF makes_reference_outside(classes[i].definition[1]\
        a_priori_semantic_relationship.referenced_properties, makes_sub_list(
        classes, 1, i - 1)) THEN
          RETURN (FALSE);
        END_IF;
      END_IF;
      IF NOT (SIZEOF(classes[i].definition[1]\class.defined_types) = 0) THEN
        IF makes_reference_outside(classes[i].definition[1]\class.defined_types
        , makes_sub_list(classes, 1, i)) THEN
          RETURN (FALSE);
        END_IF;
      END_IF;
      IF  
      'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.A_PRIORI_SEMANTIC_RELATIONSHIP'
       IN TYPEOF(classes[i].definition[1]) THEN
        IF makes_reference_outside(classes[i].definition[1]\
        a_priori_semantic_relationship.referenced_data_types, makes_sub_list(
        classes, 1, i - 1)) THEN
          RETURN (FALSE);
        END_IF;
      END_IF;
      IF NOT (SIZEOF(classes[i].definition[1]\class.associated_items) = 0) THEN
        REPEAT j := 1 TO SIZEOF(classes[i].definition[1]\class.associated_items
          );
          REPEAT k := 1 TO SIZEOF(classes[i].definition[1]\class.
            associated_items[j]\class_bsu_relationship.related_tokens);
            related_token := classes[i].definition[1]\class.associated_items[j]
            \class_bsu_relationship.related_tokens[k];
            IF ( 
            'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.TABLE_BSU' IN TYPEOF(
            related_token)) AND NOT (related_token\table_bsu.name_scope IN 
            makes_sub_list(classes, 1, i)) THEN
              RETURN (FALSE);
            END_IF;
            IF ( 
            'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.DOCUMENT_BSU' IN TYPEOF(
            related_token)) AND NOT (related_token\document_bsu.name_scope IN 
            makes_sub_list(classes, 1, i)) THEN
              RETURN (FALSE);
            END_IF;
          END_REPEAT;
        END_REPEAT;
      END_IF;
    END_IF;
  END_REPEAT;
  RETURN (TRUE);
END_FUNCTION;
 
FUNCTION presentation_unit_is_correct(prop : property_bsu; to_unit : unit) : 
  LOGICAL;
LOCAL
  prop_domain : data_type;
  prop_typeof : SET OF STRING := [];
END_LOCAL;
  IF SIZEOF(prop\basic_semantic_unit.definition) = 0 THEN
    RETURN (UNKNOWN);
  END_IF;
  prop_typeof := data_type_typeof(prop);
  IF prop_typeof = [] THEN
    RETURN (UNKNOWN);
  END_IF;
  prop_domain := data_type_of_bsu(prop)[1];
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.INT_MEASURE_TYPE' IN TYPEOF(
  prop_domain) THEN
    RETURN (derive_dimensional_exponents(to_unit) = 
    derive_dimensional_exponents(prop_domain\int_measure_type.unit.
    structured_representation));
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.REAL_MEASURE_TYPE' IN TYPEOF(
  prop_domain) THEN
    RETURN (derive_dimensional_exponents(to_unit) = 
    derive_dimensional_exponents(prop_domain\real_measure_type.unit.
    structured_representation));
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.LEVEL_TYPE' IN TYPEOF(
  prop_domain) THEN
    IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.INT_MEASURE_TYPE' IN TYPEOF(
    prop_domain\level_type.value_type) THEN
      RETURN (derive_dimensional_exponents(to_unit) = 
      derive_dimensional_exponents(prop_domain\level_type.value_type.unit.
      structured_representation));
    END_IF;
    IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.REAL_MEASURE_TYPE' IN TYPEOF(
    prop_domain\level_type.value_type) THEN
      RETURN (derive_dimensional_exponents(to_unit) = 
      derive_dimensional_exponents(prop_domain\level_type.value_type.unit.
      structured_representation));
    END_IF;
  END_IF;
  RETURN (FALSE);
END_FUNCTION;
 
FUNCTION referenced_protocols_exist_in_supported_protocols(lib : library; cl : 
  class_bsu) : LOGICAL;
LOCAL
  class_extension : SET [0:1] OF content_item := cl\basic_semantic_unit.
  referenced_by;
END_LOCAL;
  IF SIZEOF(class_extension) = 1 THEN
    RETURN (( 
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.MODEL_CLASS_EXTENSION' IN TYPEOF(
    class_extension)) AND (SIZEOF(QUERY(pr <* class_extension[1]\
    model_class_extension.referenced_external_items | NOT (pr\external_item.
    used_protocol IN lib\dictionary.base_protocols) AND NOT (pr\external_item.
    used_protocol IN lib.linked_interfaces))) <> 0));
  ELSE
    RETURN (FALSE);
  END_IF;
END_FUNCTION;
 
FUNCTION referenced_veps_exist_in_supported_veps(lib : library; cl : class_bsu)
   : LOGICAL;
LOCAL
  class_extension : SET [0:1] OF content_item := cl\basic_semantic_unit.
  referenced_by;
  class_extension_referenced_veps : SET OF 
  view_exchange_protocol_identification;
  dictionary_supported_veps : SET OF view_exchange_protocol_identification;
  tmp : LOGICAL;
END_LOCAL;
  IF SIZEOF(class_extension) = 1 THEN
    class_extension_referenced_veps := list_to_set(class_extension[1]\
    model_class_extension.referenced_view_exchange_protocol);
    dictionary_supported_veps := lib\dictionary.supported_vep;
    tmp := class_extension_referenced_veps <= dictionary_supported_veps;
    RETURN (('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.MODEL_CLASS_EXTENSION' 
    IN TYPEOF(class_extension[1])) AND NOT tmp);
  ELSE
    RETURN (FALSE);
  END_IF;
END_FUNCTION;
 
FUNCTION required_values_are_imported_properties(fm_class_ext : 
  explicit_functional_model_class_extension) : LOGICAL;
LOCAL
  res : LOGICAL := TRUE;
  prop : property_bsu;
END_LOCAL;
  IF SIZEOF(fm_class_ext.required_item_values) <> 0 THEN
    IF SIZEOF(fm_class_ext\content_item.dictionary_definition.definition) = 1
     THEN
      IF  
      'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.FM_CLASS_VIEW_OF' IN TYPEOF(
      fm_class_ext\content_item.dictionary_definition.definition[1]) THEN
        REPEAT i := 1 TO SIZEOF(fm_class_ext.required_item_values);
          prop := fm_class_ext.required_item_values[i];
          IF NOT (prop IN fm_class_ext\content_item.dictionary_definition.
          definition[1]\fm_class_view_of.imported_properties_from_item) THEN
            res := FALSE;
          END_IF;
        END_REPEAT;
      ELSE
        res := FALSE;
      END_IF;
    ELSE
      res := UNKNOWN;
    END_IF;
  END_IF;
  RETURN (res);
END_FUNCTION;
 
FUNCTION required_values_are_non_dependent_p_det(fm_class_ext : 
  explicit_functional_model_class_extension) : LOGICAL;
LOCAL
  res : LOGICAL := TRUE;
  prop : property_bsu;
END_LOCAL;
  IF SIZEOF(fm_class_ext.required_item_values) <> 0 THEN
    IF SIZEOF(fm_class_ext\content_item.dictionary_definition.definition) = 1
     THEN
      IF  
      'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.FM_CLASS_VIEW_OF' IN TYPEOF(
      fm_class_ext\content_item.dictionary_definition.definition[1]) THEN
        REPEAT i := 1 TO SIZEOF(fm_class_ext.required_item_values);
          prop := fm_class_ext.required_item_values[i];
          IF SIZEOF(prop.definition) = 1 THEN
            IF NOT ( 
            'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NON_DEPENDENT_P_DET' IN 
            TYPEOF(prop.definition[1])) THEN
              res := FALSE;
            END_IF;
          ELSE
            res := res AND UNKNOWN;
          END_IF;
        END_REPEAT;
      ELSE
        res := FALSE;
      END_IF;
    ELSE
      res := UNKNOWN;
    END_IF;
  END_IF;
  RETURN (res);
END_FUNCTION;
 
FUNCTION retrieve_functional_view_v_c_v(cl : class_bsu; pr : LIST OF 
  property_bsu) : LIST OF property_bsu;
LOCAL
  prop : LIST OF property_bsu := pr;
END_LOCAL;
  IF SIZEOF(cl.definition) = 0 THEN
    RETURN ([]);
  END_IF;
  IF NOT ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.FUNCTIONAL_VIEW_CLASS' IN 
  TYPEOF(cl.definition[1])) THEN
    RETURN ([]);
  END_IF;
  IF SIZEOF(cl.definition) = 1 THEN
    prop := prop + cl.definition[1]\functional_view_class.
    view_control_variables;
  END_IF;
  IF NOT EXISTS(cl.definition[1]\class.its_superclass) THEN
    RETURN (prop);
  ELSE
    RETURN (retrieve_functional_view_v_c_v(cl.definition[1]\class.
    its_superclass, prop));
  END_IF;
END_FUNCTION;
 
FUNCTION right_values_for_level_spec(levels :  LIST [1:4] OF level; val : 
  level_spec_value) : BOOLEAN;
LOCAL
  c_place : BOOLEAN;
  lev : SET [1:4] OF level;
END_LOCAL;
  c_place := TRUE;
  lev := list_to_set(levels);
  IF EXISTS(val.values[1]) THEN
    IF level.min IN lev THEN
      lev := lev - [level.min];
    ELSE
      c_place := FALSE;
    END_IF;
  END_IF;
  IF EXISTS(val.values[2]) THEN
    IF level.nom IN lev THEN
      lev := lev - [level.nom];
    ELSE
      c_place := FALSE;
    END_IF;
  END_IF;
  IF EXISTS(val.values[3]) THEN
    IF level.typ IN lev THEN
      lev := lev - [level.typ];
    ELSE
      c_place := FALSE;
    END_IF;
  END_IF;
  IF EXISTS(val.values[4]) THEN
    IF level.max IN lev THEN
      lev := lev - [level.max];
    ELSE
      c_place := FALSE;
    END_IF;
  END_IF;
  IF c_place THEN
    RETURN (TRUE);
  ELSE
    RETURN (FALSE);
  END_IF;
END_FUNCTION;
 
FUNCTION same_order_for_properties(first :  LIST [1:?] OF property_value; 
  current :  LIST [1:?] OF property_value) : BOOLEAN;
  IF SIZEOF(first) = SIZEOF(current) THEN
    ;
  ELSE
    RETURN (FALSE);
  END_IF;
  REPEAT i := 1 TO SIZEOF(first);
    IF NOT (first[i].prop_def = current[i].prop_def) THEN
      RETURN (FALSE);
    END_IF;
    IF  
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CONTEXT_DEPENDENT_PROPERTY_VALUE'
     IN TYPEOF(first[i]) THEN
      IF NOT ( 
      'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CONTEXT_DEPENDENT_PROPERTY_VALUE'
       IN TYPEOF(current[i])) THEN
        RETURN (FALSE);
      END_IF;
      IF NOT same_order_for_properties(first[i]\
      context_dependent_property_value.the_context, current[i]\
      context_dependent_property_value.the_context) THEN
        RETURN (FALSE);
      END_IF;
    END_IF;
    IF  
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CONTEXT_DEPENDENT_PROPERTY_VALUE'
     IN TYPEOF(current[i]) THEN
      IF NOT ( 
      'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CONTEXT_DEPENDENT_PROPERTY_VALUE'
       IN TYPEOF(first[i])) THEN
        RETURN (FALSE);
      END_IF;
    END_IF;
    IF  
    'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.DIC_CLASS_INSTANCE' IN TYPEOF(
    first[i].its_value) THEN
      IF NOT same_order_for_properties(first[i].its_value.properties, current[i
      ].its_value.properties) THEN
        RETURN (FALSE);
      END_IF;
    END_IF;
  END_REPEAT;
  RETURN (TRUE);
END_FUNCTION;
 
FUNCTION same_string_values_translations_for_class_extension(class_ext : 
  explicit_model_class_extension) : LOGICAL;
LOCAL
  comp : SET OF translated_string_value := [];
  translated_property_values : LIST OF property_value := [];
END_LOCAL;
  REPEAT i := 1 TO SIZEOF(class_ext.POPULATION);
    translated_property_values := QUERY(prop_val <* class_ext.POPULATION[i].
    properties | 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.' + 
    'TRANSLATED_STRING_VALUE' IN TYPEOF(prop_val.its_value));
    IF SIZEOF(translated_property_values) <> 0 THEN
      comp := comp + translated_property_values[1].its_value;
    END_IF;
  END_REPEAT;
  RETURN (same_translations(comp));
END_FUNCTION;
 
FUNCTION same_translations(translated_string_values : SET OF 
  translated_string_value) : LOGICAL;
LOCAL
  comp : translated_string_value;
END_LOCAL;
  IF SIZEOF(translated_string_values) <> 0 THEN
    comp := translated_string_values[1];
    REPEAT i := 2 TO SIZEOF(translated_string_values);
      IF translated_string_values[i].languages <> comp.languages THEN
        RETURN (FALSE);
      END_IF;
    END_REPEAT;
    RETURN (TRUE);
  ELSE
    RETURN (UNKNOWN);
  END_IF;
END_FUNCTION;
 
FUNCTION scalar_times_vector(scalar : REAL; vec : vector_or_direction) : vector
  ;
LOCAL
  v : direction;
  mag : REAL;
  result : vector;
END_LOCAL;
  IF NOT EXISTS(scalar) OR NOT EXISTS(vec) THEN
    RETURN (?);
  ELSE
    IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.VECTOR' IN TYPEOF(vec) THEN
      v := dummy_gri||direction(vec.orientation.direction_ratios);
      mag := scalar * vec.magnitude;
    ELSE
      v := dummy_gri||direction(vec.direction_ratios);
      mag := scalar;
    END_IF;
    IF mag < 0.0 THEN
      REPEAT i := 1 TO SIZEOF(v.direction_ratios);
        v.direction_ratios[i] := -v.direction_ratios[i];
      END_REPEAT;
      mag := -mag;
    END_IF;
    result := dummy_gri||vector(normalise(v), mag);
  END_IF;
  RETURN (result);
END_FUNCTION;
 
FUNCTION superclass_closure(current : SET OF class_bsu) : SET OF class_bsu;
LOCAL
  superclasses : SET OF class_bsu := [];
END_LOCAL;
  compute_superclass_closure(current, superclasses);
  RETURN (superclasses);
END_FUNCTION;
 
FUNCTION superclass_of_item_is_item(cl : item_class) : LOGICAL;
  IF NOT EXISTS(cl\class.its_superclass) THEN
    RETURN (TRUE);
  END_IF;
  IF SIZEOF(cl\class.its_superclass.definition) = 0 THEN
    RETURN (UNKNOWN);
  END_IF;
  RETURN ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ITEM_CLASS' IN TYPEOF(cl\
  class.its_superclass.definition[1]));
END_FUNCTION;
 
FUNCTION supplier_associated_http_files(sup_bsu : supplier_bsu) : SET OF 
  http_file;
LOCAL
  sup : supplier_element;
  files : SET OF http_file := [];
END_LOCAL;
  IF SIZEOF(sup_bsu.definition) > 0 THEN
    sup := sup_bsu.definition[1];
  ELSE
    RETURN (files);
  END_IF;
  REPEAT i := 1 TO SIZEOF(sup.associated_items);
    REPEAT j := 1 TO SIZEOF(sup.associated_items[i].related_tokens);
      REPEAT k := 1 TO SIZEOF(sup.associated_items[i].related_tokens[j].
        referenced_by);
        IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.EXTERNAL_ITEM' IN TYPEOF(
        sup.associated_items[i].related_tokens[j].referenced_by[k]) THEN
          REPEAT l := 1 TO SIZEOF(sup.associated_items[i].related_tokens[j].
            referenced_by[k]\external_item.content.consists_of);
            REPEAT m := 1 TO SIZEOF(sup.associated_items[i].related_tokens[j].
              referenced_by[k]\external_item.content.consists_of[l].
              content_files);
              IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.HTTP_FILE' IN TYPEOF
              (sup.associated_items[i].related_tokens[j].referenced_by[k]\
              external_item.content.consists_of[l].content_files[m]) THEN
                files := files + sup.associated_items[i].related_tokens[j].
                referenced_by[k]\external_item.content.consists_of[l].
                content_files[m];
              END_IF;
            END_REPEAT;
          END_REPEAT;
        END_IF;
      END_REPEAT;
    END_REPEAT;
  END_REPEAT;
  RETURN (files);
END_FUNCTION;
 
FUNCTION using_items(item : founded_item_select; checked_items : SET OF 
  founded_item_select) : SET OF founded_item_select;
LOCAL
  new_check_items : SET OF founded_item_select;
  result_items : SET OF founded_item_select;
  next_items : SET OF founded_item_select;
END_LOCAL;
  result_items := [];
  new_check_items := checked_items + item;
  next_items := QUERY(z <* bag_to_set(USEDIN(item, '')) | (
  'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.REPRESENTATION_ITEM' IN TYPEOF(z)) 
  OR ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.FOUNDED_ITEM' IN TYPEOF(z)));
  IF SIZEOF(next_items) > 0 THEN
    REPEAT i := 1 TO HIINDEX(next_items);
      IF NOT (next_items[i] IN new_check_items) THEN
        result_items := result_items + next_items[i] + using_items(next_items[i
        ], new_check_items);
      END_IF;
    END_REPEAT;
  END_IF;
  RETURN (result_items);
END_FUNCTION;
 
FUNCTION using_representations(item : founded_item_select) : SET OF 
  representation;
LOCAL
  results : SET OF representation;
  result_bag :  BAG OF representation;
  intermediate_items : SET OF founded_item_select;
END_LOCAL;
  results := [];
  result_bag := USEDIN(item, 
  'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.REPRESENTATION.ITEMS');
  IF SIZEOF(result_bag) > 0 THEN
    REPEAT i := 1 TO HIINDEX(result_bag);
      results := results + result_bag[i];
    END_REPEAT;
  END_IF;
  intermediate_items := using_items(item, []);
  IF SIZEOF(intermediate_items) > 0 THEN
    REPEAT i := 1 TO HIINDEX(intermediate_items);
      result_bag := USEDIN(intermediate_items[i], 
      'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.REPRESENTATION.ITEMS');
      IF SIZEOF(result_bag) > 0 THEN
        REPEAT j := 1 TO HIINDEX(result_bag);
          results := results + result_bag[j];
        END_REPEAT;
      END_IF;
    END_REPEAT;
  END_IF;
  RETURN (results);
END_FUNCTION;
 
FUNCTION valid_calendar_date(date : calendar_date) : LOGICAL;
  CASE date.month_component OF 
      1 : RETURN ({1 <= date.day_component <= 31});
      2 : IF leap_year(date.year_component) THEN
        RETURN ({1 <= date.day_component <= 29});
      ELSE
        RETURN ({1 <= date.day_component <= 28});
      END_IF;
      3 : RETURN ({1 <= date.day_component <= 31});
      4 : RETURN ({1 <= date.day_component <= 30});
      5 : RETURN ({1 <= date.day_component <= 31});
      6 : RETURN ({1 <= date.day_component <= 30});
      7 : RETURN ({1 <= date.day_component <= 31});
      8 : RETURN ({1 <= date.day_component <= 31});
      9 : RETURN ({1 <= date.day_component <= 30});
      10 : RETURN ({1 <= date.day_component <= 31});
      11 : RETURN ({1 <= date.day_component <= 30});
      12 : RETURN ({1 <= date.day_component <= 31});
  END_CASE;
  RETURN (FALSE);
END_FUNCTION;
 
FUNCTION valid_time(time : local_time) : BOOLEAN;
  IF EXISTS(time.second_component) THEN
    RETURN (EXISTS(time.minute_component));
  ELSE
    RETURN (TRUE);
  END_IF;
END_FUNCTION;
 
FUNCTION valid_units(m : measure_with_unit) : BOOLEAN;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.LENGTH_MEASURE' IN TYPEOF(m.
  value_component) THEN
    IF derive_dimensional_exponents(m.unit_component) <> dimensional_exponents(
    1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0) THEN
      RETURN (FALSE);
    END_IF;
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.MASS_MEASURE' IN TYPEOF(m.
  value_component) THEN
    IF derive_dimensional_exponents(m.unit_component) <> dimensional_exponents(
    0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0) THEN
      RETURN (FALSE);
    END_IF;
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.TIME_MEASURE' IN TYPEOF(m.
  value_component) THEN
    IF derive_dimensional_exponents(m.unit_component) <> dimensional_exponents(
    0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0) THEN
      RETURN (FALSE);
    END_IF;
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ELECTRIC_CURRENT_MEASURE' IN 
  TYPEOF(m.value_component) THEN
    IF derive_dimensional_exponents(m.unit_component) <> dimensional_exponents(
    0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0) THEN
      RETURN (FALSE);
    END_IF;
  END_IF;
  IF 
  'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.THERMODYNAMIC_TEMPERATURE_MEASURE' 
  IN TYPEOF(m.value_component) THEN
    IF derive_dimensional_exponents(m.unit_component) <> dimensional_exponents(
    0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0) THEN
      RETURN (FALSE);
    END_IF;
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CELSIUS_TEMPERATURE_MEASURE' IN 
  TYPEOF(m.value_component) THEN
    IF derive_dimensional_exponents(m.unit_component) <> dimensional_exponents(
    0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0) THEN
      RETURN (FALSE);
    END_IF;
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.AMOUNT_OF_SUBSTANCE_MEASURE' IN 
  TYPEOF(m.value_component) THEN
    IF derive_dimensional_exponents(m.unit_component) <> dimensional_exponents(
    0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0) THEN
      RETURN (FALSE);
    END_IF;
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.LUMINOUS_INTENSITY_MEASURE' IN 
  TYPEOF(m.value_component) THEN
    IF derive_dimensional_exponents(m.unit_component) <> dimensional_exponents(
    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0) THEN
      RETURN (FALSE);
    END_IF;
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.PLANE_ANGLE_MEASURE' IN TYPEOF(m
  .value_component) THEN
    IF derive_dimensional_exponents(m.unit_component) <> dimensional_exponents(
    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0) THEN
      RETURN (FALSE);
    END_IF;
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.SOLID_ANGLE_MEASURE' IN TYPEOF(m
  .value_component) THEN
    IF derive_dimensional_exponents(m.unit_component) <> dimensional_exponents(
    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0) THEN
      RETURN (FALSE);
    END_IF;
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.AREA_MEASURE' IN TYPEOF(m.
  value_component) THEN
    IF derive_dimensional_exponents(m.unit_component) <> dimensional_exponents(
    2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0) THEN
      RETURN (FALSE);
    END_IF;
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.VOLUME_MEASURE' IN TYPEOF(m.
  value_component) THEN
    IF derive_dimensional_exponents(m.unit_component) <> dimensional_exponents(
    3.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0) THEN
      RETURN (FALSE);
    END_IF;
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.RATIO_MEASURE' IN TYPEOF(m.
  value_component) THEN
    IF derive_dimensional_exponents(m.unit_component) <> dimensional_exponents(
    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0) THEN
      RETURN (FALSE);
    END_IF;
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.POSITIVE_LENGTH_MEASURE' IN
  TYPEOF(m.value_component) THEN
    IF derive_dimensional_exponents(m.unit_component) <> dimensional_exponents(
    1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0) THEN
      RETURN (FALSE);
    END_IF;
  END_IF;
  IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.POSITIVE_PLANE_ANGLE_MEASURE' IN
   TYPEOF(m.value_component) THEN
    IF derive_dimensional_exponents(m.unit_component) <> dimensional_exponents(
    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0) THEN
      RETURN (FALSE);
    END_IF;
  END_IF;
  RETURN (TRUE);
END_FUNCTION;
 
FUNCTION vector_difference(arg1 : vector_or_direction; arg2 : 
  vector_or_direction) : vector;
LOCAL
  result : vector;
  res : direction;
  vec1 : direction;
  vec2 : direction;
  mag : REAL;
  mag1 : REAL;
  mag2 : REAL;
  ndim : INTEGER;
END_LOCAL;
  IF NOT EXISTS(arg1) OR NOT EXISTS(arg2) OR (arg1.dim <> arg2.dim) THEN
    RETURN (?);
  ELSE
    IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.VECTOR' IN TYPEOF(arg1) THEN
      mag1 := arg1.magnitude;
      vec1 := arg1.orientation;
    ELSE
      mag1 := 1.0;
      vec1 := arg1;
    END_IF;
    IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.VECTOR' IN TYPEOF(arg2) THEN
      mag2 := arg2.magnitude;
      vec2 := arg2.orientation;
    ELSE
      mag2 := 1.0;
      vec2 := arg2;
    END_IF;
    vec1 := normalise(vec1);
    vec2 := normalise(vec2);
    ndim := SIZEOF(vec1.direction_ratios);
    mag := 0.0;
    res := dummy_gri||direction(vec1.direction_ratios);
    REPEAT i := 1 TO ndim;
      res.direction_ratios[i] := mag1 * vec1.direction_ratios[i] + mag2 * vec2.
      direction_ratios[i];
      mag := mag + res.direction_ratios[i] * res.direction_ratios[i];
    END_REPEAT;
    IF mag > 0.0 THEN
      result := dummy_gri||vector(res, (mag));
    ELSE
      result := dummy_gri||vector(vec1, 0.0);
    END_IF;
  END_IF;
  RETURN (result);
END_FUNCTION;
 
FUNCTION view_control_variables_attributes_belong_to_domain(vcv_range : 
  view_control_variable_range) : LOGICAL;
  IF data_type_typeof(vcv_range.parameter_type) <> [] THEN
    RETURN ((data_type_non_quantitative_int_type(vcv_range.parameter_type)[1].
    domain.its_values[1].value_code <= vcv_range.range_lobound) AND (vcv_range.
    range_hibound <= data_type_non_quantitative_int_type(vcv_range.
    parameter_type)[1].domain.its_values[HIINDEX(
    data_type_non_quantitative_int_type(vcv_range.parameter_type)[1].domain.
    its_values)].value_code));
  ELSE
    RETURN (UNKNOWN);
  END_IF;
END_FUNCTION;
 
FUNCTION visible_documents(cl : class_bsu; doc :  AGGREGATE OF document_bsu) : 
  LOGICAL;
  IF NOT EXISTS(cl) THEN
    RETURN (UNKNOWN);
  END_IF;
  REPEAT i := SIZEOF(doc) TO 1;
    IF doc[i].name_scope = cl THEN
      doc := doc - doc[i];
    END_IF;
  END_REPEAT;
  IF SIZEOF(doc) = 0 THEN
    RETURN (TRUE);
  END_IF;
  IF SIZEOF(cl.definition) = 0 THEN
    RETURN (UNKNOWN);
  END_IF;
  IF EXISTS(cl.definition[1]\class.its_superclass) THEN
    RETURN (visible_documents(cl.definition[1]\class.its_superclass, doc));
  ELSE
    RETURN (FALSE);
  END_IF;
END_FUNCTION;
 
PROCEDURE compute_item_caseof_closure(current : SET OF class_bsu; VAR visited
   : SET OF class_bsu);
LOCAL
  next : SET OF class_bsu;
END_LOCAL;
  IF EXISTS(current) THEN
    IF SIZEOF(current) <> 0 THEN
      next := superclass_closure(current);
      next := next_item_caseof(next) + next;
      REPEAT i := 1 TO SIZEOF(next);
        IF NOT (next[i] IN visited) THEN
          visited := visited + next[i];
          compute_item_caseof_closure([next[i]], visited);
        END_IF;
      END_REPEAT;
    END_IF;
  ELSE
    visited := ?;
  END_IF;
END_PROCEDURE;
 
PROCEDURE compute_model_caseof_closure(current : SET OF class_bsu; VAR visited
   : SET OF class_bsu);
LOCAL
  next : SET OF class_bsu;
END_LOCAL;
  IF EXISTS(current) THEN
    IF SIZEOF(current) <> 0 THEN
      next := superclass_closure(current);
      next := next_model_caseof(next) + next;
      REPEAT i := 1 TO SIZEOF(next);
        IF NOT (next[i] IN visited) THEN
          visited := visited + next[i];
          compute_model_caseof_closure([next[i]], visited);
        END_IF;
      END_REPEAT;
    END_IF;
  ELSE
    visited := ?;
  END_IF;
END_PROCEDURE;
 
PROCEDURE compute_superclass_closure(current : SET OF class_bsu; VAR visited : 
  SET OF class_bsu);
  IF EXISTS(current) THEN
    IF SIZEOF(current) <> 0 THEN
      REPEAT i := 1 TO SIZEOF(current);
        IF SIZEOF(current[i].definition) = 0 THEN
          visited := ?;
        ELSE
          IF EXISTS(current[i].definition[1]\class.its_superclass) AND NOT (
          current[i].definition[1]\class.its_superclass IN visited) THEN
            visited := visited + [current[i].definition[1]\class.its_superclass
            ];
            compute_superclass_closure([current[i].definition[1]\class.
            its_superclass], visited);
          END_IF;
        END_IF;
      END_REPEAT;
    END_IF;
  ELSE
    visited := ?;
  END_IF;
END_PROCEDURE;
(*   *)
FUNCTION compatible_aggregate_domain_and_aggregate_value(
	dom: property_or_data_type_BSU;
	val: aggregate_entity_instance_value) : LOGICAL;

LOCAL
	the_data_type: data_type;
END_LOCAL;

-- Check the avalability of the final type of a property or a
-- data type BSU.
IF data_type_typeof(dom) = []
THEN
	RETURN(UNKNOWN);
END_IF;

-- Check that the final type of the property or data type BSU
-- is an entity_instance_type whose type_name_attribute
-- references the aggregate_type entity

IF (NOT('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ENTITY_INSTANCE_TYPE' IN data_type_typeof(dom)))
THEN
	RETURN(FALSE);
END_IF;

IF (NOT('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA' +
	'.AGGREGATE_TYPE' IN data_type_type_name(dom)))
THEN
	RETURN(FALSE);
END_IF;

-- Compute the final type of the dom property or data_type_BSU

the_data_type := data_type_final_type(dom)[1];

RETURN(compatible_aggregate_type_and_value(the_data_type, val));

END_FUNCTION; -- compatible_aggregate_domain_and_value

FUNCTION data_type_final_type(
	type_spec: property_or_data_type_BSU): SET [0:1] OF data_type;

LOCAL
	res: BOOLEAN := FALSE;
	x: data_type;
END_LOCAL;

IF NOT EXISTS(type_spec)
THEN
	RETURN([]); -- type_spec is indeterminate
END_IF;

IF ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.PROPERTY_BSU' IN
	TYPEOF(type_spec))
THEN
	IF NOT(SIZEOF(type_spec.definition) = 0)
	THEN
		x := type_spec.definition[1]\property_DET.domain;
		res := TRUE;
	END_IF;
ELSE
	IF NOT(SIZEOF(type_spec.definition) = 0)
	THEN
		x := type_spec.definition[1]\data_type_element.
			type_definition;
		res := TRUE;
	END_IF;
END_IF;

IF NOT(res)
THEN
	RETURN([]);
END_IF;

IF ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NAMED_TYPE' IN TYPEOF(x))
THEN
	IF NOT(SIZEOF(x\named_type.referred_type.definition) = 0)
	THEN
		RETURN(data_type_final_type(x\named_type.referred_type));
	ELSE
		RETURN([]);
	END_IF;
ELSE
	RETURN([x]);
END_IF;

END_FUNCTION; -- data_type_final_type

FUNCTION compatible_aggregate_type_and_value(
	the_data_type: entity_instance_type_for_aggregate;
	val: aggregate_entity_instance_value): LOGICAL;

LOCAL
	elements: LIST OF null_or_primitive_value;
	type_of_elements: data_type;
	result: LOGICAL;
	tmp: LIST OF primitive_value := [];
END_LOCAL;

elements := val.the_value.values;

-- Compute type of elements contained in the aggregate
IF ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NAMED_TYPE' IN
	TYPEOF(the_data_type.type_structure.value_type))
THEN
	IF (data_type_typeof(the_data_type.type_structure.
		value_type\named_type.referred_type) = [])
	THEN

		RETURN(UNKNOWN);
	END_IF;
	type_of_elements := data_type_final_type(the_data_type.
		type_structure.value_type\named_type.referred_type)[1];
ELSE
	type_of_elements := the_data_type.type_structure.value_type;
END_IF;

-- check that a value aggregate is compatible with its type
-- aggregate declaration
IF ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.LIST_VALUE'
	IN TYPEOF (val.the_value))
	AND NOT
	('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA'+
	'.LIST_TYPE' IN TYPEOF(the_data_type.type_structure))
THEN
	RETURN(FALSE);
END_IF;

IF ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.BAG_VALUE' IN TYPEOF(
	val.the_value)) AND NOT
	('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.'+
	'BAG_TYPE' IN TYPEOF(the_data_type.type_structure))
THEN
	RETURN(FALSE);
END_IF;

IF ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.SET_VALUE' IN TYPEOF(
	val.the_value)) AND NOT
	('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.'+
	'SET_TYPE' IN TYPEOF(the_data_type.type_structure))
THEN
	RETURN(FALSE);
END_IF;

IF ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ARRAY_VALUE' IN TYPEOF(
	val.the_value)) AND NOT
	('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.'+
	'ARRAY_TYPE' IN TYPEOF(the_data_type.type_structure))
THEN
	RETURN(FALSE);
END_IF;

IF ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.SET_WITH_SUBSET_CONSTRAINT_VALUE'
		IN TYPEOF(val.the_value)) AND NOT
	('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.'+
			'SET_WITH_SUBSET_CONSTRAINT_TYPE SET_WITH_SUBSET_CONSTRAINT_TYPE'
		IN TYPEOF(the_data_type.type_structure))
THEN
	RETURN(FALSE);
END_IF;

-- check that that low and high bounds of the values are compatible
-- with the type declaration.
IF 	(('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.LIST_VALUE'
		IN TYPEOF (val.the_value))
	OR ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.BAG_VALUE'
		IN TYPEOF (val.the_value))
	OR ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.SET_VALUE'
		IN TYPEOF (val.the_value))
	OR ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.SET_WITH_SUBSET_CONSTRAINT_VALUE'
		IN TYPEOF (val.the_value)))
	AND (
	(EXISTS(the_data_type.type_structure.bound_1))
	AND NOT
	(SIZEOF(elements) >= the_data_type.type_structure.bound_1)
	)
THEN
	RETURN(FALSE);
END_IF;

IF (('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.LIST_VALUE' IN TYPEOF(
		val.the_value))
	OR ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.BAG_VALUE' IN TYPEOF(
		val.the_value))
	OR ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.SET_VALUE' IN TYPEOF(
		val.the_value))
	OR ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.SET_WITH_SUBSET_CONSTRAINT_VALUE'
		IN TYPEOF (val.the_value)))
	AND (
	(EXISTS(the_data_type.type_structure.bound_2))
	AND NOT
	(SIZEOF(elements) <= the_data_type.type_structure.bound_2))
THEN
	RETURN(FALSE);
END_IF;


-- For array data type and values, check that size of the storage
-- list of values is size compatible with the type declaration.
IF ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ARRAY_VALUE' IN TYPEOF(
	val.the_value))
THEN
	IF (NOT(val.the_value\array_value.bound_1 =
		the_data_type.type_structure.bound_1) OR
		NOT(val.the_value\array_value.bound_2 =
		the_data_type.type_structure.bound_2))
	THEN
		RETURN(FALSE);
	END_IF;
END_IF;

-- For set_with_subset_ constraint_type, check that the possible -constraints on subset size defined at the value level are consistent with those defined at the type level.
IF
('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.SET_WITH_SUBSET_CONSTRAINT_VALUE'
		IN TYPEOF (val.the_value))
	AND NOT
	((the_data_type.type_structure.cardinal_min
	<= val.the_value\set_with_subset_constraint_value.min)
	AND
	(val.the_value\set_with_subset_constraint_value.min
	<= val.the_value\set_with_subset_constraint_value.max)
	AND
	(val.the_value\set_with_subset_constraint_value.max
	<= the_data_type.type_structure.cardinal_max))
THEN
	RETURN(FALSE);
END_IF;

-- In case of a list or array of unique values, check that no
-- value is duplicated
IF ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.LIST_VALUE' IN TYPEOF(
	val.the_value)) OR
	('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ARRAY_VALUE'
	IN TYPEOF (val.the_value))
THEN
	IF (the_data_type.type_structure.uniqueness)
	THEN
		REPEAT i := 1 TO SIZEOF(val.the_value.values);
			IF NOT('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NULL_VALUE'
				IN TYPEOF(val.the_value.values[i]))
			THEN
				tmp := tmp + val.the_value.values[i];
			END_IF;
		END_REPEAT;

		IF NOT(VALUE_UNIQUE(tmp))
		THEN
			RETURN(FALSE);
		END_IF;
	END_IF;
END_IF;

-- For an array where optional values are not allowed, check that
-- no null_value is provided
IF ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ARRAY_VALUE'
	IN TYPEOF(val.the_value))
THEN
	IF NOT(the_data_type.type_structure.are_optional)
	THEN
		REPEAT i := 1 TO SIZEOF(val.the_value.values);
			IF ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NULL_VALUE'
				IN TYPEOF(val.the_value.values[i]))
			THEN
				RETURN(FALSE);
			END_IF;
		END_REPEAT;
	END_IF;
END_IF;

-- Check for value/type compatibility for all the elements contained
-- in the aggregate

result := TRUE;

REPEAT i := 1 TO SIZEOF(elements);
	IF NOT('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NULL_VALUE'
		 IN TYPEOF(elements[i]))
	THEN
		IF('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.'
			+ 'ENTITY_INSTANCE_TYPE_FOR_AGGREGATE'
			IN TYPEOF(type_of_elements))
		THEN
			IF ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.'+
				'AGGREGATE_ENTITY_INSTANCE_VALUE' IN
				TYPEOF(elements[i]))
			THEN
				result := result AND
					compatible_aggregate_type_and_value(
					type_of_elements, elements[i]);
			ELSE
				RETURN(FALSE);
			END_IF;
		ELSE
			result := result AND compatible_final_type_and_value(
				type_of_elements, elements[i]);
		END_IF;

		IF NOT(result)
		THEN
			RETURN(FALSE);
		END_IF;
	END_IF;
END_REPEAT;

RETURN(result);

END_FUNCTION; -- compatible_aggregate_type_and_value

FUNCTION compatible_final_type_and_value(
	typ: data_type; val: primitive_value): LOGICAL;

LOCAL
	set_string: SET OF STRING := [];
	set_integer: SET OF INTEGER := [];
	code_type: non_quantitative_code_type;
	int_type: non_quantitative_int_type;
END_LOCAL;

IF ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.INTEGER_VALUE' IN TYPEOF(val))
THEN
	IF (('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.' +
		'NON_QUANTITATIVE_INT_TYPE' IN TYPEOF(typ)))
	THEN
		set_integer := [];
		code_type := typ;

		REPEAT j := 1 TO SIZEOF(code_type.domain.its_values);
			set_integer := set_integer +
				code_type.domain.its_values[j].value_code;
		END_REPEAT;

		RETURN(val IN set_integer);
	ELSE
		RETURN(('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.INT_TYPE'
			IN TYPEOF(typ)) OR
			(('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NUMBER_TYPE'
			IN TYPEOF(typ))
			AND NOT('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.REAL_TYPE'
			IN TYPEOF(typ))));
	END_IF;
END_IF;

IF ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.REAL_VALUE' IN TYPEOF(val))
THEN
	RETURN(('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.REAL_TYPE'
		IN TYPEOF(typ)) OR
		(('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NUMBER_TYPE'
		IN TYPEOF(typ))
		AND NOT('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.INT_TYPE'
		IN TYPEOF(typ))));
END_IF;

IF ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NUMBER_VALUE' IN TYPEOF(val))
THEN
	RETURN('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.NUMBER_TYPE'
		IN TYPEOF(typ));
END_IF;

IF ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.BOOLEAN_VALUE' IN TYPEOF(val))
THEN
	RETURN('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.BOOLEAN_TYPE'
		IN TYPEOF(typ));
END_IF;

IF ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.TRANSLATABLE_STRING_VALUE' IN
TYPEOF(val))
THEN
	IF (('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA' +
		'.NON_QUANTITATIVE_CODE_TYPE') IN TYPEOF(typ))
	THEN
			set_string := [];
			code_type := typ;
			REPEAT j := 1 TO SIZEOF(code_type.domain.its_values);
				set_string := set_string +
					code_type.domain.its_values[j].value_code;
			END_REPEAT;

			RETURN(('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.STRING_VALUE'
				IN TYPEOF(val)) AND (val IN set_string));

	ELSE
		RETURN('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.STRING_TYPE'
			IN TYPEOF(typ));
	END_IF;
END_IF;

IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ENTITY_INSTANCE_VALUE'
	IN TYPEOF(val)
THEN
	IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA' +
		'.UNCONTROLLED_ENTITY_INSTANCE_VALUE' IN TYPEOF(val)
	THEN
		RETURN(UNKNOWN);
	END_IF;
	IF ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.ENTITY_INSTANCE_TYPE'
		IN TYPEOF(typ)) AND
		(typ\entity_instance_type.type_name <= TYPEOF(val))
	THEN
		RETURN(TRUE);
	ELSE
		RETURN(FALSE);
	END_IF;
END_IF;

IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.DIC_CLASS_INSTANCE'
	IN TYPEOF(val)
THEN
	IF ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.CLASS_INSTANCE_TYPE'
		IN TYPEOF(typ))
	THEN
		RETURN(compatible_class_and_class(typ\class_instance_type.
			domain,val\dic_class_instance.class_def));
	ELSE
		RETURN(FALSE);
	END_IF;
END_IF;

IF 'ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.LEVEL_SPEC_VALUE' IN TYPEOF(val)
THEN
	IF ('ISO13584_25_IEC61360_5_LIBRARY_IMPLICIT_SCHEMA.LEVEL_TYPE'
		IN TYPEOF(typ))
	THEN
		RETURN(compatible_level_type_and_instance(
			typ\level_type.levels,
			TYPEOF(typ\level_type.value_type), val));
	ELSE
		RETURN(FALSE);
	END_IF;
END_IF;

RETURN(FALSE);

END_FUNCTION; -- compatible_final_type_and_value
 
END_SCHEMA;

