//! Experimental manual schema definitions corresponding following EXPRESS Schema
//!
//! ```text
//! SCHEMA ap000;
//!   ENTITY a;
//!     x: REAL;
//!     y: REAL;
//!   END_ENTITY;
//!
//!   ENTITY b;
//!     z: REAL;
//!     w: a;
//!   END_ENTITY;
//!
//!   ENTITY c;
//!     p: a;
//!     q: b;
//!   END_ENTITY;
//! END_SCHEMA;
//! ```

use crate::{
    error::*,
    parser::value::{PlaceHolder, RValue},
};
use serde::Deserialize;
use std::collections::HashMap;

pub trait Holder {
    type Owned;
    type Table;
    fn into_owned(self, table: &Self::Table) -> Result<Self::Owned>;
}

#[derive(Debug, Default)]
pub struct Ap000 {
    a: HashMap<u64, A>,
    b: HashMap<u64, BHolder>,
    c: HashMap<u64, CHolder>,
}

#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct A {
    pub x: f64,
    pub y: f64,
}

#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct B {
    pub z: f64,
    pub a: A,
}

#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct BHolder {
    pub z: f64,
    pub a: PlaceHolder<A>,
}

impl Holder for BHolder {
    type Table = Ap000;
    type Owned = B;
    fn into_owned(self, tables: &Ap000) -> Result<B> {
        let BHolder { z, a } = self;
        Ok(B {
            z,
            a: a.into_owned(&tables.a)?,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct C {
    pub p: A,
    pub q: B,
}

#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct CHolder {
    pub p: PlaceHolder<A>,
    pub q: PlaceHolder<BHolder>,
}

impl CHolder {
    pub fn into_owned(self, tables: &Ap000) -> Result<C> {
        let CHolder { p, q } = self;
        Ok(C {
            p: p.into_owned(&tables.a)?,
            q: q.into_owned(&tables.b)?.into_owned(&tables)?,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::exchange;
    use nom::Finish;

    #[test]
    fn a_from_record() {
        let (_, record) = exchange::simple_record("A(1.0, 2.0)").finish().unwrap();
        let a = A::deserialize(&record).unwrap();
        dbg!(a);
    }

    // Example Tables generated by
    //
    // ```
    // DATA;
    //   #2 = A((1.0, 2.0))
    //   #4 = B((2.0, A((4.0, 5.0))));
    //   #5 = B((2.0, #2));
    // ENDSEC;
    // ```
    fn example_table() -> Ap000 {
        let mut tables = Ap000::default();
        tables.a.insert(2, A { x: 2.0, y: 3.0 });
        tables.b.insert(
            4,
            BHolder {
                z: 2.0,
                a: PlaceHolder::Owned(A { x: 4.0, y: 5.0 }),
            },
        );
        tables.b.insert(
            5,
            BHolder {
                z: 2.0,
                a: PlaceHolder::Ref(RValue::Entity(2)),
            },
        );
        tables
    }

    #[test]
    fn b_from_record() {
        let tables = example_table();

        let (_, record) = exchange::simple_record("B(1.0, A((2.0, 3.0)))")
            .finish()
            .unwrap();
        let b = BHolder::deserialize(&record).unwrap();
        dbg!(b.into_owned(&tables).unwrap());

        let (_, record) = exchange::simple_record("B(1.0, #2)").finish().unwrap();
        let b = BHolder::deserialize(&record).unwrap();
        dbg!(b.into_owned(&tables).unwrap());
    }

    #[test]
    fn c_from_record() {
        let tables = example_table();

        // All components are inline
        let (_, record) = exchange::simple_record("C(A((1.0, 2.0)), B((1.0, A((2.0, 3.0)))))")
            .finish()
            .unwrap();
        let c = CHolder::deserialize(&record).unwrap();
        dbg!(c.into_owned(&tables).unwrap());

        // Use B with inline A
        let (_, record) = exchange::simple_record("C(A((1.0, 2.0)), #4)")
            .finish()
            .unwrap();
        let c = CHolder::deserialize(&record).unwrap();
        dbg!(c.into_owned(&tables).unwrap());

        // Use B with ref A
        let (_, record) = exchange::simple_record("C(A((1.0, 2.0)), #5)")
            .finish()
            .unwrap();
        let c = CHolder::deserialize(&record).unwrap();
        dbg!(c.into_owned(&tables).unwrap());

        // Use both reference
        let (_, record) = exchange::simple_record("C(#2, #4)").finish().unwrap();
        let c = CHolder::deserialize(&record).unwrap();
        dbg!(c.into_owned(&tables).unwrap());

        // Use both reference with DAG
        let (_, record) = exchange::simple_record("C(#2, #5)").finish().unwrap();
        let c = CHolder::deserialize(&record).unwrap();
        dbg!(c.into_owned(&tables).unwrap());
    }
}
