//! Parser for exchange structure
//!
//! Table 3 — WSN of the exchange structure
//! ----------------------------------------
//!
//! ```text
//! EXCHANGE_FILE = "ISO-10303-21;" HEADER_SECTION
//!               [ ANCHOR_SECTION ]
//!               [ REFERENCE_SECTION ]
//!               { DATA_SECTION }
//!               "END-ISO-10303-21;"
//!               { SIGNATURE_SECTION } .
//!
//! HEADER_SECTION     = "HEADER;" HEADER_ENTITY HEADER_ENTITY HEADER_ENTITY [HEADER_ENTITY_LIST] "ENDSEC;" .
//! HEADER_ENTITY_LIST = HEADER_ENTITY { HEADER_ENTITY } .
//! HEADER_ENTITY      = KEYWORD  "(" [ PARAMETER_LIST ] ")" ";" .
//!
//! PARAMETER_LIST     = PARAMETER { "," PARAMETER } .
//! PARAMETER          = TYPED_PARAMETER  | UNTYPED_PARAMETER | OMITTED_PARAMETER  .
//! TYPED_PARAMETER    = KEYWORD "(" PARAMETER ")" .
//! UNTYPED_PARAMETER  = "$" | INTEGER | REAL | STRING | RHS_OCCURENCE_NAME | ENUMERATION | BINARY | LIST .
//! OMITTED_PARAMETER  = "*" .
//! LIST               = "(" [ PARAMETER { "," PARAMETER } ] ")" .
//!
//! ANCHOR_SECTION     = "ANCHOR;" ANCHOR_LIST "ENDSEC;" .
//! ANCHOR_LIST        = { ANCHOR } .
//! ANCHOR             = ANCHOR_NAME "=" ANCHOR_ITEM { ANCHOR_TAG } ";" .
//! ANCHOR_ITEM        = "$" | INTEGER | REAL | STRING | ENUMERATION | BINARY | RHS_OCCURRENCE_NAME | RESOURCE | ANCHOR_ITEM_LIST .
//! ANCHOR_ITEM_LIST   = "(" [ ANCHOR_ITEM { "," ANCHOR_ITEM } ] ")" .
//! ANCHOR_TAG         = "{" TAG_NAME ":" ANCHOR_ITEM "}" .
//!
//! REFERENCE_SECTION  = "REFERENCE;" REFERENCE_LIST "ENDSEC;" .
//! REFERENCE_LIST     = { REFERENCE } .
//! REFERENCE          = LHS_OCCURRENCE_NAME "=" RESOURCE ";" .
//!
//! DATA_SECTION       = "DATA" [ "(" PARAMETER_LIST ")" ] ";" ENTITY_INSTANCE_LIST "ENDSEC;" .
//! ENTITY_INSTANCE_LIST = { ENTITY_INSTANCE } .
//! ENTITY_INSTANCE    = SIMPLE_ENTITY_INSTANCE | COMPLEX_ENTITY_INSTANCE .
//! SIMPLE_ENTITY_INSTANCE  = ENTITY_INSTANCE_NAME "=" SIMPLE_RECORD ";" .
//! COMPLEX_ENTITY_INSTANCE = ENTITY_INSTANCE_NAME "=" SUBSUPER_RECORD ";" .
//! SIMPLE_RECORD      = KEYWORD "(" [ PARAMETER_LIST ] ")" .
//! SUBSUPER_RECORD    = "(" SIMPLE_RECORD_LIST ")" .
//! SIMPLE_RECORD_LIST = SIMPLE_RECORD { SIMPLE_RECORD } .
//!
//! SIGNATURE_SECTION  = "SIGNATURE" SIGNATURE_CONTENT "ENDSEC;".
//! ```
//!

use super::{combinator::*, token::*};
