//! Parser for string control derectives
//!
//! Table 4 — String control directives
//! ------------------------------------
//!
//! ```text
//! CONTROL_DIRECTIVE = PAGE | ALPHABET | EXTENDED2 | EXTENDED4 | ARBITRARY .
//! PAGE = REVERSE_SOLIDUS "S" REVERSE_SOLIDUS LATIN_CODEPOINT .
//! ALPHABET = REVERSE_SOLIDUS "P" UPPER REVERSE_SOLIDUS .
//! EXTENDED2 = REVERSE_SOLIDUS "X2" REVERSE_SOLIDUS HEX_TWO { HEX_TWO } END_EXTENDED .
//! EXTENDED4 = REVERSE_SOLIDUS "X4" REVERSE_SOLIDUS HEX_FOUR { HEX_FOUR } END_EXTENDED .
//! END_EXTENDED = REVERSE_SOLIDUS "X0" REVERSE_SOLIDUS .
//! ARBITRARY = REVERSE_SOLIDUS "X" REVERSE_SOLIDUS HEX_ONE .
//! HEX_ONE = HEX HEX .
//! HEX_TWO = HEX_ONE HEX_ONE .
//! HEX_FOUR = HEX_TWO HEX_TWO .
//! ```
