(*
 $Id: 10303-1283-arm-resource_as_realized_characterized.exp,v 1.2 2006/08/07 07:44:46 wg12deputy Exp $
 ISO TC184/SC4/WG12 N3142 - ISO/TS 10303-1283 Resource as realized characterized - EXPRESS ARM
 Supersedes ISO TC184/SC4/WG12 N2423
*) 


SCHEMA Resource_as_realized_characterized_arm;

USE FROM Approval_arm;    -- ISO/TS 10303-1012

USE FROM Attribute_classification_arm;    -- ISO/TS 10303-1246

USE FROM Date_time_assignment_arm;    -- ISO/TS 10303-1014

USE FROM Identification_assignment_arm;    -- ISO/TS 10303-1021

USE FROM Justification_arm;    -- ISO/TS 10303-1263

USE FROM Multi_linguism_arm;    -- ISO/TS 10303-1105

USE FROM Person_organization_assignment_arm;    -- ISO/TS 10303-1013

USE FROM Process_property_assignment_arm;    -- ISO/TS 10303-1040

USE FROM Resource_as_realized_arm;    -- ISO/TS 10303-1269

USE FROM Resource_management_characterized_arm;    -- ISO/TS 10303-1282

USE FROM Resource_property_assignment_arm;    -- ISO/TS 10303-1273

USE FROM State_definition_arm;    -- ISO/TS 10303-1255

USE FROM State_observed_arm;    -- ISO/TS 10303-1256


TYPE resource_as_realized_approval_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON approval_item WITH 
   (Resource_as_realized);
END_TYPE; 

TYPE resource_as_realized_characterized_activity_definition = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON characterized_activity_definition WITH 
   (Resource_as_realized_assignment);
END_TYPE; 

TYPE resource_as_realized_characterized_resource_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON characterized_resource_select WITH 
   (Resource_as_realized);
END_TYPE; 

TYPE resource_as_realized_classified_attribute_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON classified_attribute_select WITH 
   (Resource_as_realized, 
    Resource_as_realized_relationship);
END_TYPE; 

TYPE resource_as_realized_date_or_date_time_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON date_or_date_time_item WITH 
   (Resource_as_realized);
END_TYPE; 

TYPE resource_as_realized_identification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON identification_item WITH 
   (Resource_as_realized);
END_TYPE; 

TYPE resource_as_realized_justification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON justification_item WITH 
   (Resource_as_realized);
END_TYPE; 

TYPE resource_as_realized_organization_or_person_in_organization_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON organization_or_person_in_organization_item WITH 
   (Resource_as_realized);
END_TYPE; 

TYPE resource_as_realized_state_definition_of_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON state_of_item WITH 
   (Resource_as_realized, 
    Resource_as_realized_assignment, 
    Resource_as_realized_relationship, 
    Resource_as_realized_resource_item);
END_TYPE; 

TYPE resource_as_realized_state_of_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON state_definition_of_item WITH 
   (Resource_as_realized, 
    Resource_as_realized_assignment, 
    Resource_as_realized_relationship, 
    Resource_as_realized_resource_item);
END_TYPE; 

TYPE resource_as_realized_string_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON string_select WITH 
   (Resource_as_realized, 
    Resource_as_realized_relationship);
END_TYPE; 

END_SCHEMA;  -- Resource_as_realized_characterized_arm
