(*
 $Id: 10303-1161-mim-Class_of_involvement_of_product_in_connection.exp,v 1.4 2006/08/04 12:11:54 wg12deputy Exp $
 ISO TC184/SC4/WG12 N2742 - ISO/TS 10303-1161 Class of involvement of product in connection - EXPRESS MIM
 Supersedes ISO TC184/SC4/WG12 N1972
*)

SCHEMA Class_of_involvement_of_product_in_connection_mim;

USE FROM Class_mim;    --  ISO/TS 10303-1070
USE FROM Class_of_connection_of_product_mim;    --  ISO/TS 10303-1159
USE FROM Class_of_product_mim;    --  ISO/TS 10303-1077
USE FROM Product_version_relationship_mim;    --  ISO/TS 10303-1020

ENTITY class_of_connection_of_product_with_involvements
  SUBTYPE OF (class_of_connection_of_product, class_of_product);
END_ENTITY;

ENTITY class_of_involvement_of_product_in_connection
  SUBTYPE OF (product_definition_formation_relationship, class);
  SELF\product_definition_formation_relationship.relating_product_definition_formation : class_of_connection_of_product_with_involvements;
  SELF\product_definition_formation_relationship.related_product_definition_formation : class_of_product;
END_ENTITY;

END_SCHEMA;
