(*
$Id: 10303-1259-mim-cdts_activity_as_realized.exp,v 1.1 2003/07/15 09:43:14 wg12deputy Exp $
ISO TC184/SC4/WG12 N1443 - ISO/CD-TS 10303-1259 Activity as realized - EXPRESS MIM
*) 


SCHEMA Activity_as_realized_mim; 

USE FROM action_schema;    -- ISO 10303-41

USE FROM Activity_mim;    -- ISO/TS 10303-1047


ENTITY action_actual
  SUBTYPE OF (action);
END_ENTITY;

ENTITY action_happening
  SUBTYPE OF (action_relationship);
END_ENTITY;

END_SCHEMA;  -- Activity_as_realized_mim


