(*   $Id: 10303-1510-arm-geometrically_bounded_wireframe.exp,v 1.4 2003/10/21 12:20:22 wg12deputy Exp $
  ISO/TC184/SC4 WG12N1278 - ISO/TS 10303-1510 Geometrically bounded wireframe - EXPRESS ARM
 *)

SCHEMA Geometrically_bounded_wireframe_arm;

USE FROM Elemental_geometric_shape_arm; 

ENTITY Geometrically_bounded_wireframe_shape_representation
SUBTYPE OF (Geometric_model);
END_ENTITY;

END_SCHEMA;
