[package]
name = "espr-playground"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.78"

[dependencies.web-sys]
version = "0.3"
features = [
    "Document",
    "Element",
    "Window",
]

[dependencies.espr]
path = "../espr"
