(* Document WG12 N550: EXPRESS listing of ISO 10303-104 IS *)

SCHEMA structural_response_definition_schema;

  REFERENCE FROM product_property_definition_schema
      (property_definition,
       shape_aspect);

ENTITY structural_response_property
  SUBTYPE OF (property_definition);
END_ENTITY;

ENTITY fea_model_definition
  SUBTYPE OF (shape_aspect);
END_ENTITY;

ENTITY node_definition
  SUBTYPE OF (shape_aspect);
END_ENTITY;

ENTITY element_definition
  SUBTYPE OF (shape_aspect);
END_ENTITY;

END_SCHEMA; -- structural_response_definition_schema

SCHEMA structural_response_representation_schema;

  REFERENCE FROM fea_scalar_vector_tensor_schema
      (scalar,
       symmetric_tensor2_2d,
       symmetric_tensor2_3d,
       symmetric_tensor4_2d,
       symmetric_tensor4_3d);

  REFERENCE FROM finite_element_analysis_control_and_result_schema
      (curve_element_variable,
       measure_or_unspecified_value,
       surface_2d_edge,
       surface_2d_face,
       surface_3d_edge,
       surface_3d_face,
       surface_element_variable,
       volume_2d_edge,
       volume_2d_face,
       volume_3d_edge,
       volume_3d_face,
       volume_variable);

  REFERENCE FROM geometric_model_schema 
      (solid_model);

  REFERENCE FROM geometry_schema 
      (axis2_placement_2d,
       axis2_placement_3d,
       cartesian_point,
       cross_product,
       curve,
       cylindrical_point,
       degenerate_pcurve,
       direction,
       geometric_representation_context,
       geometric_representation_item,
       normalise,
       point,
       point_on_curve,
       point_on_surface,
       point_replica,
       spherical_point,
       surface);

  REFERENCE FROM group_schema 
      (group,
       group_relationship);

  REFERENCE FROM material_property_definition_schema 
      (material_property);

  REFERENCE FROM material_property_representation_schema 
      (material_property_representation);

  REFERENCE FROM measure_schema 
      (context_dependent_measure,
       length_measure,
       parameter_value,
       plane_angle_measure,
       thermodynamic_temperature_measure);

  REFERENCE FROM product_property_representation_schema 
      (property_definition_representation);

  REFERENCE FROM representation_schema 
      (representation,
       representation_item,
       representation_relationship,
       using_representations);

  REFERENCE FROM structural_response_definition_schema
      (element_definition,
       fea_model_definition,
       node_definition,
       structural_response_property);

  REFERENCE FROM support_resource_schema 
      (identifier,
       label,
       text);

TYPE axi_or_plane = ENUMERATION OF
  (axisymmetric,
   planar);
END_TYPE;

TYPE coordinate_system_type = ENUMERATION OF
     (cartesian,
      cylindrical,
      spherical);
END_TYPE;

TYPE element_order = ENUMERATION OF
     (linear,
      quadratic,
      cubic);
END_TYPE;

TYPE plane_2d_element_purpose = SELECT
     (enumerated_plane_2d_element_purpose,
      application_defined_element_purpose);
END_TYPE;

TYPE enumerated_plane_2d_element_purpose = ENUMERATION OF
     (plane_stress,
      plane_strain);
END_TYPE;

TYPE application_defined_element_purpose = STRING;
END_TYPE;

TYPE volume_element_purpose = SELECT
     (enumerated_volume_element_purpose,
      application_defined_element_purpose);
END_TYPE;

TYPE enumerated_volume_element_purpose = ENUMERATION OF
     (stress_displacement);
END_TYPE;

TYPE surface_element_purpose = SELECT
     (enumerated_surface_element_purpose,
      application_defined_element_purpose);
END_TYPE;

TYPE enumerated_surface_element_purpose = ENUMERATION OF
     (membrane_direct,
      membrane_shear,
      bending_direct,
      bending_torsion,
      normal_to_plane_shear);
END_TYPE;

TYPE curve_element_purpose = SELECT
     (enumerated_curve_element_purpose,
      application_defined_element_purpose);
END_TYPE;

TYPE enumerated_curve_element_purpose = ENUMERATION OF
     (axial,
      y_y_bending,
      z_z_bending,
      torsion,
      x_y_shear,
      x_z_shear,
      warping);
END_TYPE;

TYPE volume_3d_element_shape = ENUMERATION OF
     (hexahedron,
      wedge,
      tetrahedron,
      pyramid);
END_TYPE;

TYPE element_2d_shape = ENUMERATION OF
     (quadrilateral,
      triangle);
END_TYPE;

TYPE matrix_property_type = SELECT
  (enumerated_matrix_property_type,
   application_defined_matrix_property_type);
END_TYPE;

TYPE enumerated_matrix_property_type = ENUMERATION OF
     (stiffness,
      mass,
      damping);
END_TYPE;

TYPE application_defined_matrix_property_type = STRING;
END_TYPE;

TYPE surface_matrix_property_type = SELECT
  (enumerated_surface_matrix_property_type,
   application_defined_matrix_property_type);
END_TYPE;

TYPE enumerated_surface_matrix_property_type = ENUMERATION OF
     (membrane_direct,
      membrane_shear,
      bending_direct,
      bending_torsion,
      normal_to_plane_shear,
      membrane_direct_mass,
      membrane_shear_mass,
      bending_direct_mass,
      bending_torsion_mass,
      normal_to_plane_shear_mass,
      mass);
END_TYPE;

TYPE curve_matrix_property_type = SELECT
  (enumerated_curve_matrix_property_type,
   application_defined_matrix_property_type);
END_TYPE;

TYPE enumerated_curve_matrix_property_type = ENUMERATION OF
     (axial,
      y_y_bending,
      z_z_bending,
      torsion,
      x_y_shear,
      x_z_shear,
      warping,
      axial_mass,
      y_y_bending_mass,
      z_z_bending_mass,
      torsion_mass,
      x_y_shear_mass,
      x_z_shear_mass,
      warping_mass,
      mass);
END_TYPE;

TYPE matrix_symmetry = ENUMERATION OF
     (symmetric,
      diagonal);
END_TYPE;

TYPE degree_of_freedom = SELECT
  (enumerated_degree_of_freedom,
   application_defined_degree_of_freedom);
END_TYPE;

TYPE enumerated_degree_of_freedom = ENUMERATION OF
     (x_translation, y_translation, z_translation,
      x_rotation, y_rotation, z_rotation,
      warp);
END_TYPE;

TYPE application_defined_degree_of_freedom = STRING;
END_TYPE;

TYPE curve_element_freedom = SELECT
     (enumerated_curve_element_freedom,
      application_defined_degree_of_freedom);
END_TYPE;

TYPE enumerated_curve_element_freedom = ENUMERATION OF
     (x_translation, y_translation, z_translation,
      x_rotation, y_rotation, z_rotation,
      warp,
      none);
END_TYPE;

TYPE integration_rule = ENUMERATION OF
     (gaussian,
      simpson);
END_TYPE;

TYPE shape_function = ENUMERATION OF
     (lagrangian,
      serendipity,
      hermitian,
      unspecified);
END_TYPE;

TYPE volume_2d_element_representation = SELECT
  (axisymmetric_volume_2d_element_representation,
   plane_volume_2d_element_representation);
END_TYPE;

TYPE surface_2d_element_representation = SELECT
  (axisymmetric_surface_2d_element_representation,
   plane_surface_2d_element_representation);
END_TYPE;

TYPE curve_2d_element_representation = SELECT
  (axisymmetric_curve_2d_element_representation,
   plane_curve_2d_element_representation);
END_TYPE;

TYPE volume_2d_element_descriptor = SELECT
     (axisymmetric_volume_2d_element_descriptor,
      plane_volume_2d_element_descriptor);
END_TYPE;

TYPE surface_2d_element_descriptor = SELECT
     (axisymmetric_surface_2d_element_descriptor,
      plane_surface_2d_element_descriptor);
END_TYPE;

TYPE curve_2d_element_descriptor = SELECT
     (axisymmetric_curve_2d_element_descriptor,
      plane_curve_2d_element_descriptor);
END_TYPE;

TYPE volume_3d_element_coordinate_system = SELECT
  (arbitrary_volume_3d_element_coordinate_system,
   parametric_volume_3d_element_coordinate_system);
END_TYPE;

TYPE volume_2d_element_coordinate_system = SELECT
  (arbitrary_volume_2d_element_coordinate_system,
   parametric_volume_2d_element_coordinate_system);
END_TYPE;

TYPE surface_3d_element_coordinate_system = SELECT
  (aligned_surface_3d_element_coordinate_system,
   parametric_surface_3d_element_coordinate_system,
   constant_surface_3d_element_coordinate_system);
END_TYPE;

TYPE surface_2d_element_coordinate_system = SELECT
  (aligned_surface_2d_element_coordinate_system,
   parametric_surface_2d_element_coordinate_system);
END_TYPE;

TYPE curve_3d_element_coordinate_system = SELECT
  (aligned_curve_3d_element_coordinate_system,
   parametric_curve_3d_element_coordinate_system);
END_TYPE;

TYPE curve_element_end_coordinate_system = SELECT
     (fea_axis2_placement_3d,
      curve_3d_element_coordinate_system);
END_TYPE;

TYPE directionally_explicit_element_coordinate_system = SELECT
  (directionally_explicit_element_coordinate_system_arbitrary,
   directionally_explicit_element_coordinate_system_aligned);
END_TYPE;

TYPE element_aspect = SELECT
     (element_volume,
      volume_3d_face,
      volume_2d_face,
      volume_3d_edge,
      volume_2d_edge,
      surface_3d_face,
      surface_2d_face,
      surface_3d_edge,
      surface_2d_edge,
      curve_edge);
END_TYPE;

TYPE element_volume = ENUMERATION OF
     (volume);
END_TYPE;

TYPE curve_edge = ENUMERATION OF
     (element_edge);
END_TYPE;

TYPE node_or_node_group = SELECT
     (node_representation,
      node_group);
END_TYPE;

TYPE element_or_element_group = SELECT
     (element_representation,
      element_group);
END_TYPE;

ENTITY fea_model
  SUPERTYPE OF (ONEOF(fea_model_2d,
                      fea_model_3d))
  SUBTYPE OF (representation);
  creating_software         : text;
  intended_analysis_code    : SET [1:?] OF text;
  description               : text;
  analysis_type             : text;
UNIQUE
  UR1:  SELF\representation.name;
END_ENTITY;

ENTITY fea_model_3d
  SUBTYPE OF (fea_model);
WHERE
  WR1: SELF\representation.context_of_items\
       geometric_representation_context.coordinate_space_dimension = 3;
END_ENTITY;

ENTITY fea_model_2d
  SUBTYPE OF (fea_model);
  type_of_2d_analysis       : axi_or_plane;
WHERE
  WR1: SELF\representation.context_of_items\
       geometric_representation_context.coordinate_space_dimension = 2;
END_ENTITY;

ENTITY structural_response_property_definition_representation
  SUBTYPE OF (property_definition_representation);
WHERE
  WR1: (('STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' +
         'STRUCTURAL_RESPONSE_PROPERTY') IN TYPEOF 
         (SELF\property_definition_representation.definition));
  WR2: ((('STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.FEA_MODEL'
        IN TYPEOF 
        (SELF\property_definition_representation.used_representation))
        AND
        ('STRUCTURAL_RESPONSE_DEFINITION_SCHEMA.FEA_MODEL_DEFINITION'
        IN TYPEOF 
        (SELF\property_definition_representation.definition.definition)))
       OR
      (('STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.ELEMENT_REPRESENTATION'
        IN TYPEOF 
        (SELF\property_definition_representation.used_representation))
        AND
        ('STRUCTURAL_RESPONSE_DEFINITION_SCHEMA.ELEMENT_DEFINITION'
        IN TYPEOF 
        (SELF\property_definition_representation.definition.definition)))
       OR
      (('STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.NODE_REPRESENTATION'
        IN TYPEOF 
        (SELF\property_definition_representation.used_representation))
        AND
        ('STRUCTURAL_RESPONSE_DEFINITION_SCHEMA.NODE_DEFINITION'
        IN TYPEOF 
        (SELF\property_definition_representation.definition.definition))));
END_ENTITY;

ENTITY fea_representation_item
  SUPERTYPE OF (ONEOF
               (arbitrary_volume_3d_element_coordinate_system,
                parametric_volume_3d_element_coordinate_system,
                arbitrary_volume_2d_element_coordinate_system,
                parametric_volume_2d_element_coordinate_system,
                aligned_surface_3d_element_coordinate_system,
                parametric_surface_3d_element_coordinate_system,
                constant_surface_3d_element_coordinate_system,
                aligned_surface_2d_element_coordinate_system,
                parametric_surface_2d_element_coordinate_system,
                aligned_curve_3d_element_coordinate_system,
                parametric_curve_3d_element_coordinate_system,
                parametric_curve_3d_element_coordinate_direction,
                curve_2d_element_coordinate_system,
                directionally_explicit_element_coordinate_system_arbitrary,
                directionally_explicit_element_coordinate_system_aligned))
  SUBTYPE OF (representation_item);
END_ENTITY;

ENTITY direction_node
  SUBTYPE OF (direction);
  node_1                    : node_representation;
  node_2                    : node_representation;
DERIVE
  SELF\direction.direction_ratios : LIST [2:3] OF REAL := 
                                    build_direction_node (node_1, node_2);
WHERE
  WR1: SIZEOF (QUERY(item <* node_1\representation.items |
              'GEOMETRY_SCHEMA.CARTESIAN_POINT' IN TYPEOF (item))) = 1;
  WR2: SIZEOF (QUERY(item <* node_2\representation.items |
              'GEOMETRY_SCHEMA.CARTESIAN_POINT' IN TYPEOF (item))) = 1;
  WR3: NOT ((direction_ratios[1] = 0.0) AND
            (direction_ratios[2] = 0.0) AND
            (direction_ratios[3] = 0.0));
END_ENTITY;

ENTITY fea_axis2_placement_2d
  SUBTYPE OF (axis2_placement_2d);
  system_type               : coordinate_system_type;
  description               : text;
END_ENTITY;

ENTITY fea_axis2_placement_3d
  SUBTYPE OF (axis2_placement_3d);
  system_type               : coordinate_system_type;
  description               : text;
END_ENTITY;

ENTITY node_set
  SUBTYPE OF (geometric_representation_item);
  nodes                     : SET [1:?] OF node_representation;
WHERE
  WR1: SIZEOF (QUERY (tmp <* nodes | 
               tmp\representation.context_of_items :<>:
               nodes[1]\representation.context_of_items)) = 0;
END_ENTITY;

ENTITY analysis_item_within_representation;
  name                      : label;
  description               : text;
  item                      : representation_item;
  rep                       : representation;
WHERE
  WR1: SIZEOF (QUERY (tmp <* using_representations(item) | 
                      tmp :=: rep)) = 1;
END_ENTITY;

ENTITY node_geometric_relationship;
  node_ref                  : node_or_node_group;
  item                      : analysis_item_within_representation;
WHERE
  WR1: 'GEOMETRY_SCHEMA.GEOMETRIC_REPRESENTATION_ITEM' IN TYPEOF(item.item);
END_ENTITY;

ENTITY element_geometric_relationship;
  element_ref               : element_or_element_group;
  item                      : analysis_item_within_representation;
  aspect                    : element_aspect;
WHERE
  WR1: 'GEOMETRY_SCHEMA.GEOMETRIC_REPRESENTATION_ITEM' IN TYPEOF(item.item);
  WR2: consistent_geometric_reference (aspect, item.item);
  WR3: consistent_element_or_group_reference (aspect, element_ref);
END_ENTITY;

ENTITY node_representation
  SUPERTYPE OF (ONEOF
                     (node,
                      dummy_node,
                      geometric_node))
  SUBTYPE OF (representation);
  model_ref                 : fea_model;
UNIQUE
  UR1: model_ref, SELF\representation.name;
END_ENTITY;

ENTITY node
  SUPERTYPE OF (node_with_vector ANDOR
                node_with_solution_coordinate_system)
  SUBTYPE OF (node_representation);
WHERE
  WR1: SIZEOF (QUERY(item <* SELF\representation.items |
              'GEOMETRY_SCHEMA.POINT' 
              IN TYPEOF (item))) = 1;
END_ENTITY;

ENTITY node_with_vector
  SUBTYPE OF (node);
WHERE
  WR1: SIZEOF (QUERY(item <* SELF\representation.items |
              'GEOMETRY_SCHEMA.DIRECTION' 
              IN TYPEOF (item))) = 1;
END_ENTITY;

ENTITY node_with_solution_coordinate_system
  SUBTYPE OF (node);
WHERE
  WR1: ( (SIZEOF (QUERY(item <* SELF\representation.items |
              'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' +
              'FEA_AXIS2_PLACEMENT_3D' 
              IN TYPEOF (item))) = 1)
          AND
          (SELF\representation.context_of_items\
       geometric_representation_context.coordinate_space_dimension = 3) )
     OR
       ( (SIZEOF (QUERY(item <* SELF\representation.items |
              'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' +
              'FEA_AXIS2_PLACEMENT_2D' 
              IN TYPEOF (item))) = 1)
          AND
          (SELF\representation.context_of_items\
       geometric_representation_context.coordinate_space_dimension = 2) );
END_ENTITY;

ENTITY dummy_node
  SUBTYPE OF (node_representation);
END_ENTITY;

ENTITY geometric_node
  SUBTYPE OF (node_representation);
WHERE
  WR1: SIZEOF (QUERY(item <* SELF\representation.items |
              'GEOMETRY_SCHEMA.POINT' 
              IN TYPEOF (item))) = 1;
END_ENTITY;

ENTITY substructure_node_relationship
  SUBTYPE OF (representation_relationship);
WHERE
  WR1: 'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.NODE_REPRESENTATION' 
        IN TYPEOF (SELF\representation_relationship.rep_1);
  WR2: 'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.NODE_REPRESENTATION' 
        IN TYPEOF (SELF\representation_relationship.rep_2);
END_ENTITY;

ENTITY element_representation
  SUPERTYPE OF (ONEOF(volume_3d_element_representation,
                      axisymmetric_volume_2d_element_representation,
                      plane_volume_2d_element_representation,
                      surface_3d_element_representation,
                      axisymmetric_surface_2d_element_representation,
                      plane_surface_2d_element_representation,
                      curve_3d_element_representation,
                      axisymmetric_curve_2d_element_representation,
                      plane_curve_2d_element_representation,
                      point_element_representation,
                      directionally_explicit_element_representation,
                      explicit_element_representation,
                      substructure_element_representation))
  SUBTYPE OF (representation);
  node_list                 : LIST [1:?] OF node_representation;
WHERE
  WR1: SIZEOF (QUERY(item <* node_list |
              'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' +
              'GEOMETRIC_NODE' 
              IN TYPEOF (item))) = 0;
 END_ENTITY;

ENTITY volume_3d_element_representation
  SUBTYPE OF (element_representation);
  model_ref                 : fea_model_3d;
  element_descriptor        : volume_3d_element_descriptor;
  material                  : element_material;
UNIQUE
  UR1: model_ref, SELF\representation.name;
WHERE
  WR1: SIZEOF (QUERY(item <* SELF\representation.items |
               'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' +
               'PARAMETRIC_VOLUME_3D_ELEMENT_COORDINATE_SYSTEM'
               IN TYPEOF (item))) +
       SIZEOF (QUERY(item <* SELF\representation.items |
               'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' +
               'ARBITRARY_VOLUME_3D_ELEMENT_COORDINATE_SYSTEM'
               IN TYPEOF (item))) = 1;
  WR2: SIZEOF (QUERY(item1 <* material.properties |
        (SIZEOF (QUERY (item2 <* 
        item1\property_definition_representation.used_representation.items |
         SIZEOF (['STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_LINEAR_ELASTICITY',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_MASS_DENSITY',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_TANGENTIAL_COEFFICIENT_OF_LINEAR_THERMAL_EXPANSION',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_SECANT_COEFFICIENT_OF_LINEAR_THERMAL_EXPANSION',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_MOISTURE_ABSORPTION'] * TYPEOF (item2)
                  ) = 1
        )) = 1
       ))) >= 1;
  WR3: 'REPRESENTATION_SCHEMA.PARAMETRIC_REPRESENTATION_CONTEXT'
        IN TYPEOF (SELF\representation.context_of_items); 
  FU1:  required_3d_nodes (
        SELF\element_representation.node_list,
        element_descriptor.shape,
        element_descriptor\element_descriptor.topology_order);
END_ENTITY;

ENTITY axisymmetric_volume_2d_element_representation
  SUBTYPE OF (element_representation);
  model_ref                 : fea_model_2d;
  element_descriptor        : axisymmetric_volume_2d_element_descriptor;
  angle_property            : axisymmetric_2d_element_property;
  material                  : element_material;
UNIQUE
  UR1: model_ref, SELF\representation.name;
WHERE
  WR1: model_ref.type_of_2d_analysis = axisymmetric;
  WR2: SIZEOF (QUERY(item <* SELF\representation.items |
              'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' +
              'PARAMETRIC_VOLUME_2D_ELEMENT_COORDINATE_SYSTEM'
              IN TYPEOF (item))) +
       SIZEOF (QUERY(item <* SELF\representation.items |
              'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' +
              'ARBITRARY_VOLUME_2D_ELEMENT_COORDINATE_SYSTEM'
              IN TYPEOF (item))) = 1;
  WR3: SIZEOF (QUERY(item1 <* material.properties |
        (SIZEOF (QUERY (item2 <* 
        item1\property_definition_representation.used_representation.items |
         SIZEOF (['STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_LINEAR_ELASTICITY',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_MASS_DENSITY',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_AREA_DENSITY',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_TANGENTIAL_COEFFICIENT_OF_LINEAR_THERMAL_EXPANSION',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_SECANT_COEFFICIENT_OF_LINEAR_THERMAL_EXPANSION',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_MOISTURE_ABSORPTION'] * TYPEOF (item2)
                  ) = 1
        )) = 1
       ))) >= 1;
  WR4: 'REPRESENTATION_SCHEMA.PARAMETRIC_REPRESENTATION_CONTEXT'
        IN TYPEOF (SELF\representation.context_of_items); 
  FU1:  required_2d_nodes (
        SELF\element_representation.node_list,
        element_descriptor.shape,
        element_descriptor\element_descriptor.topology_order);
END_ENTITY;

ENTITY plane_volume_2d_element_representation
  SUBTYPE OF (element_representation);
  model_ref                 : fea_model_2d;
  element_descriptor        : plane_volume_2d_element_descriptor;
  depth_property            : plane_2d_element_property;
  material                  : element_material;
UNIQUE
  UR1: model_ref, SELF\representation.name;
WHERE
  WR1: model_ref.type_of_2d_analysis = planar;
  WR2: SIZEOF (QUERY(item <* SELF\representation.items |
              'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' +
              'PARAMETRIC_VOLUME_2D_ELEMENT_COORDINATE_SYSTEM'
              IN TYPEOF (item))) +
       SIZEOF (QUERY(item <* SELF\representation.items |
              'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' +
              'ARBITRARY_VOLUME_2D_ELEMENT_COORDINATE_SYSTEM'
              IN TYPEOF (item))) = 1;
  WR3: SIZEOF (QUERY(item1 <* material.properties |
        (SIZEOF (QUERY (item2 <* 
        item1\property_definition_representation.used_representation.items |
         SIZEOF (['STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_LINEAR_ELASTICITY',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_MASS_DENSITY',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_AREA_DENSITY',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_TANGENTIAL_COEFFICIENT_OF_LINEAR_THERMAL_EXPANSION',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_SECANT_COEFFICIENT_OF_LINEAR_THERMAL_EXPANSION',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_MOISTURE_ABSORPTION'] * TYPEOF (item2)
                  ) = 1
        )) = 1
       ))) >= 1;
  WR4: 'REPRESENTATION_SCHEMA.PARAMETRIC_REPRESENTATION_CONTEXT'
        IN TYPEOF (SELF\representation.context_of_items); 
  FU1:  required_2d_nodes (
        SELF\element_representation.node_list,
        element_descriptor.shape,
        element_descriptor\element_descriptor.topology_order);
END_ENTITY;

ENTITY surface_3d_element_representation
  SUBTYPE OF (element_representation);
  model_ref                 : fea_model_3d;
  element_descriptor        : surface_3d_element_descriptor;
  property                  : surface_element_property;
  material                  : element_material;
UNIQUE
  UR1: model_ref, SELF\representation.name;
WHERE
  WR1: SIZEOF (QUERY(item <* SELF\representation.items |
              'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' +
              'PARAMETRIC_SURFACE_3D_ELEMENT_COORDINATE_SYSTEM'
              IN TYPEOF (item))) +
       SIZEOF (QUERY(item <* SELF\representation.items |
              'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' +
              'CONSTANT_SURFACE_3D_ELEMENT_COORDINATE_SYSTEM'
              IN TYPEOF (item))) +
       SIZEOF (QUERY(item <* SELF\representation.items |
              'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' +
              'ALIGNED_SURFACE_3D_ELEMENT_COORDINATE_SYSTEM'
              IN TYPEOF (item))) = 1;
  WR2: SIZEOF (QUERY(item1 <* material.properties |
        (SIZEOF (QUERY (item2 <* 
        item1\property_definition_representation.used_representation.items |
         SIZEOF (['STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_LINEAR_ELASTICITY',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_MASS_DENSITY',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_AREA_DENSITY',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_TANGENTIAL_COEFFICIENT_OF_LINEAR_THERMAL_EXPANSION',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_SECANT_COEFFICIENT_OF_LINEAR_THERMAL_EXPANSION',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_MOISTURE_ABSORPTION',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_SHELL_MEMBRANE_STIFFNESS',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_SHELL_BENDING_STIFFNESS',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_SHELL_MEMBRANE_BENDING_COUPLING_STIFFNESS',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_SHELL_SHEAR_STIFFNESS'] * TYPEOF (item2)
                  ) = 1
        )) = 1
       ))) >= 1;
  WR3: 'REPRESENTATION_SCHEMA.PARAMETRIC_REPRESENTATION_CONTEXT'
        IN TYPEOF (SELF\representation.context_of_items); 
  FU1:  required_2d_nodes (
        SELF\element_representation.node_list,
        element_descriptor.shape,
        element_descriptor\element_descriptor.topology_order);
END_ENTITY;

ENTITY axisymmetric_surface_2d_element_representation
  SUBTYPE OF (element_representation);
  model_ref                 : fea_model_2d;
  element_descriptor        : axisymmetric_surface_2d_element_descriptor;
  property                  : surface_element_property;
  angle_property            : axisymmetric_2d_element_property;
  material                  : element_material;
UNIQUE
  UR1: model_ref, SELF\representation.name;
WHERE
  WR1: model_ref.type_of_2d_analysis = axisymmetric;
  WR2: SIZEOF (QUERY(item <* SELF\representation.items |
              'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' +
              'PARAMETRIC_SURFACE_2D_ELEMENT_COORDINATE_SYSTEM'
               IN TYPEOF (item))) +
       SIZEOF (QUERY(item <* SELF\representation.items |
              'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' +
              'ALIGNED_SURFACE_2D_ELEMENT_COORDINATE_SYSTEM' 
               IN TYPEOF (item))) = 1;
  WR3: SIZEOF (QUERY(item1 <* material.properties |
        (SIZEOF (QUERY (item2 <* 
        item1\property_definition_representation.used_representation.items |
         SIZEOF (['STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_LINEAR_ELASTICITY',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_MASS_DENSITY',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_AREA_DENSITY',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_TANGENTIAL_COEFFICIENT_OF_LINEAR_THERMAL_EXPANSION',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_SECANT_COEFFICIENT_OF_LINEAR_THERMAL_EXPANSION',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_MOISTURE_ABSORPTION',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_SHELL_MEMBRANE_STIFFNESS',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_SHELL_BENDING_STIFFNESS',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_SHELL_MEMBRANE_BENDING_COUPLING_STIFFNESS',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_SHELL_SHEAR_STIFFNESS'] * TYPEOF (item2)
                  ) = 1
        )) = 1
       ))) >= 1;
  WR4: 'REPRESENTATION_SCHEMA.PARAMETRIC_REPRESENTATION_CONTEXT'
        IN TYPEOF (SELF\representation.context_of_items); 
  FU1:  required_1d_nodes (
        SELF\element_representation.node_list,
        element_descriptor\element_descriptor.topology_order);
END_ENTITY;

ENTITY plane_surface_2d_element_representation
  SUBTYPE OF (element_representation);
  model_ref                 : fea_model_2d;
  element_descriptor        : plane_surface_2d_element_descriptor;
  property                  : surface_element_property;
  depth_property            : plane_2d_element_property;
  material                  : element_material;
UNIQUE
  UR1: model_ref, SELF\representation.name;
WHERE
  WR1: model_ref.type_of_2d_analysis = planar;
  WR2: SIZEOF (QUERY(item <* SELF\representation.items |
              'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' +
              'PARAMETRIC_SURFACE_2D_ELEMENT_COORDINATE_SYSTEM'
              IN TYPEOF (item))) +
       SIZEOF (QUERY(item <* SELF\representation.items |
              'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' +
              'ALIGNED_SURFACE_2D_ELEMENT_COORDINATE_SYSTEM' 
              IN TYPEOF (item))) = 1;
  WR3: SIZEOF (QUERY(item1 <* material.properties |
        (SIZEOF (QUERY (item2 <* 
        item1\property_definition_representation.used_representation.items |
         SIZEOF (['STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_LINEAR_ELASTICITY',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_MASS_DENSITY',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_AREA_DENSITY',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_TANGENTIAL_COEFFICIENT_OF_LINEAR_THERMAL_EXPANSION',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_SECANT_COEFFICIENT_OF_LINEAR_THERMAL_EXPANSION',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_MOISTURE_ABSORPTION',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_SHELL_MEMBRANE_STIFFNESS',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_SHELL_BENDING_STIFFNESS',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_SHELL_MEMBRANE_BENDING_COUPLING_STIFFNESS',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_SHELL_SHEAR_STIFFNESS'] * TYPEOF (item2)
                  ) = 1
        )) = 1
       ))) >= 1;
  WR4: 'REPRESENTATION_SCHEMA.PARAMETRIC_REPRESENTATION_CONTEXT'
        IN TYPEOF (SELF\representation.context_of_items); 
  FU1:  required_1d_nodes (
        SELF\element_representation.node_list,
        element_descriptor\element_descriptor.topology_order);
END_ENTITY;

ENTITY curve_3d_element_representation
  SUBTYPE OF (element_representation);
  model_ref                 : fea_model_3d;
  element_descriptor        : curve_3d_element_descriptor;
  property                  : curve_3d_element_property;
  material                  : element_material;
UNIQUE
  UR1: model_ref, SELF\representation.name;
WHERE
  WR1: SIZEOF (QUERY(item <* SELF\representation.items |
              'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' +
              'PARAMETRIC_CURVE_3D_ELEMENT_COORDINATE_SYSTEM'
              IN TYPEOF (item))) +
       SIZEOF (QUERY(item <* SELF\representation.items |
              'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' +
              'ALIGNED_CURVE_3D_ELEMENT_COORDINATE_SYSTEM'
              IN TYPEOF (item))) = 1;
  WR2: SIZEOF (QUERY(item1 <* material.properties |
        (SIZEOF (QUERY (item2 <* 
        item1\property_definition_representation.used_representation.items |
         SIZEOF (['STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_LINEAR_ELASTICITY',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_MASS_DENSITY',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_AREA_DENSITY',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_TANGENTIAL_COEFFICIENT_OF_LINEAR_THERMAL_EXPANSION',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_SECANT_COEFFICIENT_OF_LINEAR_THERMAL_EXPANSION',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_MOISTURE_ABSORPTION'] * TYPEOF (item2)
                  ) = 1
        )) = 1
       ))) >= 1;
  WR3: 'REPRESENTATION_SCHEMA.PARAMETRIC_REPRESENTATION_CONTEXT'
        IN TYPEOF (SELF\representation.context_of_items); 
  FU1:  required_1d_nodes (
        SELF\element_representation.node_list,
        element_descriptor\element_descriptor.topology_order);
END_ENTITY;

ENTITY axisymmetric_curve_2d_element_representation
  SUBTYPE OF (element_representation);
  model_ref                 : fea_model_2d;
  element_descriptor        : axisymmetric_curve_2d_element_descriptor;
  property                  : curve_2d_element_property;
  angle_property            : axisymmetric_2d_element_property;
  material                  : element_material;
UNIQUE
  UR1: model_ref, SELF\representation.name;
WHERE
  WR1: model_ref.type_of_2d_analysis = axisymmetric;
  WR2: SIZEOF (QUERY(item <* SELF\representation.items |
              'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' +
              'CURVE_2D_ELEMENT_COORDINATE_SYSTEM'
              IN TYPEOF (item))) = 1;
  WR3: SIZEOF (QUERY(item1 <* material.properties |
        (SIZEOF (QUERY (item2 <* 
        item1\property_definition_representation.used_representation.items |
         SIZEOF (['STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_LINEAR_ELASTICITY',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_MASS_DENSITY',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_AREA_DENSITY',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_TANGENTIAL_COEFFICIENT_OF_LINEAR_THERMAL_EXPANSION',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_SECANT_COEFFICIENT_OF_LINEAR_THERMAL_EXPANSION',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_MOISTURE_ABSORPTION'] * TYPEOF (item2)
                  ) = 1
        )) = 1
       ))) >= 1;
  WR4: 'REPRESENTATION_SCHEMA.PARAMETRIC_REPRESENTATION_CONTEXT'
        IN TYPEOF (SELF\representation.context_of_items); 
  FU1:  required_0d_nodes (
        SELF\element_representation.node_list);
END_ENTITY;

ENTITY plane_curve_2d_element_representation
  SUBTYPE OF (element_representation);
  model_ref                 : fea_model_2d;
  element_descriptor        : plane_curve_2d_element_descriptor;
  property                  : curve_2d_element_property;
  depth_property            : plane_2d_element_property;
  material                  : element_material;
UNIQUE
  UR1: model_ref, SELF\representation.name;
WHERE
  WR1: model_ref.type_of_2d_analysis = planar;
  WR2: SIZEOF (QUERY(item <* SELF\representation.items |
              'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' +
              'CURVE_2D_ELEMENT_COORDINATE_SYSTEM'
              IN TYPEOF (item))) = 1;
  WR3: SIZEOF (QUERY(item1 <* material.properties |
        (SIZEOF (QUERY (item2 <* 
        item1\property_definition_representation.used_representation.items |
         SIZEOF (['STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_LINEAR_ELASTICITY',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_MASS_DENSITY',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_AREA_DENSITY',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_TANGENTIAL_COEFFICIENT_OF_LINEAR_THERMAL_EXPANSION',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_SECANT_COEFFICIENT_OF_LINEAR_THERMAL_EXPANSION',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_MOISTURE_ABSORPTION'] * TYPEOF (item2)
                  ) = 1
        )) = 1
       ))) >= 1;
  WR4: 'REPRESENTATION_SCHEMA.PARAMETRIC_REPRESENTATION_CONTEXT'
        IN TYPEOF (SELF\representation.context_of_items); 
  FU1:  required_0d_nodes (
        SELF\element_representation.node_list);
END_ENTITY;

ENTITY element_descriptor
  SUPERTYPE OF (ONEOF (volume_3d_element_descriptor,
                       axisymmetric_volume_2d_element_descriptor,
                       plane_volume_2d_element_descriptor,
                       surface_3d_element_descriptor,
                       axisymmetric_surface_2d_element_descriptor,
                       plane_surface_2d_element_descriptor,
                       curve_3d_element_descriptor,
                       axisymmetric_curve_2d_element_descriptor,
                       plane_curve_2d_element_descriptor));
  topology_order            : element_order;
  description               : text;
END_ENTITY;

ENTITY volume_3d_element_descriptor
  SUBTYPE OF (element_descriptor);
  purpose                   : SET [1:?] OF volume_element_purpose;
  shape                     : volume_3d_element_shape;
END_ENTITY;

ENTITY axisymmetric_volume_2d_element_descriptor
  SUBTYPE OF (element_descriptor);
  purpose                   : SET [1:?] OF SET [1:?] OF 
                              volume_element_purpose;
  shape                     : element_2d_shape;
END_ENTITY;

ENTITY plane_volume_2d_element_descriptor
  SUBTYPE OF (element_descriptor);
  purpose                   : SET [1:?] OF SET [1:?] OF 
                              volume_element_purpose;
  shape                     : element_2d_shape;
  assumption                : plane_2d_element_purpose;
END_ENTITY;

ENTITY volume_3d_element_basis;
  descriptor                : volume_3d_element_descriptor;
  variable                  : volume_variable;
  variable_order            : element_order;
  variable_shape_function   : shape_function;
  evaluation_points         : LIST [1:?] OF volume_element_location;
END_ENTITY;

ENTITY volume_2d_element_basis;
  descriptor                : volume_2d_element_descriptor;
  variable                  : volume_variable;
  variable_order            : element_order;
  variable_shape_function   : shape_function;
  evaluation_points         : LIST [1:?] OF volume_element_location;
END_ENTITY;

ENTITY surface_3d_element_descriptor
  SUBTYPE OF (element_descriptor);
  purpose                   : SET [1:?] OF SET [1:?] OF 
                              surface_element_purpose;
  shape                     : element_2d_shape;
END_ENTITY;

ENTITY axisymmetric_surface_2d_element_descriptor
  SUBTYPE OF (element_descriptor);
  purpose                   : SET [1:?] OF SET [1:?] OF 
                              surface_element_purpose;
END_ENTITY;

ENTITY plane_surface_2d_element_descriptor
  SUBTYPE OF (element_descriptor);
  purpose                   : SET [1:?] OF SET [1:?] OF 
                              surface_element_purpose;
  assumption                : plane_2d_element_purpose;
END_ENTITY;

ENTITY surface_3d_element_basis;
  descriptor                : surface_3d_element_descriptor;
  variable                  : surface_element_variable;
  variable_order            : element_order;
  variable_shape_function   : shape_function;
  evaluation_points         : LIST [1:?] OF surface_element_location;
END_ENTITY;

ENTITY surface_2d_element_basis;
  descriptor                : surface_2d_element_descriptor;
  variable                  : surface_element_variable;
  variable_order            : element_order;
  variable_shape_function   : shape_function;
  evaluation_points         : LIST [1:?] OF surface_element_location;
END_ENTITY;

ENTITY curve_3d_element_descriptor
  SUBTYPE OF (element_descriptor);
  purpose                   : SET [1:?] OF SET [1:?] OF 
                              curve_element_purpose;
END_ENTITY;

ENTITY axisymmetric_curve_2d_element_descriptor
  SUBTYPE OF (element_descriptor);
  purpose                   : SET [1:?] OF SET [1:?] OF 
                              curve_element_purpose;
END_ENTITY;

ENTITY plane_curve_2d_element_descriptor
  SUBTYPE OF (element_descriptor);
  purpose                   : SET [1:?] OF SET [1:?] OF 
                              curve_element_purpose;
  assumption                : plane_2d_element_purpose;
END_ENTITY;

ENTITY curve_3d_element_basis;
  descriptor                : curve_3d_element_descriptor;
  variable                  : curve_element_variable;
  variable_order            : element_order;
  variable_shape_function   : shape_function;
  evaluation_points         : LIST [1:?] OF curve_element_location;
END_ENTITY;

ENTITY curve_2d_element_basis;
  descriptor                : curve_2d_element_descriptor;
  variable                  : curve_element_variable;
END_ENTITY;

ENTITY point_element_representation
  SUBTYPE OF (element_representation);
  model_ref                 : fea_model;
  description               : text;
  matrix_set                : SET [1:?] OF point_element_matrix;
UNIQUE
  UR1: model_ref, SELF\representation.name;
WHERE
  WR1: SIZEOF (QUERY(item <* SELF\representation.items |
              'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' +
              'FEA_AXIS2_PLACEMENT_3D'
              IN TYPEOF (item))) = 1;
  FU1:  required_0d_nodes (
        SELF\element_representation.node_list);
END_ENTITY;

ENTITY point_element_matrix
  SUPERTYPE OF (ONEOF(stationary_mass,
                      grounded_spring,
                      grounded_damper));
END_ENTITY;

ENTITY stationary_mass
  SUBTYPE OF (point_element_matrix);
  mass                      : ARRAY [1:3] OF context_dependent_measure;
  moments_of_inertia        : symmetric_tensor2_3d;
  coordinate_system         : fea_axis2_placement_3d;
  offset_vector             : ARRAY [1:3] OF context_dependent_measure;
END_ENTITY;

ENTITY grounded_spring
  SUBTYPE OF (point_element_matrix);
  stiffness_coefficients    : ARRAY [1:6] OF context_dependent_measure;
END_ENTITY;

ENTITY grounded_damper
  SUBTYPE OF (point_element_matrix);
  damping_coefficients      : ARRAY [1:6] OF context_dependent_measure;
END_ENTITY;

ENTITY directionally_explicit_element_representation
  SUBTYPE OF (element_representation);
  model_ref                 : fea_model;
  systems_and_freedoms      : LIST [2:2] OF system_and_freedom;
  description               : text;
  coefficient               : directionally_explicit_element_coefficient;
UNIQUE
  UR1: model_ref, SELF\representation.name;
WHERE
  FU1:  required_1d_nodes (
        SELF\element_representation.node_list,
        linear);
END_ENTITY;

ENTITY system_and_freedom;
  matrix_coordinate_system  : 
                     directionally_explicit_element_coordinate_system;
  freedom                   : degree_of_freedom;
END_ENTITY;

ENTITY directionally_explicit_element_coefficient;
  property_type             : matrix_property_type;
  coefficient               : context_dependent_measure;
END_ENTITY;

ENTITY explicit_element_representation
  SUBTYPE OF (element_representation);
  model_ref                 : fea_model;
  description               : text;
  matrix                    : explicit_element_matrix;
UNIQUE
  UR1: model_ref, SELF\representation.name;
WHERE
  WR1: SIZEOF (QUERY(item <* SELF\representation.items |
              ('STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' +
              'FEA_AXIS2_PLACEMENT_3D') 
              IN TYPEOF (item))) = 1;
  WR2:  SIZEOF (matrix.node_dof_list) = 
        SIZEOF (SELF\element_representation.node_list);
END_ENTITY;

ENTITY explicit_element_matrix;
  property_type             : matrix_property_type;
  symmetry                  : matrix_symmetry;
  node_dof_list             : LIST [1:?] OF LIST [1:?] OF degree_of_freedom;
  matrix_values             : LIST [1:?] OF context_dependent_measure;
WHERE
  WR1: SIZEOF (matrix_values) = number_of_terms (node_dof_list, symmetry);
END_ENTITY;

ENTITY substructure_element_representation
  SUBTYPE OF (element_representation);
  model_ref                 : fea_model;
  substructure_model_ref    : fea_model;
UNIQUE
  UR1: model_ref, SELF\representation.name;
END_ENTITY;

ENTITY aligned_axis_tolerance;
  model_ref                 : fea_model;
  tolerance                 : context_dependent_measure;
END_ENTITY;

ENTITY arbitrary_volume_3d_element_coordinate_system
  SUBTYPE OF (fea_representation_item);
  coordinate_system         : fea_axis2_placement_3d;
END_ENTITY;

ENTITY parametric_volume_3d_element_coordinate_system
  SUBTYPE OF (fea_representation_item);
  axis_1                    : INTEGER;
  axis_2                    : INTEGER;
  eu_angles                 : euler_angles;
WHERE
  WR1:  (axis_1 >= 1) AND (axis_1 <= 3) AND
        (axis_2 >= 1) AND (axis_2 <= 3) AND
        NOT (axis_1 = axis_2);
END_ENTITY;

ENTITY arbitrary_volume_2d_element_coordinate_system
  SUBTYPE OF (fea_representation_item);
  orientation               : direction;
WHERE
  WR1: SELF\geometric_representation_item.dim=2;
END_ENTITY;

ENTITY parametric_volume_2d_element_coordinate_system
  SUBTYPE OF (fea_representation_item);
  axis                      : INTEGER;
  angle                     : plane_angle_measure;
WHERE
  WR1:  (axis >= 1) AND (axis <= 2);
END_ENTITY;

ENTITY aligned_surface_3d_element_coordinate_system
  SUBTYPE OF (fea_representation_item);
  coordinate_system         : fea_axis2_placement_3d;
END_ENTITY;

ENTITY parametric_surface_3d_element_coordinate_system
  SUBTYPE OF (fea_representation_item);
  axis                      : INTEGER;
  angle                     : plane_angle_measure;
WHERE
  WR1:  (axis >= 1) AND (axis <= 2);
END_ENTITY;

ENTITY constant_surface_3d_element_coordinate_system
  SUBTYPE OF (fea_representation_item);
  axis                      : INTEGER;
  angle                     : plane_angle_measure;
WHERE
  WR1:  (axis >= 1) AND (axis <= 2);
END_ENTITY;

ENTITY aligned_surface_2d_element_coordinate_system
  SUBTYPE OF (fea_representation_item);
  orientation               : direction;
WHERE
  WR1: SELF\geometric_representation_item.dim=2;
END_ENTITY;

ENTITY parametric_surface_2d_element_coordinate_system
  SUBTYPE OF (fea_representation_item);
END_ENTITY;

ENTITY aligned_curve_3d_element_coordinate_system
  SUBTYPE OF (fea_representation_item);
  coordinate_system         : fea_axis2_placement_3d;
END_ENTITY;

ENTITY parametric_curve_3d_element_coordinate_system
  SUBTYPE OF (fea_representation_item);
  direction            :  parametric_curve_3d_element_coordinate_direction;
END_ENTITY;

ENTITY parametric_curve_3d_element_coordinate_direction
  SUBTYPE OF (fea_representation_item);
  orientation               : direction;
WHERE
  WR1: SELF\geometric_representation_item.dim=3;
END_ENTITY;

ENTITY curve_2d_element_coordinate_system
  SUBTYPE OF (fea_representation_item);
  orientation               : direction;
WHERE
  WR1: SELF\geometric_representation_item.dim=2;
END_ENTITY;

ENTITY directionally_explicit_element_coordinate_system_arbitrary
  SUBTYPE OF (fea_representation_item);
  arbitrary_system          : fea_axis2_placement_3d;
END_ENTITY;

ENTITY directionally_explicit_element_coordinate_system_aligned
  SUBTYPE OF (fea_representation_item);
  aligned_system            : curve_3d_element_coordinate_system;
END_ENTITY;

ENTITY euler_angles;
  angles                    : ARRAY [1:3] OF plane_angle_measure;
END_ENTITY;

ENTITY volume_3d_element_integrated_matrix;
  descriptor                : volume_3d_element_descriptor;
  property_type             : matrix_property_type;
  integration_description   : text;
END_ENTITY;

ENTITY volume_3d_element_integrated_matrix_with_definition
  SUBTYPE OF (volume_3d_element_integrated_matrix);
  integration_definition    : volume_3d_element_field_integration;
END_ENTITY;

TYPE volume_3d_element_field_integration = SELECT
  (element_integration_algebraic,
   volume_3d_element_field_integration_rule,
   volume_3d_element_field_integration_explicit);
END_TYPE;

TYPE element_integration_algebraic = ENUMERATION OF (algebraic);
END_TYPE;

ENTITY volume_3d_element_field_integration_rule;
  integration_method        : integration_rule;
  integration_order         : ARRAY [1:3] OF INTEGER;
END_ENTITY;

ENTITY volume_3d_element_field_integration_explicit;
  integration_positions_and_weights: SET [1:?] OF volume_position_weight;
END_ENTITY;

ENTITY volume_position_weight;
  integration_position      : volume_element_location;
  integration_weight        : context_dependent_measure;
END_ENTITY;

ENTITY volume_2d_element_integrated_matrix;
  descriptor                : volume_2d_element_descriptor;
  property_type             : matrix_property_type;
  integration_description   : text;
END_ENTITY;

ENTITY volume_2d_element_integrated_matrix_with_definition
  SUBTYPE OF (volume_2d_element_integrated_matrix);
  integration_definition    : volume_2d_element_field_integration;
END_ENTITY;

TYPE volume_2d_element_field_integration = SELECT
  (element_integration_algebraic,
   volume_2d_element_field_integration_rule,
   volume_2d_element_field_integration_explicit);
END_TYPE;

ENTITY volume_2d_element_field_integration_rule;
  integration_method        : integration_rule;
  integration_order         : ARRAY [1:2] OF INTEGER;
END_ENTITY;

ENTITY volume_2d_element_field_integration_explicit;
  integration_positions_and_weights: SET [1:?] OF volume_position_weight;
END_ENTITY;

ENTITY surface_3d_element_integrated_matrix;
  descriptor                : surface_3d_element_descriptor;
  property_type             : surface_matrix_property_type;
  integration_description   : text;
END_ENTITY;

ENTITY surface_3d_element_integrated_matrix_with_definition
  SUBTYPE OF (surface_3d_element_integrated_matrix);
  integration_definition    : surface_3d_element_integration;
END_ENTITY;

ENTITY surface_3d_element_integration;
  field                     : surface_3d_element_field_integration;
  section                   : surface_section_integration;
END_ENTITY;

TYPE surface_3d_element_field_integration = SELECT
  (element_integration_algebraic,
   surface_3d_element_field_integration_rule,
   surface_3d_element_field_integration_explicit);
END_TYPE;

TYPE surface_section_integration = SELECT
  (element_integration_algebraic,
   surface_section_integration_rule,
   surface_section_integration_explicit);
END_TYPE;

ENTITY surface_3d_element_field_integration_rule;
  integration_method        : integration_rule;
  integration_order         : ARRAY [1:2] OF INTEGER;
END_ENTITY;

ENTITY surface_3d_element_field_integration_explicit;
  integration_positions_and_weights: SET [1:?] OF surface_position_weight;
END_ENTITY;

ENTITY surface_position_weight;
  integration_position      : surface_element_location;
  integration_weight        : context_dependent_measure;
END_ENTITY;

ENTITY surface_section_integration_rule;
  integration_method        : integration_rule;
  integration_order         : INTEGER;
END_ENTITY;

ENTITY surface_section_integration_explicit;
  integration_positions_and_weights : SET [1:?] OF 
                                      surface_section_position_weight;
END_ENTITY;

ENTITY surface_section_position_weight;
  integration_position      : surface_section_element_location;
  integration_weight        : context_dependent_measure;
END_ENTITY;

ENTITY surface_2d_element_integrated_matrix;
  descriptor                : surface_2d_element_descriptor;
  property_type             : surface_matrix_property_type;
  integration_description   : text;
END_ENTITY;

ENTITY surface_2d_element_integrated_matrix_with_definition
  SUBTYPE OF (surface_2d_element_integrated_matrix);
  integration_definition    : surface_2d_element_integration;
END_ENTITY;

ENTITY surface_2d_element_integration;
  element_length            : surface_2d_element_length_integration;
  section                   : surface_section_integration;
END_ENTITY;

TYPE surface_2d_element_length_integration = SELECT
  (element_integration_algebraic,
   surface_2d_element_length_integration_rule,
   surface_2d_element_length_integration_explicit);
END_TYPE;

ENTITY surface_2d_element_length_integration_rule;
  integration_method        : integration_rule;
  integration_order         : INTEGER;
END_ENTITY;

ENTITY surface_2d_element_length_integration_explicit;
  integration_positions_and_weights: SET [1:?] OF surface_position_weight;
END_ENTITY;

ENTITY curve_3d_element_integrated_matrix;
  descriptor                : curve_3d_element_descriptor;
  property_type             : curve_matrix_property_type;
  integration_description   : text;
END_ENTITY;

ENTITY curve_3d_element_integrated_matrix_with_definition
  SUBTYPE OF (curve_3d_element_integrated_matrix);
  integration_definition    : curve_3d_element_integration;
END_ENTITY;

ENTITY curve_3d_element_integration;
  element_length            : curve_3d_element_length_integration;
  section                   : curve_section_integration_explicit;
END_ENTITY;

TYPE curve_3d_element_length_integration = SELECT
  (element_integration_algebraic,
   curve_3d_element_length_integration_rule,
   curve_3d_element_length_integration_explicit);
END_TYPE;

ENTITY curve_3d_element_length_integration_rule;
  integration_method        : integration_rule;
  integration_order         : INTEGER;
END_ENTITY;

ENTITY curve_3d_element_length_integration_explicit;
  integration_positions_and_weights: SET [1:?] OF 
                                     curve_3d_element_position_weight;
END_ENTITY;

ENTITY curve_3d_element_position_weight;
  integration_position      : curve_volume_element_location;
  integration_weight        : context_dependent_measure;
END_ENTITY;

ENTITY curve_section_integration_explicit;
  integration_positions     : SET [1:?] OF curve_section_element_location;
END_ENTITY;

ENTITY curve_2d_element_integrated_matrix;
  descriptor                : curve_2d_element_descriptor;
  property_type             : curve_matrix_property_type;
  integration_description   : text;
END_ENTITY;

ENTITY curve_2d_element_integrated_matrix_with_definition
  SUBTYPE OF (curve_2d_element_integrated_matrix);
  integration_definition    : curve_2d_element_integration;
END_ENTITY;

ENTITY curve_2d_element_integration;
  section                   : LIST [1:?] OF curve_section_element_location;
END_ENTITY;

ENTITY fea_parametric_point
  SUBTYPE OF (point);
  coordinates               : LIST [1:3] OF parameter_value;
WHERE
  WR1: valid_parametric_coordinate (coordinates);
  WR2:  SIZEOF (TYPEOF (SELF) *
         ['GEOMETRY_SCHEMA.CARTESIAN_POINT',
          'GEOMETRY_SCHEMA.POINT_ON_CURVE',
          'GEOMETRY_SCHEMA.POINT_ON_SURFACE',
          'GEOMETRY_SCHEMA.DEGENERATE_PCURVE',
          'GEOMETRY_SCHEMA.POINT_REPLICA',
          'GEOMETRY_SCHEMA.SPHERICAL_POINT',
          'GEOMETRY_SCHEMA.CYLINDRICAL_POINT'])
         = 0;
END_ENTITY;

ENTITY volume_element_location;
  coordinates               : fea_parametric_point;
END_ENTITY;

ENTITY surface_volume_element_location;
  field_location            : surface_element_location;
  section_location          : surface_section_element_location;
END_ENTITY;

ENTITY surface_element_location;
  coordinates               : fea_parametric_point;
END_ENTITY;

ENTITY surface_section_element_location
  SUPERTYPE OF (ONEOF (surface_section_element_location_absolute,
                       surface_section_element_location_dimensionless));
  above_material_discontinuity : LOGICAL;
END_ENTITY;

ENTITY surface_section_element_location_absolute
  SUBTYPE OF (surface_section_element_location);
  offset                    : context_dependent_measure;
END_ENTITY;

ENTITY surface_section_element_location_dimensionless
  SUBTYPE OF (surface_section_element_location);
  coordinate                : LIST [1:1] OF parameter_value;
WHERE
  WR1: valid_parametric_coordinate (coordinate);
END_ENTITY;

ENTITY curve_volume_element_location;
  field_location            : curve_element_location;
  section_location          : curve_section_element_location;
END_ENTITY;

ENTITY curve_element_location;
  coordinate                : fea_parametric_point;
END_ENTITY;

ENTITY curve_section_element_location;
  offsets                   : ARRAY [1:2] of context_dependent_measure;
END_ENTITY;

ENTITY element_material;
  material_id               : identifier;
  description               : text;
  properties                : SET [1:?] OF material_property_representation;
END_ENTITY;

ENTITY fea_material_property_geometric_relationship;
  material_ref              : fea_material_property_representation;
  item                      : analysis_item_within_representation;
WHERE
  WR1: 'GEOMETRY_SCHEMA.GEOMETRIC_REPRESENTATION_ITEM' IN TYPEOF(item.item);
END_ENTITY;

ENTITY fea_material_property_representation
  SUBTYPE OF (material_property_representation);
WHERE
  WR1: SIZEOF (QUERY (item <* 
       SELF\property_definition_representation.used_representation.items |
         SIZEOF (['STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_LINEAR_ELASTICITY',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_MASS_DENSITY',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_AREA_DENSITY',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_TANGENTIAL_COEFFICIENT_OF_LINEAR_THERMAL_EXPANSION',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_SECANT_COEFFICIENT_OF_LINEAR_THERMAL_EXPANSION',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_MOISTURE_ABSORPTION',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_SHELL_MEMBRANE_STIFFNESS',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_SHELL_BENDING_STIFFNESS',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_SHELL_MEMBRANE_BENDING_COUPLING_STIFFNESS',
                  'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.' + 
                  'FEA_SHELL_SHEAR_STIFFNESS'] * TYPEOF (item)
                  ) = 1
       )) = 1;
  WR2: 'MATERIAL_PROPERTY_DEFINITION_SCHEMA.MATERIAL_PROPERTY' IN 
       TYPEOF (SELF\property_definition_representation.definition);
END_ENTITY;

ENTITY fea_material_property_representation_item
  SUPERTYPE OF (ONEOF (fea_linear_elasticity,
                   fea_mass_density,
                   fea_area_density,
                   fea_tangential_coefficient_of_linear_thermal_expansion,
                   fea_secant_coefficient_of_linear_thermal_expansion,
                   fea_moisture_absorption,
                   fea_shell_membrane_stiffness,
                   fea_shell_bending_stiffness,
                   fea_shell_membrane_bending_coupling_stiffness,
                   fea_shell_shear_stiffness))
  SUBTYPE OF (representation_item);
END_ENTITY;

ENTITY fea_linear_elasticity
  SUBTYPE OF (fea_material_property_representation_item);
  fea_constants             : symmetric_tensor4_3d;
END_ENTITY;

ENTITY fea_mass_density
  SUBTYPE OF (fea_material_property_representation_item);
  fea_constant              : scalar;
END_ENTITY;

ENTITY fea_area_density
  SUBTYPE OF (fea_material_property_representation_item);
  fea_constant              : scalar;
END_ENTITY;

ENTITY fea_tangential_coefficient_of_linear_thermal_expansion
  SUBTYPE OF (fea_material_property_representation_item);
  fea_constants             : symmetric_tensor2_3d;
END_ENTITY;

ENTITY fea_secant_coefficient_of_linear_thermal_expansion
  SUBTYPE OF (fea_material_property_representation_item);
  fea_constants             : symmetric_tensor2_3d;
  reference_temperature     : thermodynamic_temperature_measure;
END_ENTITY;

ENTITY fea_moisture_absorption
  SUBTYPE OF (fea_material_property_representation_item);
  fea_constants             : symmetric_tensor2_3d;
END_ENTITY;

ENTITY fea_shell_membrane_stiffness
  SUBTYPE OF (fea_material_property_representation_item);
  fea_constants             : symmetric_tensor4_2d;
END_ENTITY;

ENTITY fea_shell_bending_stiffness
  SUBTYPE OF (fea_material_property_representation_item);
  fea_constants             : symmetric_tensor4_2d;
END_ENTITY;

ENTITY fea_shell_membrane_bending_coupling_stiffness
  SUBTYPE OF (fea_material_property_representation_item);
  fea_constants             : symmetric_tensor4_2d;
END_ENTITY;

ENTITY fea_shell_shear_stiffness
  SUBTYPE OF (fea_material_property_representation_item);
  fea_constants             : symmetric_tensor2_2d;
END_ENTITY;

ENTITY surface_element_property;
  property_id               : identifier;
  description               : text;
  section                   : surface_section_field;
END_ENTITY;

ENTITY surface_section_field
  SUPERTYPE OF (ONEOF (surface_section_field_constant,
                       surface_section_field_varying));
END_ENTITY;

ENTITY surface_section_field_constant
  SUBTYPE OF (surface_section_field);
  definition                : surface_section;
END_ENTITY;

ENTITY surface_section_field_varying
  SUBTYPE OF (surface_section_field);
  definitions               : LIST [1:?] OF surface_section;
  additional_node_values    : BOOLEAN;
END_ENTITY;

ENTITY surface_section
  SUPERTYPE OF (ONEOF (uniform_surface_section,
                       uniform_surface_section_layered));
  offset                     : measure_or_unspecified_value;
  non_structural_mass        : measure_or_unspecified_value;
  non_structural_mass_offset : measure_or_unspecified_value;
END_ENTITY;

ENTITY uniform_surface_section
  SUBTYPE OF (surface_section);
  thickness                 : context_dependent_measure;
  bending_thickness         : measure_or_unspecified_value;
  shear_thickness           : measure_or_unspecified_value;
END_ENTITY;

ENTITY uniform_surface_section_layered
  SUBTYPE OF (surface_section);
END_ENTITY;

ENTITY fea_surface_section_geometric_relationship;
  section_ref               : surface_section;
  item                      : analysis_item_within_representation;
WHERE
  WR1: 'GEOMETRY_SCHEMA.GEOMETRIC_REPRESENTATION_ITEM' IN TYPEOF(item.item);
END_ENTITY;

ENTITY curve_3d_element_property;
  property_id               : identifier;
  description               : text;
  interval_definitions      : LIST [1:?] OF curve_element_interval;
  end_offsets               : ARRAY [1:2] OF curve_element_end_offset;
  end_releases              : ARRAY [1:2] OF curve_element_end_release;
END_ENTITY;

ENTITY curve_element_interval
  SUPERTYPE OF (ONEOF (curve_element_interval_constant,
                       curve_element_interval_linearly_varying));
  finish_position           : curve_element_location;
  eu_angles                 : euler_angles;
END_ENTITY;

ENTITY curve_element_interval_constant
  SUBTYPE OF (curve_element_interval);
  section                : curve_element_section_definition;
END_ENTITY;

ENTITY curve_element_interval_linearly_varying
  SUBTYPE OF (curve_element_interval);
  sections               : ARRAY [1:2] OF curve_element_section_definition;
END_ENTITY;

ENTITY curve_2d_element_property;
  property_id               : identifier;
  description               : text;
  section                   : curve_element_section_definition;
END_ENTITY;

ENTITY curve_element_section_definition
  SUPERTYPE OF (curve_element_section_derived_definitions);
  description               : text;
  section_angle             : plane_angle_measure;
END_ENTITY;

ENTITY curve_element_section_derived_definitions
  SUBTYPE OF (curve_element_section_definition);
  cross_sectional_area      : context_dependent_measure;
  shear_area                : ARRAY [1:2] OF measure_or_unspecified_value;
  second_moment_of_area     : ARRAY [1:3] OF context_dependent_measure;
  torsional_constant        : context_dependent_measure;
  warping_constant          : measure_or_unspecified_value;
  location_of_centroid      : ARRAY [1:2] OF measure_or_unspecified_value;
  location_of_shear_centre  : ARRAY [1:2] OF measure_or_unspecified_value;
  location_of_non_structural_mass
                            : ARRAY [1:2] OF measure_or_unspecified_value;
  non_structural_mass       : measure_or_unspecified_value;
  polar_moment              : measure_or_unspecified_value;
END_ENTITY;

ENTITY fea_curve_section_geometric_relationship;
  section_ref               : curve_element_section_definition;
  item                      : analysis_item_within_representation;
WHERE
  WR1: 'GEOMETRY_SCHEMA.GEOMETRIC_REPRESENTATION_ITEM' IN TYPEOF(item.item);
END_ENTITY;

ENTITY curve_element_end_offset;
  coordinate_system         : curve_element_end_coordinate_system;
  offset_vector             : ARRAY [1:3] OF context_dependent_measure;
END_ENTITY;

ENTITY curve_element_end_release;
  coordinate_system        : curve_element_end_coordinate_system;
  releases                 : LIST [1:?] OF curve_element_end_release_packet;
END_ENTITY;

ENTITY curve_element_end_release_packet;
  release_freedom           : curve_element_freedom;
  release_stiffness         : context_dependent_measure;
END_ENTITY;

ENTITY axisymmetric_2d_element_property;
  angle                     : plane_angle_measure;
END_ENTITY;

ENTITY plane_2d_element_property
  SUPERTYPE OF (simple_plane_2d_element_property);
  depth                     : context_dependent_measure;
END_ENTITY;

ENTITY simple_plane_2d_element_property
  SUBTYPE OF (plane_2d_element_property);
END_ENTITY;

ENTITY fea_group
  SUPERTYPE OF (ONEOF(element_group,
                      node_group))
  SUBTYPE OF (group);
  model_ref                 : fea_model;
END_ENTITY;

ENTITY element_group
  SUBTYPE OF (fea_group);
  elements                  : SET [1:?] OF element_representation;
END_ENTITY;

ENTITY node_group
  SUBTYPE OF (fea_group);
  nodes                     : SET [1:?] OF node_representation;
END_ENTITY;

ENTITY fea_group_relation
  SUBTYPE OF (group_relationship);
WHERE
  WR1: 'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.FEA_GROUP'
        IN TYPEOF (SELF\group_relationship.relating_group);
  WR2: 'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.FEA_GROUP'
        IN TYPEOF (SELF\group_relationship.related_group);
END_ENTITY;

ENTITY volume_3d_element_group
  SUBTYPE OF (element_group);
WHERE
  WR1: SIZEOF(query(item <* elements |
       NOT ('STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.'+
            'VOLUME_3D_ELEMENT_REPRESENTATION' IN TYPEOF (item))))=0;
END_ENTITY;

ENTITY volume_2d_element_group
  SUBTYPE OF (element_group);
WHERE
  WR1: SIZEOF(QUERY(item <* elements |
       (NOT ('STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.'+
             'AXISYMMETRIC_VOLUME_2D_ELEMENT_REPRESENTATION'
              IN TYPEOF(item)) AND
        NOT ('STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.'+
             'PLANE_VOLUME_2D_ELEMENT_REPRESENTATION'
              IN TYPEOF(item)))))=0;
END_ENTITY;

ENTITY surface_3d_element_group
  SUBTYPE OF (element_group);
WHERE
  WR1: SIZEOF(query(item <* elements |
       NOT ('STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.'+
            'SURFACE_3D_ELEMENT_REPRESENTATION' IN TYPEOF (item))))=0;
END_ENTITY;

ENTITY surface_2d_element_group
  SUBTYPE OF (element_group);
WHERE
  WR1: SIZEOF(QUERY(item <* elements |
       (NOT ('STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.'+
             'AXISYMMETRIC_SURFACE_2D_ELEMENT_REPRESENTATION'
              IN TYPEOF(item)) AND
        NOT ('STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.'+
             'PLANE_SURFACE_2D_ELEMENT_REPRESENTATION'
              IN TYPEOF(item)))))=0;
END_ENTITY;

ENTITY curve_3d_element_group
  SUBTYPE OF (element_group);
WHERE
  WR1: SIZEOF(query(item <* elements |
       NOT ('STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.'+
            'CURVE_3D_ELEMENT_REPRESENTATION' IN TYPEOF (item))))=0;
END_ENTITY;

ENTITY curve_2d_element_group
  SUBTYPE OF (element_group);
WHERE
  WR1: SIZEOF(QUERY(item <* elements |
       (NOT ('STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.'+
             'AXISYMMETRIC_CURVE_2D_ELEMENT_REPRESENTATION'
              IN TYPEOF(item)) AND
        NOT ('STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.'+
             'PLANE_CURVE_2D_ELEMENT_REPRESENTATION'
              IN TYPEOF(item)))))=0;
END_ENTITY;

FUNCTION required_0d_nodes
  (node_list                : LIST [1:?] OF node_representation): BOOLEAN;

  RETURN (SIZEOF (node_list) = 1);

END_FUNCTION;

FUNCTION required_1d_nodes
  (node_list                : LIST [1:?] OF node_representation;
   order                    : element_order) : BOOLEAN;  

  LOCAL
   end_nodes                : INTEGER;
   additional_nodes         : INTEGER;
  END_LOCAL;

  end_nodes := 2;

  IF (order = linear) THEN
    additional_nodes := 0;
  END_IF;
  IF (order = quadratic) THEN
    additional_nodes := 1;
  END_IF;
  IF (order = cubic) THEN
    additional_nodes := 2;
  END_IF;

  RETURN (SIZEOF (node_list) = end_nodes + additional_nodes);

END_FUNCTION;

FUNCTION required_2d_nodes
  (node_list                : LIST [1:?] OF node_representation;
   element_shape            : element_2d_shape;
   order                    : element_order) : BOOLEAN;
  LOCAL
    vertex_nodes            : INTEGER;
    edge_nodes              : INTEGER;
    edge_face_body_nodes    : INTEGER;
  END_LOCAL;

  IF (element_shape = triangle) THEN
    vertex_nodes := 3;
    IF (order = linear) THEN
      edge_nodes           := 0;
      edge_face_body_nodes := 0;
    END_IF;
    IF (order = quadratic) THEN
      edge_nodes           := 3;
      edge_face_body_nodes := 3;
    END_IF;
    IF (order = cubic) THEN
      edge_nodes           := 6;
      edge_face_body_nodes := 7;
    END_IF;
  END_IF;

  IF (element_shape = quadrilateral) THEN
    vertex_nodes := 4;
    IF (order = linear) THEN
      edge_nodes           := 0;
      edge_face_body_nodes := 0;
    END_IF;
    IF (order = quadratic) THEN
      edge_nodes           := 4;
      edge_face_body_nodes := 5;
    END_IF;
    IF (order = cubic) THEN
      edge_nodes           := 8;
      edge_face_body_nodes := 12;
    END_IF;
  END_IF;

  RETURN ((SIZEOF (node_list) = vertex_nodes + edge_nodes) OR 
          (SIZEOF (node_list) = vertex_nodes + edge_face_body_nodes));

END_FUNCTION;

FUNCTION required_3d_nodes
  (node_list                : LIST [1:?] OF node_representation;
   element_shape            : volume_3d_element_shape;
   order                    : element_order) : BOOLEAN;
  LOCAL
    vertex_nodes            : INTEGER;
    edge_nodes              : INTEGER;
    edge_face_body_nodes    : INTEGER;
  END_LOCAL;

  IF (element_shape = hexahedron) THEN
    vertex_nodes := 8;
    IF (order = linear) THEN
      edge_nodes           := 0;
      edge_face_body_nodes := 0;
    END_IF;
    IF (order = quadratic) THEN
      edge_nodes           := 12;
      edge_face_body_nodes := 19;
    END_IF;
    IF (order = cubic) THEN
      edge_nodes           := 24;
      edge_face_body_nodes := 56;
    END_IF;
  END_IF;

  IF (element_shape = wedge) THEN
    vertex_nodes := 6;
    IF (order = linear) THEN
      edge_nodes           := 0;
      edge_face_body_nodes := 0;
    END_IF;
    IF (order = quadratic) THEN
      edge_nodes           := 9;
      edge_face_body_nodes := 12;
    END_IF;
    IF (order = cubic) THEN
      edge_nodes           := 18;
      edge_face_body_nodes := 34;
    END_IF;
  END_IF;

  IF (element_shape = tetrahedron) THEN
    vertex_nodes := 4;
    IF (order = linear) THEN
      edge_nodes           := 0;
      edge_face_body_nodes := 0;
    END_IF;
    IF (order = quadratic) THEN
      edge_nodes           := 6;
      edge_face_body_nodes := 6;
    END_IF;
    IF (order = cubic) THEN
      edge_nodes           := 12;
      edge_face_body_nodes := 16;
    END_IF;
  END_IF;

  IF (element_shape = pyramid) THEN
    vertex_nodes := 5;
    IF (order = linear) THEN
      edge_nodes           := 0;
      edge_face_body_nodes := 0;
    END_IF;
    IF (order = quadratic) THEN
      edge_nodes           := 8;
      edge_face_body_nodes := 9;
    END_IF;
    IF (order = cubic) THEN
      edge_nodes           := 16;
      edge_face_body_nodes := 25;
    END_IF;
  END_IF;

  RETURN ((SIZEOF (node_list) = vertex_nodes + edge_nodes) OR 
          (SIZEOF (node_list) = vertex_nodes + edge_face_body_nodes));

END_FUNCTION;

FUNCTION number_of_terms
  (node_dof_list           : LIST [1:?] OF LIST [1:?] OF degree_of_freedom;
   matrix_type             : matrix_symmetry) : INTEGER;
  LOCAL
    num_terms              : INTEGER;
    number_of_freedoms     : INTEGER;
  END_LOCAL;

  number_of_freedoms := 0; (* loop for each item in the outer list*)

  REPEAT i := 1 TO SIZEOF (node_dof_list); (* find size of inner list*)
    number_of_freedoms := number_of_freedoms + SIZEOF (node_dof_list[i]);
  END_REPEAT;

  IF (matrix_type = symmetric) THEN
    num_terms := (number_of_freedoms * (number_of_freedoms+1)) DIV 2;
  END_IF;

  IF (matrix_type = diagonal) THEN
    num_terms := number_of_freedoms;
  END_IF;

RETURN (num_terms);

END_FUNCTION;

FUNCTION valid_parametric_coordinate
    (coordinates            :  LIST [1:3] OF parameter_value): BOOLEAN;

    LOCAL
      i                     : INTEGER;
    END_LOCAL; 

    REPEAT i:=1 TO HIINDEX(coordinates);
      IF ((1.0 < coordinates[i]) OR (coordinates[i] < -1.0)) THEN
        RETURN (FALSE);
      END_IF;
    END_REPEAT;

    RETURN (TRUE);

END_FUNCTION;

FUNCTION build_direction_node
    (node_1                 : node_representation;
     node_2                 : node_representation): LIST [2:3] OF REAL;

LOCAL
  nodal_direction_ratios    : LIST [2:3] OF REAL;
  u                         : direction;
  i                         : INTEGER;
  ndim                      : INTEGER;
  rep_items                 : SET [1:?] of representation_item;
  node_1_point              : cartesian_point;
  node_2_point              : cartesian_point;
END_LOCAL;

rep_items := node_1.items;
REPEAT i := 1 TO SIZEOF(rep_items);
  IF ('GEOMETRY_SCHEMA.CARTESIAN_POINT' IN TYPEOF(rep_items[i])) THEN
    node_1_point := rep_items[i];
    ESCAPE;
  END_IF; 
END_REPEAT;

rep_items := node_2.items;
REPEAT i := 1 TO SIZEOF(rep_items);
  IF ('GEOMETRY_SCHEMA.CARTESIAN_POINT' IN TYPEOF(rep_items[i])) THEN
    node_2_point := rep_items[i];
    ESCAPE;
  END_IF; 
END_REPEAT;

ndim := HIINDEX(node_2_point.coordinates);
REPEAT i := 1 TO ndim;
  u.direction_ratios[i] := node_2_point.coordinates[i] - 
                           node_1_point.coordinates[i];
END_REPEAT;

u := normalise (u);
REPEAT i := 1 TO ndim;
  nodal_direction_ratios[i] := u.direction_ratios[i];
END_REPEAT;

RETURN (nodal_direction_ratios);

END_FUNCTION;

FUNCTION consistent_geometric_reference (
  aspect                    : GENERIC;
  item                      : geometric_representation_item) : BOOLEAN;
 
LOCAL
  srrs                      : STRING;
  feacr                     : STRING;
  aspect_type               : SET [1:?] OF STRING;
  item_type                 : SET [1:?] OF STRING;
END_LOCAL;

srrs        := 'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.';
feacr       := 'FINITE_ELEMENT_ANALYSIS_CONTROL_AND_RESULT_SCHEMA.';
aspect_type := TYPEOF (aspect);
item_type   := TYPEOF (item);

IF ('GEOMETRIC_MODEL_SCHEMA.SOLID_MODEL' IN item_type) THEN
  IF ((srrs + 'ELEMENT_VOLUME') IN aspect_type) THEN
    RETURN (TRUE);
  END_IF;
END_IF;

IF (('GEOMETRY_SCHEMA.SURFACE' IN item_type) OR
    ('TOPOLOGY_SCHEMA.FACE_SURFACE' IN item_type)) THEN
  IF SIZEOF ([(feacr + 'VOLUME_3D_FACE'),
              (feacr + 'VOLUME_2D_FACE'),
              (feacr + 'SURFACE_3D_FACE'),
              (feacr + 'SURFACE_2D_FACE')] *
               aspect_type ) = 1 THEN
    RETURN (TRUE);
  END_IF;
END_IF;

IF (('GEOMETRY_SCHEMA.CURVE' IN item_type) OR
    ('TOPOLOGY_SCHEMA.EDGE_CURVE' IN item_type)) THEN
  IF SIZEOF ([(feacr + 'VOLUME_3D_EDGE'),
              (feacr + 'VOLUME_2D_EDGE'),
              (feacr + 'SURFACE_3D_EDGE'), 
              (feacr + 'SURFACE_2D_EDGE'),
              (srrs  + 'CURVE_EDGE')] *
               aspect_type ) = 1 THEN
    RETURN (TRUE);
  END_IF;
END_IF;

RETURN (FALSE);

END_FUNCTION;

FUNCTION consistent_element_or_group_reference (
  aspect                    : GENERIC;
  element                   : GENERIC) : BOOLEAN;
 
LOCAL
  srrs                      : STRING;
  i                         : INTEGER;
END_LOCAL;

srrs := 'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.';

IF ((srrs + 'ELEMENT_REPRESENTATION') IN TYPEOF(element)) THEN
  RETURN (consistent_element_reference (aspect, element));
END_IF;

IF ((srrs + 'ELEMENT_GROUP') IN TYPEOF(element)) THEN
  REPEAT i := 1 TO HIINDEX (element.elements);
    IF NOT (consistent_element_reference (aspect, element.elements[i])) 
     THEN
      RETURN (FALSE);
    END_IF;
  END_REPEAT;
  RETURN (TRUE);
END_IF;

RETURN (FALSE);

END_FUNCTION;

FUNCTION consistent_element_reference (
  aspect                    : GENERIC;
  element                   : element_representation) : BOOLEAN;

LOCAL
  srrs                      : STRING;
  feacr                     : STRING;
  aspect_type               : SET [1:?] OF STRING;
  element_type              : SET [1:?] OF STRING;
END_LOCAL;

srrs         := 'STRUCTURAL_RESPONSE_REPRESENTATION_SCHEMA.';
feacr        := 'FINITE_ELEMENT_ANALYSIS_CONTROL_AND_RESULT_SCHEMA.';
aspect_type  := TYPEOF (aspect);
element_type := TYPEOF (element);

IF ((srrs + 'ELEMENT_REPRESENTATION')
    IN element_type) THEN
  IF ((srrs + 'ELEMENT_VOLUME') IN aspect_type) THEN
    RETURN (TRUE);
  END_IF;
END_IF;

IF ((srrs + 'VOLUME_3D_ELEMENT_REPRESENTATION')
    IN element_type) THEN
  IF (((feacr + 'VOLUME_3D_FACE') IN aspect_type) OR
      ((feacr + 'VOLUME_3D_EDGE') IN aspect_type)) THEN
    RETURN (TRUE);
  END_IF;
END_IF;

IF (((srrs + 'AXISYMMETRIC_VOLUME_2D_ELEMENT_REPRESENTATION')
     IN element_type) OR
    ((srrs + 'PLANE_VOLUME_2D_ELEMENT_REPRESENTATION') 
     IN element_type)) THEN
  IF (((feacr + 'VOLUME_2D_FACE') IN aspect_type) OR
      ((feacr + 'VOLUME_2D_EDGE') IN aspect_type)) THEN
    RETURN (TRUE);
  END_IF;
END_IF;

IF ((srrs + 'SURFACE_3D_ELEMENT_REPRESENTATION')
    IN element_type) THEN
  IF (((feacr + 'SURFACE_3D_FACE') IN aspect_type) OR
      ((feacr + 'SURFACE_3D_EDGE') IN aspect_type)) THEN
    RETURN (TRUE);
  END_IF;
END_IF;

IF (((srrs + 'AXISYMMETRIC_SURFACE_2D_ELEMENT_REPRESENTATION')
    IN element_type) OR
    ((srrs + 'PLANE_SURFACE_2D_ELEMENT_REPRESENTATION')
     IN element_type)) THEN
  IF (((feacr + 'SURFACE_2D_FACE') IN aspect_type) OR
      ((feacr + 'SURFACE_2D_EDGE') IN aspect_type)) THEN
  RETURN (TRUE);
  END_IF;
END_IF;

IF (((srrs + 'CURVE_3D_ELEMENT_REPRESENTATION') 
     IN element_type) OR
    ((srrs + 'AXISYMMETRIC_CURVE_2D_ELEMENT_REPRESENTATION') 
     IN element_type) OR
    ((srrs + 'PLANE_CURVE_2D_ELEMENT_REPRESENTATION') 
     IN element_type)) THEN
  IF ((srrs + 'CURVE_EDGE') IN aspect_type) THEN
    RETURN (TRUE);
  END_IF;
END_IF;

RETURN (FALSE);

END_FUNCTION;

END_SCHEMA; -- structural_response_representation_schema

SCHEMA finite_element_analysis_control_and_result_schema;

  REFERENCE FROM fea_scalar_vector_tensor_schema
      (anisotropic_symmetric_tensor2_2d,
       anisotropic_symmetric_tensor2_3d,
       anisotropic_symmetric_tensor4_2d,
       isotropic_symmetric_tensor2_3d,
       orthotropic_symmetric_tensor2_3d,
       scalar,
       symmetric_tensor2_2d,
       symmetric_tensor2_3d,
       symmetric_tensor4_2d,
       tensor1,
       tensor1_2d,
       tensor1_3d);

  REFERENCE FROM geometric_model_schema 
      (solid_model);

  REFERENCE FROM geometry_schema 
      (curve,
       point,
       surface);

  REFERENCE FROM measure_schema 
      (context_dependent_measure,
       count_measure,
       length_measure,
       plane_angle_measure);

  REFERENCE FROM structural_response_representation_schema 
      (analysis_item_within_representation,
       axisymmetric_curve_2d_element_descriptor,
       axisymmetric_curve_2d_element_representation,
       axisymmetric_surface_2d_element_descriptor,
       axisymmetric_surface_2d_element_representation,
       axisymmetric_volume_2d_element_descriptor,
       axisymmetric_volume_2d_element_representation,
       curve_2d_element_coordinate_system,
       curve_2d_element_descriptor,
       curve_2d_element_group,
       curve_2d_element_representation,
       curve_3d_element_coordinate_system,
       curve_3d_element_descriptor,
       curve_3d_element_group,
       curve_3d_element_representation,
       curve_element_location,
       curve_section_element_location,
       curve_volume_element_location,
       degree_of_freedom,
       directionally_explicit_element_representation,
       element_descriptor,
       element_group,
       element_representation,
       explicit_element_representation,
       fea_axis2_placement_3d,
       fea_model,      
       node_group,
       node_representation,
       plane_curve_2d_element_descriptor,
       plane_curve_2d_element_representation,
       plane_surface_2d_element_descriptor,
       plane_surface_2d_element_representation,
       plane_volume_2d_element_descriptor,
       plane_volume_2d_element_representation,
       point_element_representation,
       substructure_element_representation,
       surface_2d_element_coordinate_system,
       surface_2d_element_descriptor,
       surface_2d_element_group,
       surface_2d_element_representation,
       surface_3d_element_coordinate_system,
       surface_3d_element_descriptor,
       surface_3d_element_group,
       surface_3d_element_representation,
       surface_element_location,
       surface_section_element_location,
       surface_volume_element_location,
       volume_2d_element_coordinate_system,
       volume_2d_element_descriptor,
       volume_2d_element_group,
       volume_2d_element_representation,
       volume_3d_element_coordinate_system,
       volume_3d_element_group,
       volume_3d_element_descriptor,
       volume_3d_element_representation,
       volume_element_location);

  REFERENCE FROM support_resource_schema 
      (identifier,
       label,
       text);

TYPE model_or_control_element = SELECT
     (element_representation,
      constraint_element);
END_TYPE;

TYPE cylindrical_harmonic_number = INTEGER;
WHERE
  WR1: SELF >= 0;
END_TYPE;

TYPE volume_3d_face = INTEGER;
WHERE
  WR1: (SELF >= 1) AND (SELF <= 6);
END_TYPE;

TYPE volume_2d_face = INTEGER;
WHERE
  WR1: (SELF >= 1) AND (SELF <= 4);
END_TYPE;

TYPE volume_3d_edge = INTEGER;
WHERE
  WR1: (SELF >= 1) AND (SELF <= 12);
END_TYPE;

TYPE volume_2d_edge = INTEGER;
WHERE
  WR1: (SELF >= 1) AND (SELF <= 4);
END_TYPE;

TYPE surface_3d_face = INTEGER;
WHERE
  WR1: (SELF >= 1) AND (SELF <= 2);
END_TYPE;

TYPE surface_3d_edge = INTEGER;
WHERE
  WR1: (SELF >= 1) AND (SELF <= 4);
END_TYPE;

TYPE surface_2d_face = INTEGER;
WHERE
  WR1: (SELF >= 1) AND (SELF <= 2);
END_TYPE;

TYPE surface_2d_edge = INTEGER;
WHERE
  WR1: (SELF >= 1) AND (SELF <= 2);
END_TYPE;

TYPE field_value = SELECT 
  (unspecified_value,
   scalar,
   tensor1_2d,
   tensor1_3d,
   anisotropic_symmetric_tensor2_2d,
   isotropic_symmetric_tensor2_3d,
   orthotropic_symmetric_tensor2_3d,
   anisotropic_symmetric_tensor2_3d);
END_TYPE;

TYPE unspecified_value = ENUMERATION OF
  (unspecified);
END_TYPE;

TYPE measure_or_unspecified_value = SELECT
  (context_dependent_measure,
   unspecified_value);
END_TYPE;

TYPE boundary_variable = SELECT
   (boundary_surface_scalar_variable,
   boundary_surface_vector_3d_variable,
   application_defined_scalar_variable,
   application_defined_vector_3d_variable);
END_TYPE;

TYPE boundary_aggregated_variable = SELECT
   (aggregated_vector_3d_variable,
   application_defined_vector_3d_variable);
END_TYPE;

TYPE volume_variable = SELECT 
  (volume_scalar_variable,
   volume_angular_variable,
   volume_vector_3d_variable,
   volume_tensor2_3d_variable,
   application_defined_scalar_variable,
   application_defined_vector_3d_variable,
   application_defined_tensor2_3d_variable);
END_TYPE;

TYPE volume_aggregated_variable = SELECT 
  (aggregated_scalar_variable,
   aggregated_angular_variable,
   aggregated_vector_3d_variable,
   aggregated_tensor2_3d_variable,
   application_defined_scalar_variable,
   application_defined_vector_3d_variable,
   application_defined_tensor2_3d_variable);
END_TYPE;

TYPE surface_element_variable = SELECT
  (volume_variable,
   surface_scalar_variable,
   surface_vector_2d_variable,
   surface_vector_3d_variable,
   surface_tensor2_2d_variable,
   application_defined_tensor2_2d_variable);
END_TYPE;

TYPE boundary_edge_variable = SELECT
   (boundary_curve_scalar_variable,
    boundary_curve_vector_3d_variable,
    application_defined_scalar_variable,
    application_defined_vector_3d_variable);
END_TYPE;

TYPE curve_element_variable = SELECT
  (volume_variable,
   curve_scalar_variable,
   curve_vector_2d_variable,
   application_defined_vector_2d_variable,
   curve_vector_3d_variable);
END_TYPE;

TYPE curve_scalar_variable = ENUMERATION OF 
     (curve_axial_force,
      curve_axial_strain,
      torque,
      curve_warping,
      bi_moment,
      twist);
END_TYPE;

TYPE surface_scalar_variable = ENUMERATION OF 
     (thickness,
      surface_thermal_gradient,
      reference_surface_thermal_gradient);
END_TYPE;

TYPE volume_scalar_variable = ENUMERATION OF 
     (temperature,
      moisture,
      reference_temperature,
      strain_energy_per_unit_volume);
END_TYPE;

TYPE boundary_curve_scalar_variable = ENUMERATION OF 
     (normal_force_per_unit_length);
END_TYPE;

TYPE boundary_surface_scalar_variable = ENUMERATION OF 
     (pressure);
END_TYPE;

TYPE aggregated_scalar_variable = ENUMERATION OF 
     (total_strain_energy,
      mass,
      volume);
END_TYPE;

TYPE volume_angular_variable = ENUMERATION OF 
     (constant_angular_acceleration,
      application_defined_angular_scalar_variable);
END_TYPE;

TYPE aggregated_angular_variable = ENUMERATION OF 
      (total_applied_moment,
       application_defined_aggregated_angular_scalar_variable);
END_TYPE;

TYPE application_defined_scalar_variable = STRING;
END_TYPE;

TYPE curve_vector_2d_variable = ENUMERATION OF 
     (curve_shear_force,
      curve_bending_moment,
      curve_element_curvature,
      curve_thermal_gradient,
      reference_curve_thermal_gradient);
END_TYPE;

TYPE surface_vector_2d_variable = ENUMERATION OF 
     (surface_out_of_plane_shear_force,
      surface_out_of_plane_shear_strain);
END_TYPE;

TYPE application_defined_vector_2d_variable = STRING;
END_TYPE;

TYPE curve_vector_3d_variable = ENUMERATION OF 
     (applied_force_per_unit_length,
      applied_moment_per_unit_length);
END_TYPE;

TYPE surface_vector_3d_variable = ENUMERATION OF 
     (applied_force_per_unit_area,
      applied_moment_per_unit_area);
END_TYPE;

TYPE volume_vector_3d_variable = ENUMERATION OF 
     (position,
      applied_force_per_unit_volume,
      applied_moment_per_unit_volume,
      displacement,
      infinitesimal_rotation,
      acceleration);
END_TYPE;

TYPE boundary_curve_vector_3d_variable = ENUMERATION OF 
     (applied_force_per_unit_length,
      applied_moment_per_unit_length);
END_TYPE;

TYPE boundary_surface_vector_3d_variable = ENUMERATION OF 
     (applied_force_per_unit_area,
      applied_moment_per_unit_area);
END_TYPE;

TYPE aggregated_vector_3d_variable = ENUMERATION OF 
     (total_applied_force,
      centre_of_mass_offset);
END_TYPE;

TYPE application_defined_vector_3d_variable = STRING;
END_TYPE;

TYPE surface_tensor2_2d_variable = ENUMERATION OF 
     (surface_membrane_force,
      surface_membrane_strain,
      surface_bending_moment,
      surface_curvature);
END_TYPE;

TYPE application_defined_tensor2_2d_variable = STRING;
END_TYPE;

TYPE volume_tensor2_3d_variable = ENUMERATION OF 
     (total_strain,
      stress);
END_TYPE;

TYPE aggregated_tensor2_3d_variable = ENUMERATION OF 
     (rotational_inertia);
END_TYPE;

TYPE application_defined_tensor2_3d_variable = STRING;
END_TYPE;

TYPE message_level = ENUMERATION OF 
     (error,
      warning,
      note);
END_TYPE;

TYPE surface_3d_state_coordinate_system = SELECT
     (fea_axis2_placement_3d,
      surface_3d_element_coordinate_system);
END_TYPE;

TYPE surface_2d_state_coordinate_system = SELECT
     (fea_axis2_placement_3d,
      surface_2d_element_coordinate_system);
END_TYPE;

TYPE curve_3d_state_coordinate_system = SELECT
     (fea_axis2_placement_3d,
      curve_3d_element_coordinate_system);
END_TYPE;

TYPE curve_2d_state_coordinate_system = SELECT
     (fea_axis2_placement_3d,
      curve_2d_element_coordinate_system);
END_TYPE;

TYPE action_type = ENUMERATION OF
     (applied_loads,
      residual_loads);
END_TYPE;

TYPE volume_3d_element_output_reference = SELECT
     (volume_3d_element_representation,
      volume_3d_element_descriptor,
      volume_3d_element_group,
      volume_3d_substructure_element_reference,
      analysis_item_within_representation);
END_TYPE;

TYPE volume_2d_element_output_reference = SELECT
     (volume_2d_element_representation,
      volume_2d_element_descriptor,
      volume_2d_element_group,
      volume_2d_substructure_element_reference,
      analysis_item_within_representation);
END_TYPE;

TYPE surface_3d_element_output_reference = SELECT
     (surface_3d_element_representation,
      surface_3d_element_descriptor,
      surface_3d_element_group,
      surface_3d_substructure_element_reference,
      analysis_item_within_representation);
END_TYPE;

TYPE surface_2d_element_output_reference = SELECT
     (surface_2d_element_representation,
      surface_2d_element_descriptor,
      surface_2d_element_group,
      surface_2d_substructure_element_reference,
      analysis_item_within_representation);
END_TYPE;

TYPE curve_3d_element_output_reference = SELECT
     (curve_3d_element_representation,
      curve_3d_element_descriptor,
      curve_3d_element_group,
      curve_3d_substructure_element_reference,
      analysis_item_within_representation);
END_TYPE;

TYPE curve_2d_element_output_reference = SELECT
     (curve_2d_element_representation,
      curve_2d_element_descriptor,
      curve_2d_element_group,
      curve_2d_substructure_element_reference,
      analysis_item_within_representation);
END_TYPE;

TYPE node_output_reference = SELECT
     (node_representation,
      node_group,
      substructure_node_reference,
      analysis_item_within_representation);
END_TYPE;

ENTITY control;                             
  model_ref                 : fea_model;
  control_id                : identifier;
  creating_software         : text;  
  description               : text;
  user_defined_control      : SET [1:?] OF text;
  intended_analysis_code    : SET [1:?] of text;
UNIQUE
  UR1: model_ref, control_id;
END_ENTITY;      

ENTITY analysis_step
  SUPERTYPE OF (ONEOF (control_analysis_step,
                       result_analysis_step));
  analysis_control          : control;
END_ENTITY;

ENTITY control_analysis_step
  SUPERTYPE OF (ONEOF(control_linear_static_analysis_step,
                control_linear_modes_and_frequencies_analysis_step))
  SUBTYPE OF (analysis_step);
  step_id                   : identifier;
  sequence                  : integer;
  initial_state             : state;
  description               : text;
UNIQUE
  UR1: SELF\analysis_step.analysis_control, sequence;
  UR2: SELF\analysis_step.analysis_control, step_id;
END_ENTITY;    

ENTITY symmetry_control
  SUPERTYPE OF (ONEOF (no_symmetry_control,
                       cylindrical_symmetry_control));
END_ENTITY;    

ENTITY no_symmetry_control
  SUBTYPE OF (symmetry_control);
END_ENTITY;    

ENTITY cylindrical_symmetry_control
  SUBTYPE OF (symmetry_control);
  harmonic                  : cylindrical_harmonic_number;
  phase                     : measure_or_unspecified_value;
END_ENTITY;    

ENTITY control_linear_static_analysis_step
  SUBTYPE OF (control_analysis_step);
  process                   : control_linear_static_load_increment_process;   
END_ENTITY;    

ENTITY control_linear_static_analysis_step_with_harmonic
  SUBTYPE OF (control_linear_static_analysis_step);
  symmetry                  : cylindrical_symmetry_control;
END_ENTITY;    

ENTITY control_linear_modes_and_frequencies_analysis_step
  SUBTYPE OF (control_analysis_step);
  process                   : control_linear_modes_and_frequencies_process;
  number_of_modes           : count_measure;
  frequency_range           : ARRAY [1:2] OF context_dependent_measure;
END_ENTITY;    

ENTITY constraint_element
  SUPERTYPE OF (ONEOF (single_point_constraint_element,
                       linear_constraint_equation_element,
                       nodal_dof_reduction,
                       point_constraint,
                       curve_constraint,
                       surface_constraint,
                       solid_constraint));
  element_id                : identifier;
  steps                     : SET [1:?] OF control_analysis_step;
END_ENTITY;                              

ENTITY single_point_constraint_element
  SUBTYPE OF (constraint_element);
  required_node             : node_output_reference;
  coordinate_system         : fea_axis2_placement_3d;  
  freedoms_and_values       : SET [1:?] OF freedom_and_coefficient;
  description               : text;
END_ENTITY;

ENTITY linear_constraint_equation_element
  SUBTYPE OF (constraint_element);
  freedoms_and_coefficients : SET [1:?] OF 
                                 linear_constraint_equation_nodal_term;
  description               : text;
END_ENTITY;

ENTITY linear_constraint_equation_nodal_term;
  node                      : node_representation;
  coordinate_system         : fea_axis2_placement_3d;
  freedom_and_coefficient_term : freedom_and_coefficient;
  dependent                 : LOGICAL;
END_ENTITY;

ENTITY freedom_and_coefficient;
  freedom                   : degree_of_freedom;
  a                         : measure_or_unspecified_value;
END_ENTITY;

ENTITY nodal_dof_reduction
  SUBTYPE OF (constraint_element);
  required_node             : node_output_reference;
  coordinate_system         : fea_axis2_placement_3d;  
  freedoms                  : SET [1:?] OF degree_of_freedom;
  description               : text;
END_ENTITY;

ENTITY point_constraint
  SUBTYPE OF (constraint_element);
  required_point            : analysis_item_within_representation;
  coordinate_system         : fea_axis2_placement_3d;
  freedoms_and_coefficients : SET [1:?] OF freedom_and_coefficient;
  description               : text;
WHERE
  WR1: ('GEOMETRY_SCHEMA.POINT' IN TYPEOF (required_point.item)) OR
       ('TOPOLOGY_SCHEMA.VERTEX_POINT' IN TYPEOF (required_point.item));
END_ENTITY;

ENTITY curve_constraint
  SUBTYPE OF (constraint_element);
  required_curve            : analysis_item_within_representation;
  coordinate_system         : fea_axis2_placement_3d;
  freedoms_and_coefficients : SET [1:?] OF freedom_and_coefficient;
  description               : text;
WHERE
  WR1: ('GEOMETRY_SCHEMA.CURVE' IN TYPEOF (required_curve.item)) OR
       ('TOPOLOGY_SCHEMA.EDGE_CURVE' IN TYPEOF (required_curve.item));
END_ENTITY;

ENTITY surface_constraint
  SUBTYPE OF (constraint_element);
  required_surface          : analysis_item_within_representation;
  coordinate_system         : fea_axis2_placement_3d;
  freedoms_and_coefficients : SET [1:?] OF freedom_and_coefficient;
  description               : text;
WHERE
  WR1: ('GEOMETRY_SCHEMA.SURFACE' IN TYPEOF (required_surface.item)) OR
       ('TOPOLOGY_SCHEMA.FACE_SURFACE' IN TYPEOF (required_surface.item));
END_ENTITY;

ENTITY solid_constraint
  SUBTYPE OF (constraint_element);
  required_solid            : analysis_item_within_representation;
  coordinate_system         : fea_axis2_placement_3d;
  freedoms_and_coefficients : SET [1:?] OF freedom_and_coefficient;
  description               : text;
WHERE
  WR1: 'GEOMETRIC_MODEL_SCHEMA.SOLID_MODEL' IN TYPEOF (required_solid.item);
END_ENTITY;

ENTITY control_process
  SUPERTYPE OF (ONEOF (control_linear_static_load_increment_process,
                       control_linear_modes_and_frequencies_process));
  process_id                : identifier;
  description               : text;
END_ENTITY;

ENTITY control_linear_static_load_increment_process
  SUBTYPE OF (control_process);
  final_input_state         : state;
END_ENTITY;

ENTITY control_linear_modes_and_frequencies_process
  SUBTYPE OF (control_process);
  final_input_state         : state;
END_ENTITY;

ENTITY element_sequence;
  order_id                  : identifier;
  control_ref               : control;
  purpose                   : text;
  elements                  : LIST [1:?] OF model_or_control_element;
UNIQUE
  UR1: order_id, control_ref;
END_ENTITY;

ENTITY node_sequence;
  order_id                  : identifier;
  control_ref               : control;
  purpose                   : text;
  nodes                     : LIST [1:?] OF node_representation;
UNIQUE
  UR1: order_id, control_ref;
END_ENTITY;

ENTITY result;                             
  result_id                 : identifier;
  creating_software         : text;  
  description               : text;
END_ENTITY;      

ENTITY result_analysis_step
  SUPERTYPE OF (ONEOF (result_linear_static_analysis_sub_step,
                result_linear_modes_and_frequencies_analysis_sub_step))
  SUBTYPE OF (analysis_step);
  analysis_result           : result;
UNIQUE
  UR1: SELF\analysis_step.analysis_control, analysis_result;
END_ENTITY;

ENTITY result_linear_static_analysis_sub_step
  SUBTYPE OF (result_analysis_step);
  state                     : calculated_state;
END_ENTITY;

ENTITY result_linear_modes_and_frequencies_analysis_sub_step
  SUBTYPE OF (result_analysis_step);
  states                    : SET [1:?] OF calculated_state;
END_ENTITY;

ENTITY control_result_relationship;
  control                   : control_analysis_step;
  result                    : result_analysis_step;
END_ENTITY;

ENTITY state
  SUPERTYPE OF (ONEOF (specified_state,
                       calculated_state,
                       linearly_superimposed_state,
                       output_request_state));
  state_id                  : identifier;
  description               : text;
END_ENTITY;    

ENTITY state_with_harmonic
  SUBTYPE OF (state);
  symmetry                  : cylindrical_symmetry_control;
END_ENTITY;    

ENTITY specified_state
  SUBTYPE OF (state);
END_ENTITY;

ENTITY calculated_state
  SUBTYPE OF (state);
END_ENTITY;

ENTITY linearly_superimposed_state
  SUBTYPE OF (state);
INVERSE
  components                : SET [1:?] OF state_component FOR state;
END_ENTITY;

ENTITY state_component
  SUBTYPE OF (state);
  state                     : linearly_superimposed_state;
  factor                    : context_dependent_measure;
END_ENTITY;

ENTITY output_request_state
  SUBTYPE OF (state);
  steps                     : SET [1:?] OF control_analysis_step;
END_ENTITY;

ENTITY state_relationship;
  name                      : label;
  description               : text;
  relating_state            : state;
  related_state             : state;
END_ENTITY;

ENTITY state_definition
  SUPERTYPE OF (ONEOF (field_variable_definition,
                       nodal_freedom_and_value_definition,
                       element_nodal_freedom_actions,
                       point_freedom_and_value_definition,
                       curve_freedom_and_value_definition,
                       surface_freedom_and_value_definition,
                       solid_freedom_and_value_definition,
                       linear_constraint_equation_element_value,
                       single_point_constraint_element_values,
                       analysis_message));
  defined_state             : state;
END_ENTITY;

ENTITY field_variable_definition
  SUPERTYPE OF (ONEOF (field_variable_element_definition,
                       field_variable_element_group_value,
                       field_variable_whole_model_value,
                       field_variable_node_definition))
  SUBTYPE OF (state_definition);
END_ENTITY;

ENTITY field_variable_element_definition
  SUPERTYPE OF (ONEOF (volume_3d_element_field_variable_definition,
                       volume_2d_element_field_variable_definition,
                       surface_3d_element_field_variable_definition,
                       surface_2d_element_field_variable_definition,
                       curve_3d_element_field_variable_definition,
                       curve_2d_element_field_variable_definition))
  SUBTYPE OF (field_variable_definition);
END_ENTITY;

ENTITY volume_3d_element_field_variable_definition
  SUPERTYPE OF (ONEOF (
   volume_3d_element_location_point_variable_values,
   volume_3d_whole_element_variable_value,
   volume_3d_element_constant_specified_variable_value,
   volume_3d_element_nodal_specified_variable_values,
   volume_3d_element_boundary_location_point_variable_values,
   volume_3d_element_boundary_whole_face_variable_value,
   volume_3d_element_boundary_constant_specified_variable_value,
   volume_3d_element_boundary_nodal_specified_variable_values,
   volume_3d_element_boundary_edge_location_point_volume_variable_values,
   volume_3d_element_boundary_edge_whole_edge_variable_value,
   volume_3d_element_boundary_edge_constant_specified_volume_variable_value,
   volume_3d_element_boundary_edge_nodal_specified_variable_values))

  SUBTYPE OF (field_variable_element_definition);
  element                   : volume_3d_element_output_reference;
END_ENTITY;

ENTITY volume_3d_element_location_point_variable_values
  SUBTYPE OF (volume_3d_element_field_variable_definition);
  basis                     : BOOLEAN;
  values_and_locations      : SET [1:?] OF 
                              volume_3d_element_value_and_location;
  variable                  : volume_variable;
WHERE
  WR1: consistent_set_values (values_and_locations, variable);
  WR2: appropriate_set_value_existence (values_and_locations, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY volume_3d_element_value_and_location;
  simple_value              : field_value;
  location                  : volume_element_location;
  coordinate_system         : OPTIONAL volume_3d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
END_ENTITY;

ENTITY volume_3d_whole_element_variable_value
  SUBTYPE OF (volume_3d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : volume_aggregated_variable;
  coordinate_system         : OPTIONAL volume_3d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY volume_3d_element_constant_specified_variable_value
  SUBTYPE OF (volume_3d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : volume_variable;
  coordinate_system         : OPTIONAL volume_3d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY volume_3d_element_nodal_specified_variable_values
  SUBTYPE OF (volume_3d_element_field_variable_definition);
  values                    : LIST [1:?] OF field_value;
  additional_node_values    : BOOLEAN;
  variable                  : volume_variable;
WHERE
  WR1: consistent_list_values (values, variable);
  WR2: appropriate_list_value_existence (values, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY volume_3d_element_boundary_location_point_variable_values
  SUBTYPE OF (volume_3d_element_field_variable_definition);
  basis                     : BOOLEAN;
  values_and_locations      : SET [1:?] OF 
                              volume_3d_element_value_and_location;
  variable                  : boundary_variable;
  element_face              : volume_3d_face;
WHERE
  WR1: consistent_set_values (values_and_locations, variable);
  WR2: appropriate_set_value_existence (values_and_locations, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY volume_3d_element_boundary_whole_face_variable_value
  SUBTYPE OF (volume_3d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : boundary_aggregated_variable;
  element_face              : volume_3d_face;
  coordinate_system         : OPTIONAL volume_3d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY volume_3d_element_boundary_constant_specified_variable_value
  SUBTYPE OF (volume_3d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : boundary_variable;
  element_face              : volume_3d_face;
  coordinate_system         : OPTIONAL volume_3d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY volume_3d_element_boundary_nodal_specified_variable_values
  SUBTYPE OF (volume_3d_element_field_variable_definition);
  values                    : LIST [1:?] OF field_value;
  additional_node_values    : BOOLEAN;
  variable                  : boundary_variable;
  element_face              : volume_3d_face;
WHERE
  WR1: consistent_list_values (values, variable);
  WR2: appropriate_list_value_existence (values, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY 
 volume_3d_element_boundary_edge_location_point_volume_variable_values
  SUBTYPE OF (volume_3d_element_field_variable_definition);
  basis                     : BOOLEAN;
  values_and_locations      : SET [1:?] OF 
                              volume_3d_element_value_and_location;
  variable                  : boundary_edge_variable;
  element_edge              : volume_3d_edge;
WHERE
  WR1: consistent_set_values (values_and_locations, variable);
  WR2: appropriate_set_value_existence (values_and_locations, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY volume_3d_element_boundary_edge_whole_edge_variable_value
  SUBTYPE OF (volume_3d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : boundary_aggregated_variable;
  element_edge              : volume_3d_edge;
  coordinate_system         : OPTIONAL volume_3d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY 
 volume_3d_element_boundary_edge_constant_specified_volume_variable_value
  SUBTYPE OF (volume_3d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : boundary_edge_variable;
  element_edge              : volume_3d_edge;
  coordinate_system         : OPTIONAL volume_3d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY volume_3d_element_boundary_edge_nodal_specified_variable_values
  SUBTYPE OF (volume_3d_element_field_variable_definition);
  values                    : LIST [1:?] OF field_value;
  additional_node_values    : BOOLEAN;
  variable                  : boundary_edge_variable;
  element_edge              : volume_3d_edge;
WHERE
  WR1: consistent_list_values (values, variable);
  WR2: appropriate_list_value_existence (values, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY volume_2d_element_field_variable_definition
  SUPERTYPE OF (ONEOF (
   volume_2d_element_location_point_variable_values,
   volume_2d_whole_element_variable_value,
   volume_2d_element_constant_specified_variable_value,
   volume_2d_element_nodal_specified_variable_values,
   volume_2d_element_boundary_location_point_variable_values,
   volume_2d_element_boundary_whole_face_variable_value,
   volume_2d_element_boundary_constant_specified_variable_value,
   volume_2d_element_boundary_nodal_specified_variable_values,
   volume_2d_element_boundary_edge_location_point_volume_variable_values,
   volume_2d_element_boundary_edge_whole_edge_variable_value,
   volume_2d_element_boundary_edge_constant_specified_volume_variable_value,
   volume_2d_element_boundary_edge_nodal_specified_variable_values))

  SUBTYPE OF (field_variable_element_definition);
  element                   : volume_2d_element_output_reference;
END_ENTITY;

ENTITY volume_2d_element_location_point_variable_values
  SUBTYPE OF (volume_2d_element_field_variable_definition);
  basis                     : BOOLEAN;
  values_and_locations      : SET [1:?] OF 
                              volume_2d_element_value_and_location;
  variable                  : volume_variable;
WHERE
  WR1: consistent_set_values (values_and_locations, variable);
  WR2: appropriate_set_value_existence (values_and_locations, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY volume_2d_element_value_and_location;
  simple_value              : field_value;
  location                  : volume_element_location;
  coordinate_system         : OPTIONAL volume_2d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
END_ENTITY;

ENTITY volume_2d_whole_element_variable_value
  SUBTYPE OF (volume_2d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : volume_aggregated_variable;
  coordinate_system         : OPTIONAL volume_2d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY volume_2d_element_constant_specified_variable_value
  SUBTYPE OF (volume_2d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : volume_variable;
  coordinate_system         : OPTIONAL volume_2d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY volume_2d_element_nodal_specified_variable_values
  SUBTYPE OF (volume_2d_element_field_variable_definition);
  values                    : LIST [1:?] OF field_value; 
  additional_node_values    : BOOLEAN;
  variable                  : volume_variable;
WHERE
  WR1: consistent_list_values (values, variable);
  WR2: appropriate_list_value_existence (values, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY volume_2d_element_boundary_location_point_variable_values
  SUBTYPE OF (volume_2d_element_field_variable_definition);
  basis                     : BOOLEAN;
  values_and_locations      : SET [1:?] OF 
                              volume_2d_element_value_and_location;
  variable                  : boundary_variable;
  element_face              : volume_2d_face;
WHERE
  WR1: consistent_set_values (values_and_locations, variable);
  WR2: appropriate_set_value_existence (values_and_locations, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY volume_2d_element_boundary_whole_face_variable_value
  SUBTYPE OF (volume_2d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : boundary_aggregated_variable;
  element_face              : volume_2d_face;
  coordinate_system         : OPTIONAL volume_2d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY volume_2d_element_boundary_constant_specified_variable_value
  SUBTYPE OF (volume_2d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : boundary_variable;
  element_face              : volume_2d_face;
  coordinate_system         : OPTIONAL volume_2d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY volume_2d_element_boundary_nodal_specified_variable_values
  SUBTYPE OF (volume_2d_element_field_variable_definition);
  values                    : LIST [1:?] OF field_value;
  variable                  : boundary_variable;
  additional_node_values    : BOOLEAN;
  element_face              : volume_2d_face;
WHERE
  WR1: consistent_list_values (values, variable);
  WR2: appropriate_list_value_existence (values, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY 
 volume_2d_element_boundary_edge_location_point_volume_variable_values
  SUBTYPE OF (volume_2d_element_field_variable_definition);
  basis                     : BOOLEAN;
  values_and_locations      : SET [1:?] OF 
                              volume_2d_element_value_and_location;
  variable                  : boundary_edge_variable;
  element_edge              : volume_2d_edge;
WHERE
  WR1: consistent_set_values (values_and_locations, variable);
  WR2: appropriate_set_value_existence (values_and_locations, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY volume_2d_element_boundary_edge_whole_edge_variable_value
  SUBTYPE OF (volume_2d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : boundary_aggregated_variable;
  element_edge              : volume_2d_edge;
  coordinate_system         : OPTIONAL volume_2d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY 
 volume_2d_element_boundary_edge_constant_specified_volume_variable_value
  SUBTYPE OF (volume_2d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : boundary_edge_variable;
  element_edge              : volume_2d_edge;
  coordinate_system         : OPTIONAL volume_2d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY volume_2d_element_boundary_edge_nodal_specified_variable_values
  SUBTYPE OF (volume_2d_element_field_variable_definition);
  values                    : LIST [1:?] OF field_value;
  additional_node_values    : BOOLEAN;
  variable                  : boundary_edge_variable;
  element_edge              : volume_2d_edge;
WHERE
  WR1: consistent_list_values (values, variable);
  WR2: appropriate_list_value_existence (values, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY surface_3d_element_field_variable_definition
  SUPERTYPE OF (ONEOF (
  surface_3d_element_location_point_volume_variable_values,
  surface_3d_element_location_point_variable_values,
  surface_3d_whole_element_variable_value,
  surface_3d_element_constant_specified_variable_value,
  surface_3d_element_constant_specified_volume_variable_value,
  surface_3d_element_nodal_specified_variable_values,
  surface_3d_element_boundary_location_point_surface_variable_values,
  surface_3d_element_boundary_whole_face_variable_value,
  surface_3d_element_boundary_constant_specified_variable_value,
  surface_3d_element_boundary_constant_specified_surface_variable_value,
  surface_3d_element_boundary_nodal_specified_variable_values,
  surface_3d_element_boundary_edge_location_point_surface_variable_values,
  surface_3d_element_boundary_edge_location_point_variable_values,
  surface_3d_element_boundary_edge_whole_edge_variable_value,
  surface_3d_element_boundary_edge_constant_specified_variable_value,
  surface_3d_element_boundary_edge_constant_specified_surface_variable_value,
  surface_3d_element_boundary_edge_nodal_specified_variable_values))

  SUBTYPE OF (field_variable_element_definition);
  element                   : surface_3d_element_output_reference;
END_ENTITY;

ENTITY surface_3d_element_location_point_volume_variable_values
  SUBTYPE OF (surface_3d_element_field_variable_definition);
  basis                     : BOOLEAN;
  values_and_locations      : SET [1:?] OF 
                              surface_3d_element_value_and_volume_location;
  variable                  : volume_variable;
WHERE
  WR1: consistent_set_values (values_and_locations, variable);
  WR2: appropriate_set_value_existence (values_and_locations, 
       TYPEOF (SELF\state_definition.defined_state));

END_ENTITY;

ENTITY surface_3d_element_value_and_location;
  simple_value              : field_value;
  location                  : surface_element_location;
  coordinate_system         : OPTIONAL surface_3d_state_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
END_ENTITY;

ENTITY surface_3d_element_value_and_volume_location;
  simple_value              : field_value;
  location                  : surface_volume_element_location;
  coordinate_system         : OPTIONAL surface_3d_state_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
END_ENTITY;

ENTITY surface_3d_element_location_point_variable_values
  SUBTYPE OF (surface_3d_element_field_variable_definition);
  basis                     : BOOLEAN;
  values_and_locations      : SET [1:?] OF 
                              surface_3d_element_value_and_location;
  variable                  : surface_element_variable;
WHERE
  WR1: consistent_set_values (values_and_locations, variable);
  WR2: appropriate_set_value_existence (values_and_locations, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY surface_3d_whole_element_variable_value
  SUBTYPE OF (surface_3d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : volume_aggregated_variable;
  coordinate_system         : OPTIONAL surface_3d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY surface_3d_element_constant_specified_variable_value
  SUBTYPE OF (surface_3d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : surface_element_variable;
  coordinate_system         : OPTIONAL surface_3d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY surface_3d_element_constant_specified_volume_variable_value
  SUBTYPE OF (surface_3d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : volume_variable;
  coordinate_system         : OPTIONAL surface_3d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY surface_3d_element_nodal_specified_variable_values
  SUBTYPE OF (surface_3d_element_field_variable_definition);
  values                    : LIST [1:?] OF field_value;
  additional_node_values    : BOOLEAN;
  variable                  : surface_element_variable;
WHERE
  WR1: consistent_list_values (values, variable);
  WR2: appropriate_list_value_existence (values, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY 
 surface_3d_element_boundary_location_point_surface_variable_values
  SUBTYPE OF (surface_3d_element_field_variable_definition);
  basis                     : BOOLEAN;
  values_and_locations      : SET [1:?] OF 
                              surface_3d_element_value_and_location;
  variable                  : boundary_variable;
  element_face              : surface_3d_face;
WHERE
  WR1: consistent_set_values (values_and_locations, variable);
  WR2: appropriate_set_value_existence (values_and_locations, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY surface_3d_element_boundary_whole_face_variable_value
  SUBTYPE OF (surface_3d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : boundary_aggregated_variable;
  element_face              : surface_3d_face;
  coordinate_system         : OPTIONAL surface_3d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY 
 surface_3d_element_boundary_constant_specified_surface_variable_value
  SUBTYPE OF (surface_3d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : boundary_variable;
  element_face              : surface_3d_face;
  coordinate_system         : OPTIONAL surface_3d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY surface_3d_element_boundary_constant_specified_variable_value
  SUBTYPE OF (surface_3d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : boundary_aggregated_variable;
  element_face              : surface_3d_face;
  coordinate_system         : OPTIONAL surface_3d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY surface_3d_element_boundary_nodal_specified_variable_values
  SUBTYPE OF (surface_3d_element_field_variable_definition);
  values                    : LIST [1:?] OF field_value;
  additional_node_values    : BOOLEAN;
  variable                  : boundary_variable;
  element_face              : surface_3d_face;
WHERE
  WR1: consistent_list_values (values, variable);
  WR2: appropriate_list_value_existence (values, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY 
 surface_3d_element_boundary_edge_location_point_surface_variable_values
  SUBTYPE OF (surface_3d_element_field_variable_definition);
  basis                     : BOOLEAN;
  values_and_locations      : SET [1:?] OF 
                              surface_3d_element_value_and_volume_location;
  variable                  : boundary_edge_variable;
  element_edge              : surface_3d_edge;
WHERE
  WR1: consistent_set_values (values_and_locations, variable);
  WR2: appropriate_set_value_existence (values_and_locations, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY 
 surface_3d_element_boundary_edge_location_point_variable_values
  SUBTYPE OF (surface_3d_element_field_variable_definition);
  basis                     : BOOLEAN;
  values_and_locations      : SET [1:?] OF 
                              surface_3d_element_value_and_location;
  variable                  : boundary_edge_variable;
  element_edge              : surface_3d_edge;
WHERE
  WR1: consistent_set_values (values_and_locations, variable);
  WR2: appropriate_set_value_existence (values_and_locations, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY surface_3d_element_boundary_edge_whole_edge_variable_value
  SUBTYPE OF (surface_3d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : boundary_aggregated_variable;
  element_edge              : surface_3d_edge;
  coordinate_system         : OPTIONAL surface_3d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY 
 surface_3d_element_boundary_edge_constant_specified_surface_variable_value
  SUBTYPE OF (surface_3d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : boundary_edge_variable;
  element_edge              : surface_3d_edge;
  coordinate_system         : OPTIONAL surface_3d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY surface_3d_element_boundary_edge_constant_specified_variable_value
  SUBTYPE OF (surface_3d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : boundary_edge_variable;
  element_edge              : surface_3d_edge;
  coordinate_system         : OPTIONAL surface_3d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY surface_3d_element_boundary_edge_nodal_specified_variable_values
  SUBTYPE OF (surface_3d_element_field_variable_definition);
  values                    : LIST [1:?] OF field_value;
  additional_node_values    : BOOLEAN;
  variable                  : boundary_edge_variable;
  element_edge              : surface_3d_edge;
WHERE
  WR1: consistent_list_values (values, variable);
  WR2: appropriate_list_value_existence (values, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY surface_2d_element_field_variable_definition
  SUPERTYPE OF (ONEOF (
  surface_2d_element_location_point_volume_variable_values,
  surface_2d_element_location_point_variable_values,
  surface_2d_whole_element_variable_value,
  surface_2d_element_constant_specified_variable_value,
  surface_2d_element_constant_specified_volume_variable_value,
  surface_2d_element_nodal_specified_variable_values,
  surface_2d_element_boundary_location_point_surface_variable_values,
  surface_2d_element_boundary_whole_face_variable_value,
  surface_2d_element_boundary_constant_specified_variable_value,
  surface_2d_element_boundary_constant_specified_surface_variable_value,
  surface_2d_element_boundary_nodal_specified_variable_values,
  surface_2d_element_boundary_edge_location_point_surface_variable_values,
  surface_2d_element_boundary_edge_location_point_variable_values,
  surface_2d_element_boundary_edge_whole_edge_variable_value,
  surface_2d_element_boundary_edge_constant_specified_variable_value,
  surface_2d_element_boundary_edge_constant_specified_surface_variable_value,
  surface_2d_element_boundary_edge_nodal_specified_variable_values))

  SUBTYPE OF (field_variable_element_definition);
  element                   : surface_2d_element_output_reference;
END_ENTITY;

ENTITY surface_2d_element_location_point_volume_variable_values
  SUBTYPE OF (surface_2d_element_field_variable_definition);
  basis                     : BOOLEAN;
  values_and_locations      : SET [1:?] OF 
                              surface_2d_element_value_and_volume_location;
  variable                  : volume_variable;
WHERE
  WR1: consistent_set_values (values_and_locations, variable);
  WR2: appropriate_set_value_existence (values_and_locations, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY surface_2d_element_value_and_location;
  simple_value              : field_value;
  location                  : surface_element_location;
  coordinate_system         : OPTIONAL surface_2d_state_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
END_ENTITY;

ENTITY surface_2d_element_value_and_volume_location;
  simple_value              : field_value;
  location                  : surface_volume_element_location;
  coordinate_system         : OPTIONAL surface_2d_state_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
END_ENTITY;

ENTITY surface_2d_element_location_point_variable_values
  SUBTYPE OF (surface_2d_element_field_variable_definition);
  basis                     : BOOLEAN;
  values_and_locations      : SET [1:?] OF 
                              surface_2d_element_value_and_location;
  variable                  : surface_element_variable;
WHERE
  WR1: consistent_set_values (values_and_locations, variable);
  WR2: appropriate_set_value_existence (values_and_locations, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY surface_2d_whole_element_variable_value
  SUBTYPE OF (surface_2d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : volume_aggregated_variable;
  coordinate_system         : OPTIONAL surface_2d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY surface_2d_element_constant_specified_variable_value
  SUBTYPE OF (surface_2d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : surface_element_variable;
  coordinate_system         : OPTIONAL surface_2d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY surface_2d_element_constant_specified_volume_variable_value
  SUBTYPE OF (surface_2d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : volume_variable;
  coordinate_system         : OPTIONAL surface_2d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY surface_2d_element_nodal_specified_variable_values
  SUBTYPE OF (surface_2d_element_field_variable_definition);
  values                    : LIST [1:?] OF field_value;
  additional_node_values    : BOOLEAN;
  variable                  : surface_element_variable;
WHERE
  WR1: consistent_list_values (values, variable);
  WR2: appropriate_list_value_existence (values, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY 
 surface_2d_element_boundary_location_point_surface_variable_values
  SUBTYPE OF (surface_2d_element_field_variable_definition);
  basis                     : BOOLEAN;
  values_and_locations      : SET [1:?] OF 
                              surface_2d_element_value_and_location;
  variable                  : boundary_variable;
  element_face              : surface_2d_face;
WHERE
  WR1: consistent_set_values (values_and_locations, variable);
  WR2: appropriate_set_value_existence (values_and_locations, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY surface_2d_element_boundary_whole_face_variable_value
  SUBTYPE OF (surface_2d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : boundary_aggregated_variable;
  element_face              : surface_2d_face;
  coordinate_system         : OPTIONAL surface_2d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY 
 surface_2d_element_boundary_constant_specified_surface_variable_value
  SUBTYPE OF (surface_2d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : boundary_variable;
  element_face              : surface_2d_face;
  coordinate_system         : OPTIONAL surface_2d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY surface_2d_element_boundary_constant_specified_variable_value
  SUBTYPE OF (surface_2d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : boundary_aggregated_variable;
  element_face              : surface_2d_face;
  coordinate_system         : OPTIONAL surface_2d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY surface_2d_element_boundary_nodal_specified_variable_values
  SUBTYPE OF (surface_2d_element_field_variable_definition);
  values                    : LIST [1:?] OF field_value;
  additional_node_values    : BOOLEAN;
  variable                  : boundary_variable;
  element_face              : surface_2d_face;
WHERE
  WR1: consistent_list_values (values, variable);
  WR2: appropriate_list_value_existence (values, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY 
 surface_2d_element_boundary_edge_location_point_surface_variable_values
  SUBTYPE OF (surface_2d_element_field_variable_definition);
  basis                     : BOOLEAN;
  values_and_locations      : SET [1:?] OF 
                              surface_2d_element_value_and_volume_location;
  variable                  : boundary_edge_variable;
  element_edge              : surface_2d_edge;
WHERE
  WR1: consistent_set_values (values_and_locations, variable);
  WR2: appropriate_set_value_existence (values_and_locations, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY 
 surface_2d_element_boundary_edge_location_point_variable_values
  SUBTYPE OF (surface_2d_element_field_variable_definition);
  basis                     : BOOLEAN;
  values_and_locations      : SET [1:?] OF 
                              surface_2d_element_value_and_location;
  variable                  : boundary_edge_variable;
  element_edge              : surface_2d_edge;
WHERE
  WR1: consistent_set_values (values_and_locations, variable);
  WR2: appropriate_set_value_existence (values_and_locations, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY surface_2d_element_boundary_edge_whole_edge_variable_value
  SUBTYPE OF (surface_2d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : boundary_aggregated_variable;
  element_edge              : surface_2d_edge;
  coordinate_system         : OPTIONAL surface_2d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY 
 surface_2d_element_boundary_edge_constant_specified_surface_variable_value
  SUBTYPE OF (surface_2d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : boundary_edge_variable;
  element_edge              : surface_2d_edge;
  coordinate_system         : OPTIONAL surface_2d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY surface_2d_element_boundary_edge_constant_specified_variable_value
  SUBTYPE OF (surface_2d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : boundary_edge_variable;
  element_edge              : surface_2d_edge;
  coordinate_system         : OPTIONAL surface_2d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY surface_2d_element_boundary_edge_nodal_specified_variable_values
  SUBTYPE OF (surface_2d_element_field_variable_definition);
  values                    : LIST [1:?] OF field_value;
  additional_node_values    : BOOLEAN;
  variable                  : boundary_edge_variable;
  element_edge              : surface_2d_edge;
WHERE
  WR1: consistent_list_values (values, variable);
  WR2: appropriate_list_value_existence (values, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY curve_3d_element_field_variable_definition
  SUPERTYPE OF (ONEOF (
            curve_3d_element_location_point_volume_variable_values,
            curve_3d_element_location_point_variable_values,
            curve_3d_whole_element_variable_value,
            curve_3d_element_constant_specified_variable_value,
            curve_3d_element_constant_specified_volume_variable_value,
            curve_3d_element_nodal_specified_variable_values))

  SUBTYPE OF (field_variable_element_definition);
  element                   : curve_3d_element_output_reference;
END_ENTITY;

ENTITY curve_3d_element_location_point_volume_variable_values
  SUBTYPE OF (curve_3d_element_field_variable_definition);
  basis                     : BOOLEAN;
  values_and_locations      : SET [1:?] OF 
                              curve_3d_element_value_and_volume_location;
  variable                  : volume_variable;
WHERE
  WR1: consistent_set_values (values_and_locations, variable);
  WR2: appropriate_set_value_existence (values_and_locations, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY curve_3d_element_value_and_location;
  simple_value              : field_value;
  location                  : curve_element_location;
  coordinate_system         : OPTIONAL curve_3d_state_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
END_ENTITY;

ENTITY curve_3d_element_value_and_volume_location;
  simple_value              : field_value;
  location                  : curve_volume_element_location;
  coordinate_system         : OPTIONAL curve_3d_state_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
END_ENTITY;

ENTITY curve_3d_element_location_point_variable_values
  SUBTYPE OF (curve_3d_element_field_variable_definition);
  basis                     : BOOLEAN;
  values_and_locations      : SET [1:?] OF 
                              curve_3d_element_value_and_location;
  variable                  : curve_element_variable;
WHERE
  WR1: consistent_set_values (values_and_locations, variable);
  WR2: appropriate_set_value_existence (values_and_locations, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY curve_3d_whole_element_variable_value
  SUBTYPE OF (curve_3d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : volume_aggregated_variable;
  coordinate_system         : OPTIONAL curve_3d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY curve_3d_element_constant_specified_variable_value
  SUBTYPE OF (curve_3d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : curve_element_variable;
  coordinate_system         : OPTIONAL curve_3d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY curve_3d_element_constant_specified_volume_variable_value
  SUBTYPE OF (curve_3d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : volume_variable;
  coordinate_system         : OPTIONAL curve_3d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY curve_3d_element_nodal_specified_variable_values
  SUBTYPE OF (curve_3d_element_field_variable_definition);
  values                    : LIST [1:?] OF field_value;
  additional_node_values    : BOOLEAN;
  variable                  : curve_element_variable;
WHERE
  WR1: consistent_list_values (values, variable);
  WR2: appropriate_list_value_existence (values, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY curve_2d_element_field_variable_definition
  SUPERTYPE OF (ONEOF (
            curve_2d_element_location_point_volume_variable_values,
            curve_2d_element_location_point_variable_values,
            curve_2d_whole_element_variable_value,
            curve_2d_element_constant_specified_variable_value,
            curve_2d_element_constant_specified_volume_variable_value))
  SUBTYPE OF (field_variable_element_definition);
  element                   : curve_2d_element_output_reference;
END_ENTITY;

ENTITY curve_2d_element_location_point_volume_variable_values
  SUBTYPE OF (curve_2d_element_field_variable_definition);
  basis                     : BOOLEAN;
  values_and_locations      : SET [1:?] OF 
                              curve_2d_element_value_and_volume_location;
  variable                  : curve_element_variable;
WHERE
  WR1: consistent_set_values (values_and_locations, variable);
  WR2: appropriate_set_value_existence (values_and_locations, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY curve_2d_element_value_and_location;
  simple_value              : field_value;
  location                  : curve_section_element_location;
  coordinate_system         : OPTIONAL curve_2d_state_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
END_ENTITY;

ENTITY curve_2d_element_value_and_volume_location;
  simple_value              : field_value;
  location                  : curve_volume_element_location;
  coordinate_system         : OPTIONAL curve_2d_state_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
END_ENTITY;

ENTITY curve_2d_element_location_point_variable_values
  SUBTYPE OF (curve_2d_element_field_variable_definition);
  basis                     : BOOLEAN;
  values_and_locations      : SET [1:?] OF 
                              curve_2d_element_value_and_location;
  variable                  : curve_element_variable;
WHERE
  WR1: consistent_set_values (values_and_locations, variable);
  WR2: appropriate_set_value_existence (values_and_locations, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY curve_2d_whole_element_variable_value
  SUBTYPE OF (curve_2d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : volume_aggregated_variable;
  coordinate_system         : OPTIONAL curve_2d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY curve_2d_element_constant_specified_variable_value
  SUBTYPE OF (curve_2d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : surface_element_variable;
  coordinate_system         : OPTIONAL curve_2d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY curve_2d_element_constant_specified_volume_variable_value
  SUBTYPE OF (curve_2d_element_field_variable_definition);
  simple_value              : field_value;
  variable                  : volume_variable;
  coordinate_system         : OPTIONAL curve_2d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY field_variable_element_group_value
  SUBTYPE OF (field_variable_definition);
  group                     : element_group;
  simple_value              : field_value;
  variable                  : volume_aggregated_variable;
  coordinate_system         : OPTIONAL fea_axis2_placement_3d;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY field_variable_whole_model_value
  SUBTYPE OF (field_variable_definition);
  simple_value              : field_value;
  variable                  : volume_aggregated_variable;
  coordinate_system         : OPTIONAL fea_axis2_placement_3d;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY field_variable_node_definition
  SUPERTYPE OF (ONEOF (volume_3d_node_field_variable_definition,
                       volume_2d_node_field_variable_definition,
                       surface_3d_node_field_variable_definition,
                       surface_2d_node_field_variable_definition,
                       curve_3d_node_field_variable_definition,
                       curve_2d_node_field_variable_definition))
  SUBTYPE OF (field_variable_definition);
  node                      : node_output_reference;
  group                     : OPTIONAL element_group;
END_ENTITY;

ENTITY volume_3d_node_field_variable_definition
  SUBTYPE OF (field_variable_node_definition);
  simple_value              : field_value;
  variable                  : volume_variable;
  coordinate_system         : OPTIONAL volume_3d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY volume_2d_node_field_variable_definition
  SUBTYPE OF (field_variable_node_definition);
  simple_value              : field_value;
  variable                  : volume_variable;
  coordinate_system         : OPTIONAL volume_2d_element_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY surface_3d_node_field_variable_definition
  SUPERTYPE OF (ONEOF (
            surface_3d_node_field_section_variable_values,
            surface_3d_node_field_aggregated_variable_values))
  SUBTYPE OF (field_variable_node_definition);
END_ENTITY;

ENTITY surface_3d_node_field_section_variable_values
  SUBTYPE OF (surface_3d_node_field_variable_definition);
  simple_value              : field_value;
  variable                  : surface_element_variable;
  location                  : surface_section_element_location;
  coordinate_system         : OPTIONAL surface_3d_state_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY surface_3d_node_field_aggregated_variable_values
  SUBTYPE OF (surface_3d_node_field_variable_definition);
  simple_value              : field_value;
  variable                  : volume_aggregated_variable;
  coordinate_system         : OPTIONAL surface_3d_state_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY surface_2d_node_field_variable_definition
  SUPERTYPE OF (ONEOF (
            surface_2d_node_field_section_variable_values,
            surface_2d_node_field_aggregated_variable_values))
  SUBTYPE OF (field_variable_node_definition);
END_ENTITY;

ENTITY surface_2d_node_field_section_variable_values
  SUBTYPE OF (surface_2d_node_field_variable_definition);
  simple_value              : field_value;
  variable                  : surface_element_variable;
  location                  : surface_section_element_location;
  coordinate_system         : OPTIONAL surface_2d_state_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY surface_2d_node_field_aggregated_variable_values
  SUBTYPE OF (surface_2d_node_field_variable_definition);
  simple_value              : field_value;
  variable                  : volume_aggregated_variable;
  coordinate_system         : OPTIONAL surface_2d_state_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY curve_3d_node_field_variable_definition
  SUPERTYPE OF (ONEOF (
            curve_3d_node_field_section_variable_values,
            curve_3d_node_field_aggregated_variable_values))
  SUBTYPE OF (field_variable_node_definition);
END_ENTITY;

ENTITY curve_3d_node_field_section_variable_values
  SUBTYPE OF (curve_3d_node_field_variable_definition);
  simple_value              : field_value;
  variable                  : curve_element_variable;
  location                  : curve_section_element_location;
  coordinate_system         : OPTIONAL curve_3d_state_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY curve_3d_node_field_aggregated_variable_values
  SUBTYPE OF (curve_3d_node_field_variable_definition);
  simple_value              : field_value;
  variable                  : volume_aggregated_variable;
  coordinate_system         : OPTIONAL curve_3d_state_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY curve_2d_node_field_variable_definition
  SUPERTYPE OF (ONEOF (
            curve_2d_node_field_section_variable_values,
            curve_2d_node_field_aggregated_variable_values))
  SUBTYPE OF (field_variable_node_definition);
END_ENTITY;

ENTITY curve_2d_node_field_section_variable_values
  SUBTYPE OF (curve_2d_node_field_variable_definition);
  simple_value              : field_value;
  variable                  : curve_element_variable;
  location                  : curve_section_element_location;
  coordinate_system         : OPTIONAL curve_2d_state_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY curve_2d_node_field_aggregated_variable_values
  SUBTYPE OF (curve_2d_node_field_variable_definition);
  simple_value              : field_value;
  variable                  : volume_aggregated_variable;
  coordinate_system         : OPTIONAL curve_2d_state_coordinate_system;
WHERE
  WR1: necessary_value_coordinate_system (simple_value, coordinate_system);
  WR2: consistent_value (simple_value, variable);
  WR3: appropriate_value_existence (simple_value, 
       TYPEOF (SELF\state_definition.defined_state));
END_ENTITY;

ENTITY nodal_freedom_and_value_definition
  SUPERTYPE OF (ONEOF (nodal_freedom_values,
                       nodal_freedom_action_definition))
  SUBTYPE OF (state_definition);
  node                      : node_output_reference;    
  coordinate_system         : fea_axis2_placement_3d;
  degrees_of_freedom        : freedoms_list;
  values                    : LIST [1:?] OF measure_or_unspecified_value;
WHERE
  WR1: SIZEOF(degrees_of_freedom.freedoms) = SIZEOF (values);
END_ENTITY;

ENTITY nodal_freedom_values
  SUBTYPE OF (nodal_freedom_and_value_definition);
END_ENTITY;

ENTITY nodal_freedom_action_definition
  SUBTYPE OF (nodal_freedom_and_value_definition);
  action                    : action_type;
END_ENTITY;

ENTITY element_nodal_freedom_actions
  SUBTYPE OF (state_definition);
  element                   : model_or_control_element;
  nodal_action              : LIST [1:?] OF 
                                 element_nodal_freedom_terms;
END_ENTITY;

ENTITY element_nodal_freedom_terms;
  coordinate_system         : fea_axis2_placement_3d;
  degrees_of_freedom        : freedoms_list;
  values                    : LIST [1:?] OF measure_or_unspecified_value;
WHERE
  WR1: SIZEOF(degrees_of_freedom.freedoms) = SIZEOF (values);
END_ENTITY;

ENTITY point_freedom_and_value_definition
  SUPERTYPE OF (ONEOF (point_freedom_values,
                       point_freedom_action_definition))
  SUBTYPE OF (state_definition);
  required_point            : analysis_item_within_representation;
  coordinate_system         : fea_axis2_placement_3d;
  degrees_of_freedom        : freedoms_list;
  values                    : LIST [1:?] OF measure_or_unspecified_value;
WHERE
  WR1: SIZEOF(degrees_of_freedom.freedoms) = SIZEOF (values);
  WR2: ('GEOMETRY_SCHEMA.POINT' IN TYPEOF (required_point.item)) OR
       ('TOPOLOGY_SCHEMA.VERTEX_POINT' IN TYPEOF (required_point.item));
END_ENTITY;

ENTITY point_freedom_values
  SUBTYPE OF (point_freedom_and_value_definition);
END_ENTITY;

ENTITY point_freedom_action_definition
  SUBTYPE OF (point_freedom_and_value_definition);
  action                    : action_type;
END_ENTITY;

ENTITY curve_freedom_and_value_definition
  SUPERTYPE OF (ONEOF (curve_freedom_values,
                       curve_freedom_action_definition))
  SUBTYPE OF (state_definition);
  required_curve            : analysis_item_within_representation;
  coordinate_system         : fea_axis2_placement_3d;
  degrees_of_freedom        : freedoms_list;
  values                    : LIST [1:?] OF measure_or_unspecified_value;
WHERE
  WR1: SIZEOF(degrees_of_freedom.freedoms) = SIZEOF (values);
  WR2: ('GEOMETRY_SCHEMA.CURVE' IN TYPEOF (required_curve.item)) OR
       ('TOPOLOGY_SCHEMA.EDGE_CURVE' IN TYPEOF (required_curve.item));
END_ENTITY;

ENTITY curve_freedom_values
  SUBTYPE OF (curve_freedom_and_value_definition);
END_ENTITY;

ENTITY curve_freedom_action_definition
  SUBTYPE OF (curve_freedom_and_value_definition);
  action                    : action_type;
END_ENTITY;

ENTITY surface_freedom_and_value_definition
  SUPERTYPE OF (ONEOF (surface_freedom_values,
                       surface_freedom_action_definition))
  SUBTYPE OF (state_definition);
  required_surface          : analysis_item_within_representation;
  coordinate_system         : fea_axis2_placement_3d;
  degrees_of_freedom        : freedoms_list;
  values                    : LIST [1:?] OF measure_or_unspecified_value;
WHERE
  WR1: SIZEOF(degrees_of_freedom.freedoms) = SIZEOF (values);
  WR2: ('GEOMETRY_SCHEMA.SURFACE' IN TYPEOF (required_surface.item)) OR
       ('TOPOLOGY_SCHEMA.FACE_SURFACE' IN TYPEOF (required_surface.item));
END_ENTITY;

ENTITY surface_freedom_values
  SUBTYPE OF (surface_freedom_and_value_definition);
END_ENTITY;

ENTITY surface_freedom_action_definition
  SUBTYPE OF (surface_freedom_and_value_definition);
  action                    : action_type;
END_ENTITY;

ENTITY solid_freedom_and_value_definition
  SUPERTYPE OF (ONEOF (solid_freedom_values,
                       solid_freedom_action_definition))
  SUBTYPE OF (state_definition);
  required_solid            : analysis_item_within_representation;
  coordinate_system         : fea_axis2_placement_3d;
  degrees_of_freedom        : freedoms_list;
  values                    : LIST [1:?] OF measure_or_unspecified_value;
WHERE
  WR1: SIZEOF(degrees_of_freedom.freedoms) = SIZEOF (values);
  WR2: 'GEOMETRIC_MODEL_SCHEMA.SOLID_MODEL' IN TYPEOF (required_solid.item);
END_ENTITY;

ENTITY solid_freedom_values
  SUBTYPE OF (solid_freedom_and_value_definition);
END_ENTITY;

ENTITY solid_freedom_action_definition
  SUBTYPE OF (solid_freedom_and_value_definition);
  action                    : action_type;
END_ENTITY;

ENTITY freedoms_list;
  freedoms                  : LIST [1:?] OF degree_of_freedom;
END_ENTITY;

ENTITY linear_constraint_equation_element_value
  SUBTYPE OF (state_definition);
  element                   : linear_constraint_equation_element;
  b                         : measure_or_unspecified_value;
END_ENTITY;

ENTITY single_point_constraint_element_values
  SUBTYPE OF (state_definition);
  element                   : single_point_constraint_element;
  degrees_of_freedom        : freedoms_list;
  b                         : LIST [1:?] OF measure_or_unspecified_value;
WHERE
  WR1: SIZEOF(degrees_of_freedom.freedoms) = SIZEOF (b);
END_ENTITY;

ENTITY analysis_message
  SUPERTYPE OF (ONEOF (whole_model_analysis_message,
                       element_analysis_message,
                       node_analysis_message,
                       element_group_analysis_message))
  SUBTYPE OF (state_definition);
  level                     : message_level;
  message_text              : text;
END_ENTITY;

ENTITY whole_model_analysis_message
  SUPERTYPE OF (whole_model_modes_and_frequencies_analysis_message)
  SUBTYPE OF (analysis_message);
END_ENTITY;

ENTITY whole_model_modes_and_frequencies_analysis_message
  SUBTYPE OF (whole_model_analysis_message);
  mode                      : count_measure;
  frequency                 : context_dependent_measure;
END_ENTITY;

ENTITY element_analysis_message
  SUBTYPE OF (analysis_message);
  element                   : element_representation;
END_ENTITY;

ENTITY node_analysis_message
  SUBTYPE OF (analysis_message);
  node                      : node_output_reference;
END_ENTITY;

ENTITY element_group_analysis_message
  SUBTYPE OF (analysis_message);
  group                     : element_group;
END_ENTITY;

ENTITY volume_3d_substructure_element_reference;
  substructure_element_ref  : substructure_element_representation;
  element_ref               : volume_3d_element_representation;
END_ENTITY;

ENTITY volume_2d_substructure_element_reference;
  substructure_element_ref  : substructure_element_representation;
  element_ref               : volume_2d_element_representation;
END_ENTITY;

ENTITY surface_3d_substructure_element_reference;
  substructure_element_ref  : substructure_element_representation;
  element_ref               : surface_3d_element_representation;
END_ENTITY;

ENTITY surface_2d_substructure_element_reference;
  substructure_element_ref  : substructure_element_representation;
  element_ref               : surface_2d_element_representation;
END_ENTITY;

ENTITY curve_3d_substructure_element_reference;
  substructure_element_ref  : substructure_element_representation;
  element_ref               : curve_3d_element_representation;
END_ENTITY;

ENTITY curve_2d_substructure_element_reference;
  substructure_element_ref  : substructure_element_representation;
  element_ref               : curve_2d_element_representation;
END_ENTITY;

ENTITY substructure_node_reference;
  substructure_element_ref  : substructure_element_representation;
  node_ref                  : node_representation;
END_ENTITY;

FUNCTION necessary_value_coordinate_system 
    (cs_value               : field_value;
     coordinate_system      : GENERIC): BOOLEAN;

    IF (SIZEOF (
        ['FEA_SCALAR_VECTOR_TENSOR_SCHEMA.TENSOR1_2D',
         'FEA_SCALAR_VECTOR_TENSOR_SCHEMA.TENSOR1_3D',
         'FEA_SCALAR_VECTOR_TENSOR_SCHEMA.SYMMETRIC_TENSOR2_2D',
         'FEA_SCALAR_VECTOR_TENSOR_SCHEMA.SYMMETRIC_TENSOR2_3D'] *
        TYPEOF (cs_value)) = 1) THEN
        IF (NOT EXISTS (coordinate_system) ) THEN
            RETURN (FALSE);
        END_IF;
    END_IF;

    RETURN (TRUE);

END_FUNCTION;

FUNCTION consistent_set_values
    (values_and_locations   : SET [1:?] OF GENERIC;
     variable               : GENERIC) : BOOLEAN;

    LOCAL
     vv_type                : STRING;
     fv_type                : SET [1:?] OF STRING;
     i                      : INTEGER;
    END_LOCAL;

    vv_type := variable_value_type (variable);

    REPEAT i := 1 TO HIINDEX (values_and_locations);

       fv_type := TYPEOF (values_and_locations[i].simple_value);

       IF NOT (('FINITE_ELEMENT_ANALYSIS_CONTROL_AND_RESULT_SCHEMA.' +
           'UNSPECIFIED_VALUE') IN fv_type) THEN

          IF NOT (vv_type IN fv_type) THEN
             RETURN (FALSE);
          END_IF;

       END_IF;

    END_REPEAT;

    RETURN (TRUE);

END_FUNCTION;

FUNCTION consistent_list_values
    (values                 : LIST [1:?] OF field_value;
     variable               : GENERIC) : BOOLEAN;
 
    LOCAL
     vv_type                : STRING;
     fv_type                : SET [1:?] OF STRING;
     i                      : INTEGER;
    END_LOCAL;

    vv_type := variable_value_type (variable);

    REPEAT i := 1 TO HIINDEX (values);

       fv_type := TYPEOF (values[i]);

       IF NOT (('FINITE_ELEMENT_ANALYSIS_CONTROL_AND_RESULT_SCHEMA.' +
           'UNSPECIFIED_VALUE') IN fv_type) THEN

          IF NOT (vv_type IN fv_type) THEN
             RETURN (FALSE);
          END_IF;

       END_IF;

    END_REPEAT;

    RETURN (TRUE);

END_FUNCTION;

FUNCTION consistent_value
    (c_value                : field_value;
     variable               : GENERIC) : BOOLEAN;

    LOCAL
     vv_type                : STRING;
     fv_type                : SET [1:?] OF STRING;
    END_LOCAL;

    vv_type := variable_value_type (variable);

    fv_type := TYPEOF (c_value);

    IF NOT (('FINITE_ELEMENT_ANALYSIS_CONTROL_AND_RESULT_SCHEMA.' +
       'UNSPECIFIED_VALUE') IN fv_type) THEN

       IF NOT (vv_type IN fv_type) THEN
          RETURN (FALSE);
       END_IF;

    END_IF;

    RETURN (TRUE);

END_FUNCTION;

FUNCTION variable_value_type
    (variable               : GENERIC) : STRING;

    LOCAL
     svt                    : STRING;
     feacr                  : STRING;
     variable_typeof        : SET [1:?] OF STRING;
    END_LOCAL;
        
    svt     := 'FEA_SCALAR_VECTOR_TENSOR_SCHEMA.';
    feacr   := 'FINITE_ELEMENT_ANALYSIS_CONTROL_AND_RESULT_SCHEMA.';
    variable_typeof := TYPEOF (variable);

    IF SIZEOF ([(feacr + 'CURVE_SCALAR_VARIABLE'),
                (feacr + 'SURFACE_SCALAR_VARIABLE'),
                (feacr + 'VOLUME_SCALAR_VARIABLE'),
                (feacr + 'BOUNDARY_CURVE_SCALAR_VARIABLE'),
                (feacr + 'BOUNDARY_SURFACE_SCALAR_VARIABLE'),
                (feacr + 'AGGREGATED_SCALAR_VARIABLE'),
                (feacr + 'VOLUME_ANGULAR_VARIABLE'),
                (feacr + 'AGGREGATED_ANGULAR_VARIABLE'),
                (feacr + 'APPLICATION_DEFINED_SCALAR_VARIABLE')] *
               variable_typeof ) = 1 THEN
        RETURN (svt + 'SCALAR');
    END_IF;

    IF SIZEOF ([(feacr + 'CURVE_VECTOR_2D_VARIABLE'),
                (feacr + 'SURFACE_VECTOR_2D_VARIABLE'),
                (feacr + 'APPLICATION_DEFINED_VECTOR_2D_VARIABLE')] *
               variable_typeof ) = 1 THEN
        RETURN (svt + 'TENSOR1_2D');
    END_IF;

    IF SIZEOF ([(feacr + 'CURVE_VECTOR_3D_VARIABLE'),
                (feacr + 'SURFACE_VECTOR_3D_VARIABLE'),
                (feacr + 'VOLUME_VECTOR_3D_VARIABLE'),
                (feacr + 'BOUNDARY_CURVE_VECTOR_3D_VARIABLE'),
                (feacr + 'BOUNDARY_SURFACE_VECTOR_3D_VARIABLE'),
                (feacr + 'AGGREGATED_VECTOR_3D_VARIABLE'),
                (feacr + 'APPLICATION_DEFINED_VECTOR_3D_VARIABLE')] *
               variable_typeof ) = 1 THEN
        RETURN (svt + 'TENSOR1_3D');
    END_IF;

    IF SIZEOF ([(feacr + 'SURFACE_TENSOR2_2D_VARIABLE'),
                (feacr + 'APPLICATION_DEFINED_TENSOR2_2D_VARIABLE')] *
               variable_typeof ) = 1 THEN
        RETURN (svt + 'SYMMETRIC_TENSOR2_3D');
    END_IF;

    IF SIZEOF ([(feacr + 'VOLUME_TENSOR2_3D_VARIABLE'),
                (feacr + 'AGGREGATED_TENSOR2_3D_VARIABLE'),
                (feacr + 'APPLICATION_DEFINED_TENSOR2_3D_VARIABLE')] *
               variable_typeof ) = 1 THEN
        RETURN (svt + 'SYMMETRIC_TENSOR2_3D');
    END_IF;

    RETURN ('NO_MATCH');

END_FUNCTION;

FUNCTION appropriate_set_value_existence
    (values_and_locations   : SET [1:?] OF GENERIC;
     type_self              : SET [1:?] OF STRING) : BOOLEAN;

    LOCAL
     i                      : INTEGER;
    END_LOCAL;

    REPEAT i := 1 TO HIINDEX (values_and_locations);
       IF NOT (appropriate_value_existence
                (values_and_locations[i].simple_value, type_self)) 
          THEN
          RETURN (FALSE);
       END_IF;
    END_REPEAT;

    RETURN (TRUE);

END_FUNCTION;

FUNCTION appropriate_list_value_existence
    (values                 : LIST [1:?] OF GENERIC;
     type_self              : SET [1:?] OF STRING) : BOOLEAN;

    LOCAL
     i                      : INTEGER;
    END_LOCAL;

    REPEAT i := 1 TO HIINDEX (values);
       IF NOT (appropriate_value_existence (values[i], type_self)) THEN
          RETURN (FALSE);
       END_IF;
    END_REPEAT;

    RETURN (TRUE);

END_FUNCTION;

FUNCTION appropriate_value_existence
    (a_value_e              : GENERIC;
     type_self              : SET [1:?] OF STRING) : BOOLEAN;

    LOCAL
     feacr                  : STRING;
     value_typeof           : SET [1:?] OF STRING;
    END_LOCAL;
        
    feacr := 'FINITE_ELEMENT_ANALYSIS_CONTROL_AND_RESULT_SCHEMA.';
    value_typeof := TYPEOF(a_value_e);

    IF (((feacr + 'OUTPUT_REQUEST_STATE') IN type_self) AND
       NOT ((feacr + 'UNSPECIFIED_VALUE') IN value_typeof)) THEN
       RETURN (FALSE);
    END_IF;

    RETURN (TRUE);

END_FUNCTION;

END_SCHEMA; -- finite_element_analysis_control_and_result_schema

SCHEMA fea_scalar_vector_tensor_schema;

  REFERENCE FROM measure_schema 
      (context_dependent_measure);

  REFERENCE FROM representation_schema
      (representation_item);

TYPE angular_value = 
     context_dependent_measure;
END_TYPE;

TYPE scalar = 
     context_dependent_measure;
END_TYPE;

TYPE tensor1 = SELECT
  (tensor1_2d,
   tensor1_3d);
END_TYPE;

TYPE tensor1_2d = 
     ARRAY [1:2] OF context_dependent_measure;
END_TYPE;

TYPE tensor1_3d = 
  ARRAY [1:3] OF context_dependent_measure;
END_TYPE;

TYPE symmetric_tensor2_2d = SELECT
  (anisotropic_symmetric_tensor2_2d);
END_TYPE;

TYPE anisotropic_symmetric_tensor2_2d = 
  ARRAY [1:3] OF context_dependent_measure;
END_TYPE;

TYPE symmetric_tensor2_3d = SELECT
  (isotropic_symmetric_tensor2_3d,
   orthotropic_symmetric_tensor2_3d,
   anisotropic_symmetric_tensor2_3d);
END_TYPE;

TYPE isotropic_symmetric_tensor2_3d = 
     context_dependent_measure;
END_TYPE;

TYPE orthotropic_symmetric_tensor2_3d = 
     ARRAY [1:3] OF context_dependent_measure;
END_TYPE;

TYPE anisotropic_symmetric_tensor2_3d = 
     ARRAY [1:6] OF context_dependent_measure;
END_TYPE;

TYPE symmetric_tensor4_2d = SELECT
  (anisotropic_symmetric_tensor4_2d);
END_TYPE;

TYPE anisotropic_symmetric_tensor4_2d = 
     ARRAY [1:6] OF context_dependent_measure;
END_TYPE;

TYPE tensor_type = SELECT 
  (scalar,
   angular_value,
   tensor1_2d,
   tensor1_3d,
   anisotropic_symmetric_tensor2_2d,
   isotropic_symmetric_tensor2_3d,
   orthotropic_symmetric_tensor2_3d,
   anisotropic_symmetric_tensor2_3d,
   anisotropic_symmetric_tensor4_2d,
   anisotropic_symmetric_tensor4_3d,
   fea_isotropic_symmetric_tensor4_3d,
   fea_iso_orthotropic_symmetric_tensor4_3d,
   fea_transverse_isotropic_symmetric_tensor4_3d,
   fea_column_normalised_orthotropic_symmetric_tensor4_3d,
   fea_column_normalised_monoclinic_symmetric_tensor4_3d);
END_TYPE;

TYPE symmetric_tensor4_3d = SELECT
 (anisotropic_symmetric_tensor4_3d,
  fea_isotropic_symmetric_tensor4_3d,
  fea_iso_orthotropic_symmetric_tensor4_3d,
  fea_transverse_isotropic_symmetric_tensor4_3d,
  fea_column_normalised_orthotropic_symmetric_tensor4_3d,
  fea_column_normalised_monoclinic_symmetric_tensor4_3d);
END_TYPE;

TYPE anisotropic_symmetric_tensor4_3d = 
     ARRAY [1:21] OF context_dependent_measure;
END_TYPE;

TYPE fea_isotropic_symmetric_tensor4_3d = 
     ARRAY [1:2] OF context_dependent_measure;
END_TYPE;

TYPE fea_iso_orthotropic_symmetric_tensor4_3d = 
     ARRAY [1:3] OF context_dependent_measure;
END_TYPE;

TYPE fea_transverse_isotropic_symmetric_tensor4_3d = 
     ARRAY [1:5] OF context_dependent_measure;
END_TYPE;

TYPE fea_column_normalised_orthotropic_symmetric_tensor4_3d = 
     ARRAY [1:9] OF context_dependent_measure;
END_TYPE;

TYPE fea_column_normalised_monoclinic_symmetric_tensor4_3d = 
     ARRAY [1:13] OF context_dependent_measure;
END_TYPE;

ENTITY tensor_representation_item
  SUBTYPE OF (representation_item);
  tensor_value              : tensor_type;
END_ENTITY;

END_SCHEMA; -- fea_scalar_vector_tensor_schema
