(*
 $Id: 10303-1169-arm-Activity_structure_and_classification.exp,v 1.4 2006/08/04 12:01:50 wg12deputy Exp $
 ISO TC184/SC4/WG12 N2708 - ISO/TS 10303-1169 Activity structure and classification - EXPRESS ARM
 Supersedes ISO TC184/SC4/WG12 N1834
*)

SCHEMA Activity_structure_and_classification_arm;

USE FROM Class_of_activity_library_arm;    -- ISO/TS 10303-1174
USE FROM Classification_arm;    -- ISO/TS 10303-1212
USE FROM External_item_identification_assignment_arm;    -- ISO/TS 10303-1128
USE FROM Individual_activity_structure_arm;    -- ISO/TS 10303-1175

TYPE individual_activity_or_activity_relationship = SELECT BASED_ON classification_select WITH 
  (Individual_activity,
  Composition_of_individual_activity,
  Connection_of_individual_activity,
  Individual_involvement_in_activity);
END_TYPE;

TYPE complete_membership_individual_activity_or_activity_relationship = SELECT BASED_ON complete_membership_select WITH 
  (Individual_activity,
  Composition_of_individual_activity,
  Connection_of_individual_activity,
  Individual_involvement_in_activity);
END_TYPE;

TYPE externally_identified_class_of_activity_or_relationship = SELECT BASED_ON external_identification_item WITH 
  (Class_of_activity,
  Class_of_composition_of_activity,
  Class_of_connection_of_activity,
  Class_of_involvement_in_activity);
END_TYPE;

END_SCHEMA;
