(*
 $Id: 10303-1163-arm-Individual_product_structure.exp,v 1.4 2006/08/04 12:01:50 wg12deputy Exp $
 ISO TC184/SC4/WG12 N2792 - ISO/TS 10303-1163 Individual product structure - EXPRESS ARM
 Supersedes ISO TC184/SC4/WG12 N1977
*)

SCHEMA Individual_product_structure_arm;

USE FROM Composition_of_individual_product_arm;    --  ISO/TS 10303-1166
USE FROM Connection_of_individual_product_arm;    --  ISO/TS 10303-1167
USE FROM Containment_of_individual_product_arm;    --  ISO/TS 10303-1168
USE FROM Involvement_of_individual_product_in_connection_arm;    --  ISO/TS 10303-1165
USE FROM Product_as_individual_arm;    --  ISO/TS 10303-1164

END_SCHEMA;
