(*
 $Id: 10303-1156-arm-Product_structure_and_classification.exp,v 1.4 2006/08/04 12:01:50 wg12deputy Exp $
 ISO TC184/SC4/WG12 N2807 - ISO/TS 10303-1156 Product structure and classification - EXPRESS ARM
 Supersedes ISO TC184/SC4/WG12 N1953
*)

SCHEMA Product_structure_and_classification_arm;

USE FROM Class_of_product_library_arm;    --  ISO/TS 10303-1162
USE FROM Classification_arm;    --  ISO/TS 10303-1212
USE FROM External_item_identification_assignment_arm;    --  ISO/TS 10303-1128
USE FROM Individual_product_structure_arm;    --  ISO/TS 10303-1163

TYPE individual_product_or_product_relationship = SELECT BASED_ON classification_select WITH 
  (Product_as_individual_version,
  Composition_of_individual_product,
  Connection_of_individual_product,
  Containment_of_individual_product,
  Involvement_of_individual_product_in_connection);
END_TYPE;

TYPE complete_membership_individual_product_or_product_relationship = SELECT BASED_ON complete_membership_select WITH 
  (Product_as_individual_version,
  Composition_of_individual_product,
  Connection_of_individual_product,
  Containment_of_individual_product,
  Involvement_of_individual_product_in_connection);
END_TYPE;

TYPE externally_identified_class_of_product_or_relationship = SELECT BASED_ON external_identification_item WITH 
  (Class_of_product,
  Class_of_composition_of_product,
  Class_of_connection_of_product,
  Class_of_containment_of_product,
  Class_of_involvement_of_product_in_connection);
END_TYPE;

END_SCHEMA;
