(*
 $Id: 10303-1156-mim-Product_structure_and_classification.exp,v 1.4 2006/08/04 12:11:54 wg12deputy Exp $
 ISO TC184/SC4/WG12 N2808 - ISO/TS 10303-1156 Product structure and classification - EXPRESS MIM
 Supersedes ISO TC184/SC4/WG12 N1954
*)

SCHEMA Product_structure_and_classification_mim;

USE FROM Class_of_product_library_mim;    --  ISO/TS 10303-1162
USE FROM Classification_mim;    --  ISO/TS 10303-1212
USE FROM External_item_identification_assignment_mim;    --  ISO/TS 10303-1128
USE FROM Individual_product_structure_mim;    --  ISO/TS 10303-1163

TYPE individual_product_or_product_relationship = SELECT BASED_ON classification_select WITH 
  (product_as_individual_version,
  composition_of_individual_product,
  connection_of_individual_product,
  containment_of_individual_product,
  involvement_of_individual_product_in_connection);
END_TYPE;

TYPE complete_membership_individual_product_or_product_relationship = SELECT BASED_ON complete_membership_select WITH 
  (product_as_individual_version,
  composition_of_individual_product,
  connection_of_individual_product,
  containment_of_individual_product,
  involvement_of_individual_product_in_connection);
END_TYPE;

TYPE externally_identified_class_of_product_or_relationship = SELECT BASED_ON external_identification_item WITH 
  (class_of_product,
  class_of_composition_of_product,
  class_of_connection_of_product,
  class_of_containment_of_product,
  class_of_involvement_of_product_in_connection);
END_TYPE;

END_SCHEMA;
