(*
 $Id: 10303-1166-mim-Composition_of_individual_product.exp,v 1.4 2006/08/04 12:11:55 wg12deputy Exp $
 ISO TC184/SC4/WG12 N2763 - ISO/TS 10303-1166 Composition of individual product - EXPRESS MIM
 Supersedes ISO TC184/SC4/WG12 N1984
*)

SCHEMA Composition_of_individual_product_mim;

USE FROM Product_as_individual_mim;    --  ISO/TS 10303-1164
USE FROM Product_version_relationship_mim;    --  ISO/TS 10303-1020

ENTITY composition_of_individual_product
  SUBTYPE OF (product_definition_formation_relationship);
  SELF\product_definition_formation_relationship.relating_product_definition_formation : product_as_individual_version;
  SELF\product_definition_formation_relationship.related_product_definition_formation : product_as_individual_version;
END_ENTITY;

END_SCHEMA;
