(*
 $Id: 10303-1165-arm-Involvement_of_individual_product_in_connection.exp,v 1.4 2006/08/04 12:01:50 wg12deputy Exp $
 ISO TC184/SC4/WG12 N2795 - ISO/TS 10303-1165 Involvement of individual product in connection - EXPRESS ARM
 Supersedes ISO TC184/SC4/WG12 N1980
*)

SCHEMA Involvement_of_individual_product_in_connection_arm;

USE FROM Connection_of_individual_product_arm;    --  ISO/TS 10303-1167
USE FROM Product_as_individual_arm;    --  ISO/TS 10303-1164
USE FROM Product_version_relationship_arm;    --  ISO/TS 10303-1020

ENTITY Connection_of_individual_product_with_involvements
  SUBTYPE OF (Connection_of_individual_product, Product_as_individual_version);
END_ENTITY;

ENTITY Involvement_of_individual_product_in_connection
  SUBTYPE OF (Product_version_relationship);
  SELF\Product_version_relationship.relating_version : Connection_of_individual_product_with_involvements;
  SELF\Product_version_relationship.related_version : Product_as_individual_version;
END_ENTITY;

END_SCHEMA;

