(*
 $Id: 10303-1046-mim-product_replacement.exp,v 1.4 2006/08/07 09:42:03 wg12deputy Exp $
 ISO TC184/SC4/WG12 N1145 - ISO/TS 10303-1046 Product replacement - EXPRESS MIM
*)
    
SCHEMA Product_replacement_mim;

USE FROM Assembly_structure_mim; -- ISO 10303-1026
USE FROM Product_identification_mim; -- ISO 10303-1017

USE FROM product_structure_schema -- ISO 10303-44
  (alternate_product_relationship,
   assembly_component_usage_substitute);
END_SCHEMA;




